### ISSUE TITLE
Volume plugin inside docker container?

### ISSUE THREAD

**Issue by frimdo** [docker/for-linux#10]
**Is there any way to run volume plugin inside a docker container? I guess that the container would have to be privileged and have docker socket mounted as volume. I tried it, with [infinit],(https://infinit.sh/documentation/docker/volume-plugin) but it didn't work. Did I do something wrong or is it not possible?**

If not, It would be killer feature, especially if there would be a possibility to create a service for it to (create the plugin on all nodes of cluster).

And if not, is there a way for volume plugin to communicate over an overlay network?

**Comment by cpuguy83** [comment]
Yes, you can run anything inside a container. Plugins, especially volume plugins, however need special setup for this.

Note that Docker now has a dedicated plugin object, and plugin specific images on dockerhub/docker store that you can use (which ultimately runs a container). Just `docker plugin install <plugin img>`
