### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by AllieUbisse** [docker/for-linux#1005]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
>physical

**Comment by vitaliikapliuk** [comment]
Try with `sudo`

**Comment by AllieUbisse** [comment]
@vitaliikapliuk 
Running on **WSL**  
-----OUT-PUT------
```
 sudo service docker status                                                                                          
 * Docker is not running

 sudo service docker start                                                                                         
 * Starting Docker: docker                                                                                                                   
[ OK ] 

 sudo service docker status                                                                                        
 * Docker is running

  sudo docker run hello-world   
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Comment by fjwbarnard** [comment]
Docker daemon CANNOT be run on WSL. WSL2 supports it though

**Comment by thaJeztah** [comment]
Yes, WSL is not supported as it does not provide all the kernel facilities needed to run Docker. Current versions of Docker Desktop is the recommended way to run Docker on Windows, and can use WSL2 to run docker (see https://docs.docker.com/docker-for-windows/wsl/)

closing this ticket because of the above, but feel free to continue the conversation
