### ISSUE TITLE
Docker armhf unable to run arm64v8 containers

### ISSUE THREAD

**Issue by guysoft** [docker/for-linux#1008]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Docker armhf userspace should be able to run arm64v8 containers when kernel is 64bit

### Actual behavior
Docker armhf userspace unable to run arm64v8 containers when kernel is 64bit

### Steps to reproduce the behavior
1. run on a raspberrypi with the 64bit kernel enabled:
```
sudo docker run -it arm64v8/debian
```
Should give a shell but exists immediately
You can get a shell if you run:
2. 
```
sudo docker run -it --security-opt seccomp:unconfined  arm64v8/debian
```
(taken from https://github.com/moby/moby/issues/20550 )  

**Output of `docker version`:**

```
Docker version 19.03.2, build 6a30dfc
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 32
  Running: 27
  Paused: 0
  Stopped: 5
 Images: 164
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.80-v8+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.719GiB
 Name: golem5
 ID: UV6Y:66BM:W3AF:SA7J:6GP6:S3LW:M2ZX:ERNE:5MTD:M2XI:F57G:V6Z3
 Docker Root Dir: /mnt/sda1/docker
 Debug Mode: false
 Username: guysoft
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

RaspberryPi, if you want a pre-installed image with docker and docker-compose you can use this:
https://github.com/guysoft/MtigOS

This is a copy of the issue https://github.com/docker/distribution/issues/3008#event-3354161573
Asked by @dmcgowan to move it here.

## Possible solution implementation
Solution to this bug has been suggested by @volschin at https://github.com/docker/distribution/issues/3008#issuecomment-575924166
The problem seem to be the archMap part of the default.json. Replacing this by
```
"architectures": [ "SCMP_ARCH_AARCH64", "SCMP_ARCH_ARM" ],
```
all seem to work.

**Comment by thaJeztah** [comment]
@justincormack PTAL

@guysoft sorry for having you go through multiple issue trackers, but the change in the seccomp-profile would have to be made in the https://github.com/moby/moby repository, so perhaps we should have an issue there.

I asked @justincormack to have a quick look at the proposed change to the profile (so we could wait for that)

**Comment by thaJeztah** [comment]
Let me close this one in favour of https://github.com/moby/moby/issues/41092, thanks!
