### ISSUE TITLE
docker Exited(139) no logs print

### ISSUE THREAD

**Issue by GitSoftwareNow** [docker/for-linux#1010]
how can I resolve it?

**Comment by cpuguy83** [comment]
Try running docker with starve? When you say Docker exited, what do you mean? Is that "dockerd" or the "docker" cli, or a container?

There's no info for us to go on here,  or even version details. I understand it may be difficult to get such information depending on what's happening, but even details like "unable to get version" is helpful.

Closing for now, but happy to help. Just need more info to go on.

**Comment by GitSoftwareNow** [comment]
The container exit 139 no logs prints
