### ISSUE TITLE
Docker behaves subtly differently on different machines

### ISSUE THREAD

**Issue by Giszmo** [docker/for-linux#1018]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Running the same docker image on different hosts yields equal results.

### Actual behavior

Compiling a project within a docker container on my laptop yields a different result than when using the same docker image on other machines.

### Steps to reproduce the behavior

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 88
 Server Version: 19.03.8
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 151
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.34GiB
 Name: codex
 ID: ZRAP:TBB3:NYOT:X6KF:NUBD:QUQ2:VD6O:X3PV:5QSQ:2NAL:5HQ5:UQPC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: giszmo
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

As explained on [this stackoverflow question](https://stackoverflow.com/questions/61947996/why-might-the-host-behave-more-deterministic-than-a-docker-container?noredirect=1#comment109567698_61947996), this issue persists after upgrading ubuntu 19.10 to 20.04 and docker from 19.03.6 to 19.03.8 and was tested on a total of 8 systems. Using docker on my machine breaks build reproducibility while not using Docker can produce reproducible builds where others use Docker to reproduce.

**Comment by thaJeztah** [comment]
Just some questions from the top of my head;

- Are all docker situations running with the same kernel, docker version and with the same storage driver?
- Are they using the same underlying filesystem (e.g. `extfs` or `xfs`)?

I see you're using a bind-mount to build the source; are you seeing the same problem if you would perform the build as part of the Dockerfile? (not bind-mounting the source?). I recently looked at an issue where timestamps were truncated (https://github.com/docker/for-linux/issues/990#issuecomment-620538818), causing `autoheader` to produce different results.

**Comment by Giszmo** [comment]
>     * Are all docker situations running with the same kernel, docker version and with the same storage driver?

The full list of systems tested on is:

* **A**: My new PC without Docker
* **AD1**: My new PC with Docker, using our Dockerfile based on ubuntu:18.04 compiled "a year ago"
* **AD2**: My new PC with Docker, using our Dockerfile based on ubuntu:19:10 compiled now
* **B**: My laptop (that I had copied the disk from to my new PC) without Docker
* **BD**: My laptop with Docker
* **CD1**: Co-worker's laptop with Docker, using our Dockerfile based on ubuntu:18.04 compiled "a year ago"
* **CD2**: Co-worker's laptop with Docker, using our Dockerfile based on ubuntu:19:10 compiled now
* **DD**: A Digital Ocean VPS with our Dockerfile based on ubuntu:18.04 compiled now

In all scenarios we got either of two build results:

* Variant X using A, B, CD1, CD2 and DD.
* Variant Y using AD1, AD2 and BD.

The pattern does not change between Docker 19.03.6 and 19.03.8, host ubuntu 19.10 and 20.04 or image based on ubuntu 18.04 and ubuntu 20.04.

>     * Are they using the same underlying filesystem (e.g. `extfs` or `xfs`)?

They are using disorderfs to fix file ordering issues.

> I see you're using a bind-mount to build the source; are you seeing the same problem if you would perform the build as part of the Dockerfile? (not bind-mounting the source?). I recently looked at an issue where timestamps were truncated ([#990 (comment)](https://github.com/docker/for-linux/issues/990#issuecomment-620538818)), causing `autoheader` to produce different results.

The diff is very localized in a range of 1kB of the 20MB output and looks like maybe a compiler optimization being skipped in one variant. Do you want me to learn about bind-mounts and performing the build as part of the Dockerfile to answer this? Do you mean to avoid the --volume part cause I could not figure out yet now to do the disorderfs part inside the docker container without providing docker with a disorderfs mount.

**Comment by Giszmo** [comment]
I now formatted my laptop, installed Ubuntu 20.04 and tried to build with docker and get the same variant Y again. With the walletscrutiny/android:3 Docker image this time.

**Comment by Giszmo** [comment]
To add yet another setup (and to confirm I'm still having this issue), I now have the issue on a VirtualBox Debian 10, too. Will edit my "full list" above.

**Comment by mankoff** [comment]
Is there any chance that you've created images from the same Dockerfile on these different hosts, rather than created one image, pushed to DockerHub, and then pulled? Attempting to re-create from a Dockerfile on different hosts/OS/versions will lead to different outputs.

**Comment by Giszmo** [comment]
This issue is stale and I have moved on. @mankoff might be right although I am pretty sure I did build the image on involved machines multiple times and given the Dockerfile is pretty specific, it should still be pretty deterministic. Anyway, the issue is resolved for me.

**Comment by ii616** [comment]
I am having the same issue.
