### ISSUE TITLE
non-text STDOUT corrupted with JSON logging driver

### ISSUE THREAD

**Issue by sjdv1982** [docker/for-linux#1022]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

`docker logs $container` should give the correct contents of STDOUT, also if STDOUT contains non-text characters.

### Actual behavior

For the standard JSON log driver, non-text bytes are corrupted. The corruption happens both with `docker logs` and when STDOUT is retrieved using the Python Docker API.

Capturing STDOUT manually does the correct thing, and so does the local log driver.

### Steps to reproduce the behavior

The following script creates a small Numpy array that is printed to STDOUT:

- For the standard log driver (`f1.npy` for manual STDOUT, `f1-log.npy` for  `docker logs`)

- For the local log driver (`f2.npy` for manual STDOUT, `f2-log.npy` for  `docker logs`)

`md5sum` shows that `f1.npy`, `f2.npy`, `f2-log.npy` have the same (correct) value, whereas `f1-log.npy` is corrupted

The image (`jupyter/scipy-notebook`) should be replaceable by any image with Python + Numpy installed.

```bash
#!/bin/bash

docker run jupyter/scipy-notebook \
  python3 -c 'import os, numpy as np; np.save("test.npy", np.arange(3)); os.system("cat test.npy")' \
  > f1.npy
container=$(docker ps -a | grep jupyter/scipy-notebook | awk '{print $1}')
docker logs $container > f1-log.npy
docker rm $container

docker run --log-driver local jupyter/scipy-notebook \
  python3 -c 'import os, numpy as np; np.save("test.npy", np.arange(3)); os.system("cat test.npy")' \
  > f2.npy
container=$(docker ps -a | grep jupyter/scipy-notebook | awk '{print $1}')
docker logs $container > f2-log.npy
docker rm $container

md5sum f[1-2]*.npy
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 379
 Server Version: 19.03.9
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 401
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.581GiB
 Name: sjoerd-HP-ZBook-15-G3
 ID: 7UNT:PPSO:A7RK:C756:FCIZ:XT2T:S3CE:YKI5:TSSN:VUVN:7SEM:3EEZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: rpbs
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: the aufs storage-driver is deprecated, and will be removed in a future release.
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Physical

**Comment by cpuguy83** [comment]
Don't do that. I don't think it's reasonable to assume the logging driver can spit out binary data.

Instead you can attach to the container I/O directly, and you likely want to disable logging.

**Comment by sjdv1982** [comment]
Could you clarify? I want to capture STDOUT in a memory buffer (using the Python API). Isn't `docker attach` to visualize in the terminal?

**Comment by cpuguy83** [comment]
`docker attach` attaches you to the container I/O pipes. You specify which pipes you want... e.g. stdout.

In fact, `docker run` is basically `docker pull && docker create && docker attach &; docker start && fg`. You can pipe stdout/stderr directly from` docker run`. You can also choose which pipes you want: `docker run -a stdout ...`

**Comment by sjdv1982** [comment]
Thanks for the clarification. But in that case, wouldn't it be the Docker Python API doing it wrong?
[Their implementation of "docker run"](https://github.com/docker/docker-py/blob/master/docker/models/containers.py#L514) is basically `docker pull && docker create && docker start && docker wait && docker logs` .

**Comment by cpuguy83** [comment]
Absolutely if you want to get access to the raw I/O, then using the logging API is wrong.

**Comment by sjdv1982** [comment]
OK, I will file a bug report there. 

Still, when I used the Python API's `.attach` method (with logs=1), which maps to the `/attach` REST endpoint, I got the same result.

**Comment by cpuguy83** [comment]
logs=1 means to get the logs.
We don't save the container I/O except through the logging driver.
You would need to consume it as it happens.

**Comment by sjdv1982** [comment]
> logs=1 means to get the logs.
> We don't save the container I/O except through the logging driver.
> You would need to consume it as it happens.

Okay. So then, assuming that I want to capture STDOUT faithfully:
- `logs=1` is wrong (leads to corruption)
-  `docker attach` after `docker start` is also wrong (loses the initial part of STDOUT).

Thanks for the explanations. As far as I am concerned, the issue can be closed. 
Although these issues could be warned against in the documentation.

**Comment by fahadkh** [comment]
Sorry to dig this up, but wanted to note for anyone else who runs into this:

You can use the same workaround you used with the CLI - `local` logging driver can be requested in the Python SDK:

```python
client.containers.run(
    ...,
    log_config=LogConfig(type="local"),
)
```

This logging driver does not alter your stdout.
