### ISSUE TITLE
docker Enterprise edition error in AWS EC2 linux

### ISSUE THREAD

**Issue by shivpalsingh** [docker/for-linux#1023]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**
[root@ip-172-31-52-54 ~]# yum -y install docker-ee docker-ee-cli containerd.io
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package containerd.x86_64 0:1.3.2-1.amzn2 will be obsoleted
---> Package containerd.io.x86_64 0:1.3.3-3.el7 will be obsoleting
--> Processing Dependency: container-selinux >= 2:2.74 for package: containerd.io-1.3.3-3.el7.x86_64
---> Package docker-ee.x86_64 3:19.03.8-3.el7 will be installed
--> Processing Dependency: container-selinux >= 2:2.74 for package: 3:docker-ee-19.03.8-3.el7.x86_64
---> Package docker-ee-cli.x86_64 1:19.03.8-3.el7 will be installed
---> Package runc.x86_64 0:1.0.0-0.1.20200204.gitdc9208a.amzn2 will be obsoleted
--> Finished Dependency Resolution
Error: Package: 3:docker-ee-19.03.8-3.el7.x86_64 (docker-ee-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: containerd.io-1.3.3-3.el7.x86_64 (docker-ee-stable)
           Requires: container-selinux >= 2:2.74
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@ip-172-31-52-54 ~]#

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by shivpalsingh** [comment]
Can someone please respond?

**Comment by thaJeztah** [comment]
@shivpalsingh docker-ee (enterprise edition) is now part of Mirantis; https://www.mirantis.com. Could you open a support ticket with them?
