### ISSUE TITLE
Docker daemon client timout headers while waiting for connection

### ISSUE THREAD

**Issue by JegadeeshVontlin** [docker/for-linux#1024]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
 run container hello world

### Actual behavior
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Docker version 19.03.10, build 9424aeaee9

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-33-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.649GiB
 Name: jegadeesh
 ID: IJEG:2AFD:J5U3:DCR7:CASH:NMU3:GGS2:EYB6:OCTH:TISW:ULNQ:RCGA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Looks like a possible networking issue in your setup. Not sure I'm able to help without more details

**Comment by JegadeeshVontlin** [comment]
@thaJeztah  I don't think it is cause of network, because I can install other updates. May I know what more info you are asking for?

**Comment by bensampson5** [comment]
I am having the same problem as well. Also running Ubuntu 20.04 and trying to run the hello-world docker image. I am not using any kind of proxy.

Here's my error message:
```
ben@ben-desktop:~$ docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

```
ben@ben-desktop:~$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.68GiB
 Name: ben-desktop
 ID: 62GL:ECIY:T2KQ:T2XW:V3ZN:77WS:EJBR:BVV3:QRQU:OCIZ:NJ7U:24WK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by JegadeeshVontlin** [comment]
@thaJeztah Een pinging this link also doesn't work , I am not sure whether the link is actually fetching container https://registry-1.docker.io/v2/

Below is the result (100% Loss)

```
Pinging registry-1.docker.io [18.213.137.78] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 18.213.137.78:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by thaJeztah** [comment]
I checked with the Docker Hub team, and it's expected that `ping` doesn't work (icmp traffic is blocked; not exactly sure about the reason for that though), but you should be able to `curl https://registry-1.docker.io/v2/`, which (unless you set an `Authorization` header) will return a JSON error (which is expected);

```bash
curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

If that doesn't work, something in your setup / networking is preventing connections with Docker Hub

**Comment by bensampson5** [comment]
@thaJeztah - curl works as you identified.
```
curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by bensampson5** [comment]
@JegadeeshVontlin - after [some more digging ](https://forums.docker.com/t/docker-pull-results-in-request-canceled-while-waiting-for-connection-client-timeout-exceeded-while-awaiting-headers/73064)and testing. I found a solution that works on my machine. It has to do with configuring the DNS to use Google's DNS servers instead of whatever ones are currently being used.

I followed these instructions and now `docker run hello-world` works!
[https://datawookie.netlify.app/blog/2018/10/dns-on-ubuntu-18.04/](https://datawookie.netlify.app/blog/2018/10/dns-on-ubuntu-18.04/)

**Comment by JegadeeshVontlin** [comment]
@bensampson5  so , did you work with the [some more digging](https://forums.docker.com/t/docker-pull-results-in-request-canceled-while-waiting-for-connection-client-timeout-exceeded-while-awaiting-headers/73064) link and secondly followed google DNS or working with google DNS alone solved the problem for you?

**Comment by bensampson5** [comment]
@JegadeeshVontlin - the [some more digging](https://forums.docker.com/t/docker-pull-results-in-request-canceled-while-waiting-for-connection-client-timeout-exceeded-while-awaiting-headers/73064) link just had some useful suggestions to try but the Google DNS suggestion is what did the trick for me.

The nuance with the Google DNS fix is that simply modifying `/etc/resolv.conf` works but not after a reboot since it gets overwritten. However, [these instructions to permanently add Google's DNS servers](https://datawookie.netlify.app/blog/2018/10/dns-on-ubuntu-18.04/) worked for me on 20.04 even though the title says 18.04 in it.

**Comment by JegadeeshVontlin** [comment]
@bensampson5  @thaJeztah Play the music... docker pulled the hello world container without any changes.. I am closing the issue... But @bensampson5  your points are noted down for future purposes.

Thank you gyus :)

**Comment by skilo83** [comment]
I'm uninstalling Docker. I refuse to be forced to use Google DNS just to use this software. FIX THIS CRAP!

**Comment by thaJeztah** [comment]
@skilo83 there's no need to use Google's DNS servers; other DNS servers should work fine as well. There's many reasons for networking to be causing issues; for some users above, it may have been an issue in their DNS setup (and the Google dns servers happened to work)

**Comment by tienthegainz** [comment]
I am facing the same problem. I tried to change IP to `1.1.1.1` and `8.8.8.8` but none of them works. I tried some `HTTP_PROXY` like `http://proxy.example.com:80/` but it doesn't work neither. Anyone can help me with this?
