### ISSUE TITLE
Docker service stays inactive and containers doesn't restart after rebooting system.

### ISSUE THREAD

**Issue by noddy09** [docker/for-linux#1037]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
After reboot:
* Container should be restarted which are flagged with --restart always.
* `service docker status` should show `Active`.

### Actual behavior
Until any docker command executes:
* Status remains `Inactive`.
* Container are not UP and running.
After any docker command executes, for example: `docker container ls`,
then everything comes online and active.

### Steps to reproduce the behavior
* `shutdown -r now`
* Wait for system to settle down
* Check indirectly if container is up and running by using `curl` or `netstat` commands just to verify response and port bindings.
* Run any docker command like `docker container ls` it will trigger to run container.
* Service becomes active now.

**Output of `docker version`:**

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-33-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.831GiB
 Name: XXXX
 ID: QPXR:3H2L:62FW:AN45:5N5D:MUUZ:MWFF:J5RE:NDFQ:SULM:XXXX:XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  xx.xx.xx.xx:zzzz
  xx.xx.xx.xx:zzzz
  127.0.0.0/8
 Registry Mirrors:
  http://xx.xx.xx.xx:zzzz/
  http://xx.xx.xx.xx:zzzz/
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Virtual Machine via HyperV
Above details are of VM, but same problem reproduced on AWS machine also.
I created container via ssh command line in AWS also. Both env have Ubuntu 20.04 latest.
Installed docker via apt repo: `apt install docker.io`
Containers:
-kurento/kurento-media-server:latest-asan
-apache/openmeetings:min-5.0.0-M4
-mayanedms/mayanedms:3.3.7

**Comment by thaJeztah** [comment]
Looks like you have installed the package that's built and maintained by Ubuntu / Canonical.

Are you seeing the same problem with the official docker packages? (https://docs.docker.com/engine/install/ubuntu )

From your description, it seems your daemon was stopped and is started through socket activation (so first request on the docker API triggers a start of the daemon?)

**Comment by noddy09** [comment]
> Looks like you have installed the package that's built and maintained by Ubuntu / Canonical.

Yes.

> Are you seeing the same problem with the official docker packages? (https://docs.docker.com/engine/install/ubuntu )

Im on restricted env where i can't access private repo & can't use `dpkg`. :( 

> From your description, it seems your daemon was stopped and is started through socket activation (so first request on the docker API triggers a start of the daemon?)

I can see `TriggeredBy : docker.socket` in service details.

**Comment by thaJeztah** [comment]
>  can see TriggeredBy : docker.socket in service details.

Yes, that looks to be socket activation.


What does your `docker` systemd unit look like? Is it the same as https://github.com/docker/docker-ce-packaging/blob/v19.03.11/systemd/docker.service ?

You can view the unit file using `sudo systemctl cat docker.service`

**Comment by noddy09** [comment]
> What does your `docker` systemd unit look like? Is it the same as https://github.com/docker/docker-ce-packaging/blob/v19.03.11/systemd/docker.service ?

The only difference i found is:
```
diff community canonical
0a1
> # /lib/systemd/system/docker.service 
```

It is not critical but still:: I found `docker.service` unit file at `/usr/lib/systemd/system/` instead of `/etc/systemd/system` or `/lib/systemd/system/`

**Comment by cgd1** [comment]
> > can see TriggeredBy : docker.socket in service details.
> 
> Yes, that looks to be socket activation.
> 
> What does your `docker` systemd unit look like? Is it the same as https://github.com/docker/docker-ce-packaging/blob/v19.03.11/systemd/docker.service ?
> 
> You can view the unit file using `sudo systemctl cat docker.service`

Hi @thaJeztah as per other thread,

My `docker.service` file is same as referenced example.

**Comment by sylvain-rouquette** [comment]
> 
> 
> Looks like you have installed the package that's built and maintained by Ubuntu / Canonical.
> 
> Are you seeing the same problem with the official docker packages? (https://docs.docker.com/engine/install/ubuntu )

Has this been fixed in a recent version?

**Comment by cgd1** [comment]
I have tried docker-ce and docker.io

Both do are not working.

installed via `apt`

**Comment by sylvain-rouquette** [comment]
for me, the problem occured with a security update, docker was updated, the containers were stopped, but didn't restart automatically (I'm using restart unless-stopped)

**Comment by cgd1** [comment]
Using `restart: always` with docker-compose

**Comment by gsicilia82** [comment]
Same issue here with Ubuntu 20.04 (Kernel 5.10). Strange detail: After reboot, docker daemon is inactive (dead). OK.
BUT when I enter "docker" in console (or something related to docker, like "docker container ls") it becames active and everything runs like a charm. I have installed docker from Ubuntu repo.

**Comment by gsicilia82** [comment]
I had same issue with Ubuntu repo ( v19.03.8). Now, with Docker Repo v20.10.2 deamon-start works fine after server reboot .

**Comment by vhuezo** [comment]
![TDqIMeX](https://user-images.githubusercontent.com/41808201/115134413-1555f900-9fcd-11eb-8258-4e06e14d380c.png)

**Comment by sam-thibault** [comment]
I see this issue has been inactive and there could be many possible causes for a service not started.  I will close it as stale.
