### ISSUE TITLE
Proxy with authentication not working

### ISSUE THREAD

**Issue by mat-l** [docker/for-linux#1039]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker should connect to its registry and download images that a available in the public registry

### Actual behavior
Docker is not able to build own project and its not even pulling the hello-world example during testing of the porxy settings:
```
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 52.72.232.213:443: connect: connection refused.
See 'docker run --help'.
```

### Steps to reproduce the behavior

Docker cannat download any images:
```
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 52.72.232.213:443: connect: connection refused.
See 'docker run --help'.
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-101-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.789GiB
 Name: ubuntu
 ID: A544:DFTQ:4A42:WWUE:5GFA:OWXP:FBJS:RWWC:GEG6:3UOJ:BRVK:XGDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://<username>:<password>@<proxy>:<port>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
The VM is hosted in a Red Hat OpenStack environment.

I have set the Ubuntu Linux system proxy (HTTPS_PROXY,https_proxy, HTTP_PROXY, http_proxy) as follow:
```
export HTTPS_PROXY='http://<username>:<password>@<proxy>:<port>'
```

Additionally the apt-configuration is set as follow:
```
sudo touch /etc/apt/apt.conf.d/proxy.conf
sudo nano /etc/apt/apt.conf.d/proxy.conf
Acquire::http::Proxy "http://<username>:<password>@<proxy>:<port>";
```

Until this point everything is working fine while considering to url-encode special characters such as: https://duckduckgo.com/?q=url+encode+%25%40!%3F&kl=at-de&ia=answer

I have set "systemd" environmental variable over here "/etc/systemd/system/docker.service.d/http-proxy.conf":
```
[Service]
Environment="HTTP_PROXY=http://<username>:<password>@<proxy>:<port>"
Environment="HTTPS_PROXY=http://<username>:<password>@<proxy>:<port>"
Environment="NO_PROXY=localhost,127.0.0.1"
```

In "/etc/default/docker" I have also written down the proxy settings:
```
# Docker Upstart and SysVinit configuration file
# THIS FILE DOES NOT APPLY TO SYSTEMD
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/admin/systemd/
# Customize location of Docker binary (especially for development testing).
#DOCKERD="/usr/local/bin/dockerd"
# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"
http_proxy="HTTP_PROXY=http://<username>:<password>@<proxy>:<port>"
https_proxy="HTTP_PROXY=http://<username>:<password>@<proxy>:<port>"
HTTP_PROXY="HTTP_PROXY=http://<username>:<password>@<proxy>:<port>"
HTTPS_PROXY="HTTP_PROXY=http://<username>:<password>@<proxy>:<port>"

# This is also a handy place to tweak where Docker's temporary files go.
#export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"
```

The problem seems to be either the parsing of the passwords from the Linux environmental varibles, or systemd or the docker configs itself. I have always used url-encoding, but it doesn't work.
Also passing the proxy authentication during a "docker run" command is not working: `sudo docker run --env http_proxy='http://<username>:<password>@<proxy>:<port>' hello-world`.

Is it a bug in one of the parsing function or do I have to encode my password individually in the differend configs?

Appreciate any help and support.
Best regards

**Comment by thaJeztah** [comment]
Your `docker info` output only shows the `HTTP_PROXY`, not the `HTTPS_PROXY`; 

```
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://<username>:<password>@<proxy>:<port>
 Registry: https://index.docker.io/v1/
```

did you reload the configuration and service after configuring your systemd unit (`sudo systemctl daemon-reload` and `sudo systemctl restart docker` ?) see instructions on this page; https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

I'm not sure though if using a non-HTTPS proxy for HTTPS traffic works 🤔 (but haven't tried)


> Also passing the proxy authentication during a "docker run" command is not working: sudo docker run --env http_proxy='http://<username>:<password>@<proxy>:<port>' hello-world.

Setting that environment variable on `docker run` will only set the environment variable _inside_ the container, but won't use it for the docker daemon (which performs the `docker pull`)

**Comment by mat-l** [comment]
I was able to solve the problem by defining a new password. The problem was a special character which made trouble within the proxy settings of Docker or in combination with systemd. The question to avoid such problems is, how one has to encode the passwort, that also special characters do not lead to such a problem.

**Comment by thaJeztah** [comment]
Do you know what character caused the issue?

**Comment by mat-l** [comment]
I assume it was the '@' character in thr password, but didn't try in detail.

**Comment by mandheer** [comment]
I run docker Desktop diagnostics and it's auto resolved.

**Comment by thaJeztah** [comment]
> The question to avoid such problems is, how one has to encode the passwort, that also special characters do not lead to such a problem.

> I assume it was the '@' character in thr password, but didn't try in detail.

Given that the password is passed in an URL, you'd normally use URL-encoding for these. I'm not behind a proxy, so can't test, but I expect using `%40` to encode the `@` in the password (`https://username:p%40ssword@myproxy.example.com`) to work.

If it doesn't, that sounds like a bug; if anyone is able to test, that would be appreciated; note my earlier comment though that the systemd `xx_PROXY` environment variables only apply to the daemon itself (so used for, e.g., pulling images). To set a proxy in a container, set it as an environment variable on the container itself (`-e HTTPS_PROXY=xxx`) or use the CLI configuration to set these automatically when starting a container from the CLI; https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by sam-thibault** [comment]
I don't see any recent response to this issue.  I will close it as stale.
