### ISSUE TITLE
docker-compose managed images not coming up only on first engine reboot

### ISSUE THREAD

**Issue by dleonard-uptycs** [docker/for-linux#1041]
* [x] This is a bug report

I am bringing up some docker containers through ansible's docker_container module, and some docker containers through docker-compose. When the server that is running these containers is rebooted, all containers come up as expected. After the reboot, when docker engine is restarted (`sudo service docker stop && sudo service docker start`), the ansible brought containers come up properly but the docker-compose ones do not. Running `docker-compose up -d` on the compose-managed containers brings them up again, and they will survive future docker engine starts. All containers (ansible brought and docker-compose) have restart-policy of on-failure, and have tried switching it to always to no avail.

### Expected behavior
The containers managed through docker-compose should survive restarting docker engine the first time.

### Actual behavior
The first time docker engine is restarted, the docker-compose containers do not come up.

### Steps to reproduce the behavior
1.) Bring up some containers through ansible's docker_container module. These containers should have restart_policy of on-failure
2.) Using docker-compose version 2, create a docker-compose.yml-base file that looks like a regular docker-compose file, defining some containers to be brought up
3.) Create docker-compose.yml file, that uses version 2's import syntax, ex:
```
services:
  app1:
    extends:
      file: docker-compose.yml-base
      service: app1
```
4.) Run ansible-playbook so that the docker containers come up
5.) Run `docker-compose up -d` so that compose managed containers come up
6.) Reboot the server with `sudo reboot`
7.) Run `sudo docker ps` to see all containers running
8.) Run `sudo service docker stop && sudo service docker start` to reboot the docker engine
9.) Notice that compose managed containers are not up
9a.) Run `docker-compose up -d` again so that compose managed containers come back
9b.) Running step 8's docker engine reboot will now not take down the compose managed containers

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-170-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.9GiB
Name: server1
ID: UCTT:4E6L:C4XW:4SRD:SSFC:NVIH:GZKP:EPYM:KYT2:LLSZ:OLA3:W2NO
Docker Root Dir: REDACTED
Debug Mode (client): false
Debug Mode (server): false
Username: REDACTED
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
These servers are physical ubuntu 16.04

**Comment by thaJeztah** [comment]
That's expected; by default, containers do not have a restart-policy set, which means that once stopped (which happens when you reboot the machine), they're not automatically restarted. see [restart_policy](https://docs.docker.com/compose/compose-file/#restart_policy) (for `docker stack deploy`), and [restart](https://docs.docker.com/compose/compose-file/#restart)


I'm closing this issue, because this doesn't look like a bug, but feel free to continue the conversation

**Comment by dleonard-uptycs** [comment]
Hey @thaJeztah thanks for the quick response. I forgot to mention something of importance. On restarting a server, we have shutdown service that gracefully stops all containers. On startup, we have a script that runs docker-compose up, which is why the containers are up after a server reboots. So everything should have their restart_policy set at this point right? 

If so, why is it that the docker_compose managed containers do not come up when the docker service is restarted just the first time, but they successfully come up each subsequent time the docker service is restarted, while containers brought up by `docker run` come up every time?

**Comment by thaJeztah** [comment]
I don't know what options the ansible module sets; you can compare configurations (`docker container inspect xxx`) between the ones started through compose and the ones started through ansible.

> So everything should have their restart_policy set at this point right?

It means you're manually starting containers, but I don't see how that sets a restart policy for the container itself. Note that `docker-compose up` does more than just starting the containers, it may also be (re)creating networks, setting up links between containers, etc.

**Comment by dleonard-uptycs** [comment]
For all containers, we are using network mode = host, so comparing a docker-compose managed container to a non-compose managed container's NetworkSettings from `docker inspect` only has difference in `SandboxID` and `EndpointID`. Both of the restart policies between the containers are the same:

```
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            }
```

I have taken a look at all of the other fields in docker inspect as well, there appears to be nothing of substantiative difference between the two.
