### ISSUE TITLE
containerd.sock failed installation

### ISSUE THREAD

**Issue by richdev135** [docker/for-linux#1050]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Successful installation

### Actual behavior
```bash
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
containerd.io is already the newest version (1.2.13-2).
docker-ce-cli is already the newest version (5:19.03.12~3-0~ubuntu-focal).
docker-ce is already the newest version (5:19.03.12~3-0~ubuntu-focal).
0 upgraded, 0 newly installed, 0 to remove and 99 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up docker-ce (5:19.03.12~3-0~ubuntu-focal) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2020-06-28 09:24:20 CST; 9ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 28858 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 28858 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Steps to reproduce the behavior
Followed instructions from [https://docs.docker.com/engine/install/ubuntu/](url)
I ran `$ sudo apt-get install docker-ce docker-ce-cli containerd.io`

**Output of `docker version`:**

```
sudo docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
$ sudo docker info
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Ubuntu 20.04

**Comment by richdev135** [comment]
Output from ```journalctl -xe```

[journal.txt](https://github.com/docker/for-linux/files/4842528/journal.txt)

**Comment by thaJeztah** [comment]
Looks like this may be the problem; 

```
failed to start daemon: Error initializing network controller: list bridge addresses failed:
PredefinedLocalScopeDefaultNetworks List: [172.17.0.0/16 172.18.0.0/16 172.19.0.0/16 172.20.0.0/16 172.21.0.0/16 172.22.0.0/16 172.23.0.0/16 172.24.0.0/16 172.25.0.0/16 172.26.0.0/16 172.27.0.0/16 172.28.0.0/16 172.29.0.0/16 172.30.0.0/16 172.31.0.0/16 192.168.0.0/20 192.168.16.0/20 192.168.32.0/20 192.168.48.0/20 192.168.64.0/20 192.168.80.0/20 192.168.96.0/20 192.168.112.0/20 192.168.128.0/20 192.168.144.0/20 192.168.160.0/20 192.168.176.0/20 192.168.192.0/20 192.168.208.0/20 192.168.224.0/20 192.168.240.0/20]:
no available network
```


When the docker daemon starts, it looks for an available/non-conflicting IP-range to use for the internal (container-container) networks; if all of those IP-ranges are already in use, it will fail as it won't be able to automatically pick an IP-range.

Do you perhaps have a VPN running on that machine? Some VPN installs will "claim" all IP ranges, and can cause that problem.

I don't think there's a bug at hand here, so I'll close the issue, but feel free to continue the conversation

**Comment by richdev135** [comment]
I disabled my VPN and I didn't get this error. Thanks!

I'm experiencing a different error running hello-world, but I'm sure it's got nothing to do with this issue.  I totally appreciate your help.

`$ sudo docker run hello-world
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/a0a121d195e910b0634738e084aaa80e91dd5c5fa33eb50382dfb14571d98e08-init: mount target=/var/lib/docker/aufs/mnt/a0a121d195e910b0634738e084aaa80e91dd5c5fa33eb50382dfb14571d98e08-init data=br:/var/lib/docker/aufs/diff/a0a121d195e910b0634738e084aaa80e91dd5c5fa33eb50382dfb14571d98e08-init=rw:/var/lib/docker/aufs/diff/bef15c0721c08ff6e7c92c8bbd4c6420698460cf02c25f3d9981ac71e3c78ec8=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument.`

**Comment by thaJeztah** [comment]
not sure what's causing that.

Note that the aufs storage driver is being deprecated; if possible I'd recommend using the default (overlay2) storage driver
