### ISSUE TITLE
IPAM config 

### ISSUE THREAD

**Issue by dgarros** [docker/for-linux#1051]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
I suspect this was opened accidentally, as there's no info in the description
