### ISSUE TITLE
Unable to do dns-lookup when using custom user ids

### ISSUE THREAD

**Issue by lightlike** [docker/for-linux#1052]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Proper dns-lookup behaviour

### Actual behavior

Unable to do dns-lookup when using custom user ids

### Steps to reproduce the behavior

1 - Install docker with user id support like:
- any linuxserver.io docker
- itzg/minecraft-server

2 - set custom user-id (like 1009:1001 in my case)
3 - try using any feature that needs to resolve a dns-address

#### Tested

- networks set to host, bridge, custom bridge
- works when setting user-id and group-id to 0 (root) (only tested with Minecraft)
- ping and nslookup in and outside of docker container as root and other users
- dns-configuration is correct

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 9
  Paused: 0
  Stopped: 2
 Images: 11
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.6.0-0.bpo.2-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.47GiB
 Name: srv-omv.local
 ID: TX4U:3RY2:KD7H:WSLP:NPOW:QBXV:23TO:4OPL:37D4:UZL2:KE2D:DLAS
 Docker Root Dir: /srv/dev-disk-by-label-DATA0/Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

HP Proliant Microserver Gen8 (16GB Ram upgrade)
Openmediavault Usul 5.6.0

**Comment by thaJeztah** [comment]
Do you have more details / exact steps how to reproduce? One thing I noticed is that the  image is actually _running_ as `root`, but starts a child-process as a non-privileged user using `su-exec` (which could be related); https://github.com/itzg/docker-minecraft-server/blob/f5dde77efe253e7ac668acb721f6257db32f818d/start#L48

```
exec su-exec ${runAsUser}:${runAsGroup} ${SCRIPTS:-/}start-configuration $@
```


Trying to reproduce on a `busybox` image;

Running container as `root`;

```bash
docker run --rm busybox nslookup -type=A google.com
Server:		67.207.67.2
Address:	67.207.67.2:53

Non-authoritative answer:
Name:	google.com
Address: 108.177.126.100
Name:	google.com
Address: 108.177.126.101
Name:	google.com
Address: 108.177.126.139
Name:	google.com
Address: 108.177.126.102
Name:	google.com
Address: 108.177.126.113
Name:	google.com
Address: 108.177.126.138
```

Running container as non-root;

```bash
docker run --rm -u 1000:1000 busybox nslookup -type=A google.com
Server:		67.207.67.2
Address:	67.207.67.2:53

Non-authoritative answer:
Name:	google.com
Address: 74.125.128.101
Name:	google.com
Address: 74.125.128.102
Name:	google.com
Address: 74.125.128.100
Name:	google.com
Address: 74.125.128.139
Name:	google.com
Address: 74.125.128.138
Name:	google.com
Address: 74.125.128.113
```

And with an alpine image, installing `su-exec` and then running the same as user `1000:1000`;

```bash
docker run --rm alpine sh -c 'apk add --no-cache su-exec && exec su-exec 1000:1000 nslookup -type=A google.com'


fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing su-exec (0.2-r1)
Executing busybox-1.31.1-r16.trigger
OK: 6 MiB in 15 packages
Server:		67.207.67.2
Address:	67.207.67.2:53

Non-authoritative answer:
Name:	google.com
Address: 74.125.128.138
Name:	google.com
Address: 74.125.128.113
Name:	google.com
Address: 74.125.128.139
Name:	google.com
Address: 74.125.128.102
Name:	google.com
Address: 74.125.128.100
Name:	google.com
Address: 74.125.128.101
```

**Comment by lightlike** [comment]
I have no idea what parameters are set during installation or service start.
This is a "set install path", "click install" installation using [omvextrasorg](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg) for openmediavault.

I just tried `nslookup` on [linuxserver/docker-nextcloud](https://github.com/linuxserver/docker-nextcloud)

`user=root`
```
>nslookup google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   google.com
Address: 2a00:1450:4001:814::200e

Non-authoritative answer:
Name:   google.com
Address: 216.58.207.46
```
`user=1000:1000`
```
>nslookup google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   google.com
Address: 2a00:1450:4001:814::200e

Non-authoritative answer:
Name:   google.com
Address: 216.58.207.46
```

but `user=1006:1001` (my user for nextcloud)
```
>nslookup google.com
nslookup: write to '127.0.0.1': Connection refused
;; connection timed out; no servers could be reached
```

which seems weird to me. (I am pretty new to this so I do not know a lot about the inner workings)

When setting the user on nextcloud to 1000:100 (and after fixing errors) it seems that the server works fine. (but I will have to play with that as I do not want any registered user to have access to all these files)

**Comment by lightlike** [comment]
As for the Minecraft docker. It is created with a command similar to this:

```
docker create \
  --name MC1.14.4\
  -p 25565:25565 \
  -e UID=1009 \
  -e GID=1001 \
  -e EULA=TRUE \
  -e VERSION=1.14.4 \
  -e MAX_MEMORY=8G \
  -e TYPE=... \
  -e TZ=Europe/London \
  -v /path/to/files:/data \
  --restart=unless-stopped \
  itzg/minecraft-server
```

Could it be that the problem arises because the other users I use have no admin privileges?

**Comment by thaJeztah** [comment]
Trying with the `nextcloud` image, and that looks to work, but given, those images seem to be setting up a "virtual machine" like environment inside the container (with an init system and multiple services running), and in my steps, I'm overriding the entry point, instead only running the `nslookup`;

```bash
docker run --rm -u 1006:1001 --entrypoint="" linuxserver/nextcloud nslookup -type=A google.com
Server:		67.207.67.2
Address:	67.207.67.2:53

Non-authoritative answer:
Name:	google.com
Address: 74.125.128.139
Name:	google.com
Address: 74.125.128.138
Name:	google.com
Address: 74.125.128.100
Name:	google.com
Address: 74.125.128.113
Name:	google.com
Address: 74.125.128.102
Name:	google.com
Address: 74.125.128.101
```

**Comment by thaJeztah** [comment]
> Could it be that the problem arises because the other users I use have no admin privileges?

Permissions on the host should not matter, apart from possibly that user not having (write) access to bind-mounted files from the host. I'm not familiar enough with those images to tell what's all set-up for users if the container is started with a custom user/group ID.

**Comment by lightlike** [comment]
There might be a problem the users as I made it so the users are unable to change there password and edit themselves (I have no idea what I was thinking there).
I am currently having some other problems with my machine as well which disable me to change anything about those users.

I am planning to reinstall the entire system tomorrow and come back when I have run some more tests.

**Comment by lightlike** [comment]
Did the reinstall and the problem still exists.

0 (root): works
1000: works
100x: does not work

I created 1000 and all of the 100x users in the same way so that cannot be it.
The flag I thought might have been the problem was `disallowusermod` (do not know if this is a linux or omv flag) is not the problem.

This has to be a docker problem, as this happens with docker containers of different authors.

I always get
```
nslookup: write to '127.0.0.1': Connection refused
;; connection timed out; no servers could be reached
```
which seems weird to me.

**Comment by thaJeztah** [comment]
> I created 1000 and all of the 100x users in the same way

Where are you creating the users? Note that for a container, the user doesn't have to exist (when using numeric ID's) the `--user` option specifies the uid/gid used to start the container's process, but containers are not VM's, and there's no "login session" started, only a sandboxed process.

Do you see the problem with a minimal example, e.g. the one I used above;

```
docker run --rm -u 1006:1001 --entrypoint="" linuxserver/nextcloud nslookup -type=A google.com
```

**Comment by lightlike** [comment]
For `docker run --rm -u 1006:1001 --entrypoint="" linuxserver/nextcloud nslookup -type=A google.com` I get:

```
nslookup: read: Connection refused
nslookup: read: Connection refused
;; connection timed out; no servers could be reached
```

**Comment by lightlike** [comment]
I am creating the users on the host machine via web admin interface.
I know that the users do not have to be created in the docker container.

The Problem is: Those Dockers worked before I reinstalled the Host System last Weekend as I borked the Machine.
Could it be that the newer version of OpenMediaVault is at fault (old system installer was 5.0.5 new installer was 5.3.9)?
Should I take this to them?

**Comment by thaJeztah** [comment]
Tried again to reproduce on a fresh Debian 10 machine;

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-8-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.951GiB
 Name: debian-s-1vcpu-2gb-ams3-01
 ID: 4QFV:RINJ:C4VU:IHYJ:WYQX:NVEO:RRUI:6XO2:E27N:DFND:FH4J:SF6L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```


But same result:

```
docker run --rm -u 1006:1001 --entrypoint="" linuxserver/nextcloud nslookup -type=A google.com
Unable to find image 'linuxserver/nextcloud:latest' locally
latest: Pulling from linuxserver/nextcloud
6eb1af1a521f: Pull complete
66fa287bda10: Pull complete
7de41abee0a4: Pull complete
35df37958b43: Pull complete
b9af69d4a348: Pull complete
2242b6f0409d: Pull complete
cf31ef8bebe2: Pull complete
Digest: sha256:9234cf813c6817bc0b225ccc4651011edec63f2093dda75ff8773a72645601ee
Status: Downloaded newer image for linuxserver/nextcloud:latest
Server:		67.207.67.3
Address:	67.207.67.3:53

Non-authoritative answer:
Name:	google.com
Address: 108.177.126.139
Name:	google.com
Address: 108.177.126.100
Name:	google.com
Address: 108.177.126.138
Name:	google.com
Address: 108.177.126.113
Name:	google.com
Address: 108.177.126.102
Name:	google.com
Address: 108.177.126.101
```

I do see you're running with a non-standard Kernel version for Debian (5.x instead of Debian's 4.19 kernel). Could possibly be related (not sure). Also tried on an Ubuntu 20.04 machine with Kernel 5.4, and didn't see the problem there.

**Comment by sam-thibault** [comment]
I don't see any recent activity and this was not reproducible.  I will close it as stale.
