### ISSUE TITLE
Error while running Docker build

### ISSUE THREAD

**Issue by SureshKuchana** [docker/for-linux#1053]
Hi All, could you please help me out.
I am using WSL to run docker
Docker version 19.03.12, build 48a66213fe

FROM python:3.8-alpine

LABEL maintainer="Suresh Koochana"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

RUN mkdir /app

WORKDIR /app

COPY ./app /app

RUN adduser -D user
USER user

output : ---------
Sending build context to Docker daemon  66.05kB
Step 1/10 : FROM python:3.8-alpine
3.8-alpine: Pulling from library/python
df20fa9351a1: Pull complete
36b3adc4ff6f: Pull complete
7031d6d6c7f1: Pull complete
81b7f5a7444b: Pull complete
0f8a54c5d7c7: Pull complete
Digest: sha256:c5623df482648cacece4f9652a0ae04b51576c93773ccd43ad459e2a195906dd
Status: Downloaded newer image for python:3.8-alpine
 ---> 8ecf5a48c789
Step 2/10 : LABEL maintainer="Suresh Koochana"
 ---> Running in 12d351be681d
Removing intermediate container 12d351be681d
 ---> 7dd44c8ea8b3
Step 3/10 : ENV PYTHONUNBUFFERED 1
 ---> Running in 4a48e7220973
Removing intermediate container 4a48e7220973
 ---> dcbc76fd76fd
Step 4/10 : COPY ./requirements.txt /requirements.txt
 ---> 73f308762398
Step 5/10 : RUN pip3 install -r /requirements.txt
 ---> Running in 236e877fca24
Collecting Django==3.0.7
  Downloading Django-3.0.7-py3-none-any.whl (7.5 MB)
Collecting djangorestframework==3.11.0
  Downloading djangorestframework-3.11.0-py3-none-any.whl (911 kB)
Collecting asgiref~=3.2
  Downloading asgiref-3.2.10-py3-none-any.whl (19 kB)
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Installing collected packages: asgiref, sqlparse, pytz, Django, djangorestframework
Successfully installed Django-3.0.7 asgiref-3.2.10 djangorestframework-3.11.0 pytz-2020.1 sqlparse-0.3.1
Removing intermediate container 236e877fca24
 ---> 81121bf5ae29
Step 6/10 : RUN mkdir /app
 ---> Running in f6c99994d1ca
Removing intermediate container f6c99994d1ca
 ---> 0454d34931ae
Step 7/10 : WORKDIR /app
 ---> Running in b58692767391
Removing intermediate container b58692767391
 ---> 5815ed85e9b0
Step 8/10 : COPY ./app /app
**COPY failed: stat /var/lib/docker/tmp/docker-builder955337978/app: no such file or directory**

Thanks & Regards
Suresh Koochana.

**Comment by SuperSandro2000** [comment]
You are trying to copy a directory which does not exist.

**Comment by SureshKuchana** [comment]
@SuperSandro2000  thanks a lot
