### ISSUE TITLE
UCP node is down*

### ISSUE THREAD

**Issue by sharathmankala** [docker/for-linux#1056]
Hi Team,
in Currently we have docker swarm  cluster (2 ucp managers, 3 DTR,8 Worker nodes).
regularly **UCP node is down** and when we have cheeked we found below logs.

1bf03a3dea42        docker/ucp-controller:3.0.16   "/bin/controller -..."   6 weeks ago         Up 2 hours (unhealthy)   0.0.0.0:443->8080/tcp                                                             ucp-controller

Jun 30 06:55:47 <<Server-Name>> dockerd[170345]: time="2020-06-30T06:55:47.013173738-04:00" level=warning msg="failed to deactivate service binding for container ucp-auth-worker.eerffzdv7pf4niyhbdvjmwq4b.7w2gvl2dppk5gvf83ig88ejsf" error="No such container: ucp-auth-worker.eerffzdv7pf4niyhbdvjmwq4b.7w2gvl2dppk5gvf83ig88ejsf" module="node/agent" node.id=eerffzdv7pf4niyhbdvjmwq4b
Jun 30 06:55:47 <<Server-Name>> dockerd[170345]: time="2020-06-30T06:55:47.013249743-04:00" level=warning msg="failed to deactivate service binding for container ucp-auth-api.eerffzdv7pf4niyhbdvjmwq4b.b19c7cw5yekvkwtpmttdwknil" error="No such container: ucp-auth-api.eerffzdv7pf4niyhbdvjmwq4b.b19c7cw5yekvkwtpmttdwknil" module="node/agent" node.id=eerffzdv7pf4niyhbdvjmwq4b
Jun 30 06:55:48 <<Server-Name>> dockerd[170345]: time="2020-06-30T06:55:48.721532640-04:00" level=info msg="raft.node: 5bb381625e03eea5 elected leader 2a9538a8fe219083 at term 128" module=raft node.id=eerffzdv7pf4niyhbdvjmwq4b 

* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Docker Enterprise (UCP, DTR) was acquired by Mirantis, and is no longer maintained by Docker; could you open a  support ticket with the Mirantis team? https://www.mirantis.com/software/docker/docker-enterprise/
