### ISSUE TITLE
Docker setting  http_proxy will proxy all http request？

### ISSUE THREAD

**Issue by hryh** [docker/for-linux#1058]
* [ ] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
I don't know if this is a bug? I configured an HTTP proxy for docker，which also works for other HTTP requests，such as visit a API。

### Actual behavior
I hope docker's proxy does not affect other HTTP requests。

### Steps to reproduce the behavior

**Output of `docker version`:**

Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:34 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Output of `docker info`:**

Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 41qb58ze4gzc0dh9a8qhdlbhv
  Is Manager: false
  Node Address: 192.168.120.171
  Manager Addresses:
   192.168.120.163:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-101-generic
 Operating System: Ubuntu 16.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.41GiB
 Name: worker-171
 ID: RPCQ:PSBJ:EWYI:QYQV:PEVE:OVUM:ZTWE:IUCF:3TDU:5263:Y32R:QQFG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://192.168.120.100:8080
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.120.200
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Can you provide more details? How are you configuring `HTTP_PROXY` / `HTTPS_PROXY`, and what API calls are handled by the proxy ? Are those API calls made on the host? In a container?

**Comment by hryh** [comment]
Of course.
I have three machines,IP 100,171,172. 
100 is the proxy server.171 installed the docker.172 provides a restful API. 
Because docker needs to access the Internet, HTTP proxy is configured. the configuration reference of [docker deamon http proxy](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy).
After the proxy configuration is completed, my docker can pull the image from Internet, but when I use curl to access the HTTP API, it also go to the proxy.
```shell
docker pull nginx  // it's true
curl 192.168.120.172/api/clock // far away
```

**Comment by hryh** [comment]
All HTTP requests from 171 are proxied to 100.
I don't know why. Is that normal?

**Comment by hryh** [comment]
171 joined a docker swarm cluster as a worker.I think this can't affect it.

**Comment by thaJeztah** [comment]
> My configuration
>
>    [Service]
>    Environment="HTTP_PROXY=http://192.168.120.100:808"

That configuration sets the `HTTP_PROXY` environment variable for `dockerd`, but doesn't set it for other processes, so should not affect (say) `curl` in your shell.  Did you perhaps set `HTTP_PROXY` in your `~/.profile` or some other configuration file for your shell?

**Comment by hryh** [comment]
> That configuration sets the `HTTP_PROXY` environment variable for `dockerd`, but doesn't set it for other processes, so should not affect (say) `curl` in your shell. Did you perhaps set `HTTP_PROXY` in your `~/.profile` or some other configuration file for your shell?
I think so,This is a problem on my server, but I did not reproduce it locally. Maybe it is a problem with a certain configuration of the server. However, I did not find it,at least not found in  ~/.profile.
Thank you very much for your answer.
