### ISSUE TITLE
dockerfile multistage build copy, paths given by file

### ISSUE THREAD

**Issue by spotiris** [docker/for-linux#1060]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Motivation
Multistage build dockerfiles can be used to create images which reuse layers and minimise filesize by copying build outputs.
A common build system is CMake, which produces an install_manifest.txt file which points to where the built files have been installed. Each manifest may contain many paths which are required to be copied, from different directories.

Currently the behaviour of `COPY --from BASE SRC DST` requires either the SRC to be a known directory or multiple `COPY` commands be used; one for each line in install_manifest.txt. Producing Dockerfiles with possibly a hundred or more COPY commands is obviously not a good process. 
Because install_manifest.txt lies in the container, it can not be used to produce the COPY commands in the Dockerfile. 

### Proposed feature
Adding a feature to the COPY semantics to be able to read paths from a file on the host or container would enable the programmatic and selective copying of files between builds.
An example:

```docker
# copy using paths on image my_base:1.0.0 tp, default DST would be to mirror the SRC paths
COPY --from my_base:1.0.0 PATHS:/build/my_project/install_manifest.txt
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:              
 Debug Mode: false
                                      
Server:       
 Containers: 57                                                             
  Running: 0                     
  Paused: 0       
  Stopped: 57                                                               
 Images: 83
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true     
  Native Overlay Diff: true
 Logging Driver: json-file    
 Cgroup Driver: cgroupfs 
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-46-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.82GiB
 Name: buffalo
 ID: 4PG7:3OCT:MRWB:XGP2:OA2E:2VFQ:QHWV:6PUB:HJBX:6TE2:UHAY:GBNQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
None

**Comment by thaJeztah** [comment]
I think adding support for and `install_manifest.txt` file is a bit too specific for this purpose (and other tools may use different conventions/formats).

That said, if you enable BuildKit (`DOCKER_BUILDKIT=1`), and use the "experimental" syntax; https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md

You could use the `RUN --mount` option to mount the stage from which you want to copy those files. Then, in the `RUN`, you can parse the `install_manifest.txt` and copy all files that you want to copy.

Something like:

```dockerfile
# syntax=docker/dockerfile:experimental

FROM foo AS build
RUN make build # or whatever you need to run to build, and what generates the `install_manifest.txt`

FROM bar AS final
RUN --mount=from=build,src=/build/my_project/,dst=/somewhere/ \
  cat /build/my_project/install_manifest.txt | xargs cp ............
```

**Comment by spotiris** [comment]
@thaJeztah : This addresses my feature request completely. Thank you for taking the time to reply, I never thought of looking in the experimental docs.

**Comment by thaJeztah** [comment]
Perfect! We still need to decide which of the experimental features could be considered to move out of experimental (which would likely help making them more discoverable)

Glad to hear that it worked for your use-case; while we _do_ accept new features to be added, we always try to keep things "simple" (if possible). Adding features is often the "easy" part; maintaining them, and not ending up with feature-creep is the hard part.

That said: if you have use-cases that you think could be improved; keep 'em coming; it helps the maintainers getting a "feel" for what problems people run into, and may help come up with improvements / new ideas 👍
