### ISSUE TITLE
The static binary install dose not include cli-plugins (buildx, app)

### ISSUE THREAD

**Issue by BarnabyShearer** [docker/for-linux#1066]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

The 19.03.0 client release notes include "Added support for Docker buildx.", and the various distribution packages all include the cli-plugins. It seems reasonable to expect that the static binary release also would.
This is exacerbated by the usage documentation implying you can expect `DOCKER_CLI_EXPERIMENTAL=enabled docker buildx` to just work; and the error message `docker buildx build --platform linux/amd64` "unknown flag: --platform" not being clear you are missing a plugin.
This has caused issues like https://github.com/docker-library/docker/issues/156 in the downstream docker image.

### Actual behavior

```
curl -s https://download.docker.com/linux/static/stable/x86_64/docker-19.03.9.tgz | tar -tz
docker/
docker/docker-init
docker/runc
docker/docker
docker/docker-proxy
docker/containerd
docker/ctr
docker/dockerd
docker/containerd-shim
```

**Comment by cpuguy83** [comment]
@tiborvass

**Comment by thaJeztah** [comment]
Relates to https://github.com/docker/docker-ce-packaging/pull/415. Discussion was still ongoing if the plugins should be included in the static packages, or if they should be in a separate tar.gz to keep size down, and/or in favour of the github release of the plugins (e.g. https://github.com/docker/buildx/releases)
