### ISSUE TITLE
Docker containers use 128 as default "/proc/sys/net/core/somaxconn" value instead of using host machine value

### ISSUE THREAD

**Issue by Zanis7** [docker/for-linux#1068]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker should use host machines somaxconn value

### Actual behavior
Docker assigns 128 as default somaxconn

### Steps to reproduce the behavior
In my docker host the somaxconn value is 16000. But docker assigns somaxconn value as 128 for containers. 
```
$ cat /proc/sys/net/core/somaxconn
16000
$ docker run -it alpine cat /proc/sys/net/core/somaxconn
128
```

I'm able to change it by passing sysctl arg during docker run. Do I have to pass it every-time, even though my host machine has higher somaxconn value ?

```
$ docker run -it --sysctl net.core.somaxconn=4096 alpine cat /proc/sys/net/core/somaxconn
4096
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 35
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 31.26GiB
Name: user
ID: 5MSD:2NII:R5WJ:6NLO:PJYR:O4R4:2MC3:NYQR:M5S3:O3KD:EP27:PKOX
Docker Root Dir: /home/user/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Centos - VM

**Comment by thaJeztah** [comment]
Yes, this is expected; these options are namespaced, and the container gets its own settings for these.

> Do I have to pass it every-time, even though my host machine has higher somaxconn value ?

Yes, this is a run-time option (not something that can be "baked" in the image), so you'll have to set it when starting the container, so either pass the flag when manually running a container, or set it in your `docker-compose.yml` if you use docker-compose to start the container.

Closing this issue because this doesn't look like a bug, but feel free to continue the conversation

**Comment by Zanis7** [comment]
Thanks for your quick support .

> Yes, this is a run-time option (not something that can be "baked" in the image), so you'll have to set it when starting the container,

Is it possible to set this config at any global docker conf, instead of specifying it for every container start. And is there any specific reason why docker chooses the value '128'?

**Comment by Zanis7** [comment]
Okay. Thanks a lot for your support.
