### ISSUE TITLE
docker install failing using yum

### ISSUE THREAD

**Issue by afayaz-mdsol** [docker/for-linux#1073]
I am trying to install docker on amazon workspace using yum, I am getting this error:

    SDAWS\afayaz@a-1a8b3jpiv96s5 ~]$ sudo yum install docker
    Loaded plugins: amzn_workspaces_filter_updates, halt_os_update_check, update-motd
    Resolving Dependencies
    --> Running transaction check
    ---> Package docker.x86_64 0:19.03.6ce-4.amzn2 will be installed
    --> Processing Dependency: runc >= 1.0.0 for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: containerd >= 1.3.2 for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: pigz for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: libcgroup for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Running transaction check
    ---> Package containerd.io.x86_64 0:1.2.13-3.2.el7 will be installed
    --> Processing Dependency: container-selinux >= 2:2.74 for package: containerd.io-1.2.13-3.2.el7.x86_64
    ---> Package libcgroup.x86_64 0:0.41-21.amzn2 will be installed
    ---> Package pigz.x86_64 0:2.3.4-1.el7 will be installed
    --> Finished Dependency Resolution
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nod

I ran it with skip broken, now I got this output

    [SDAWS\afayaz@a-1a8b3jpiv96s5 ~]$ sudo yum install docker --skip-broken
    Loaded plugins: amzn_workspaces_filter_updates, halt_os_update_check, update-motd
    Resolving Dependencies
    --> Running transaction check
    ---> Package docker.x86_64 0:19.03.6ce-4.amzn2 will be installed
    --> Processing Dependency: runc >= 1.0.0 for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: containerd >= 1.3.2 for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: pigz for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Processing Dependency: libcgroup for package: docker-19.03.6ce-4.amzn2.x86_64
    --> Running transaction check
    ---> Package containerd.io.x86_64 0:1.2.13-3.2.el7 will be installed
    --> Processing Dependency: container-selinux >= 2:2.74 for package: containerd.io-1.2.13-3.2.el7.x86_64
    ---> Package libcgroup.x86_64 0:0.41-21.amzn2 will be installed
    ---> Package pigz.x86_64 0:2.3.4-1.el7 will be installed
    
    Packages skipped because of dependency problems:
        containerd.io-1.2.13-3.2.el7.x86_64 from docker-ce-stable
        docker-19.03.6ce-4.amzn2.x86_64 from amzn2extra-docker
        libcgroup-0.41-21.amzn2.x86_64 from amzn2-core
        pigz-2.3.4-1.el7.x86_64 from epel

Can somebody please help me to resolve this.

**Comment by thaJeztah** [comment]
Those looks like packages that are built by amazon; ` docker.x86_64 0:19.03.6ce-4.amzn2` What distro is installed on those environments? If it's CentOS 7, you could try installing the official packages for CentOS 7 works (https://docs.docker.com/engine/install/centos/)

But otherwise, we're unfortunately unable to help, and I would recommend opening a Amazon support ticket.


I'm closing this issue because of the above, but feel free to continue the conversation

**Comment by afayaz-mdsol** [comment]
These are the contents of my /etc/os-release file

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/:

**Comment by thaJeztah** [comment]
Ah, yes, thought about that after I posted; we (currently) don't have packages for Amazon Linux; those are built by Amazon, so best to report there.

**Comment by samuelkarp** [comment]
It looks like you're having problems because you're attempting to install a mix of Amazon Linux 2 packages and CentOS packages on an Amazon Linux 2 host.  You can see this at the bottom of the output you posted:

```
Packages skipped because of dependency problems:
    containerd.io-1.2.13-3.2.el7.x86_64 from docker-ce-stable
    docker-19.03.6ce-4.amzn2.x86_64 from amzn2extra-docker
    libcgroup-0.41-21.amzn2.x86_64 from amzn2-core
    pigz-2.3.4-1.el7.x86_64 from epel
```

The `docker-ce-stable` repository is providing the `containerd.io-1.2.13-3.2.el7.x86_64` package, which has requirements that cannot be fulfilled on Amazon Linux 2.  If you remove this repository, you should be able to install Docker from the `amzn2extra-docker` repository.

**Comment by afayaz-mdsol** [comment]
Thanks a lot , @samuelkarp , it solved the issue: these commands I followed and I was able to successfully install docker on amazon workspace

```
sudo yum remove docker-ce.repo
sudo rpm -qf /etc/yum.repos.d/docker-ce.repo
sudo rm -rf /etc/yum.repos.d/docker-ce.repo

sudo yum clean all
sudo amazon-linux-extras list
sudo amazon-linux-extras enable docker
```

Thanks again,

**Comment by thaJeztah** [comment]
> It looks like you're having problems because you're attempting to install a mix of Amazon Linux 2 packages and CentOS packages on an Amazon Linux 2 host

Good catch, thanks!!

**Comment by duaneguthrie** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=945144#945144
more of the same.
