### ISSUE TITLE
Docker Changing the User's Run Folder on Ubuntu 20.04

### ISSUE THREAD

**Issue by natewiebe13** [docker/for-linux#1074]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
`/run/user/1000/` to remain owned by the user when booting up.

### Actual behavior
`/run/user/1000/` becomes owned by root which breaks multiple system services.

### Steps to reproduce the behavior

**Note:** This doesn't happen on Ubuntu 18.04, but happens on 20.04. Likely `dockerd` just needs to start later in the boot cycle.

1. Have your primary user added to the `docker` group so it can run commands.
2. Have a service that bind-mounts the ssh agent socket and will start on reboot.
```yaml
version: '3.5'

services:
    php:
        image: php:7.4-fpm
        environment:
            SSH_AUTH_SOCK: /ssh-agent
        restart: unless-stopped
        volumes:
            - $SSH_AUTH_SOCK:/ssh-agent
```
3. Start the setup with `docker-compose up -d`
4. Restart your computer
5. Running `journalctl --boot | grep /run/user/1000`, you should see output like:
```
Jul 29 09:55:32 nate dockerd[1724]: time="2020-07-29T09:55:32.466385600-04:00" level=error msg="Failed to start container 9ae00385f15f8fc675a88825d9b697ba3e2b31a865f97e8e7a1e7d068d378321: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/run/user/1000/keyring/ssh\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/16f731202b84b51ff24875a52597dca77fa4bedfcba9685257cdab00c8fa0fd7/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/16f731202b84b51ff24875a52597dca77fa4bedfcba9685257cdab00c8fa0fd7/merged/ssh-agent\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"
Jul 29 09:58:07 nate systemd[1]: Starting User Runtime Directory /run/user/1000...
Jul 29 09:58:07 nate systemd[1]: Finished User Runtime Directory /run/user/1000.
Jul 29 09:58:07 nate systemd[4921]: pam_systemd(systemd-user:session): Runtime directory '/run/user/1000' is not owned by UID 1000, as it should.
Jul 29 09:58:07 nate gdm-password][4911]: pam_systemd(gdm-password:session): Runtime directory '/run/user/1000' is not owned by UID 1000, as it should.
Jul 29 09:58:13 nate ubuntu-software-service.desktop[5571]: cmd_run.go:927: WARNING: cannot start document portal: Expected portal at "/run/user/1000/doc", got "/home/nate/.cache/doc"
Jul 29 09:58:14 nate ubuntu-software-service.desktop[5639]: mkdir: cannot create directory '/run/user/1000/snap.snap-store': Permission denied
Jul 29 09:58:15 nate snap-store[5571]: unable to create directory '/run/user/1000/snap.snap-store/dconf': Permission denied.  dconf will not work properly.
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 228
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: nate
 ID: W2HS:4DFB:L3OW:2SVK:AOVF:MXZZ:5PAT:XCN4:U43L:IYVB:67D7:4QVB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: natewiebe13
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
I think I understand what's happening, but don't think there's an easy (or at least not a "generic") solution.


I suspect Ubuntu 20.04 started using `$XDG_RUNTIME_DIR` for the ssh agent. `$XDG_RUNTIME_DIR` is specific to each user, and (see the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)) is bound to the user's login session;

> The lifetime of the directory MUST be bound to the user being logged in. It MUST be created when the user first logs in and if the user fully logs out the directory MUST be removed. 

The problem in this case is that;

The docker daemon is a "system" process, it's not bound to a specific user. The docker service is started before users are logged in (which also is the common situation for a server situation)

However, the container you created;

- Has a restart policy; it will be restarted when docker restarts (and docker is not aware that that specific container assumes a login session is started for user "X")
- While the compose file uses `$SSH_AUTH_SOCK` to get the correct path for the socket, that environment variable will only be evaluated when the container is created. After that, the container's configuration is immutable. (so even if the ssh-agent is started when the container starts, it _could_ mean it's looking for an old / wrong location)
- The compose file uses the "short-hand" notation to define the bind-mount (`<host-path>:<container-path>`). The short-hand notation will automatically create the path on the host if it's missing. That seemed like a "good idea" at the time, but in hind-sight is causing many issues (we tried deprecating the behavior, but too many people rely on it, so we had to revert that https://github.com/moby/moby/pull/21666).
    If the path (`$SSH_AUTH_SOCK` in this case) isn't found when the container is started, the docker daemon will create the path on the host. Given that it has no knowledge if the path is expected to be a "directory" or a "file", the default ("directory") is assumed, and because the daemon runs as `root`, the path is created with `root` as owner. Effectively, this means that when the container is started, and `$SSH_AUTH_SOCK` is missing (which is the case until the user logs in), that the daemon creates a directory with that name.

As a workaround, you can use the long-form notation to specify the bind-mount; https://docs.docker.com/compose/compose-file/#long-syntax-3 (which is the equivalent of the long-form `--mount` flag on `docker run`). The long-form syntax uses a different API, and will _not_ automatically create the path on the host; instead, it will produce an error (which causes the container to fail when starting, until the path in `$SSH_AUTH_SOCK` is found. With a restart policy set on the container, this will likely mean the container will continue fail (and be restarted) until the user logs in.

**Comment by natewiebe13** [comment]
Would this also be an issue if/when ssh forwarding gets implemented? [[blog post](https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066)]

**Comment by thaJeztah** [comment]
That option is already implemented, but used during `docker build`; in addition, ssh forwarding doesn't mount the ssh-agent in the container, and that approach is more secure than mounting it.

Does your container need access to the ssh-agent at runtime? Giving your container access means that if the container is compromised, everyone would have access to it.

**Comment by natewiebe13** [comment]
Right, that's for build time. We were using the ssh agent for development only when bind-mounting the project to the container, which doesn't happen with production. We've started moving from using SSH_AUTH_SOCK to bind-mounting our ssh keys read-only. I think we can close this one out.

**Comment by thaJeztah** [comment]
> We've started moving from using SSH_AUTH_SOCK to bind-mounting our ssh keys read-only

We've had some discussion about implementing the same feature  as `docker build --ssh` for `docker run`, but not sure if it's being worked on already.

> We were using the ssh agent for development only when bind-mounting the project to the container

If this is for development only (for interactive work on the project), perhaps disabling the restart policy (to prevent the containers from automatically restarting on reboot) would help as well.

**Comment by natewiebe13** [comment]
> If this is for development only (for interactive work on the project), perhaps disabling the restart policy (to prevent the containers from automatically restarting on reboot) would help as well.

This and using longhand like you suggested earlier were both options we had considered. Our decision to bind-mount ssh keys had a few advantages for us.

- Removing the dependency on the ssh-agent (which we don't typically have running in our server envs for example) reduces the complexity in our pipelines for building the images and deploy scripts that would typically have to start up an ssh-agent and wrap commands, ex: `ssh-agent bash -c 'docker-compose ...'`
- Not all of our team is super familiar with docker, ssh-agents, etc. which can cause confusion and time spent debugging when ssh-agents are started at the wrong times, or don't match the behavior of ssh on the host. Pointing to a file using a bind-mount is easier to understand.
- Since this is also closer to how we do things in production, it removes more differences between development and production, which is typically ideal. This also keeps the docker-compose file lighter and in our case reduced total number of lines.

Appreciate your feedback with all of this!

**Comment by derflocki** [comment]
@thaJeztah I have been dealing with weird issues lately and it turns out I had the same problem @natewiebe13 described here. Thanks you @thaJeztah for identifying the issue and provinding a workaround!

**Comment by tonynajjar** [comment]
That's such a crazy bug with symptoms very far from the root cause; to land on this issue I went through:

1. no sound on my laptop
2. realizing pulseaudio is not launched
3. getting an error when listing user services:
```
tony@tony-xmg-22:~$ systemctl --user

Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```
4. realizing that:

```
pam_systemd(systemd-user:session): Runtime directory '/run/user/1000' is not owned by UID 1000, as it should.
```

5. finally landing on this issue. I have the same docker compose configuration.

Thanks @natewiebe13  for reporting and thanks @thaJeztah for the workarounds!

**Comment by tonynajjar** [comment]
Actually following up on this, 

> As a workaround, you can use the long-form notation to specify the bind-mount; https://docs.docker.com/compose/compose-file/#long-syntax-3 (which is the equivalent of the long-form --mount flag on docker run)

I tried this and it did not fix the issue. I am still to try removing the restart policy but I'm pretty sure it will work. However it would be really useful to keep the restart policy, is there no plan to fix this issue to avoid having to workaround it? Thanks
