### ISSUE TITLE
Debian packaging should also state "Provides: docker.io"

### ISSUE THREAD

**Issue by progtologist** [docker/for-linux#1077]
* [x] This is a bug report
* [ ] This is a feature request
* [X] I searched existing issues before opening this one

### Expected behavior
I have a debian package that states that it depends to docker.io. If a machine has installed docker-ce instead of docker.io I would expect that dependency to be considered fulfilled.

### Actual behavior
Apt states that docker-ce is not a replacement of docker.io, it only conflicts.

### Steps to reproduce the behavior

Running the following returns an empty string
```bash
apt-cache show docker-ce | grep Provides
```
Running the same for openresolv returns that it provides the same functionality as resolvconf
```bash
apt-cache show openresolv | grep Provides
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 3
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 Name: asynodinos
 ID: AHNZ:ANUG:EAI4:62VP:CMDF:ZGRK:RXXI:EODU:4JJV:DPEV:AB2B:GAL3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Physical system with Ubuntu 16.04, though looking at [this](https://github.com/docker/docker-ce/blob/master/components/packaging/deb/common/control) I am not expecting a different result on other debian based systems.

**Comment by thaJeztah** [comment]
Thanks for reporting! I was about to open a pull request to add it, then realised this may not work.

Both the `docker-ce` package and `docker-ce-cli` packages have a  `Conflicts` with the `docker.io` package; https://github.com/docker/docker-ce-packaging/blob/cf232a5b827952d61efa4c0d2489019c19197111/deb/common/control#L43-L48

https://github.com/docker/docker-ce-packaging/blob/cf232a5b827952d61efa4c0d2489019c19197111/deb/common/control#L64-L69

```
Conflicts: docker (<< 1.5~),
           docker-engine,
           docker-engine-cs,
           docker.io,
           lxc-docker,
           lxc-docker-virtual-package
```

Referring to the Debian packaging documentation; https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides

> ## 7.5. Virtual packages - Provides
>
> ...
> If there are both concrete and virtual packages of the same name, then the dependency may be satisfied (**or the conflict caused**) by either the concrete package with the name in question or any other concrete package which provides the virtual package with the name in question. 


If I understand that correctly (_"or the conflict caused"_), it would mean that if the `docker-ce` (the "daemon" package) would _Provide_ `docker.io`, it would mean that now the `docker-ce-cli` would _conflict_ with the `docker-ce` package.

I'm not 100% sure if I'm correct though; @tianon perhaps you know?

So, the alternative would be that the package you're installing would either change `Depends: docker.io` to `Depends: docker-ce`, or to `Depends: docker.io | docker-ce` (or maybe the `docker.io` package should `Provides: docker-ce`. but not sure how that would play out.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker-ce-packaging/pull/491 to discuss/test

**Comment by tianon** [comment]
Copying my thought from https://github.com/docker/docker-ce-packaging/pull/491#issuecomment-671591996: it feels wrong to me to have a package that `Depends: docker.io` -- I would expect `Recommends:` at most for a relation like that (even more especially in a world of compatible alternatives, but mostly because a second package cannot reasonably expect to use the installed Docker successfully in all cases without some help/configuration).

**Comment by thaJeztah** [comment]
Let me close this one, per the discussion above
