### ISSUE TITLE
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by agfn** [docker/for-linux#1078]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
```
pull ubuntu:20.04 
```

### Actual behavior
```
Sending build context to Docker daemon  2.048kB
Step 1/1 : from ubuntu:20.04
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
``` 

### Details

It works fine before. I have try some mothods in the previous issue, such as  "fix dns", "change proxy", ..., none of these works.

And the url is  accessible.

```
$ curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

### Steps to reproduce the behavior

```
$ cat Dockerfile
from ubuntu:20.04

$ docker build .
...
```

**Output of `docker version`:**

```
Docker version 19.03.5, build 633a0ea838
```

**Output of `docker info`:**

```
Sending build context to Docker daemon  2.048kB
Step 1/1 : from ubuntu:20.04
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
```
Ubuntu 18.04 (VMware)
```

**Comment by tienthegainz** [comment]
@agfn Did you find a workaround? I fixxed my DNS as previous issue but it is still not working.
