### ISSUE TITLE
docker-ce package for CentOS8/RHEL8

### ISSUE THREAD

**Issue by ChristophSeidl** [docker/for-linux#1082]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

Please provide the rpm's for CentOS 8 / RHEL 8.
https://download.docker.com/linux/rhel/

There is already a packaging file, but somehow it's not available for download.
https://github.com/docker/docker-ce-packaging/tree/master/rpm/centos-8

**Comment by mattvw** [comment]
Duplicate of https://github.com/docker/for-linux/issues/873

**Comment by chris-crone** [comment]
Hi @ChristophSeidl. We do now have packages for CentOS 8: https://download.docker.com/linux/centos/8/
