### ISSUE TITLE
Strong passwords with special symbols may not be supported by docker login --password-stdin

### ISSUE THREAD

**Issue by rirlswift** [docker/for-linux#1085]
Strong passwords cause problems with docker login even when using --password-stdin arguments
Assuming a strong password (lZ7"iK5~fK8%vM3*lG6%qE0;dA4,cW6~) and user name (someuser)

```
echo '(lZ7"iK5~fK8%vM3*lG6%qE0;dA4,cW6~'| docker login https://registry.somesite.com --username someuser --password-stdin
```

reports

```
Error response from daemon: login attempt to https://registry.somesite.com/v2/ failed with status: 401 Unauthorized
```

* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
docker login with strong passwords including symbols such as ` ! ” ? $ ? % ^ & * ( ) _ – + = { [ } ] : ; @ ‘ ~ # | \ < , > . ? /`
should work regardless of the special symbols in the password

### Actual behavior

```
echo '(lZ7"iK5~fK8%vM3*lG6%qE0;dA4,cW6~'| docker login https://registry.somesite.com --username someuser --password-stdin

Error response from daemon: login attempt to https://registry.somesite.com/v2/ failed with status: 401 Unauthorized
```

 leading and trailing `'` are NOT part of the password, but are required to escape special symbols for the shell.

### Steps to reproduce the behavior
Generate a bunch of random passwords for a docker user. Sooner, or later, docker login in the form above will encounter a sequence that it cannot handle.

In particular this happens with the specific strong password list above in actual behavior.
Note: Running docker login interactively 

```
docker login https://registry.somesite.com --username someuser
```

and pasting the identical strong password in results in a successful login!

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 36
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: snipped
 ID: snipped
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
 snipped
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support


```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

No special environment is required.

**Comment by rirlswift** [comment]
As a workaround generate a random, long (length of 32) password **WITHOUT** special symbols

**Comment by rirlswift** [comment]
Will encounter the identical error if you store the strong password in a file (yikes) and use cat

**Comment by thaJeztah** [comment]
I changed the password for a test-account on Docker Hub to your example, but I'm not able to reproduce the problem;

Tried both on Docker Desktop for Mac;

```console
docker logout
echo '(lZ7"iK5~fK8%vM3*lG6%qE0;dA4,cW6~' | docker login --username mytestaccount --password-stdin
Login Succeeded
```

And on a Linux machine without a credential helper;

```console
echo '(lZ7"iK5~fK8%vM3*lG6%qE0;dA4,cW6~' | docker login --username mytestaccount --password-stdin

WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```


Are you only seeing this problem on your own registry, or also when authenticating to Docker Hub?

**Comment by thaJeztah** [comment]
I _do_ notice you're running an outdated version of Docker 19.03 (19.03.2 is a very old patch release; current version is 19.03.12); are you seeing the same issue on a current patch release?

**Comment by arjitj2** [comment]
@thaJeztah I believe I'm seeing this same issue on Docker 20.10.14

**Comment by JPvRiel** [comment]
In my own similar case, I noticed the problem was not the password. It was the user ID. The website is forgiving with case and will accept mixed case, e.g. `CamelCase` is a valid user ID for browser based login to https://hub.docker.com, but  you must use lowercase in the CLI login command, e.g. `camelcase`

**Comment by sam-thibault** [comment]
We were not able to reproduce the original described issue.  It seems some other comments are different issues.  With regard to Docker Hub UI regarding upper-case.  Can you open a ticket in the Hub feedback issue tracker? https://github.com/docker/hub-feedback
