### ISSUE TITLE
Docker with Version18.06.1-ce  is hitting High Load Average and CPU issue always -CPU stuck is caused and System going down

### ISSUE THREAD

**Issue by venkatasaikrishna316** [docker/for-linux#1092]
Isuse: watchdog bug soft lockup - cpu#0 stuck for 22s 
docker 18.06.1-ce is always hitting HIGH Load averages and CPU  issue in linux Rhel machines and system is crashing with CPU stuck issue
[root@irlcmgperf25 uptime]# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Also attached my CPU utilization issue and high load average process in the attachment.

[load_issue.txt](https://github.com/docker/for-linux/files/5134985/load_issue.txt)

**Comment by cpuguy83** [comment]
Please post your `load_issues` into a gist or something.

That said, there is really not any information to go on here.
Other than you are using a very old version of Docker that should be updated (18.06 is out of support).

Is there any information in the docker daemon  logs? If you are using systemd+journald, this would be accessible from `journalctl -u docker`.

**Comment by sam-thibault** [comment]
I don't see any more info on this issue, so closing it as stale.
