### ISSUE TITLE
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /var/lib/dpkg/info/gcc-8-base:amd64.list: invalid argument.

### ISSUE THREAD

**Issue by suiwenfeng** [docker/for-linux#1116]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker run -p 8080:8080 hazelcast/management-center (worked in other platform)

### Actual behavior
[xxx@xxx xxx]$ docker run -p 8080:8080 hazelcast/management-center
Unable to find image 'hazelcast/management-center:latest' locally
latest: Pulling from hazelcast/management-center
096ebeedeeb6: Extracting [==================================================>]  26.57MB/26.57MB
3ac6aea685cb: Download complete 
d1b0083010f5: Download complete 
acc1dbecb164: Download complete 
83a5fcbdde9d: Download complete 
6741f9e1ab31: Download complete 
923cc8754bc4: Download complete 
87eb545149a1: Download complete 
ef239334f6ec: Download complete 
6e92c411b9d7: Download complete 
latest: Pulling from hazelcast/management-center
096ebeedeeb6: Extracting [==================================================>]  26.57MB/26.57MB
3ac6aea685cb: Download complete 
d1b0083010f5: Download complete 
acc1dbecb164: Download complete 
83a5fcbdde9d: Download complete 
6741f9e1ab31: Download complete 
923cc8754bc4: Download complete 
87eb545149a1: Download complete 
ef239334f6ec: Download complete 
6e92c411b9d7: Download complete 
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /var/lib/dpkg/info/gcc-8-base:amd64.list: invalid argument.
See 'docker run --help'.

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.12
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.8.10-200.fc32.x86_64
 Operating System: Fedora 32 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.53GiB
 Name: localhost.localdomain
 ID: RZTG:MDW2:R76W:526B:IUT4:NLWJ:IJQM:NWKS:MFER:CPP3:6TWT:77V2
 Docker Root Dir: /run/.ro862781557/media/low/2D97AD940A9AD661
 Debug Mode: false
 Username: suiwenfeng
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by AkihiroSuda** [comment]
Could you try nightly build?

```
systemctl --user stop docker
rootlesskit rm -rf .local/share/docker
rm -rf ~/bin/{docker*,containerd*,runc,rootless*}
curl -fsSL https://get.docker.com/rootless | CHANNEL=nightly sh
```

**Comment by zhuyang2356** [comment]
how do you solve the problem? I have the same issue
