### ISSUE TITLE
Not able to run Docker with cgroups being read-only in rootless mode

### ISSUE THREAD

**Issue by kenorb** [docker/for-linux#1124]
* [x] This is a bug report (related: #219, #903)
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

I'm running hello-world container using Docker 19.03.6 in Colab, but I've got the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/cpuset/215b4c6676e3f7373d2b44011f9b4e497974fcfaaa441be9a0a1074c7ea303c2: read-only file system\"": unknown.

despite I'm running dockerd in rootless mode as:

```
dockerd -b none --experimental --iptables=0 -l info --rootless
```

**Output of `docker version`:**

```
Docker version 19.03.6, build 369ce74a3c
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 1
 Server Version: 19.03.6
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: none
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 4.19.112+
 Operating System: Ubuntu 18.04.5 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 12.72GiB
 Name: 9a181768fd59
 ID: URQ4:QXQW:QQPA:4F2N:6UHY:LP6H:24JI:TB32:EGKH:VUVJ:CUZT:6CRY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

- [Colab](https://colab.research.google.com/)

Demo link:

- https://colab.research.google.com/drive/1Lmbkc7v7XjSWK64E3NY1cw7iJ0sF1brl

**Comment by kenorb** [comment]
### Workaround

For the workaround to go further, I've unmounted cpuset (`umount -vl /sys/fs/cgroup/cpuset`), however there is similar error after that.

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/devices/79fa575f45b7359172101e46cc0b3cc03e3b75e8a81e8856731aba2e24d7ecec: read-only file system\"": unknown.

See: https://colab.research.google.com/drive/1RVS5EngPybRZ45PQRmz56PPdz9nWStIb

**Comment by AkihiroSuda** [comment]
Make sure you are running rootless dockerd inside RootlessKit? (dockerd-rootless.sh)

**Comment by kenorb** [comment]
> Make sure you are running rootless dockerd inside RootlessKit? (dockerd-rootless.sh)

I've tried to run Docker using `dockerd-rootless.sh`, but it fails with:

> [rootlesskit:child ] error: executing [[ip tuntap add name tap0 mode tap] [ip link set tap0 address 02:50:00:00:00:01]]: exit status 1

Related issue: https://github.com/rootless-containers/rootlesskit/issues/181

So I think the rootless wrapper script is overdoing some network params:

> + exec rootlesskit --net=vpnkit --mtu=1500 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run /opt/docker/bin/dockerd-rootless.sh --experimental --iptables=false --storage-driver vfs

However when I run rootlesskit+dockerd directly as:

```
rootlesskit --debug --disable-host-loopback --copy-up=/etc --copy-up=/run /opt/docker/bin/dockerd -b none --experimental --iptables=false --storage-driver vfs &
```

It's no longer complains about `ip`, but gives another error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"join session keyring: create session key: operation not permitted\"": unknown.

Colab demo: https://colab.research.google.com/drive/1oRja4v-PtY6lFMJIIF79No4s3s-vbqd4#scrollTo=rc4DjM3jcL8Z

**Comment by kenorb** [comment]
It seems Rootlesskit version is useless, as it fails to run `ip tuntap add name tap0 mode tap`, but that's the point of not having the rootless mode, to not have root.

I've upgraded Docker to the latest and it works better. Most of the above errors are gone.

Steps:

```
%%shell
curl -s https://download.docker.com/linux/static/stable/x86_64/docker-19.03.9.tgz | tar vxz --strip=1 -C /usr/local/bin/
docker --version
```

```
%%shell
set -x
dockerd -D -b none --iptables=0 -l debug &
for i in $(seq 5); do [ ! -S "/var/run/docker.sock" ] && sleep 2 || break; done
docker info
docker version
docker run hello-world
docker run alpine id
kill $(jobs -p)
```

Demo: https://colab.research.google.com/drive/1OfbZGl_TLv5m_yiYPz0MrQIYe0z4nbOP#scrollTo=VhgKc1a6zMTq

Follow up bug: https://github.com/moby/moby/issues/41541

**Comment by AkihiroSuda** [comment]
Please see https://github.com/rootless-containers/rootlesskit/issues/181#issuecomment-706496478

**Comment by LifangD** [comment]
hi @kenorb , I've met the similar issue, and have you solved it? looking forward to your reply and help!

**Comment by kenorb** [comment]
> I've met the similar issue, and have you solved it?

I don't as far as I remember. Try upgrading Docker to the latest version, maybe some things are already fixed.
