### ISSUE TITLE
Docker version compatibility 

### ISSUE THREAD

**Issue by skdjango001** [docker/for-linux#1132]
Hi Team,
I am new to Docker Family and I have a query, I build a docker image on 19.X Docker Engine version, And I want to use that Image on lower versions of Docker Engine (suppose: 18.X) and start the container will it work smoothly on 18.X and 19.X as well or is there any compatibility issues on 18.X ?

same vice versa, if I build a docker image on 18.X docker Engine and same image I want to test on 19.X version as well it will work on every version smoothly or is there any issue on different versions?

**Comment by thaJeztah** [comment]
Both should work fine; docker images follow the OCI image spec (https://github.com/opencontainers/image-spec), and should be compatible with both older and newer versions of docker

**Comment by skdjango001** [comment]
Thanks @thaJeztah, 
I am trying to install docker on linux machine "Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-27-generic x86_64)" on this version   I am trying to install docker with installation steps as per docker.com.

When I am trying to run the command "sudo apt-get install docker-ce docker-ce-cli containerd.io"  I am getting the below error:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce-cli
?
Need solution for this ?

**Comment by thaJeztah** [comment]
Ubuntu 14.04 reached EOL, and we no longer publish new versions of docker for that version of Ubuntu. The last version of docker that was built for Ubuntu 14.04 was docker 18.06, which does not yet have the cli in a separate package, so instead you need to only install `docker-ce` (which includes the CLI) and `containerd.io`; 

```
sudo apt-get install docker-ce containerd.io
```

However, I would _HIGHLY_ recommend updating to an actively maintained version of Ubuntu (and Docker), because both Ubuntu 14.04 and Docker 18.06 are EOL, do not receive bug and security fixes, and are known to have vulnerabilities (some of which _critical_).

**Comment by skdjango001** [comment]
Thanks @thaJeztah  for a quick replay 
I had another problem while installing the above command.on same machine Ubuntu 14.04 version
I am getting below error:
--------------------------------------------------------------------------------------------------
sudo apt-get install docker-ce containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 containerd.io : Depends: libseccomp2 (>= 2.3.0) but 2.1.1-1ubuntu1~trusty5 is to be installed
E: Unable to correct problems, you have held broken packages.
-----------------------------------------------------------------------------------------------------------------
Is there any solution for this or should I  run only sudo apt-get install docker-ce  instead of sudo apt-get install docker-ce containerd.io  ?? Is containerd.io will cover under docker-ce input.

**Comment by thaJeztah** [comment]
> Is there any solution for this or should I run only sudo apt-get install docker-ce instead of sudo apt-get install docker-ce containerd.io ?? Is containerd.io will cover under docker-ce input.

Ah, yes, the docker-ce 18.06 package still had `containerd.io` included in it, so you don't have to install `containerd.io` separately.

I still _strongly_ encourage you to update to a current version of Ubuntu. Both Ubuntu 14.04 and Docker 18.06 have known vulnerabilities (and I think that includes possible container escapes, which means that a container can obtain full root access on the host machine)

**Comment by thaJeztah** [comment]
Let me close this ticket as it's not a bug-report, but feel free to continue the conversation
