### ISSUE TITLE
linux access command giving the wrong answer for X_OK for a non-executable file in a shared volume

### ISSUE THREAD

**Issue by r-owen** [docker/for-linux#1135]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

The linux command access(path, F_OK) should return False for a file that is not executable.

### Actual behavior

When the file is in a shared volume the access command above returns True for a file that is not executable. This despite `ls -l` showing that the file is not executable.

### Steps to reproduce the behavior

1) On macOS (I have 10.14.6): create a directory containing at least one file that is not executable.

2) Run a Docker image that runs CentOS Linux release 7.7.1908 (Core), mounting that directory into the image.
It simplifies the test if the Docker image includes Python (I have 3.7.8 but it should not matter), but it suffices to have gcc.

3) Run the following code inside the image:
```
python -c "import os; print(os.access(<path-to-non-exe-file>, os.X_OK))"
```
I see True if the file is not executable and is on my shared volume, which is incorrect.
I see the correct result of False  if the file is not executable and is internal to the Docker image.

If you would rather not use Python then compile and run the following C++ code.
I get the same results with it as I do with the Python test above.
```
#include <errno.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char* argv[]) {
    if (argc < 2) {
        printf("one argument required: the path\n");
        return 1;
    }

    char* path = argv[1];
    int rval;

    /* Check file existence. */
    rval = access(path, F_OK);
    if (rval == 0)
        printf("%s exists\n", path);
    else {
        if (errno == ENOENT) {
            printf("%s does not exist\n", path);
        } else if (errno == EACCES) {
            printf("%s is not accessible\n", path);
            return 0;
        }
    }

    /* Check executable access. */
    rval = access(path, X_OK);
    if (rval == 0) {
        printf("%s is executable\n", path);
    } else {
        printf("%s is not executable\n", path);
    }
}
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 9.737GiB
 Name: docker-desktop
 ID: VRRF:OCAS:J3SQ:5HIW:GK3Z:JA4A:VDKW:JHSQ:ET6Y:GTJ7:MONZ:7VK7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 55
  Goroutines: 68
  System Time: 2020-10-23T22:29:19.9940502Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

macOS 10.14.6
And in the Docker image:
* CentOS Linux release 7.7.1908 (Core)
* gcc (crosstool-NG 1.24.0.123_1667d2b) 7.5.0
* Python 3.7.8

**Comment by thaJeztah** [comment]
I suspect this is an issue that's specific to Docker for Mac, which uses a FUSE mount to bind mount files from the macOS host into the VM in which the container runs

If you have access to a Linux machine, are you able to reproduce the problem on that as well, or only on Docker for Mac?

**Comment by r-owen** [comment]
I would be very surprised if this bug showed up on linux, since all file permissions seem to leak through, including file ownership. But I'll see if anybody in my group has access and can test this.

**Comment by thaJeztah** [comment]
Yes, on Linux, there's no FUSE mount in place, and bind-mounts are just plain bind-mounts.

Here's on macOS;

```bash
touch non-executable.txt
ls -la non-executable.txt
-rw-r--r--  1 sebastiaan  staff  0 Oct 29 16:48 non-executable.txt

docker run -it --rm -v $(pwd):/foo python:alpine python -c "import os; print(os.access('/foo/non-executable.txt', os.X_OK))"
True
```

And the same on Linux;

```bash
touch non-executable.txt
ls -la non-executable.txt
-rw-r--r-- 1 root root 0 Oct 29 15:51 non-executable.txt

docker run -it --rm -v $(pwd):/foo python:alpine python -c "import os; print(os.access('/foo/non-executable.txt', os.X_OK))"
False
```


Given that this is specific to Docker Desktop, could you open a ticket in the docker for mac issue tracker https://github.com/docker/for-mac/issues ? Unfortunately I can't move the ticket, because it is in another organisation on GitHub (GitHub doesn't support moving tickets between organisations).

Let me close the ticket here, because the issue is not in the code maintained in this repository, but feel free to continue the conversation 👍

**Comment by r-owen** [comment]
The for-mac ticket: https://github.com/docker/for-mac/issues/5029
