### ISSUE TITLE
Centos Linux repo directory 7Server has permissions issue (403 error)

### ISSUE THREAD

**Issue by rabievdm** [docker/for-linux#1141]
Access the Docker Linux Repo and going to:
https://download.docker.com/linux/centos/7Server/
Produces an access denied error, changing the '7Server' to '7' works, but all RHEL/CentOS/OEL releasever is 7Server and thus break YUM, assuming this is a symlink that's either broken or follow symlink is not allowed on the webserver:
403 Forbidden
    Code: AccessDenied
    Message: Access Denied
    RequestId: C8B17CF0D18D3CD3
    HostId: JVO0QMk2EOHbHr/8EogGjoXisRRZEUN/SD8VUW/4AJv+WkdZ05KIlTvPWEz0zbUISa+272XnzM4=

**Comment by jota3c** [comment]
Same here, under https://download.docker.com/linux/centos/ only the subdir 7 and 8 are working. 
The 7.x, 8.x, [7|8][client|server|wokstation] are broken with 403.

**Comment by rabievdm** [comment]
Duplicate of [https://github.com/docker/for-linux/issues/1111](url)
