### ISSUE TITLE
A way to stop Docker from printing container logs

### ISSUE THREAD

**Issue by jakubgs** [docker/for-linux#1151]
### Expected behavior

I'd like Docker to stop spamming my systemd journal with container logs. I have a configuration that redirects logs to `rsyslog` and manages them separately, and yet my journal is filled with container logs as well.

### Actual behavior

The logs still appear in `docker` service logs shown by `journalctl`:
```
 > sudo journalctl -u docker -n 1 --no-pager
-- Logs begin at Tue 2020-11-24 09:12:29 UTC, end at Tue 2020-11-24 09:54:03 UTC. --
Nov 24 09:54:03 host-01.example.org docker/my-container[583]: some kind of log message
```

### Steps to reproduce the behavior

My config:
```json
{
  "log-driver": "syslog",
  "log-opts": {
    "syslog-facility": "local6",
    "env": "my-fleet",
    "tag": "{{.DaemonName}}/{{.Name}}"
  }
}
```

### Details

I checked flags of `dockerd` but there doesn't seem to be any flag that can address this:
```
 > dockerd -h | grep log
      --log-driver string                       Default driver for container logs (default "json-file")
  -l, --log-level string                        Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default
      --log-opt map                             Default log driver options for containers (default map[])
      --raw-logs                                Full timestamps without ANSI coloring
```
Changing `--log-level` to `warn` or `error` doesn't seem to stop the flow of container logs.

**Comment by thaJeztah** [comment]
Not sure if I understand the request; if you don't want container logs to be sent to your system logs, why do you configure the `syslog` driver to be used for containers?

Note that the `--log-driver` option is the default logging-driver for _containers_, not for the daemon itself; the daemon itself logs to stdout/stderr and if you run it as a systemd unit, systemd will handle those logs (and send them to journald)

**Comment by jakubgs** [comment]
The service in question is producing a LOT of logs. I mean a LOT. Which is why I'm using `syslog` driver to redirect them to a separate volume via `rsyslog`. But because the `dockerd` also prints the container logs out via its `stdout` it is also recorded by Systemd journal, which causes it to be constantly trimmed over and over again in effect losing logs for all other services.

**Comment by thaJeztah** [comment]
> But because the dockerd also prints the container logs out via its stdout

Hmm, the daemon does not output logs of the container itself

**Comment by jakubgs** [comment]
Oh, interesting, then what causes them to show up under `journalctl -u docker`?

**Comment by thaJeztah** [comment]
Wondering if it's the `syslog` driver forwarding it to journald (being the default logging driver?)

What happens if you start a container with `--log-driver=json-file` or `--log-driver=local`, do logs of that container also show up in your journald logs?

**Comment by jakubgs** [comment]
Good point, it's possible. I'll check that later today. Thanks.

**Comment by jakubgs** [comment]
I tested using `log-driver` set to `local` and I'm still seeing the logs in `journalctl -u docker`.
What's interesting is that when I stopped the systemd `docker` service and started `dockerd` myself with `sudo` the logs do not appears in `stdout`, nor do they appear anywhere in `journalctl`. So I'm doubly confused.

I even disabled `rsyslog` just to be sure it's not that:
```
 > sudo systemctl status rsyslog
● rsyslog.service - System Logging Service
     Loaded: loaded (/lib/systemd/system/rsyslog.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
```
But the logs still appear:
```
 > sudo journalctl -f -u docker | tail -n1
Nov 25 16:55:56 host-01.example.org docker/my-container[654]: some log message
```
I need to dig deeper.

**Comment by thaJeztah** [comment]
Hmm.. no idea from the top of my head.

> I tested using log-driver set to local 

Just to double-check; this is set as log-driver for the container, or did you change the daemon configuration? Because the daemon configuration only affects containers that are created _after_ modifying the configuration (once a container is created, its log-settings are "immutable")

Also; does this happen with _any_ container / image? Trying to exclude possible reasons (e.g., if the container is running privileged, running with `systemd` inside the container (thinking if that could make a D-Bus connection), a container running with `--network=host` (which would allow it to connect to other things as well, as it doesn't have network isolation), or a container bind-mounting files from the host

**Comment by jakubgs** [comment]
>the daemon configuration only affects containers that are created after modifying the configuration

Oh, I wasn't aware of this. That's very good to know, I'll try re-creating the container then.

>does this happen with any container / image?

Yes, it's not a matter of container running systemd, it just runs the process directly.

**Comment by jakubgs** [comment]
Okay, re-creating the container with `local` log driver does stop the logs from going into journal.

I have also found out this:

>Rsyslog is able to coexist with systemd with minimal changes on the part of the local system administrator. While the `systemd journal` now assumes full control of the local `/dev/log` system log socket, systemd provides access to logging data via the `/run/systemd/journal/syslog` log socket. This log socket is provided by the `syslog.socket` file that is shipped with systemd.

https://www.rsyslog.com/doc/master/configuration/modules/imuxsock.html?highlight=socket#coexistence-with-systemd

Which I confirmed:
```
 > sudo ls -la /proc/$(pidof rsyslogd)/fd | grep socket
lrwx------ 1 root   root   64 Nov 26 00:00 3 -> socket:[11963]
lrwx------ 1 root   root   64 Nov 26 00:00 6 -> socket:[13069584]
```
```
 > sudo netstat -np | grep 11963
unix  2      [ ]         DGRAM                    11963    1/systemd            /run/systemd/journal/syslog
```
This means that when `syslog` driver is used with Docker on a system that has both Systemd and Rsyslog, logs first go to `/dev/log` and then are send via Systemd to Rsyslog.

This means that I either have to us a different driver than `syslog`, OR I can specify `` to point to `/run/systemd/journal/syslog`:

>`syslog-address`
>The address of an external syslog server. The URI specifier may be `[tcp\|udp\|tcp+tls]://host:port`, `unix://path`, or `unixgram://path`. If the transport is `tcp`, `udp`, or `tcp+tls`, the default port is `514`.
>Examples:
>- `--log-opt syslog-address=tcp+tls://192.168.1.3:514`
>- `--log-opt syslog-address=unix:///tmp/syslog.sock`

https://docs.docker.com/config/containers/logging/syslog/

**Comment by jakubgs** [comment]
Although if I set `syslog-address` to `unixgram:///run/systemd/journal/syslog` I don't seem to be getting any logs from Docker.

But at least I identified the issue with where the logs are coming from. Thanks for help @thaJeztah.
