### ISSUE TITLE
UUCP client doesnt work in demonized container

### ISSUE THREAD

**Issue by alexmtv** [docker/for-linux#116]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

uucp client connents to the uucp server (in another container)  trough ssh and transfer files trough uucico. 

### Actual behavior
 uucico command doesn't even launched if the container started in demonized mode. If the same container started without -d option, it works fine. 
The command is
uucico -f -s $servername

### Steps to reproduce the behavior
Setup any uucp server with ssh-server
Setup uucp client with ssh-client in container. 
Run container with -d and without -d option. 
run uucico -f -s $servername in terminal
See uucp logs.

**Output of `docker version`:**

```
17.06.2-ce
```

**Output of `docker info`:**

```
Centos 7 kernel 3.10.0-514.26.2.el7.x86_64 on an x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Proxmox on HP Baremetal

**Comment by cpuguy83** [comment]
`-d` is a client side implementation and shouldn't effect the container by itself.
Can you provide the full (docker) command you are using in both scenarios?

**Comment by alexmtv** [comment]
After some research i found a solution. uucico must be launched with -D option. 

> -D, --nodetach
    Do not detach from the controlling terminal. Normally uucico detaches from the terminal before each call out to another system and before invoking uuxqt. This option prevents this. 

So this is not a docker issue.
