### ISSUE TITLE
Docker swarm - node - worker: I can't remove the container with the status "Created"

### ISSUE THREAD

**Issue by nnthuanegany** [docker/for-linux#1160]
* [x] This is a bug report

### Description

I'm running a cluster with docker swarm. One day, a service automatically restarted.
I checked containers for this service, oh I see a container with the status "Created".
But this service still has the container running (replicas: 1) and containers is run at a worker node.

### Expected behavior

Remove containers with the status "Stop" and "Created".

### Actual behavior

I tried using portainer and command line to remove them but no success.

### Steps to reproduce the behavior

I tried ssh to worker node and used command line like below:

```bash
docker system prune
# It does not respond and
```

`Ctrl + C` and

```bash
docker system prune
```

Result

```bash
Error response from daemon: a prune operation is already running
```

`Ctrl + C` and

```bash
docker rm -f $container_id
# It does not respond
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 9
  Paused: 0
  Stopped: 2
 Images: 48
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ----
  Is Manager: false
  Node Address: ----
  Manager Addresses:
   ----
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.2MiB
 Name: sgp1-04
 ID: ----
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Looks like you're running a very old patch release of docker 19.03, and a version of containerd (1.2.x) that reached EOL. Note that both of those have known vulnerabilities, so from that perspective alone, I'd highly recommend updating to a current version (docker 19.03.14 and containerd 1.3.9) or upgrade to the latest releases (docker 20.10.0 and containerd 1.4.x); of course test these in a staging environment before upgrading production setups.


It's possible that issues have already been fixed, and because of the above, I'm closing this ticket, but feel free to open a new ticket with details and reproduction steps if you're still running into this on a current version
