### ISSUE TITLE
Resolver: Hardcoded 1024 Concurrent Queries

### ISSUE THREAD

**Issue by joesixpack** [docker/for-linux#1165]
```
Dec 11 01:32:27 graph dockerd[775]: time="2020-12-11T01:32:27.313894086-08:00" level=error msg="[resolver] more than 1024 concurrent queries from 172.21.0.10:35758"

Dec 11 01:32:32 graph dockerd[775]: time="2020-12-11T01:32:32.376307265-08:00" level=error msg="[resolver] more than 1024 concurrent queries from 172.21.0.10:40694"

```

This needs to be made configurable.  Simply increasing from the previously fixed 100 is not good enough.

https://github.com/moby/libnetwork/issues/2214

**Comment by thaJeztah** [comment]
Could you describe under what circumstances you're running into this limit? IIUC, hitting this limit would mean that more than 1024 DNS requests are pending (which could also indicate a DNS server that's slow to respond?)

**Comment by sam-thibault** [comment]
I see no response on this one.  I will close as stale.
