### ISSUE TITLE
Hoe to disable Use gRPC Fuse 

### ISSUE THREAD

**Issue by HarshMultani** [docker/for-linux#1168]
Hi @andrewhsu , @thaJeztah , @tiborvass , @duglin. I am using docker on ubuntu 18.04.

Can you tell me whether there exists a Use gRPC option in docker for Linux - as it is there for Docker Desktop for mac.
And if it exists how should I uncheck it??

docker - version :- 19.03.13
docker-compose - version :- 1.27.4

**Comment by thaJeztah** [comment]
No, the linux binaries don't use gRPCFuse; that's only on Docker Desktop for Mac
