### ISSUE TITLE
docker install with rootless 

### ISSUE THREAD

**Issue by shiyi-pan** [docker/for-linux#1173]
Hi, is there a way to install docker as rootless user ? 
I notice there is a docker-rootless-extras compressed file. Could I install docker as rootless user with this file or not ?
thank you very much.

**Comment by thaJeztah** [comment]
Yes; instructions can be found here; https://docs.docker.com/engine/security/rootless/

**Comment by thaJeztah** [comment]
Let me close this ticket, as we generally use this issue tracker for bug-reports and feature requests, not for questions / general discussion, but feel free to continue the conversation

**Comment by shiyi-pan** [comment]
thank you for your reply . when I type the command :grep ^$(whoami): /etc/subuid  as described in https://docs.docker.com/engine/security/rootless/, I find there is no file named /etc/subuid in my system . Could you give me some advise?

**Comment by thaJeztah** [comment]
If I'm not mistaken, both `/etc/subuid` and `/etc/subgid` have to be created manually indeed.

Perhaps something that should be called out in the docs; feel free to open a pull-request for that in the documentation repository; https://github.com/docker/docker.github.io/edit/master/engine/security/rootless.md

**Comment by shiyi-pan** [comment]
Thank you for you reply, thaJeztah . I tried to  create the two file, but I'm a rootless user and don't have permission to do this. here is my code.

sudo mkdir /etc/subuid
[sudo] password for panyp:
Sorry, user panyp is not allowed to execute '/bin/mkdir /etc/subuid' as root on NCSI.njau.edu.cn.

Is this a way to make a rootless user to create file in /etc ?

**Comment by thaJeztah** [comment]
Hmmm. don't think there's a way to work around that

@AkihiroSuda any suggestions?

**Comment by AkihiroSuda** [comment]
No practical workaround in the short time.

In the long term we will be able to have subuidless containers https://github.com/rootless-containers/subuidless (freezed until OCI seccomp receiver spec settles)

**Comment by shiyi-pan** [comment]
ok,thank you for your help reply, thaJeztah and AkihiroSuda, I will find another way to install the software without docker and  i'm looking forward to your subuidless version of docker. This is a great idea. thank you again.
