### ISSUE TITLE
Docker don‘t restart

### ISSUE THREAD

**Issue by Naimkr27** [docker/for-linux#1174]
Hello everybody,

I bought an Odroid N2 + and want to run Docker on it. After the installation and after 2-3 restart everything goes great. But at some point it doesn't work anymore and when I enter any Docker command e.g. docker info or docker ps then nothing happens anymore.

The device runs ubuntu 20.04.1 which I downloaded directly from the Odroid site.

Can someone help me that it works permanently and that I don't have to write the image of Ubuntu to MicroSD every time and reinstall everything.

thank you for your help

Sorry, my englisch is not good. And i translate with google.

**Comment by thaJeztah** [comment]
How did you install docker, did you install from the official packages from download.docker.com?

Might want to check logs for the docker and/or containerd service to see if they provide more details;

```
sudo journalctl -xeu docker.service

sudo journalctl -xeu containerd.service
```

**Comment by sam-thibault** [comment]
I don't see any activity on this issue.  I will close it as stale.
