### ISSUE TITLE
Restoring Containers After Checkpoint Does Not Start From Saved State 

### ISSUE THREAD

**Issue by lzqlzqwhr** [docker/for-linux#1192]
I tried the Docker 20.10.2 to checkpoint a container, however, once restoring it does not restart from the saved state. Instead, it starts from the beginning. 

Platform: Ubuntu 18.04 
Docker version: 20.10.2 
CRIU version: 3.15 
RUNC version 1.0.0-rc92

1. Start the container: 
`docker run --security-opt=seccomp:unconfined --name cr -d busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
2. Check the log: 
`docker logs cr` 
0
1
2
3
4
5
6
7
8
9
10
11
3. Checkpoint the container: 
`docker checkpoint create cr checkpoint0`
4. Restore the container: 
`docker start --checkpoint=checkpoint0 cr`
5. Check the log again: 
`sudo docker logs`
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4

And you can see it starts from 0 again, which is the initial state of the container. However, once I tried these commands on Docker 17.03, it works fine.

**Comment by vutuong** [comment]
I got the same problem with Docker 20.10.2. Any progress to fix this?

**Comment by lzqlzqwhr** [comment]
> I got the same problem with Docker 20.10.2, version 19.03.6... Version 18.06.3 raised error:
> `Error response from daemon: failed to retrieve OCI runtime container pid: open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/6f75781052e4b95e9f829345bff7bb42365a33f2d06578b84be288a89efa316c/init.pid: no such file or directory: unknown`
> Any progress to fix this?
> P/S: Cannot find older versions 17.x in ubuntu.

**Comment by lzqlzqwhr** [comment]
You can use the following command to download and install docker 17.03 on ubuntu 18.04
**_wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.0~ce-0~ubuntu-xenial_amd64.deb
sudo dpkg -i /path/to/package.deb_**

**Comment by riteme** [comment]
Related: https://github.com/moby/moby/pull/41641

**Comment by janrieke** [comment]
Also experiencing this with:
* Ubuntu 20.04.3 LTS (Focal Fossa)
* Kernel 5.4.0-89
* Docker version: 20.10.10
* CRIU version: 3.16.1
* RUNC version 1.0.2

**Comment by riteme** [comment]
@janrieke You can check your containerd version. If it's 1.4.x, you'd better upgrade it to 1.5.x.

**Comment by janrieke** [comment]
Uh, didn't thought of that. The repository at `download.docker.com/linux/ubuntu` still serves package `containerd.io` 1.4.11-1. The package `containerd` from the official Ubuntu is already at 1.5.5.

I had to mess around with the dependencies to convince `docker-ce` not to install the outdated `containerd.io`, but `containerd` instead.

But now it works (not only docker, but also resuming from a checkpoint). Thanks @riteme!

**Comment by serefarikan** [comment]
@janrieke did you build criu from source? I've been scratching my head for an hour now: apparently there's no criu package for focal, and I was hoping I could experiment with checkpoints, so I'm kinda stuck :) it'd be great to know how you configured your system. I'm on focal as well.

**Comment by janrieke** [comment]
I installed it using this PPA: https://launchpad.net/~criu/+archive/ubuntu/ppa

**Comment by serefarikan** [comment]
@janrieke thanks a lot! I may be the only person on the planet who cannot make sense of launchpad UI. I could not find the page you gave the link to. Just realised it is reachable if I go to the bottom of the landing page for criu, expand (really small) the archives link and click on focal :) Anyway, much appreciated, thanks!
