### ISSUE TITLE
Apk index problems on armv7 (Raspberry)

### ISSUE THREAD

**Issue by FrancisHGR** [docker/for-linux#1196]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

After pulling latest version (3.13.1), apk update / upgrade / add should work.

### Actual behavior

However all commands starting with apk are throwing errors (see below). 

/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 14 distinct packages available

### Steps to reproduce the behavior

docker run -it --rm --name test alpine:3.13.1 sh
apk update

Please note: running 3.12.3 works without a problem on the same machine, same network etc.

docker run -it -rm --name test alpine:3.12.3 sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armv7/APKINDEX.tar.gz
v3.12.3-83-g9e25995019 [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.3-77-g89584230ef [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12345 distinct packages available
/ # exit

**Output of `docker version`:**

Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:18:13 2020
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:48 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        XXXX
 runc:
  Version:          1.0.0-rc92
  GitCommit:        XXXX
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Output of `docker info`:**

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 19
  Running: 2
  Paused: 0
  Stopped: 17
 Images: 57
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.83-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 924.8MiB
 Name: raspberrypi
 ID: XXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
I think this was a temporary issue with the alpine package servers (seen this happening once in a while), but looks resolved;

```
docker run -it --rm --name test alpine:3.13.1 sh

Unable to find image 'alpine:3.13.1' locally
3.13.1: Pulling from library/alpine
4c0d98bf9879: Already exists
Digest: sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930
Status: Downloaded newer image for alpine:3.13.1
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
v3.13.1-43-gc72f0fa02c [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.1-57-ge8530adb99 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 13878 distinct packages available
```

Closing as this doesn't look like a bug in docker itself (these issues may be better reported either in https://github.com/alpinelinux/docker-alpine/issues, or the alpine issue tracker; https://wiki.alpinelinux.org/wiki/Alpine_Linux:Contribute)

Feel free to continue the conversation after I closed

**Comment by FrancisHGR** [comment]
Bug unfortunately still persistent. I have additionally opened up another thread at alpine linux as suggested.

Unable to find image 'alpine:3.13.1' locally
3.13.1: Pulling from library/alpine
9b1db703a337: Pull complete
Digest: sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930
Status: Downloaded newer image for alpine:3.13.1
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
2 errors; 14 distinct packages available

**Comment by y0ast** [comment]
The answer is this: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

(alpine 3.13 isn't compatible with raspberry pi os by default due to some outdated package)

**Comment by mysystem32** [comment]
> The answer is this: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
> (alpine 3.13 isn't compatible with raspberry pi os by default due to some outdated package)

For Raspberry Pi, you can upgrade libseccomp2 to a supported version from the Debian Repos
eg.
# wget http://ftp.de.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
# dpkg -i libseccomp2_2.5.1-1_armhf.deb

**Comment by emuchogu** [comment]
> Bug unfortunately still persistent. I have additionally opened up another thread at alpine linux as suggested.
> 
> Unable to find image 'alpine:3.13.1' locally
> 3.13.1: Pulling from library/alpine
> 9b1db703a337: Pull complete
> Digest: sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930
> Status: Downloaded newer image for alpine:3.13.1
> / # apk update
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
> ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
> fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
> ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
> WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
> 2 errors; 14 distinct packages available

Getting the same error. 

3.12.3 works with no issues 
3.13.1 fails with same error -- temporary error (try again later) 

Did you find a solution?

**Comment by bozakov** [comment]
> Did you find a solution?

The workaround provided by @mysystem32 works fine.

**Comment by dreamfalcon** [comment]
The workaround worked great to fix some docker builds, but now I get an error when updating the pi.
```
pi@raspberrypi4g:~ $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libseccomp-dev : Depends: libseccomp2 (= 2.3.3-4) but 2.5.1-1+deb11u1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by nonodev96** [comment]
The repository doesn't work in alpine 3.17 with raspberry 

I added in `/etc/docker/daemon.json` the dns with 8.8.8.8 and 192.168.0.1, but nothing 😢 

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.17/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.17/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/community: No such file or directory
ERROR: unable to select packages:
  nano (no such package):
    required by: world[nano]
```
