### ISSUE TITLE
--ip6 addresses are not validated

### ISSUE THREAD

**Issue by krichter722** [docker/for-linux#1204]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
IPv6 addresses passed to `docker run` with `--ip6` are validated in order to fail early in case of invalid data, i.e. argument strings that cannot be IPv6 addresses like `2001:db8:1::x` which contains an invalid `x`.

### Actual behavior
`docker run` should fail with a return code != 0 and print a comprehensive error message stating that no valid IPv6 address has been passed to `--ip6`.

### Steps to reproduce the behavior
`docker run -it --ip6 2001:db8:1::x ubuntu:20.04 bash` starts the container.

**Comment by akerouanton** [comment]
Thanks for reporting. This issue was fixed by https://github.com/moby/moby/pull/46183, which was first released in v25.0.

```
$ docker run -it --ip6 2001:db8:1::x ubuntu:20.04 bash
docker: Error response from daemon: invalid config for network bridge: invalid endpoint settings:
* user specified IP address is supported on user defined networks only
* invalid IPv6 address: 2001:db8:1::x
* user specified IP address is supported only when connecting to networks with user configured subnets.
See 'docker run --help'.
```
