### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by jhnworks** [docker/for-linux#1218]
* [x] This is a bug report
* [ ] This is a feature request
* [x ] I searched existing issues before opening this one

### Expected behavior
docker running

### Actual behavior
failing to connect to the socker

### Steps to reproduce the behavior

Having set the CGroup=1
GRUB_CMDLINE_LINUX="ipv6.disable=1 resume=/dev/mapper/fedora-swap rd.lvm.lv=fedora/root rd.lvm.lv=fedora/swap rhgb quiet systemd.unified_cgroup_hierarchy=0"

[root@usstg2 ~]# curl -fsSL https://get.docker.com -o get-docker.sh

**Output of `docker version`:**

```
[usstg2@usstg2 ~]$ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:19:16 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
[usstg2@usstg2 ~]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
**Physical, Server edition **
[usstg2@usstg2 ~]$ cat /etc/redhat-release 
Fedora release 33 (Thirty Three)

**Comment by jhnworks** [comment]
systemd
Failed to start Docker Application Container Engine.
CODE_FILE | src/core/job.c
-- | --
CODE_FUNC | job_log_done_status_message
CODE_LINE | 941
INVOCATION_ID | a0462c4bd53b45c4a6cb7706c591bd6a
JOB_ID | 2052
JOB_RESULT | failed
JOB_TYPE | start
MESSAGE_ID | be02cf6855d2428ba40df7e9d022f03d
PRIORITY | 3
SYSLOG_FACILITY | 3
SYSLOG_IDENTIFIER | systemd
UNIT | docker.service
_BOOT_ID | 738fe478492e422e80b836876358efd9
_CAP_EFFECTIVE | 1ffffffffff
_CMDLINE | /usr/lib/systemd/systemd --switched-root --system --deserialize 29
_COMM | systemd
_EXE | /usr/lib/systemd/systemd
_GID | 0
_HOSTNAME | usstg2.lab.mobi
_MACHINE_ID | c5253ba5145245c884979803530b9f29
_PID | 1
_SELINUX_CONTEXT | kernel
_SOURCE_REALTIME_TIMESTAMP | 1615738707924501
_SYSTEMD_CGROUP | /init.scope
_SYSTEMD_SLICE | -.slice
_SYSTEMD_UNIT | init.scope
_TRANSPORT | journal
_UID | 0
__CURSOR | s=928cb79c7c5b47b28c10ad5a8644a514;i=1795213;b=738fe478492e422e80b836876358efd9;m=1096c6ea;t=5bd817bbc58bb;x=1878931470be3b4b
__MONOTONIC_TIMESTAMP | 278316778
__REALTIME_TIMESTAMP | 1615738707925179

**Comment by cpuguy83** [comment]
Please get the actual docker daemon logs.

`journalctl -fu docker`

**Comment by jhnworks** [comment]
[usstg2@usstg2 ~]$ journalctl -fu docker
-- Logs begin at Mon 2021-02-08 11:02:35 EST. --
Mar 15 20:16:11 usstg2.lab.mobi systemd[1]: Starting Docker Application Container Engine...
Mar 15 20:16:11 usstg2.lab.mobi dockerd[4326]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [fd:// unix:///var/run/docker.sock tcp://0.0.0.0:2376])
Mar 15 20:16:11 usstg2.lab.mobi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 15 20:16:11 usstg2.lab.mobi systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 15 20:16:11 usstg2.lab.mobi systemd[1]: Failed to start Docker Application Container Engine.
Mar 15 20:16:13 usstg2.lab.mobi systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Mar 15 20:16:13 usstg2.lab.mobi systemd[1]: Stopped Docker Application Container Engine.
Mar 15 20:16:13 usstg2.lab.mobi systemd[1]: docker.service: Start request repeated too quickly.
Mar 15 20:16:13 usstg2.lab.mobi systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 15 20:16:13 usstg2.lab.mobi systemd[1]: Failed to start Docker Application Container Engine.

**Comment by cpuguy83** [comment]
The docker service unit specifies `-H` flags already, and flags cannot be duplicated between command line flags (from systemd unit) and daemon.json config.

**Comment by jhnworks** [comment]
[usstg2@usstg2 ~]$ cat /etc/docker/daemon.json 
{
  "dns": ["192.168.3.1", "8.8.8.8"],
  "data-root": "/u01/workspace/docker/docker-data",
  "storage-driver": "overlay2",
  "api-cors-header": "",
  "authorization-plugins": [],
  "bip": "",
  "bridge": "",
  "cgroup-parent": "",
  "cluster-store": "",
  "cluster-store-opts": {},
  "cluster-advertise": "",
  "debug": "",
  "default-gateway": "",
  "default-gateway-v6": "",
  "default-runtime": "runc",
  "dns-opts": [],
  "dns-search": [],
  "exec-opts": [],
  "exec-root": "",
  "fixed-cidr": "",
  "fixed-cidr-v6": "",
  "graph": "",
  "group": "",
  "hosts": ["fd://","unix:///var/run/docker.sock","tcp://0.0.0.0:2376"],
  "icc": true,
  "insecure-registries": [],
  "ip": "0.0.0.0",
  "iptables": true,
  "ipv6": false,
  "ip-forward": false,
  "ip-masq": false,
  "labels": [],
  "live-restore": true,
  "log-driver": "",
  "log-level": "",
  "log-opts": {},
  "max-concurrent-downloads": 3,
  "max-concurrent-uploads": 5,
  "mtu": 0,
  "oom-score-adjust": -500,
  "pidfile": "",
  "raw-logs": false,
  "registry-mirrors": [],
  "runtimes": {},
  "selinux-enabled": false,
  "storage-opts": [],
  "swarm-default-advertise-addr": "",
  "tls": false,
  "tlscacert": "/u01/workspace/docker/tls/ca.pem",
  "tlscert": "/u01/workspace/docker/tls/server-cert.pem",
  "tlskey": "/u01/workspace/docker/tls/server-key.pem",
  "tlsverify": false,
  "userland-proxy": false,
  "userns-remap": ""
}

**Comment by cpuguy83** [comment]
If you want `"hosts": ["fd://","unix:///var/run/docker.sock","tcp://0.0.0.0:2376"],` then you need to overwrite the systemd unit file with a drop-in to replace the `ExecStart` command.

Closing since this is not an issue, but feel free to discuss.
