### ISSUE TITLE
The support status of CE and 1.12 is not clearly listed anywhere

### ISSUE THREAD

**Issue by euank** [docker/for-linux#122]
* [x] I searched existing issues before opening this one

### Expected behavior

The support status of all versions of Docker CE and open-source Docker prior to CE should be clearly displayed in the documentation.

### Actual behavior

The actual status of 1.12 and exact timeline for support for anything other than CSE and EE is murky.

### Steps to reproduce the behavior

The question I started out trying to answer is whether Docker 1.12 is still considered supported in any way. I could not find a clear answer.

I am aware of the [Maintenance Lifecycle](https://success.docker.com/Policies/Maintenance_Lifecycle) docs page, but it *only* talks about the "Commercially Supported Engine", not docker 1.12.

In addition, there's not a convenient chart for finding the support status of CE versions. I'm aware that it's 4 month periods, giving 1 month to upgrade.
However, CE versions are not being released exactly 3 months apart, and it's not obvious whether that means the previous version is now supported fo 1 month from the new version's launch date, or still 4 months from its launch date.

The documentation should have a clear, linkable, concise presentation of the support status for all versions of Docker so that users don't have to scramble in the case of a security vulnerability.

I would be happy to be proven wrong about this if there is a page or announcement which makes this all clear. Thanks!

**Comment by seemethere** [comment]
Thanks for posting this question!

Docker 1.12 is no longer receiving updates and you should update to Docker 17.09.

You're correct that some CE releases have slipped a little. We're working on making sure they arrive promptly.

Also pinging @mstanleyjones to help update docs to be clearer about this. The best resource, as of now, is probably the [original blog post](https://blog.docker.com/2017/03/docker-enterprise-edition/).

**Comment by euank** [comment]
Just to make sure the second part of my question doesn't get lost: CE versions also have some uncertainty.

As a specific example:
17.03-ce was released on 2017-03-02
17.06-ce was released on 2017-06-28

Does that mean 17.03 was supported for 4 months (until 2017-07-02, giving 4 days to migrate from .03 to .06), or was 17.03 supported up until 2017-07-28 (1 month from the release of 06)?

Regardless the answer, a clear chart answering that question too would be greatly appreciated, not just a docs update to make sure 1.12's fate is clear.

**Comment by mstanleyjones** [comment]
@euank We will clear up the confusion in the docs, but **a stable version of Docker CE is patched and updated for one month after the next CE stable version is released.**

**Comment by euank** [comment]
I'm unable to re-open this issue, but I think the support status of 1.12 and 1.13 should also be clearly described somewhere on the website.
