### ISSUE TITLE
Docker not working on a fresh arch linux install

### ISSUE THREAD

**Issue by matheusfsreinert** [docker/for-linux#1234]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

Docker not working on a fresh arch linux, it pulls the image but doesn't run. I found other errors close to this but no one that ended only with can't load program: invalid argument: unknown so I'm kinda lost, according to arch wiki it should work.

### Expected behavior
run hello-world container

### Actual behavior
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: invalid argument: unknown.
ERRO[0000] error waiting for container: context canceled

### Steps to reproduce the behavior
On a fresh arch linux install, follow the arch wiki instructions, install the docker package, start the socket and service and run `docker run hello-world`. 
`docker run -it --rm archlinux bash -c "echo hello world"` doesn't work either.

**Output of `docker version`:**

```
Client:
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.16.3
 Git commit:        370c28948e
 Built:             Mon Apr 12 14:10:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          19.03.9-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       9d988398e7
  Built:            Tue May 19 22:11:01 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 19.03.9-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0 (expected: fec3683)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.11.15-1-ck
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.726GiB
 Name: archlinux
 ID: IBII:XWHC:G3LZ:IXSX:KIIX:GYE7:TUIL:R5IN:WKJG:L3JH:ATIP:WMT6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
```

**Comment by stefanorth** [comment]
I'm having the same issue on arch and use now the [crun](https://github.com/containers/crun) runtime as a workaround.
Just install the package `crun` and add `/etc/docker/daemon.json`:
```
{
  "default-runtime": "crun",
  "runtimes": {
    "crun": {
      "path": "/usr/bin/crun"
    }
  }
}
```
You have to recreate existing containers.

**Comment by matheusfsreinert** [comment]
@stefanorth thanks for the answer, that does work but only with the `--privileged` flag, otherwise i get a `bpf create error`, but it seems that's a crun issue.

**Comment by matheusfsreinert** [comment]
Ok, it's working now. Followed the steps on the docker docs, enabled `appamor` de `seccomp`, but that didn't work. So reading the [arch wiki Linux Containers page](https://wiki.archlinux.org/index.php/Linux_Containers) I found out that the problem was the linux-ck kernel that apparently doesn't support running unprivileged containers, changed to the stock linux kernel and now it's working even without setting `crun` as the runtime.
