### ISSUE TITLE
Handler for GET /system/df returned error: context canceled - Error every 60 seconds

### ISSUE THREAD

**Issue by JonAnder83** [docker/for-linux#1238]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
No meaningful errors on the system's journal: No sudden CPU usage surges

### Actual behavior
Every 60 seconds sharp, my cpu's fans will rev up and I would get this error on the logs.
I got debug logs and can see a couple more lines but still don't know how to proceed

```
Apr 26 17:34:08 jarvis dockerd[702]: time="2021-04-26T17:34:08.016566871+02:00" level=debug msg=VolumeStore.Find ByType=service.andCombinator ByValue="[[local] 0x55e14a9957a0]"
Apr 26 17:34:08 jarvis dockerd[702]: time="2021-04-26T17:34:08.019595155+02:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: context canceled" error_type="*errors.errorString" module=api
Apr 26 17:34:08 jarvis dockerd[702]: time="2021-04-26T17:34:08.019612353+02:00" level=error msg="Handler for GET /system/df returned error: context canceled"
Apr 26 17:34:08 jarvis dockerd[702]: time="2021-04-26T17:34:08.019621221+02:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: context canceled" error_type="*errors.errorString" module=api
```
It's no particular container since this happens with all containers stopped.
Only way to stop this is to fully stop the docker daemon altogether.

### Steps to reproduce the behavior
It just happens every minute. You just have to get your docker daemon running with some containers. :(

**Output of `docker version`:**

```
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c28948e
 Built:             Mon Apr 12 14:10:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.3
  Git commit:       8728dd246c
  Built:            Mon Apr 12 14:10:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.6
 Storage Driver: btrfs
  Build Version: Btrfs v5.11.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.11.16-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.836GiB
 Name: jarvis
 ID: ZVUC:KV6C:BHXY:YP6F:DJQD:ZWGO:3BFK:2SYH:EY4E:VPYC:G4PO:ZTKS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No oom kill disable support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Standalone server (no swarm or k8s)
VMware VM
btrfs storage driver
Some containers have nfs mounts via local driver (Declared in the compose file)

Attached full debug log from boot time.
[docker_debug.log](https://github.com/docker/for-linux/files/6380517/docker_debug.log)

**Comment by chennin** [comment]
Are/were you running Zabbix?

I have docker on *zfs* and stopping the *zabbix-server* container stopped the error message and high CPU usage. As a more permanent solution, disabling the `docker.data_usage` item in the [docker template](https://www.zabbix.com/integrations/docker) also fixed it. [Reference here](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/426412-timeout-with-zabbix-agent2-using-docker-data_usage-key?p=435648#post435648)

If not Zabbix itself, it's possible there's a problem with whatever underlying module Zabbix uses to interrogate the docker data usage.

There is also [another report for btrfs](https://www.reddit.com/r/docker/comments/mxusn7/handler_for_get_systemdf_returned_error_context/) .

**Comment by cpuguy83** [comment]
As hinted above, you have something running that is calling this API and cancelling the request after 60s.

Check what else is running in the system or if you have this exposed on the network check incoming requests.

**Comment by cpuguy83** [comment]
I'm going to close this because this doesn't look like a Docker issue, but feel free to discuss.

Thank you! 🙇‍♂️👼
