### ISSUE TITLE
Cgroup v1/v2 with mixed controllers

### ISSUE THREAD

**Issue by yuzhouliu-solace** [docker/for-linux#1256]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Context
I'm experimenting with mixed mode cgroup v1 and v2 to see what happens when some controllers are handled by cgroup v1 (e.g. cpu, io, etc) and other controllers are handled by cgroup v2 (e.g. memory).
I have a Ubuntu 20.04.2 system with the kernel option `cgroup_no_v1=memory`. I did not specify `systemd.unified_cgroup_hierarchy=1` because I found that causes all controllers to be on v2.
On the host system, `/sys/fs/cgroup/memory` is empty and `cat /sys/fs/cgroup/unified/cgroup.controllers` shows `memory`. This indicates to me that the system is using cgroup v2 for memory, and everything else is on cgroup v1.

Please correct me if I'm wrong here, as the reported bug is based on this.

### Expected behavior
Bring up a container on the host system described above. Get bash into the container `sudo docker exec -it <container> bash`. Check `/sys/fs/cgroup`. I would expect the filesystem to mimic the host system, i.e. use cgroup v1 for all controllers except memory, and have a "unified" folder for cgroup v2 where `cat /sys/fs/cgroup/unified/cgroup.controllers` shows `memory`.

### Actual behavior
Inside the container, here are the contents of /sys/fs/cgroup. Notice that "memory" is missing.
```
[appuser@9ed3bc15b75a cgroup]$ ls -al /sys/fs/cgroup/
total 0
dr-xr-xr-x 13 root root 340 Jun 16 19:21 .
drwxr-xr-x 10 root root   0 Jun 16 19:21 ..
drwxr-xr-x  2 root root   0 Jun 16 19:21 blkio
lrwxrwxrwx  1 root root  11 Jun 16 19:21 cpu -> cpu,cpuacct
lrwxrwxrwx  1 root root  11 Jun 16 19:21 cpuacct -> cpu,cpuacct
drwxr-xr-x  2 root root   0 Jun 16 19:21 cpu,cpuacct
drwxr-xr-x  2 root root   0 Jun 16 19:21 cpuset
drwxr-xr-x  2 root root   0 Jun 16 19:21 devices
drwxr-xr-x  2 root root   0 Jun 16 19:21 freezer
drwxr-xr-x  2 root root   0 Jun 16 19:21 hugetlb
lrwxrwxrwx  1 root root  16 Jun 16 19:21 net_cls -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Jun 16 19:21 net_cls,net_prio
lrwxrwxrwx  1 root root  16 Jun 16 19:21 net_prio -> net_cls,net_prio
drwxr-xr-x  2 root root   0 Jun 16 19:21 perf_event
drwxr-xr-x  2 root root   0 Jun 16 19:21 pids
dr-xr-xr-x  2 root root   0 Jun 16 19:19 rdma
drwxr-xr-x  2 root root   0 Jun 16 19:21 systemd
```
Also notice there is no "unified" directory for cgroup v2.

So my question is, within the container is the memory controller being managed by v1 or v2. And why is there no exposed cgroup interface for memory?

### Steps to reproduce the behavior
Stated in Context

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1045-aws
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.842GiB
 Name: ip-172-31-11-199
 ID: 7KII:KGEL:ELF2:TUIZ:2T2H:TU5I:DIQH:XZGK:4AXE:2V4T:E7LE:J2C3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
AWS EC2 instance

**Comment by AkihiroSuda** [comment]
Mixing up v1 and v2 is unsupported

**Comment by yuzhouliu-solace** [comment]
Thanks!

And I confirmed that Podman just errors on container startup
`Error: OCI runtime error: cgroups in hybrid mode not supported, drop all controllers from cgroupv2`

Good to close.
