### ISSUE TITLE
Commit de0f898 broke Docker starting if /proc/sys/fs/may_detach_mounts exists and is not writable

### ISSUE THREAD

**Issue by lanrat** [docker/for-linux#126]
* [x] This is a bug report
* [ ] This is a feature request
* [X] I searched existing issues before opening this one

### Expected behavior
After updating to docker 17.09.0 from 17.06.2 `dockerd` starts the Docker daemon on a system that does not allow writes to `/proc/sys/fs/may_detach_mounts`

### Actual behavior
```
root@sha:~# dockerd                                                                                                                                           
INFO[2017-10-10T23:10:26.386339609+02:00] libcontainerd: new containerd process, pid: 3679                                                                    
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=1048576                                                                            
Error starting daemon: error opening may_detach_mounts kernel config file: open /proc/sys/fs/may_detach_mounts: permission denied     
```

### Steps to reproduce the behavior
Install Docker `17.09.0~ce-0~debian` inside a OpenVZ container or any other system that does not allow writes to `/proc/sys/fs/may_detach_mounts` and attempt to start the daemon.

**Output of `docker version`:**
```
root@sha:~# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:58:57 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
**Output of `docker info`:**
Unable to run as Docker does not start.

**Additional environment details (AWS, VirtualBox, physical, etc.)**

I am running Docker in Debian 9 stretch inside OpenVZ Linux 4.9.0

```
root@sha:~# ls -l /proc/sys/fs/may_detach_mounts
-r--r--r-- 1 root root 0 Oct 10 22:28 /proc/sys/fs/may_detach_mounts
```

# The exact commit that broke this is here: https://github.com/docker/docker-ce/commit/de0f898e391bebc3744a80afb118908d1acae0bc

Docker 17.06.2 works perfectly in my environment. 17.09.0 broke this. If `/proc/sys/fs/may_detach_mounts` is not writable docker should throw a soft error and not exit.

If anyone else is having this issue, you can temporarily fix it by downgrading docker: `apt install docker-ce=17.06.2~ce-0~debian`

**Comment by thaJeztah** [comment]
Looks like the error is actually on _reading_ / _opening_ the file, non on write

**Comment by thaJeztah** [comment]
ping @cpuguy83 ^^

**Comment by lanrat** [comment]
You are correct that the error is being thrown on open, but because the file is being opened for writing with `O_WRONLY` it is failing. Reading should work fine as root has the read permission.

**Comment by cpuguy83** [comment]
Yes, seems like logging a warning would be sufficient here instead of aborting startup.

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/pull/35172

**Comment by lanrat** [comment]
Will this fix be in the next release of docker-ce or just moby?
