### ISSUE TITLE
vscode don't work anymore in docker

### ISSUE THREAD

**Issue by vinniec** [docker/for-linux#1268]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Vscode/Vscodium that start correctly on docker

### Actual behavior
Only the version 1.57.1 of both software start, the new ones don't start anymore (1.58.0 and 1.58.1).
Moreover even with the working version of the programs (1.57.1), the instruction CMD ["code"] (or ["codium"])  does not start the program automatically when I use the `docker run` and I have to enter the shell every time and start the executable by hand. 

### Steps to reproduce the behavior

1. build a docker image with this command `docker build -t tinycode .` and the [code-stable-x64-1626158564.tar.gz](https://update.code.visualstudio.com/1.58.1/linux-x64/stable) archive in the same dir:
```
ARG IMGVERS=latest
FROM bensuperpc/tinycore:${IMGVERS}
LABEL maintainer "Vinnie Costante <*****@gmail.com>"

ARG DOWNDIR=/tmp/download
ARG INSTDIR=/opt/vscode

ENV LANG=C.UTF-8 LC_ALL=C PATH="${PATH}:${INSTDIR}/bin/"

RUN tce-load -wic Xlibs nss gtk3 libasound libcups python3.9 tk8.6 \
    && rm -rf /tmp/tce/optional/*
RUN sudo ln -s /lib /lib64 \
    && sudo ln -s /usr/local/etc/fonts /etc/fonts \
    && sudo mkdir -p ${DOWNDIR} ${INSTDIR} \
    && sudo chown -R tc:staff ${DOWNDIR} ${INSTDIR}
COPY code-stable-x64-1626158564.tar.gz ${DOWNDIR}/
RUN tar xvf ${DOWNDIR}/code*.gz -C ${INSTDIR} --strip-components=1 \
    && rm -rf ${DOWNDIR}  
CMD ["code"]
```
 2. run this command and inside the container's shell try to run `code` :
```
xhost +
docker run -it --rm \
--net=host \
--env="DISPLAY=unix${DISPLAY}" \
--workdir /home/tc \
--volume="$HOME/.Xauthority:/root/.Xauthority:rw" \
--name tc \
tinycode /bin/ash
```
The problem:
If the version is 1.57.1 vscode starts, if it is 1.58.0 or 1.58.1 it does not start.
Using the same distro with the same libraries on a physical machine instead of on docker, all versions of vscode work correctly.

**Output of `docker version`:**

```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.10
 Git commit:        48d30b5b32e99c932b4ea3edca74353feddd83ff
 Built:             Sat Mar 20 18:44:30 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.10
  Git commit:       46229ca1d815cfd4b50eb377ac75ad8300e13a85
  Built:            Sat Mar 20 17:55:59 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit: 
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: tmpfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-0-lts
 Operating System: Alpine Linux v3.13
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.682GiB
 Name: alpinnie
 ID: QD43:SBTR:23NR:VPF5:DMLA:WGW3:TXC6:64BP:J575:ECJ2:VUBC:WRKD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by vinniec** [comment]
the problem related with the vscode version is solved, but the problem of being able to launch vscode only from the interactive shell and not diectly with CMD of the dockerfile is still not solved.
I also tried to make a script and put it in a path for executables but the problem is the same, from the output on the terminal though I understand that the program is actually launched but then nothing happens

**Comment by thaJeztah** [comment]
Given that this works with older versions of vscode and doesn't with newer versions, but on the same version of Docker, I would suggest opening a ticket in the VSCode issue tracker; not sure if there's anything directly actionable here.
