### ISSUE TITLE
docker 20.10 on arm/v7 Rasp/Debian Buster is not functional

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [docker/for-linux#1283]
This is pretty much https://github.com/moby/moby/issues/40734

On a Raspbian buster system running fully patched official Docker builds:

```
Linux nightingale 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
Docker version 20.10.8, build 3967b7d
```

Commands will fail in seemingly random, confusing and hard to grok ways.

A simple `docker run --rm -ti debian:bullseye apt-get update` will return:

```
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [154 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [40.1 kB]
Err:2 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

The bottom-line really is about the libseccomp version that (rasp)debian Buster ships, but then, regardless of the underlying cause, Docker is simply not working on this platform - while it is listed as supported on https://docs.docker.com/engine/install/debian/

Unless there is a patch to be had (for example: shipping with a different default seccomp profile on this platform, or simply disabling seccomp), the platform combination ("debian stable on armv7") should be removed from the supported list - or at least have a big warning about it being broken...

**Comment by stevbev** [comment]
What you posted shows that Docker is actually running just fine. If Docker wasn't working correctly, you would have received some kind of Docker error outside of the container. Instead what is seen in the output is a common issue with the Debian packaging command that was run, indicating that at the time the **apt-get update** was run around 2021-08-10 the Debian apt repositories were still in process of signing the apt package lists and distributing packages across all the mirrors for the 2021-08-14 Debian Bullseye release date. I can confirm there is no current problem with the Debian repositories and the issue as reported cannot be replicated currently. This issue can likely be closed.

**Comment by cpuguy83** [comment]
it's complicated, but it's due to seccomp.
My attempt to explain below, bare in mind I'm answering from my phone:

This is due to seccomp and some newer system calls added to linux (64bit time and clone3) which are fairly fundamental and picked up by libc where, for example, libc used to call clone2 it now tries clone3 first and docker's seccomp policy denies that (actually if seccomp is old enough it doesn't even know what clone3 is).
There's some other nuance here that I'd prefer not to type in via a phone keyboard...

But... anyway due to these new system calls and the fact that docker by default applies a seccomp policy, the system calls are failing and breaking things in weird to debug ways.

Right now it's pretty pretty much required to _not_ run a container that uses a distro version (or more accurately, libc) that is newer than the host.
Upgrading libseccomp may fix it, but typically you'd get the distro's libseccomp which is not going to be up to date.

Hope this helps.

**Comment by dubo-dubon-duponey** [comment]
@stevbev the issue is unrelated to apt-get entirely - just provided as an example - other binaries will fail too.

Thanks @cpuguy83 for the details - a few additional questions:

1.  this seems to be specific to arm/v7 for me - the very same setup on an amd64 machine is working fine - does that matches your view above?
2. is the resolution "wont-fix" on this?

> Right now it's pretty pretty much required to not run a container that uses a distro version (or more accurately, libc) that is newer than the host.

3. I was not aware of that... it is somewhat concerning... is this documented somewhere on docs.docker.com ?

Thanks!

**Comment by cpuguy83** [comment]
@dubo-dubon-duponey 

> is the resolution "wont-fix" on this?

More like "cant-fix".
One can build statically compiled docker binaries (really runc is what's needed here) against a newer seccomp or install a newer seccomp than your distro provides.

You can also disable seccomp per run invocation or per dockerd instance by setting `--security-opt=seccomp:disabled`. This of course weakens the security of the container.

> I was not aware of that... it is somewhat concerning... is this documented somewhere on docs.docker.com ?

I doubt it, it's, in the grand scheme of things, a relatively new problem and also fairly technical but definitely understand a call-out may help.
