### ISSUE TITLE
docker 20.10.8 does not honor proxy-settings

### ISSUE THREAD

**Issue by matthiasradde** [docker/for-linux#1290]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I have configured docker to use a proxy-server (requiring authentication, but have tested without authentication, too - same result) - as there is no other direct way to the internet.
Docker should connect to the proxy-server for every connection towards the internet. Querying a DNS-server is not neccessary in this case.
This was working up to Docker 20.10.7 - so I assume my configuration is correct.

### Actual behavior
After updating to Docker-CE 20.10.8 the proxy-configuration is not honored anymore
I see errors like `error response from daemon: get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (client.timeout exceeded while awaiting headers)`.
Creating a tcpdump reveals that the DNS-servers are queried for A-records and AAAA-records for `registry-1.docker.io` and then tried to connect to one of the resulting IP-addresses directly. No connection to the proxy-server is established.

### Steps to reproduce the behavior
- configure Docker 20.10.7 to use a proxy-server (doesn't matter if proxy needs authentication or not)
- run `docker image pull busybox` (or any other command that requires connection to the internet)
- a tcpdump reveals that docker requests DNS-servers for A-records and AAAA-records for `registry-1.docker.io` (don't know why this is needed as the proxy-server should be used) and afterwards a connection using the proxy-server is established - everything is working fine
- update to Docker 20.10.8
- run `docker image pull busybox` (or any other command that requires connection to the internet)
- a tcpdump reveals that the DNS-servers are requested for A-records and AAAA-records for `registry-1.docker.io` and then tried to connect to one of the resulting IP-addresses directly. No connection to the proxy-server is established.
- Errors like `error response from daemon: get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (client.timeout exceeded while awaiting headers)` and similar are displayed
- reverting back to Docker 20.10.7 with `sudo apt-get install docker-ce=5:20.10.7~3-0~debian-buster` (version displayed by `apt-cache policy docker-ce`)
- redo the `docker image pull busybox` - it is working again

**Output of working `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of working `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 53
  Running: 44
  Paused: 0
  Stopped: 9
 Images: 275
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-17-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.832GiB
 Name: vm-raddems
 ID: OR2D:ARRC:YKCN:AQPF:XMSF:S5C5:HHCS:FBO5:5ZI3:7AKZ:3GZB:XSRW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://xxxxx:xxxxx@REDACTED:8081/
 No Proxy: localhost,127.0.0.1,.REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Output of NOT working `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of NOT working `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 53
  Running: 42
  Paused: 0
  Stopped: 11
 Images: 275
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-17-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.832GiB
 Name: vm-raddems
 ID: OR2D:ARRC:YKCN:AQPF:XMSF:S5C5:HHCS:FBO5:5ZI3:7AKZ:3GZB:XSRW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://xxxxx:xxxxx@REDACTED:8081/
 No Proxy: localhost,127.0.0.1,.REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
using a Debian 10 running in VMWare

**Comment by thaJeztah** [comment]
I see you have a `HTTP_PROXY` configured, but not `HTTPS_PROXY`, and this looks like the issue mentioned in the 20.10.8 release notes; https://docs.docker.com/engine/release-notes/#20108

> IMPORTANT
>
> Due to net/http changes in Go 1.16, HTTP proxies configured through the $HTTP_PROXY environment variable are no longer used for TLS (https://) connections. Make sure you also set an $HTTPS_PROXY environment variable for handling requests to https:// URLs.
> 
> Refer to the HTTP/HTTPS proxy section to learn how to configure the Docker Daemon to use a proxy server.

**Comment by thaJeztah** [comment]
Let me close this issue as I think it's related to the issue I mentioned above, but feel free to continue the conversation

**Comment by matthiasradde** [comment]
@thaJeztah - thanks for the answer - it is working now 👍
