### ISSUE TITLE
target/Dockerfile: No such file or directory

### ISSUE THREAD

**Issue by rkjeevankumar** [docker/for-linux#1328]
Started by user xxxxxxxxx
Obtained Jenkinsfile from 1851b0a875acb794b8741c110daf0df55f4ccd0f
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on xxxxxxx-Dev-Qa in /var/lib/jenkins_dev_qa/workspace/_history-service_Release_qa-sp30
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
using credential bitbucker_cloud
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository http://xxxxxx/scm/xxxx/payments-history-service.git
 > git init /var/lib/jenkins_dev_qa/workspace/_history-service_Release_qa-sp30 # timeout=10
Fetching upstream changes from http://xxxxxxxxx/scm/xxxxxx/payments-history-service.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_ASKPASS to set credentials Userid for jenkins bitbucket
 > git fetch --no-tags --progress http://xxxxxxxxx/scm/xxxxxx/payments-history-service.git +refs/heads/Release/qa-sp30:refs/remotes/origin/Release/qa-sp30 # timeout=10
Avoid second fetch
Checking out Revision 1851b0a875acb794b8741c110daf0df55f4ccd0f (Release/qa-sp30)
 > git config remote.origin.url http://xxxxxxxxx/scm/xxxxxx/payments-history-service.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/Release/qa-sp30:refs/remotes/origin/Release/qa-sp30 # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1851b0a875acb794b8741c110daf0df55f4ccd0f # timeout=10
Commit message: "Merge branch '44-gtm3-2436-permanent-iqiyi-production-defect-fix' into 'Release/qa-sp30'"
 > git rev-list --no-walk 1851b0a875acb794b8741c110daf0df55f4ccd0f # timeout=10
[Bitbucket] Notifying commit build result
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (mvn build on Release dev)
Stage "mvn build on Release dev" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (mvn build on dev)
Stage "mvn build on dev" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (mvn build on qa)
Stage "mvn build on qa" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (mvn build on pvt)
Stage "mvn build on pvt" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (mvn build on PROD)
Stage "mvn build on PROD" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (OWASP Dependency-Check Vulnerabilities)
Stage "OWASP Dependency-Check Vulnerabilities" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Static Code Review on Release Dev stage)
Stage "Static Code Review on Release Dev stage" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Static Code Review on QA stage)
Stage "Static Code Review on QA stage" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Docker file creation)
[Pipeline] sh
+ mkdir docker
[Pipeline] sh
+ sed 's/$jar_file/jar_file/g' Dockerfile
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Preparing Docker file for build)
[Pipeline] sh
+ sed 's|jar_file|payment-history-service.jar|g' docker/Dockerfile
/var/lib/jenkins_dev_qa/workspace/_history-service_Release_qa-sp30@tmp/durable-143c3f74/script.sh: line 1: target/Dockerfile: No such file or directory
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Docker image in DEV stage)
Stage "Build Docker image in DEV stage" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Docker image in QA stage)
Stage "Build Docker image in QA stage" skipped due to earlier failure(s)
....

..
...
.
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by thaJeztah** [comment]
```
sed 's|jar_file|payment-history-service.jar|g' docker/Dockerfile
/var/lib/jenkins_dev_qa/workspace/_history-service_Release_qa-sp30@tmp/durable-143c3f74/script.sh: line 1: target/Dockerfile: No such file or directory
```

This doesn't look related to Docker itself, but a failure in some script used in your CI . Looks like there's a script in your CI that clones a repository and expects a file `docker/Dockerfile` that doesn't exist.
