### ISSUE TITLE
Provide containerd.io 1.5 for Ubuntu 20.04 LTS Focal Fossa

### ISSUE THREAD

**Issue by janrieke** [docker/for-linux#1329]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

The official Ubuntu 20.04 LTS Focal Fossa repositories contain the package `containerd` in version 1.5.5. However, `download.docker.com` still contains 1.4.12-1. 

There are some fixes in 1.5 that are not in 1.4, for instance a fix for resuming from a checkpoint (see #1192).
I managed to convince my Ubuntu and Docker not to install Docker's `containerd.io`, but to use `containerd` from the official Ubuntu repository instead. That works nicely (although, admittedly, I did not run extensive tests). So at least it seems to me there are no fundamental problems with that version.

### Expected behavior
`download.docker.com` should provide `containerd.io` in 1.5.x for Ubuntu 20.04.

### Actual behavior
`download.docker.com` contains `containerd.io` in version 1.4.12-1.

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by scottyhardy** [comment]
@janrieke Could you please give some instructions on your workaround for installing containerd 1.5 with docker-ce?  I'm trying to use checkpoints and discovered like you that they don't restore the suspended image.  I've tried installing the newer containerd package but apt-get also tries to remove both containerd.io and docker-ce.

**Comment by janrieke** [comment]
I followed [these instructions](https://askubuntu.com/a/1212388).

**Comment by Mohsen7s** [comment]
stable containerd 1.6 released. Can somebody please take care of this issue ?

**Comment by janrieke** [comment]
`download.docker.com` now provides `containerd.io` version 1.5.10-1, which solves the problem for me.
