### ISSUE TITLE
cgroups: cgroup mountpoint does not exist: unknown

### ISSUE THREAD

**Issue by charliehoward** [docker/for-linux#1334]
Getting issues running docker-compose on my Pi

when I run docker-compose up -d I get this error:
ERROR: for wolweb  Cannot start service wolweb: cgroups: cgroup mountpoint does not exist: unknown

docker version: 19.03.15
docker-compose version: 1.29.2

**Comment by yamikarajput546** [comment]
There might be issues with the newer versions so you should try it.
sudo apt remove docker-ce
sudo apt install docker-ce=17.09.1~ce-0~ubuntu

**Comment by charliehoward** [comment]
I don't know what caused it but I "fixed" it with by making a .sh mounting the file manually can just ran it with crontab @reboot
