### ISSUE TITLE
Getting error "http: server gave HTTP response to HTTPS client" while trying to run even simple hell-world "docker pull hello-world"

### ISSUE THREAD

**Issue by snehakhadke** [docker/for-linux#1338]
I am trying to build project with wso2 but I was getting error as shown below for 

Pulling from wso2/wso2mi
[INFO] Image 9d48c3bd43c5: Already exists
[INFO] Image 617745506915: Already exists
[INFO] Image b0ed4aba78d0: Already exists
[INFO] Image d344d5f19356: Already exists
[INFO] Image 03a6b8902d1c: Already exists
[INFO] Image a5096227daf3: Already exists
[ERROR] error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/96/969c62cec213be2ba97bf2dad184fffedd9a72179c122286976b1b838210fed4/data?verify=1640772128-k8xBexcZ2syw6Yuw4GDJRT0elmY%3D": http: server gave HTTP response to HTTPS client
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE 

So I tried to pull hello-world from powershell still got the same issue
docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
2db29710123e: Already exists                                                                                                                                                                 error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/fe/feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412/data?verify=1640771977-1oANhLEEuGXUlIssfVsBugBs7CY%3D": http: server gave HTTP response to HTTPS client

**Comment by thaJeztah** [comment]
Thanks for reporting; just to be sure it's not something in your local environment; you're not running in an environment that's using a proxy?


If that's not the case, this looks similar to https://github.com/docker/for-linux/issues/1291. Could you perhaps provide the information that @ingshtrom asked in https://github.com/docker/for-linux/issues/1291#issuecomment-930353635 and https://github.com/docker/for-linux/issues/1291#issuecomment-998837670 ?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
