### ISSUE TITLE
Please add support for next Ubuntu 22.04 (Jammy Jellyfish) LTS release

### ISSUE THREAD

**Issue by julian-alarcon** [docker/for-linux#1345]
Please add support for Ubuntu 22.04 (still in development but with a static and [defined release schedule](https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906)).

This is the next LTS release and it will be release on April 21.

Also see #940 .

**Comment by thaJeztah** [comment]
packages are now up on download.docker.com 👍
