### ISSUE TITLE
containers with a bound device that does not exist are not restarted

### ISSUE THREAD

**Issue by blastrock** [docker/for-linux#1356]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

Run a container with a device that does not exist and with `restart=always`, like: `docker run --restart=always --device /dev/does-not-exist alpine`.

In my case, the device is `/dev/ttyUSB0`. The USB port is a bit flaky and sometimes the connection is lost.

### Actual behavior

The container fails to start:

```
docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/does-not-exist": no such file or directory.
```

and nothing more happens.

### Expected behavior

Either or both of these:

- The container fails to start, but it is restarted because of `restart=always`, as with any other failure
- The container starts even if the device does not exist, and docker lets the entry point fail by itself if the device is required. Then it will be restarted as usual because of `restart=always`

**Output of `docker version`:**

```
Docker version 18.03.0-ce, build 0520e24
```

**Output of `docker info`:**

```
Containers: 19
 Running: 17
 Paused: 0
 Stopped: 2
Images: 26
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.4.0-94-generic
Operating System: Ubuntu 20.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.306GiB
Name: axanux
ID: EZVR:TEOU:OCXW:DKOD:YI4Q:4RBN:YESS:5L7T:JBNI:ADK4:3DGN:P26S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Physical machine.

**Comment by thaJeztah** [comment]
This is the expected behaviour; in this case the container's configuration is invalid at the moment it's created, so the daemon will reject the configuration.

**Comment by 12bchl** [comment]
It's pretty difficult to get dynamic devices working in docker. Any reason why the --device option can't take effect if the device exists and not if it doesn't? I understand why hotplug is difficult, that's fine. But it would be nice to only need to stop container and restart for the now-existing device to show up. As opposed to destroying container, changing config (yes I could automate this) and then creating container again. Just a humble docker user here asking the pros :)
