### ISSUE TITLE
Any plans to add containerd 1.5.x to download.docker.com?

### ISSUE THREAD

**Issue by sorenfhansen** [docker/for-linux#1358]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

The containerd version (1.4.12) currently provided from the repos in download.docker.com is nearing end of life. it also contains a bug regarding shim and file close https://github.com/containerd/containerd/issues/5130, which will not be fixed in 1.4.
Pls. add containerd 1.5 to the download repos.

### Expected behavior
download.docker.com repositories should contain containerd 1.5.x

### Actual behavior
download.docker.com contains 1.4.12 currently

### Steps to reproduce the behavior

**Output of `docker version`:**

```
N/A
```

**Output of `docker info`:**

```
N/A
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by vladimir-shopov** [comment]
And if newer versions of containerd won't be uploaded to download.docker.com what would be the recommended way of installing it on a Linux system? Currently all 3 official installation methods (for Ubuntu) mentioned on https://docs.docker.com/engine/install/ubuntu/ lead to installing version 1.4.12.

**Comment by thaJeztah** [comment]
packages for containerd 1.5 are now up on download.docker.com
