### ISSUE TITLE
Docker install stopped working on Raspberry Pi

### ISSUE THREAD

**Issue by ArneMayer** [docker/for-linux#1368]
I have been using docker on Raspberry Pi now for a while and in the past it worked great.
But now the install seems to have stopped working. 

I am installing docker by doing:
curl -sSL https://get.docker.com | sh

### Expected Behaviour
Docker should install successfully.

### Actual Failure
But now the install fails with the following messages:

Setting up docker-ce (5:20.10.13~3-0~raspbian-bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2022-03-19 00:13:44 CET; 25ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 10622 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 10622 (code=exited, status=1/FAILURE)
        CPU: 395ms
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

systemctl status docker.service prints the following:

● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-03-19 00:13:51 CET; 9min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 10859 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 10859 (code=exited, status=1/FAILURE)
        CPU: 457ms

Mar 19 00:13:51 meb-hauskraftwerk2 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Mar 19 00:13:51 meb-hauskraftwerk2 systemd[1]: Stopped Docker Application Container Engine.
Mar 19 00:13:51 meb-hauskraftwerk2 systemd[1]: docker.service: Start request repeated too quickly.
Mar 19 00:13:51 meb-hauskraftwerk2 systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 19 00:13:51 meb-hauskraftwerk2 systemd[1]: Failed to start Docker Application Container Engine.

I am out of ideas how to fix this.

**Comment by allkindsofralph** [comment]
I am having the same issue

**Comment by WombleWoo7547** [comment]
same issue! I've also opened an issue and am troubleshooting. #1370

**Comment by WombleWoo7547** [comment]
I found the issue here! All I needed to do was reboot. I'm not sure if the ```sudo apt update && sudo apt full-upgrade && sudo apt autoremove``` did it or the reboot, or BOTH! But anyway, it's all well and good now. So do both, just to make sure, and hopefully it will work! :D

**Comment by allkindsofralph** [comment]
Restarts didn’t help me at all but I used this yesterday and was able to install when the convenience script wouldn’t work. 

`sudo apt install docker.io docker-compose`

**Comment by ArneMayer** [comment]
The issue seems to have resolved itself for me. It worked again for me today.

**Comment by glynhudson** [comment]
Same issue for me, a reboot fixed the issue. Might be a good idea to add a note to the script to prompt the user to reboot? I did a lot of head scratching before I found this thread!

**Comment by ROBdk97** [comment]
Same issue here

**Comment by nishantrai5** [comment]
Reboot fixed things for me! Never got the warning for doing a reboot >> Please add it to the installation script somewhere
