### ISSUE TITLE
Please provide a repo for Fedora 36

### ISSUE THREAD

**Issue by sanjayankur31** [docker/for-linux#1372]
* [ ] This is a bug report
* [x] This is a feature request
* [ ] I searched existing issues before opening this one

[Fedora 36 is to be released in a month](https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html): 2022-04-26

It'll be good to have a docker repo for Fedora 36 in place when the release is made so that users installing or upgrading from Fedora 34/35 have packages available to use.

Currently, dnf says that it cannot find a docker repository for F36.

### Expected behavior

Repository for Fedora 36 is available

### Actual behavior

Repository for Fedora 36 is not available

### Steps to reproduce the behavior

Follow installation steps from [docs](https://docs.docker.com/engine/install/fedora/#install-using-the-repository).

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by sanjayankur31** [comment]
Currently users will see:

```
Docker CE Stable - x86_64                                                                                                                    858  B/s | 384  B     00:00    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/fedora/36/x86_64/stable/repodata/repomd.xml (IP: 54.192.137.35)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by sanjayankur31** [comment]
Workaround is to use `dnf --releasever=35 ...` to get it to use the docker F35 repo.

**Comment by Axiol** [comment]
> Workaround is to use `dnf --releasever=35 ...` to get it to use the docker F35 repo.

I can see that it wants to downgrade packages (flatpack, rpm, ... ). Wouldn't this be a problem?

**Comment by sanjayankur31** [comment]
F36 packages should have newer versions than F35 ones, so this *should* not happen. Please post on the Fedora channels if you run into issues with this, I guess? https://ask.fedoraproject.org etc

**Comment by thaJeztah** [comment]
packages for fedora 36 are now up on download.docker.com
