### ISSUE TITLE
Using docker images to start applications forces me to use root due to "PermissionError"

### ISSUE THREAD

**Issue by caliari-italo** [docker/for-linux#1375]
Hello everyone. I hope you all doing fine.

I'm using TensorFlow gpu docker image to start spyder-ide and it is working just fine with root. 

The _Dockerfile_ used to build the image is:
```
FROM tensorflow/tensorflow:latest-gpu
RUN apt-get update
RUN apt-get install python3-opencv libasound2 -y
RUN apt-get install -qq pyqt5-dev-tools libxcb-xinerama0 xterm --fix-missing
RUN pip install --upgrade pip
RUN pip install spyder
RUN pip install numpy
RUN pip install pandas
RUN pip install sklearn
RUN pip install matplotlib
WORKDIR /home
```

and the docker arguments used to start the image are:
```
sudo docker run -it \
    --gpus all \
    --env="DISPLAY" \
    --net=host \
    -v '/tmp/.X11-unix':'/tmp/.X11-unix' \
    -v $PWD:'/home' myimage \
    env QTWEBENGINE_DISABLE_SANDBOX=1 spyder
```

This works just fine but I wish not use root for this to avoid creating protected files.

But setting the user with  "--user $(id -u):$(id -g)" as in:
```
sudo docker run -it \
    --user $(id -u):$(id -g) \
    --gpus all \
    --env="DISPLAY" \
    --net=host \
    -v '/tmp/.X11-unix':'/tmp/.X11-unix' \
    -v $PWD:'/home' myimage \
    env QTWEBENGINE_DISABLE_SANDBOX=1 spyder
```

gives me the following error

  ```
File "/usr/local/bin/spyder", line 5, in <module>
    from spyder.app.start import main
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/start.py", line 45, in <module>
    from spyder.config.base import (get_conf_path, running_in_mac_app,
  File "/usr/local/lib/python3.8/dist-packages/spyder/config/base.py", line 357, in <module>
    LANG_FILE = get_conf_path('langconfig')
  File "/usr/local/lib/python3.8/dist-packages/spyder/config/base.py", line 237, in get_conf_path
    os.makedirs(xdg_config_home)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```

I would really appreciate some insights on this problem. Thank you all in advance.

**Comment by thaJeztah** [comment]
Thanks for reporting; this doesn't look like a bug. Starting a container as a different uid/gid does "just that"; the container's main process is started as the given user ID, which means the process running inside the container won't be `root` (or the container image's default user), and possibly doesn't have access to files, unless they have been given the correct permissions (same as how permissions are handled in a non-containerised environment).

- make sure that files that were added as part of the Dockerfile, and that must be accessible by a "non-root" user at runtime have the right permissions inside the image (if it needs a file or directory at `/.config` within the container, make sure that file or directory exists with the right permissions (e.g. group read/writable or if needed world read/writable).
- for files and directories you're bind-mounting from the host, take into account that those will pertain the permissions as defined on the host (see https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker/29251160#29251160 for some more details)

Closing this ticket, as it doesn't look like a bug, but feel free to continue the conversation
