### ISSUE TITLE
docker stack does not actually ignore "build"

### ISSUE THREAD

**Issue by kaos14** [docker/for-linux#1380]
According to compose spec https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension an extension can be used anywhere in the compose structure as long as it starts with "x-". But when the extension is used in an ignored fragment, then `docker stack` fails.

This can be a problem with `docker stack` or a general problem with extensions not actually allowed in places that should be ignored regardless. 

* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

```
docker stack deploy -c docker-compose.yml foo
```
runs correctly

### Actual behavior

```
docker stack deploy -c docker-compose.yml foo
```
fails with error:
```
services.addon.build Additional property x-bake is not allowed
```
### Steps to reproduce the behavior

- Download the compose example from https://docs.docker.com/engine/reference/commandline/buildx_bake/#extension-field-with-compose
- Prepend with `version: '3.8'`
```
# docker-compose.yml
version: '3.8'
services:
  addon:
    image: ct-addon:bar
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CT_ECR: foo
        CT_TAG: bar
      x-bake:
        tags:
          - ct-addon:foo
          - ct-addon:alp
        platforms:
          - linux/amd64
          - linux/arm64
        cache-from:
          - user/app:cache
          - type=local,src=path/to/cache
        cache-to: type=local,dest=path/to/cache
        pull: true

  aws:
    image: ct-fake-aws:bar
    build:
      dockerfile: ./aws.Dockerfile
      args:
        CT_ECR: foo
        CT_TAG: bar
      x-bake:
        secret:
          - id=mysecret,src=./secret
          - id=mysecret2,src=./secret2
        platforms: linux/arm64
        output: type=docker
        no-cache: true
```
- Run `docker stack deploy -c docker-compose.yml foo`

**Output of `docker version`:**

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~20.04.2
  GitCommit:        
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 96
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: q8xg3bto6a08ljh17ldhv6dms
  Is Manager: true
  ClusterID: 9br2kz32r6a6wkamflri0mnbq
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.28
  Manager Addresses:
   192.168.1.28:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-107-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.17GiB
 Name: kaos
 ID: XTH4:MDRF:FKUK:LKU2:JDL3:GDZY:VK4Q:CECH:EF3A:DMSJ:2HC5:4MS6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
docker stack uses the compose v3 specification, which pre-dates the "compose-spec"; the file is verified against the v3.8 spec in your example, which is in https://github.com/docker/cli/blob/v20.10.15/cli/compose/schema/data/config_schema_v3.8.json

**Comment by kaos14** [comment]
@thaJeztah I'm not sure your explanation address the issue here. `version: 3.8` is there only for the stack not to complain about unsupported compose file version

In other words, why does docker stack correctly ignore attributes like "x-foo" in the compose file, and at the same time fails on an "x-foo" attribute in "build" section?

OK:
```
version: '3.8'
x-foo: True
services:
  addon:
    build: 
      context: .
```

Errors out:
```
version: '3.8'
services:
  addon:
    build: 
      context: .
      x-foo: True
```

**Comment by thaJeztah** [comment]
Because in the 3.8 schema, `x-` attributes are allows at the top level; https://github.com/docker/cli/blob/v20.10.15/cli/compose/schema/data/config_schema_v3.8.json#L67
and within "definitions" https://github.com/docker/cli/blob/v20.10.15/cli/compose/schema/data/config_schema_v3.8.json#L328

but not within the `build` section; 

https://github.com/docker/cli/blob/v20.10.15/cli/compose/schema/data/config_schema_v3.8.json#L78-L94

**Comment by kaos14** [comment]
The documentation at https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension clearly states that: 
> They [`x-` attributes] **can be used within any structure** in a Compose file.

There is an example at https://docs.docker.com/engine/reference/commandline/buildx_bake/#extension-field-with-compose which sole purpose is to document the usage of `x-bake` in `build` section.

Also it seems the schema at https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json allows using `x-` attributes in `build`.

Is the documentation wrong? Is it a version mix-up? Why is docker cli using different schema?

**Comment by kaos14** [comment]
Ok, I think I understand your answer now. The spec you are referring to is actually stack schema, not compose, though the url contains "compose"...

Going back to the main issue: Why does docker stack complain about something it should ignore anyway? Why does the schema specify `build` field at all? Does it really matter if `build` section is syntactically correct if it is later ignored?

I would suggest just adding `"patternProperties": {"^x-": {}}` to the `build` section as a quick fix, but I see there are more discrepancies between stack and compose in the `build` secion. 

How about swapping the whole `build` section definition with something like`"patternProperties": {"^build$": {}}` at `service` level to completely ignore it just like with `x-` attributes?

**Comment by kaos14** [comment]
@thaJeztah I look forward to your reply.
