### ISSUE TITLE
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

### ISSUE THREAD

**Issue by Passenger12138** [docker/for-linux#1387]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I downloaded the pytorch/pytorch:1.3-cuda10.1-cudnn7-devel image and tried to start it with sudo nvidia-docker run -itd -p 5004:22 pytorch/pytorch:1.3-cuda10.1-cudnn7-devel , the expected result is a normal startup, but a confusing error is encountered

### Actual behavior
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

![image](https://user-images.githubusercontent.com/47623700/162998046-1b466635-9be4-4d50-824d-3fcadb95c17d.png)

### Steps to reproduce the behavior

**Output of `docker version`:**

```
a123@a123-Precision-7920-Tower:~$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

![image](https://user-images.githubusercontent.com/47623700/162998385-541860f7-14fd-478f-a1f0-f08d07d9e74f.png)

```

**Output of `docker info`:**

```
a123@a123-Precision-7920-Tower:~$ sudo docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-107-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 40
 Total Memory: 187.6GiB
 Name: a123-Precision-7920-Tower
 ID: Q5N6:TH4V:KR4R:3VQM:MDA3:MO33:H3D6:QHUL:POYY:Q43R:2PDO:RBVQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://f1z25q5p.mirror.aliyuncs.com/
 Live Restore Enabled: false

WARNING: No swap limit support
![image](https://user-images.githubusercontent.com/47623700/162998850-14de42a3-328a-47fd-9812-175c14beaee9.png)

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
a123@a123-Precision-7920-Tower:~$ uname -r
5.4.0-107-generic

a123@a123-Precision-7920-Tower:~$ uname -r
5.4.0-107-generic
a123@a123-Precision-7920-Tower:~$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

a123@a123-Precision-7920-Tower:~$ getenforce
Disabled

**Comment by WombleWoo7547** [comment]
It looks to be something to do with NVIDIA? Maybe try looking for some drivers in the apt repos. Or update to 20.04 or 22.04 LTS. Also if you installed docker through cURL, try using apt or if you installed using apt try cURL. Can you also supply your hardware info. You may be using the wrong version of the image.

**Comment by thaJeztah** [comment]
Yes, this doesn't directly look related to docker itself; perhaps something for https://github.com/NVIDIA/nvidia-docker

**Comment by mateoradman** [comment]
Steps on how to solve this problem:
OS: Ubuntu 22.04
Docker version: 20.10.16
Nvidia-docker2: 2.10.0

1. Make sure you have Nvidia drivers installed by running `nvidia-smi` and getting the output you expect.
2. Install nvidia-docker2 by following the installation guide here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-ubuntu-and-debian

Add `no-cgroups = false` to `/etc/nvidia-container-runtime/config.toml`
```
[nvidia-container-cli] 
no-cgroups = false 
```
and then `sudo systemctl restart docker`.

**Comment by prateekkrjain** [comment]
No luck with this. 

Followed steps mentioned here: https://docs.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/requirements.html

`docker info`

`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Kernel Version: 4.4.0-19041-Microsoft
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.37GiB
 Name: LAPTOP-C2AFN23K
 ID: BW3L:ZSIT:Y6G7:YVYP:4QKS:M6CB:3NHQ:FEWH:O3YG:S2BV:MPO7:TZQM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support`

**Comment by shiwakant** [comment]
For me, it only works when all docker commands are run at root-level privileges!
