### ISSUE TITLE
Docker stats returning null in Arch linux but empty array in Debian

### ISSUE THREAD

**Issue by Tricky12321** [docker/for-linux#1389]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
When asking the docker.socket for status like so:
`curl --unix-socket /var/run/docker.sock http://localhost/containers/<container-id-or-name>/stats?stream=false`
The output is in json
`...
{"io_service_bytes_recursive":[],"io_serviced_recursive":[],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]}
...`

### Actual behavior
Arch linux responds like: 
`...
{"io_service_bytes_recursive":REDACTED,"io_serviced_recursive":null,"io_queue_recursive":null,"io_service_time_recursive":null,"io_wait_time_recursive":null,"io_merged_recursive":null,"io_time_recursive":null,"sectors_recursive":null}
...`

Debian responds like:
`...
{"io_service_bytes_recursive":[],"io_serviced_recursive":[],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]}
...`

### Steps to reproduce the behavior
Run this command:
`curl --unix-socket /var/run/docker.sock http://localhost/containers/<container-id-or-name>/stats?stream=false`
On Debian with docker installed and on Arch linux with docker installed and compare output of an identical container.
Output differes in that Arch Linux returns null values, but Debian returns empty array.

**Output of `docker version`:**
(Same version was used for both Debian and Arch Linux)
Also tested with `Docker version 20.10.7` same result
```
Docker version 20.10.12
```

**Output of `docker info`:**
From arch linux
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  compose: Docker Compose (Docker Inc., 2.3.3)

Server:
 Containers: 17
  Running: 15
  Paused: 0
  Stopped: 2
 Images: 1359
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.10-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.79GiB
 Name: moonskye-srv-1
 ID: AO2T:U4YT:AGV3:T7OG:BV5W:M5FA:NVYN:2WRS:376U:RQQ3:7AJV:E4D7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
I seem to recall there were some fixes in containerd for this; from the commit, it looks like you're running containerd v1.6.0; are you still able to produce this on a current version of containerd 1.6 (and docker)?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
