### ISSUE TITLE
Can't use open anymore and is depreciated but no solution is provided

### ISSUE THREAD

**Issue by BCdeveloper98** [docker/for-linux#1396]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

It should have opened the Docker.app

### Actual behavior

I am building a solution on hyperledger fabric and following official documentation.

I am using this command :

open /Applications/Docker.app

But it gives an error of : 

` open /Applications/Docker.app
`

`Command 'open' not found, did you mean:

  command 'gopen' from deb gnustep-gui-runtime (0.27.0-5build2)
  command 'pen' from deb pen (0.34.1-1build1)
  command 'wopen' from deb gworkspace.app (0.9.4-2)

Try: sudo apt install <deb name>

sudo open /Applications/Docker.app
sudo: open: command not found
`

@andrewhsu 

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied


```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-41-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.5GiB
 Name: siba-Precision-5820-Tower
 ID: DCJ4:RFYV:TZFG:N2GG:TROX:BATS:XQGH:F5KN:SEEX:KMST:DSGO:26SZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Physical

**Comment by thaJeztah** [comment]
`/Applications/Docker.app`  would be where Docker Desktop on macOS is installed; is this issue about Docker Desktop for Linux?

**Comment by BCdeveloper98** [comment]
Yes it is issue with docker linux

**Comment by thaJeztah** [comment]
Have you installed _Docker Desktop_ for Linux (https://docs.docker.com/desktop/linux/), or only the Docker Engine ? Was this an existing installation, or a fresh install? (did it work before on the same machine?)

**Comment by thaJeztah** [comment]
closing as more information is needed
