### ISSUE TITLE
http://%2Fvar%2Frun%2Fdocker.sock/v1.26/build?

### ISSUE THREAD

**Issue by vaishnavipro** [docker/for-linux#1397]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
Seems like this was opened by mistake?

**Comment by thaJeztah** [comment]
Looks like another spam account; reported for abuse
