### ISSUE TITLE
failed to start daemon: Couldn't create reference store repository: EOF

### ISSUE THREAD

**Issue by wangzheooo** [docker/for-linux#1403]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Start Docker 

### Actual behavior
Get error when starting Docker 

### Steps to reproduce the behavior
$ sudo dockerd
INFO[2022-06-02T22:07:57.749867610+08:00] Starting up                                  
INFO[2022-06-02T22:07:57.750951434+08:00] parsed scheme: "unix"                         module=grpc
INFO[2022-06-02T22:07:57.750969383+08:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-06-02T22:07:57.750986066+08:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2022-06-02T22:07:57.751002986+08:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-06-02T22:07:57.752766889+08:00] parsed scheme: "unix"                         module=grpc
INFO[2022-06-02T22:07:57.752785958+08:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2022-06-02T22:07:57.752798417+08:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2022-06-02T22:07:57.752805047+08:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2022-06-02T22:07:57.760528619+08:00] [graphdriver] using prior storage driver: overlay2 
failed to start daemon: Couldn't create reference store repository: EOF

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:29:29 2020
 OS/Arch:           linux/amd64
 Experimental:      false
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info: read unix @->/var/run/docker.sock: read: connection reset by peer
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
```
$ uname -a
Linux izm5edevpwjux6yjnqmvf6z 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core
```

**Comment by wangzheooo** [comment]
https://github.com/moby/moby/issues/28977

**Comment by thaJeztah** [comment]
It looks like you're running an older version of docker that reached EOL; was this a fresh installation or an existing install? Are you still able to reproduce this on a currently maintained version of docker (20.10 or up)?

When you ran `sudo dockerd`, was the docker systemd service also running?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
