### ISSUE TITLE
The problem is shown in the following picture

### ISSUE THREAD

**Issue by LiuWenPeng666** [docker/for-linux#1407]
![image](https://user-images.githubusercontent.com/44110991/173041017-26bfef84-caa8-4cff-be7e-8f0d78b9fd40.png)

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
