### ISSUE TITLE
Support for Ubuntu 17.10 (artful)

### ISSUE THREAD

**Issue by fentas** [docker/for-linux#141]
Refering from https://github.com/moby/moby/issues/34577 I open an issue here now.
As far I now `artful` was released 2 days ago (https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes) and I am unable to install docker via `get.docker.com`.

* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Installing docker.

### Actual behavior
```sh
/tmp> curl -fsSL get.docker.com -o get-docker.sh
/tmp> sh get-docker.sh
# Executing docker install script, commit: 490beaa

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/
```

**Comment by seemethere** [comment]
Packaging support is bring added here: https://github.com/docker/docker-ce-packaging/pull/55

Install support will be added to test.docker.com after rc1 of 17.11.0-ce.

Install support will be added for get.docker.com after GA of 17.11.0-ce

**Comment by seemethere** [comment]
Also the repository for the install script is located at:

https://github.com/docker/docker-install

**Comment by Stradivario** [comment]
docker: 

```
sudo apt-get install docker.io
```
Compose
```
sudo apt-get install docker-compose
```

**Comment by pauljherring** [comment]
> sudo apt-get install docker.io


Why are you recommending to install an old version that we are told explicitly to remove when installing -ce? (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#uninstall-old-versions)

**Comment by evenfrost** [comment]
While waiting for official Artful release, you can install latest Docker semi-manually:
```bash
curl -O https://download.docker.com/linux/ubuntu/dists/zesty/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
sudo dpkg -i docker-ce_17.09.0_ce-0_ubuntu_amd64.deb
```

**Comment by jlnr** [comment]
^ works. You'll also need to download docker-compose as shown in the official docs, *not* via apt-get (the latter will remove docker-ce and reinstall the outdated docker.io package):

https://docs.docker.com/compose/install/

**Comment by seemethere** [comment]
Submitted a PR to add temporary support for artful for `get.docker.com` and `test.docker.com`

https://github.com/docker/docker-install/pull/44

**Comment by seemethere** [comment]
Support was cherry picked into Docker CE for 17.11: https://github.com/docker/docker-ce/pull/283

**Comment by thaJeztah** [comment]
Thanks! Let me close this one then

**Comment by pawelprazak** [comment]
Still no supported repository for Artful:
    
```
Err:11 https://download.docker.com/linux/ubuntu artful Release                       
  404  Not Found [IP: 52.84.194.62 443]
Reading package lists... Done                      
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by thaJeztah** [comment]
@pawelprazak read above; it will be for docker 17.11, which has not been released yet

**Comment by seemethere** [comment]
Also just for clarification, `17.11.0-ce` is an `edge` release and will therefore be in the `edge` channel. Packages will be available in the `stable` channel for Ubuntu Artful for the next `stable` release which should be `17.12.0-ce`.

**Comment by Davidnet** [comment]
Could you update the docs when this is supported?

**Comment by seemethere** [comment]
@Davidnet yes we will update the documentation when this is officially released, I will also comment on the issue when release the first RC (Release Candidate) as well as for GA!

**Comment by seemethere** [comment]
With `17.11.0-ce-rc2` Ubuntu Artful repositories are now live on download.docker.com!

https://github.com/docker/docker-install/pull/46 adds it to the `test.docker.com` script which can be used to try out the latest RC on Ubuntu Artful!

**Comment by pieval** [comment]
Is it supposed to work now with the main installation process on the stable branch fr ubuntu 17.10 ?

Right now I'manable to get docker-ce using 
```
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```
But I can see there is a folder for artful here : https://download.docker.com/linux/ubuntu/dists/artful/stable/

Did I miss something ?

**Comment by seemethere** [comment]
@pieval https://github.com/docker/for-linux/issues/141#issuecomment-341129767

**Comment by dbrimley** [comment]
It looks like there are still issues when downloading using the official instructions on...

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1

```
dbrimley@agunta:~/Downloads$ sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    $(lsb_release -cs) \
>    stable"
dbrimley@agunta:~/Downloads$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu artful-security InRelease [70.3 kB]
Hit:2 http://gb.archive.ubuntu.com/ubuntu artful InRelease                                                                                                               
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                             
Hit:4 http://ppa.launchpad.net/webupd8team/java/ubuntu artful InRelease                                                                                                  
Get:5 http://gb.archive.ubuntu.com/ubuntu artful-updates InRelease [76.7 kB]                                                                                             
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                                                                               
Hit:7 http://ppa.launchpad.net/webupd8team/terminix/ubuntu artful InRelease                                                                                              
Get:8 https://download.docker.com/linux/ubuntu artful InRelease [39.1 kB]                                                                                                
Hit:9 http://gb.archive.ubuntu.com/ubuntu artful-backports InRelease                                                                                                     
Get:10 http://security.ubuntu.com/ubuntu artful-security/universe amd64 DEP-11 Metadata [2,184 B]                                         
Hit:12 https://download.sublimetext.com apt/stable/ InRelease                                                               
Get:13 http://gb.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages [22.3 kB]
Get:14 http://gb.archive.ubuntu.com/ubuntu artful-updates/main i386 Packages [22.3 kB]                    
Get:15 http://gb.archive.ubuntu.com/ubuntu artful-updates/main amd64 DEP-11 Metadata [8,272 B]
Get:16 http://gb.archive.ubuntu.com/ubuntu artful-updates/universe amd64 DEP-11 Metadata [2,188 B]                            
Hit:17 https://repo.skype.com/deb stable InRelease                                                         
Fetched 243 kB in 1s (198 kB/s)                                            
Reading package lists... Done
dbrimley@agunta:~/Downloads$ sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
dbrimley@agunta:~/Downloads$ ^C
dbrimley@agunta:~/Downloads$ lsb_release -cs
artful
```

**Comment by thaJeztah** [comment]
@dbrimley see https://github.com/docker/for-linux/issues/141#issuecomment-341126785 and https://github.com/docker/for-linux/issues/141#issuecomment-341129767

>

**Comment by dbrimley** [comment]
Thanks for the update, any idea when this will be available?

Also, I would suggest you change your installation instructions and remove the $(lsb_release -cs) that way it won't try to download packages that are not available, especially when there are weeks and months delay between docker and an ubuntu release.

Right now you are publishing download instructions that are broken.

**Comment by fentas** [comment]
@dbrimley As far I know, first will be RC3 released on Monday and very soon (in a few days ?) it will be available.
ref: https://github.com/moby/moby/issues/35310#issuecomment-341840942

**Comment by thaJeztah** [comment]
> Right now you are publishing download instructions that are broken.

That's where the "requirements" section is for: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#os-requirements

> ### OS requirements
> 
> To install Docker CE, you need the 64-bit version of one of these Ubuntu
versions:
> 
> - Zesty 17.04
> - Xenial 16.04 (LTS)
> - Trusty 14.04 (LTS)

**Comment by anandbaskaran** [comment]
@thaJeztah Thank you for the detailed comments! 

Do you have an **estimated release date** for `17.11.0-ce edge version` and `17.12.0-ce stable version`

**Comment by pawelprazak** [comment]
@thaJeztah I've read the instructions like 3 times and haven't noticed that before, you might reconsider making the docs clearer. Judging from this thread, I'm not the only one who's confused.

**Comment by thaJeztah** [comment]
@anandbaskaran I don't know if there's a final date yet; to install on Ubuntu 17.10 before it's released, you can either try installing the packages for Ubuntu 17.04 (they should likely just work fine), or enable the "test" channel, which would install the release candidates. For production, I would generally recommend using the Ubuntu LTS versions (as they have a longer support cycle, so you won't run into these issues).

@pawelprazak thanks for your feedback! could you open an issue in the documentation issue tracker with suggestions to make the system requirements more apparent? Easiest way to do so is to use the links in the navigation bar on the right of that page;

<img width="233" alt="screen shot 2017-11-06 at 14 43 46" src="https://user-images.githubusercontent.com/1804568/32443937-1be0c36a-c301-11e7-8860-a368d342c590.png">

**Comment by skavinvarnan** [comment]
Point the installer to fetch from zesty (17.04). It works fine

in point 4 of [setting up a repository](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository)

Replace
`$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"`

with 
`$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   zesty \
   stable"`

**Comment by theunsa** [comment]
@skavinvarnan :+1:  good enough workaround until 17.12.0-ce

**Comment by snapshotpl** [comment]
I cannot install on 17.10 using zesty ( @skavinvarnan solution):
```
Job for docker.service failed because the service did not take the steps required by its unit configuration.
See "systemctl  status docker.service" and "journalctl  -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: protocol) since Wed 2017-11-08 20:55:10 CET; 6ms ago
     Docs: https://docs.docker.com
  Process: 23014 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=2)
 Main PID: 23014 (code=exited, status=2)
      CPU: 1min 30.062s

lis 08 20:55:10 witold-desktop systemd[1]: docker.service: Unit entered failed state.
lis 08 20:55:10 witold-desktop systemd[1]: docker.service: Failed with result 'protocol'.
```

**Comment by ross-spencer** [comment]
The script here works a treat for Artful (17.10) and installs 17.10.0-ce: https://github.com/docker/docker-install

**Comment by beruic** [comment]
@ross-spencer Did you install `test`? I still see no packages at https://download.docker.com/linux/ubuntu/dists/artful/pool/stable/amd64/.

**Comment by seemethere** [comment]
I will make an announcement on this issue when packages are released on specific channels. No need to keep repeating the same comments.

**Comment by ross-spencer** [comment]
@beruic download.docker.com, the script references Artful: https://github.com/docker/docker-install/blob/master/install.sh#L61 So I tried it and it worked (at least until the packages are released)

**Comment by thaJeztah** [comment]
Yes, the script had a temporary redirect added to install `zesty` packages on artful; https://github.com/docker/docker-install/commit/49ee7c14ad54293e7891579d0a07a0c7558289a8#diff-3fbb47e318cd8802bd325e7da9aaabe8R360

**Comment by beruic** [comment]
So when packages are released, I can just remove the repositories, and run the script again? :)

**Comment by luislobo** [comment]
As of today, this works:
```
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   test"
```
That is, using the "test" repository

**Comment by juliojimenez** [comment]
This seemed to have worked:

`sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     edge"`

**Comment by seemethere** [comment]
as @juliojimenez has already pointed out:

With the `GA` of `17.11.0-ce` you can now use the `edge` channel to get Docker CE for Ubuntu Artful!

get.docker.com and test.docker.com have already been updated with the support for Ubuntu Artful so if you are looking for an easy way to install Docker CE for Ubuntu Artful give this a try:

```bash
$ curl -fsSL get.docker.com > get-docker.sh
$ sh get-docker.sh
```

**Comment by beruic** [comment]
Since `curl` is not installed by default on Ubuntu, here is the `wget` version of the first line:
```bash
$ wget get.docker.com -O get-docker.sh
```
Alternatively use the one liner
```bash
$ wget -q get.docker.com -O- | sh
```

**Comment by thaJeztah** [comment]
> To avoid saving the script, use the one liner

Be aware that this script performs privileged actions; generally it's recommended to not `curl | sh` (or `wget | sh`) scripts, but download the script and verify that you're ok with its contents before executing it.

**Comment by bohdantrotsenko** [comment]
@pieval 
https://download.docker.com/linux/ubuntu/dists/artful/stable/Contents-amd64 has 0 bytes.

**Comment by thaJeztah** [comment]
@bohdantrotsenko Docker 17.11 is an _edge_ release, so it's not yet in the _stable_ channel; it will be once 17.12 is released see three comments up https://github.com/docker/for-linux/issues/141#issuecomment-345898792

**Comment by dstibbe** [comment]
Installation documentation is still unclear about all of this. Please update your documentation.

**Comment by thaJeztah** [comment]
@dstibbe please be specific about what's not clear in the documentation? Here's some parts of the installation https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

<img width="607" alt="screen shot 2017-12-21 at 22 43 51" src="https://user-images.githubusercontent.com/1804568/34276160-73d88b1c-e6a0-11e7-86e2-785da4d69359.png">

<img width="978" alt="screen shot 2017-12-21 at 22 43 14" src="https://user-images.githubusercontent.com/1804568/34276165-7d588e6c-e6a0-11e7-80d0-c9d6fc5a705c.png">


Or, using the script at https://get.docker.com:

<img width="975" alt="screen shot 2017-12-21 at 22 42 54" src="https://user-images.githubusercontent.com/1804568/34276178-8c852d8c-e6a0-11e7-88bc-9c47b6972542.png">

**Comment by seemethere** [comment]
Docker CE `17.12.0-ce` now adds packages in the `stable` channel for Ubuntu Artful!

**Comment by dbrimley** [comment]
@seemethere You're right artful now works as an apt repository...

```deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable```

Versions on website have also been updated to show artful, so thumbs up and thanks everyone.

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#os-requirements

**Comment by Ustingit** [comment]
https://base64.co.za/install-docker-ce-on-ubuntu-17-10-artful-aardvark/ help me with this issue

**Comment by seemethere** [comment]
@Ustingit those instructions are no longer necessary. Feel free to utilize the official docs on how to install Docker CE on Ubuntu Artful
