### ISSUE TITLE
"Download Update" button not working on 4.12.0

### ISSUE THREAD

**Issue by chrisimcevoy** [docker/for-linux#1439]
I'm trying to update Docker Desktop for Linux from 4.12.0 to 4.13.0.

When I click the "Download Update" button, it opens the [release notes](https://docs.docker.com/desktop/release-notes/) in my browser.

(When I click the "Release Notes" button, it does the same thing.)

Is this button supposed to actually do an update on Linux? I'm on Fedora, so I just upgraded by downloading the rpm and installing with dnf.

![image](https://user-images.githubusercontent.com/12284065/197287424-5e8b4221-252e-47de-a0cd-3d990f170806.png)

**Comment by nicks** [comment]
I think this is currently expected...we don't have any auto-installer on Linux. Downloading the deb/rpm from the CLI is what the install instructions say to do.

**Comment by chrisimcevoy** [comment]
Thanks @nicks
