### ISSUE TITLE
dockerd daemon.json runtime documentation

### ISSUE THREAD

**Issue by mcastelino** [docker/for-linux#144]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

As per the documentation additional runtimes can be added to docker via daemon.json

https://docs.docker.com/engine/reference/commandline/dockerd/#docker-runtime-execution-options

```
{
	"default-runtime": "runc",
	"runtimes": {
		"runc": {
			"path": "runc"
		},
		"custom": {
			"path": "/usr/local/bin/my-runc-replacement",
			"runtimeArgs": [
				"--debug"
			]
		}
	}
}
```

### Actual behavior

In the actual implementation specifying runc in addition the new runtime that is being added results in the failure of dockerd to start with an error (As runc is reserved and picked up by default, specifying runc will cause issues).

```
[...]: unable to configure the Docker daemon with file /etc/docker/daemon.json: configuration validation from file failed (runtime name 'runc' is reserved)
```

### Steps to reproduce the behavior

**Output of `docker version`:**

```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

So the documentation needs to be updated to reflect that runc should not be specified.

A valid configuration of the type below results in the expected behaviour
```
{
"storage-driver": "devicemapper",
"storage-opts": [
        "dm.directlvm_device=/dev/sdc",
        "dm.thinp_percent=95",
        "dm.thinp_metapercent=1",
        "dm.thinp_autoextend_threshold=80",
        "dm.thinp_autoextend_percent=20",
        "dm.directlvm_device_force=true"
],
       "default-runtime": "cc-runtime",
        "runtimes": {
             "cc-runtime": {
                      "path": "/usr/bin/cc-runtime"
             }
        }
}
```

And as you can see below, runc is picked up by default

```
docker info | grep runtime
Runtimes: cc-runtime runc
WARNING: No swap limit support
Default Runtime: cc-runtime
```

**Comment by thaJeztah** [comment]
Thanks! Yes, `runc` is indeed a reserved name, and we didn't consider that when adding the example. I opened a pull request to update the example, using a runtime that's probably familiar to you 😉  https://github.com/docker/cli/pull/644
