### ISSUE TITLE
Docker stats always return null for 'io_service_time_recursive', 'io_wait_time_recursive', io_queue_recursive

### ISSUE THREAD

**Issue by Jae1313** [docker/for-linux#1440]
We want to calculate docker diskio latency and queue number, it seems could use io_service_time, io_wait_time and io_queue_recursive.
But in our testbed, those fields always report null.
`# curl --unix-socket /var/run/docker.sock "http://localhost/containers/e73e861a3f6f/stats?stream=0" | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2990    0  2990    0     0   2956      0 --:--:--  0:00:01 --:--:--  2957
{
    "blkio_stats": {
        "io_merged_recursive": [],
        "io_queue_recursive": [],
        "io_service_bytes_recursive": [
            {
                "major": 8,
                "minor": 0,
                "op": "Read",
                "value": 8192
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Write",
                "value": 13356544
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Sync",
                "value": 13356544
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Async",
                "value": 8192
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Total",
                "value": 13364736
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Read",
                "value": 8192
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Write",
                "value": 13356544
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Sync",
                "value": 13356544
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Async",
                "value": 8192
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Total",
                "value": 13364736
            }
        ],
        "io_service_time_recursive": [],
        "io_serviced_recursive": [
            {
                "major": 8,
                "minor": 0,
                "op": "Read",
                "value": 2
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Write",
                "value": 2973
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Sync",
                "value": 2973
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Async",
                "value": 2
            },
            {
                "major": 8,
                "minor": 0,
                "op": "Total",
                "value": 2975
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Read",
                "value": 2
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Write",
                "value": 2973
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Sync",
                "value": 2973
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Async",
                "value": 2
            },
            {
                "major": 253,
                "minor": 0,
                "op": "Total",
                "value": 2975
            }
        ],
        "io_time_recursive": [],
        "io_wait_time_recursive": [],
        "sectors_recursive": []
    },
    "cpu_stats": {
        "cpu_usage": {
            "percpu_usage": [
                23363825457,
                26329622212,
                24282005426,
                23010308204,
                22621964722,
                22904147606,
                23388294099,
                22381241952
            ],
            "total_usage": 188281409678,
            "usage_in_kernelmode": 82550000000,
            "usage_in_usermode": 93840000000
        },
        "online_cpus": 8,
        "system_cpu_usage": 5206080275808967,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "id": "e73e861a3f6f344a8bfab697a299f873b9861577d9c90def9ad0616122cbe368",
    "memory_stats": {
        "limit": 33736589312,
        "max_usage": 442966016,
        "stats": {
            "active_anon": 395341824,
            "active_file": 5029888,
            "cache": 12341248,
            "dirty": 0,
            "hierarchical_memory_limit": 9223372036854771712,
            "hierarchical_memsw_limit": 9223372036854771712,
            "inactive_anon": 0,
            "inactive_file": 7311360,
            "mapped_file": 32768,
            "pgfault": 1760682,
            "pgmajfault": 0,
            "pgpgin": 943660,
            "pgpgout": 914646,
            "rss": 395341824,
            "rss_huge": 289406976,
            "total_active_anon": 395341824,
            "total_active_file": 5029888,
            "total_cache": 12341248,
            "total_dirty": 0,
            "total_inactive_anon": 0,
            "total_inactive_file": 7311360,
            "total_mapped_file": 32768,
            "total_pgfault": 1760682,
            "total_pgmajfault": 0,
            "total_pgpgin": 943660,
            "total_pgpgout": 914646,
            "total_rss": 395341824,
            "total_rss_huge": 289406976,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "usage": 407683072
    },
    "name": "/ranzk-aln-tcdvc7vm-69",
    "num_procs": 0,
    "pids_stats": {
        "current": 54
    },
    "precpu_stats": {
        "cpu_usage": {
            "percpu_usage": [
                23362033947,
                26326341153,
                24280114146,
                23008000213,
                22620712588,
                22901941995,
                23388162838,
                22380818030
            ],
            "total_usage": 188268124910,
            "usage_in_kernelmode": 82550000000,
            "usage_in_usermode": 93840000000
        },
        "online_cpus": 8,
        "system_cpu_usage": 5206072305808967,
        "throttling_data": {
            "periods": 0,
            "throttled_periods": 0,
            "throttled_time": 0
        }
    },
    "preread": "2022-11-03T06:48:39.588202741Z",
    "read": "2022-11-03T06:48:40.593896853Z",
    "storage_stats": {}
}
`

Docker version: 
 Docker version 20.10.9, build c2ea9bc

containerd: 1.6.9 

Host OS:
# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

**Comment by neersighted** [comment]
Can you still reproduce this on a more current version? e.g. 23.0.x or 24.0.x, and containerd 1.6.16+?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
