### ISSUE TITLE
Can not pull docker images on Ubuntu 20.04

### ISSUE THREAD

**Issue by heindrickdumdum0217** [docker/for-linux#1442]
When I run `docker pull` command, it shows retrying and finally fail with `unexpected EOF` error message.

```
Using default tag: latest
latest: Pulling from library/postgres
a603fa5e3b41: Retrying in 7 seconds 
02d7a77348fd: Downloading [==================================================>]  1.587MB/1.587MB
16b62ca80c8f: Waiting 
fbd795da1fe1: Waiting 
9c68de39d930: Waiting 
2e441a95082c: Waiting 
1c97f440fe14: Waiting 
87a3f78bc5d1: Waiting 
264b18cba666: Waiting 
bea1513c492d: Waiting 
ed48cace97fa: Waiting 
e3c377e275ff: Waiting 
86fa351e30cb: Waiting 
unexpected EOF
```

I tried with different images and different docker versions, but no luck.
https://docs.docker.com/engine/install/ubuntu/

```
# List the available versions:
apt-cache madison docker-ce | awk '{ print $3 }'

5:20.10.16~3-0~ubuntu-jammy
5:20.10.15~3-0~ubuntu-jammy
5:20.10.14~3-0~ubuntu-jammy
5:20.10.13~3-0~ubuntu-jammy
```

**Comment by thaJeztah** [comment]
Please provide more information as requested in the [issue-template](https://github.com/moby/moby/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`


The `EOF` message can be the result of either the daemon crashing, or other things, such as the host running out of memory or out of disk space.

Given that the information currently included in this ticket does not provide enough information to make it actionable, I'm closing this ticket, but feel free to continue the conversation.
