### ISSUE TITLE
/home/xxx/.docker/buildx/activity/default: permission denied

### ISSUE THREAD

**Issue by marcpawl-arista** [docker/for-linux#1451]
A file containing a timestamp keeps getting created with ownership as root.  Which prevents docker build to function.

~/.docker/buildx/activity$ sudo cat default
2023-03-22T01:17:40Z
~/.docker/buildx/activity$ ls -l
total 4
-rw------- 1 root root 20 Mar 21 18:17 default

'docker', 'build', '--platform=linux/x86_64', '--pull', '-t', 'yyy:zzz', '--build-arg', 'SUITE=focal', '/tmp/tmpqodzl15i'
ERROR: open /home/xxx/.docker/buildx/activity/default: permission denied

~/.docker/buildx/activity$ uname -a
Linux wwww 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~/.docker/buildx/activity$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 167
  Running: 2
  Paused: 0
  Stopped: 165
 Images: 17
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-135-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 188.7GiB
 Name: wwwww
 ID: 23d68622-dbd4-4561-b290-b3ab3891f6d9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://vvvv
 Live Restore Enabled: true

WARNING: No swap limit support

**Comment by marcpawl-arista** [comment]
Problem was caused by using the bionic version of the docker packages on focal.  Switching to the focal packages made the problem go away.

**Comment by DanijelDomazet** [comment]
> Problem was caused by using the bionic version of the docker packages on focal. 

How could that happen?
