### ISSUE TITLE
Unable to install Docker in CentOS 7.9 using Oracle Virtual Machine in mac Ventura 

### ISSUE THREAD

**Issue by subhankar-banerjee** [docker/for-linux#1452]
I> sudo yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine   ( This command worked fine  )
ii> sudo yum install -y yum-utils ( This command worked fine  )
iii> sudo yum-config-manager \
     --add-repo \
     https://download.docker.com/linux/centos/docker-ce.repo ( didn't work )
iv> sudo yum-config-manager --setopt="docker-ce-stable.baseurl=https://download.docker.com/linux/centos/7/x86_64/stable" --save ( ( This command worked fine  )
v> sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm ( This command worked fine  )
vi> sudo yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm ( didn't worked  )
vii> sudo yum install -y docker-ce docker-ce-cli containerd.io
viii> sudo systemctl enable docker
ix> sudo systemctl start docker
x> sudo docker run -it --name hello-world --rm hello-world

I am trying to install docker from the above steps but still I am unable to complete the installation due to multiple issues  ... this is the below error ---

[root@kube-master install-docker]# sudo yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Cannot open: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm. Skipping.
Error: Nothing to do
[root@kube-master install-docker]

need urgent help on this issue ...

**Comment by subhankar-banerjee** [comment]
can some one share some option urgently to proceed ....

**Comment by thaJeztah** [comment]
Instructions for installing on centos can be found here: https://docs.docker.com/engine/install/centos/


There should not be a need to references any of the packages directly (i.e. your step to directly reference https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm)

Make sure you're installing for the correct architecture though (if you're on an Apple M1 or M2, you're likely looking for the arm64 packages, not x86)

**Comment by subhankar-banerjee** [comment]
issue resolved we can close that request
