### ISSUE TITLE
Tensorflow 2.12.0 won't let pytorch 2.0.0 import, if it is imported first

### ISSUE THREAD

**Issue by RickSanchezStoic** [docker/for-linux#1455]
Code to reproduce the error:
```
docker run --rm -it ubuntu:22.04
// once inside
apt-get update && apt-get install python3
apt-get install pip
pip install tensorflow -y
pip install torch --extra-index-url https://download.pytorch.org/whl/cu118 -y
python3
import tensorflow
import torch
```
Note: the issue will persist even if you install torch-cpu, also on any Ubuntu:20.04 and above

**Comment by thaJeztah** [comment]
This looks to be an issue with installing packages inside a container, and not an issue with Docker itself.

Closing this in favor of https://github.com/tensorflow/tensorflow/issues/60389
