### ISSUE TITLE
no stable docker-ce releases available in the Fedora 38 repo

### ISSUE THREAD

**Issue by SingingBush** [docker/for-linux#1456]
Fedora 38 has been available for a while and now officially released but the stable builds for docker are not being made available to the Fedora 38 path on download.docker.com:

https://download.docker.com/linux/fedora/38/x86_64/stable/Packages/

releases are available in the older paths such as `/fedora/37/`, please can an existing version of docker-ce be made available to the new Fedora version.

**Comment by jorgeperezlara** [comment]
Is there any ETA for this?

**Comment by jorgeperezlara** [comment]
It seems it's now live.

**Comment by jmevel** [comment]
> It seems it's now live.

Yes, I confirm it's working now!

**Comment by cpuguy83** [comment]
Closing since this seems resolved.
