### ISSUE TITLE
Got At least one invalid signature was encountered when use apt after change root directory

### ISSUE THREAD

**Issue by dipras** [docker/for-linux#1459]
I want to change my docker directory on mounted drive by filled "data-root" in /etc/docker/daemon.json. When i do this, i always get this error. But when i not change the root directory, this error will not appear. I don't know why this error only happen when i change the root directory to mounted drive
![image](https://github.com/docker/for-linux/assets/51155424/b1b9971e-826a-486a-89fd-41fbf9f27679)

**Comment by thaJeztah** [comment]
I don't see immediately how those changes would affect this issue inside the container.

Could you post the output of `docker version` and `docker info`

**Comment by dipras** [comment]
I have found the problem, it turns out the problem is with the file system of my mounted drive
