### ISSUE TITLE
Docker apt Packages file size mismatch

### ISSUE THREAD

**Issue by frank-hopkin** [docker/for-linux#1475]
Trying to run apt-get update when the docker repository is installed in Debian Bullseye causes a failure.

Err:9 https://download.docker.com/linux/debian bullseye/stable amd64 Packages
  File has unexpected size (26476 != 27148). Mirror sync in progress? [IP: redacted]
  Hashes of expected file:
   - Filesize:27148 [weak]
   - SHA512:141bfc312c7840382e9e11095311d940b3e88de55fea12a7245e568a7106d844555bce27cccca847c928526fce0e7015272004ec3abb3a1a69f1025c468d7b36
   - SHA256:e436133f2f60aa51f0b15ab63677bb93bf8091316d7c2dba7d2f7abd4d7a9664
   - SHA1:1d18e3cc9fb721b7e3acff4e6d871e381f5dd313 [weak]
   - MD5Sum:2bf1fde7ef66d1712828981f788ac437 [weak]
  Release file created at: Thu, 24 Aug 2023 14:10:42 +0000

**Comment by mlcdf** [comment]
Debian 10 and 12 are also affected by this.

**Comment by mpounsett** [comment]
Same.  This appears to be have been a problem for about 24 hours now.

Judging by the google results, this seems to happen a lot.  Is there no monitoring in place to detect when the mirrors get a truncated file?

**Comment by nickgrajecki** [comment]
Same issue here

```Err:5 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 216.137.44.20 443]
  Hashes of expected file:
   - Filesize:12572 [weak]
   - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
   - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
   - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
   - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
  Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
Fetched 43.3 kB in 0s (107 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages.bz2  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 216.137.44.20 443]
   Hashes of expected file:
    - Filesize:12572 [weak]
    - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
    - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
    - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
    - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
   Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
```

**Comment by leandroramos** [comment]
Same issue here

**Comment by michael-zeitler** [comment]
Same Issue here as well

**Comment by likethecolor** [comment]
Having a similar issue trying to run `sh get-docker.sh` through gitlab's ci/cd pipeline. Was fine yesterday, Aug 24, 2023 @ 16:23 CDT. I came in this morning and reran that same job and this error started to appear (no changes to the deployment scripts).
```
$ curl -fsSL https://get.docker.com/ -o get-docker.sh
$ sh get-docker.sh --dry-run

<snip>

$ sh get-docker.sh
# Executing docker install script, commit: c2de0811708b6d9015ed1a2c80f02c9b70c8ce7b
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: Failed to fetch https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages.bz2  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 3.163.24.100 443]
   Hashes of expected file:
    - Filesize:12572 [weak]
    - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
    - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
    - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
    - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
   Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by isuftin** [comment]
Possibly related. RHEL 8 here. Seeing intermittent..

Failed to download metadata for repo 'docker-ce-stable': Yum repo downloading error: Downloading error(s): repodata/ed67480d9d2325c2bde62bf77f5111a8845162f50d91521e5d0b2985e1539f71-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/b1627cb5314e821c4f725e02661ece5b90e6e59ba01ef8d26c3f47f21b9dffd4-filelists.xml.gz - Cannot download, all mirrors were already tried without success

**Comment by frank-hopkin** [comment]
Succeeded just now

**Comment by bartlaarhoven** [comment]
I had the same issue on Debian 12, seems to be resolved now.

**Comment by lythandas** [comment]
It's ok as well on Buster

**Comment by likethecolor** [comment]
woo-hoo!  It's working now (orig comment above: https://github.com/docker/for-linux/issues/1475#issuecomment-1693448232)

**Comment by isuftin** [comment]
Seems to be working again on RHEL 8
