### ISSUE TITLE
/etc/init.d/docker: 62: ulimit: error setting limit (Invalid argument) Problem

### ISSUE THREAD

**Issue by RoyalAmrah** [docker/for-linux#1480]
When Dind is installed with the sh file obtained from https://get.docker.com, an error message as follows is received when starting docker:
/etc/init.d/docker:62: ulimit: limit setting error (Invalid argument)
This is because line 62 of the /etc/init.d/docker file says **ulimit -Hn 524288**.
This line should be saved by deleting the -H argument and changing it to **ulimit -n 524288**. After this docker can now be run.
Container where the error was received: _Debian GNU/Linux 11 (bullseye)_
This error started to be received approximately as of Friday, January 19, 21:00:00UTC 2024.

**Comment by thaJeztah** [comment]
looks like the same issue as https://github.com/docker/cli/issues/4807. Let me close this one in favour of the other, which has more details
