### ISSUE TITLE
This looks like a runc bug.

### ISSUE THREAD

**Issue by Jackson368755** [docker/for-linux#1486]
This looks like a runc bug.

As an example (using ctr for simplicity to mount a filesystem):

```bash
$ mkdir -p /tmp/test/rootfs
$ sudo ctr image mount docker.io/library/busybox:latetst /tmp/test/rootfs
$ sudo runc spec --bundle /tmp/test # creates a default runc spec
$ sudo mv /tmp/test/config.json /tmp/test/config.json.orig
$ sudo jq '.process += { "args": ["stat", "-c", "%a", "/tmp/test"]} | .mounts += [{ "destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"] }]' /tmp/test/config.json.orig > /tmp/test/config.json
$ sudo runc run --bundle /tmp/test
444
$ sudo runc run --bundle /tmp/test
755
```

* Note: to properly clean this up run: `sudo ctr image unmount /tmp/test/rootfs && sudo ctr snapshot rm /tmp/test/rootfs`

This means it can actually be reproduced by pre-creating the destination dir for the tmpfs.

_Originally posted by @cpuguy83 in https://github.com/docker/for-linux/issues/138#issuecomment-1603045301_

**Comment by cpuguy83** [comment]
Please keep discussion in the original issue.
