### ISSUE TITLE
AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by kanishkamehta801** [docker/for-linux#1490]
In Centos Machine, while starting webui inside docker, I am getting below issue.

Issue : [Wed Feb 21 08:36:40.336002 2024] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
docker version : Client: Docker Engine - Community
Version: 25.0.3
API version: 1.44
Go version: go1.21.6
Git commit: 4debf41
Built: Tue Feb 6 21:17:10 2024
OS/Arch: linux/amd64
Context: default

Server: Docker Engine - Community
Engine:
Version: 25.0.3
API version: 1.44 (minimum version 1.24)
Go version: go1.21.6
Git commit: f417435
Built: Tue Feb 6 21:16:08 2024
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.6.28
GitCommit: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
runc:
Version: 1.1.12
GitCommit: v1.1.12-0-g51d5e94
docker-init:
Version: 0.19.0
GitCommit: de40ad0

my docker container keeps on restarting again and again and is not coming up

CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS                         PORTS                                                 NAMES
a87d539c0f53   front_end:v1           "httpd-foreground"       2 hours ago    Restarting (1) 7 seconds ago                                                         gnb_web_ui_service-frontend_1
5d6129679be2   back_end:v1            "docker-entrypoint.s…"   2 hours ago    Up 2 hours                     0.0.0.0:3000->3000/tcp, :::3000->3000/tcp             gnb_web_ui_service-backend_1
aeb872d19a8e   keycloak_service_ran   "/opt/jboss/tools/do…"   2 hours ago    Up 2 hours                     8443/tcp, 0.0.0.0:9897->8080/tcp, :::9897->8080/tcp   keycloak_service-keycloak_1

**Comment by cpuguy83** [comment]
Doing some google searches, it looks like you need to upgrade your kernel version or downgrade apache (httpd).

Closing as this is not related to docker AFAICT.
