### ISSUE TITLE
Please Provide a repo for FEDORA 40

### ISSUE THREAD

**Issue by hhlp** [docker/for-linux#1491]
[]  This is a bug report
[x]This is a feature request
[x] I searched existing issues before opening this one

The Docker-CE Fedora repository is the recommended way to install it. It has many benefits over installing from a package or any other method.

Fedora also releases a new version every six months. The Fedora repository also takes a very long time to become ready after the release of a new version, with many issues being opened after each recent Fedora is released.

Fedora has officially branched Version 40 might have a beta release on — 2024-03-19 and the Final Version Will be ready
 2024-04-23	 — Final release target date 1

I'm filing this issue to hopefully put this task on the radar so that there might be a repository set up in time for the Fedora 40 release cycle...

NOTE

Some of us migrate when the beta version when is ready so we have to disable the repository and wait for it to be ready

Release Schedule: https://fedorapeople.org/groups/schedule/f-40/f-40-key-tasks.html

Regards.,

**Comment by AkihiroSuda** [comment]
Added here:
- https://github.com/docker/docker-ce-packaging/pull/992

**Comment by thaJeztah** [comment]
closing, as packages for fedora 40 should be available now; https://download.docker.com/linux/fedora/40/
