### ISSUE TITLE
When stopping a 'Restarting' container invoked with --restart it's stopped but restarted again upon docker engine restart

### ISSUE THREAD

**Issue by alonho** [docker/for-linux#15]
### Expected behavior
When running a container with --restart=unless-stopped, it shouldn't be restarted when docker engine restarts if it was explicitly stopped by the user (docker stop).

### Information
CentOS Linux release 7.3.1611 (Core)
Docker version 17.04.0-ce, build 4845c56

### Steps to reproduce the behavior
docker run --restart=unless-stopped centos sleep 1
\# wait for the container to be 'Restarting'
docker stop `docker ps -q`
service docker restart
docker ps # shows the container has restarted

**Comment by thaJeztah** [comment]
let me close this one in favor of https://github.com/moby/moby/issues/34028
