### ISSUE TITLE
No repository packages for Ubuntu 17.10

### ISSUE THREAD

**Issue by beruic** [docker/for-linux#160]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

I have just added the docker repositories to my Ubuntu 17.10 box, but cannot install `docker-ce`, because https://download.docker.com/linux/ubuntu/dists/artful/pool/stable/amd64/ contains no files.

**Comment by seemethere** [comment]
Duplicate: https://github.com/docker/for-linux/issues/141
