### ISSUE TITLE
Running shellscript in a dockerfile

### ISSUE THREAD

**Issue by K7king** [docker/for-linux#161]
My requirement is to get into the docker container /opt folder  and run a shellscript file.
I am able to move to that folder but didn't find any command in  docker to execute a shell script..
Could you please assist me to run a shellscript in a dockerfile

**Comment by cpuguy83** [comment]
@K7king 
```
COPY my_script.sg /tmp/
RUN cd /opt && /tmp/my_script.sh
```

**Comment by cpuguy83** [comment]
Closing since this isn't really an issue.
For community support, please use the [Docker Community Slack](https://community.docker.com/registrations/groups/4316)

Thanks 🙇
