### ISSUE TITLE
Please provide repo for docker-ce on Fedora 27

### ISSUE THREAD

**Issue by blitzd** [docker/for-linux#164]
Same issue as here https://github.com/docker/for-linux/issues/35

Fedora 27 is now released. Anyone upgrading to it with a working yum repo for Fedora 26/Docker will run into:

```
Failed to synchronize cache for repo 'docker-ce-stable', disabling.
Failed to synchronize cache for repo 'docker-ce-edge', disabling.
```

**Comment by seemethere** [comment]
Packaging code has already been submitted here: https://github.com/docker/docker-ce-packaging/pull/59

The next eligible release of Docker CE for Fedora 27 will be `17.12.0-ce`.

Not entirely sure why you would be having repository issues though after the upgrade.

**Comment by blitzd** [comment]
@seemethere the repositories for 27 don't yet exist here:

https://download.docker.com/linux/fedora/$releasever

And so it gives the `Failed` message. To my knowledge the installed version _is_ still working though.

**Comment by seemethere** [comment]
The repositories will not be available until the release of `17.12.0-ce` in December.

Until then the Fedora 26 repositories should work.

**Comment by blitzd** [comment]
Anyone who goes through the standard setup for the repositories will end up with a docker-ce.repo like so:

```
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/fedora/gpg
```

Both the release version and the basearch are dynamic (as they should be), and now point to non-existent 27.

**Comment by seemethere** [comment]
@blitzd This is going to be an issue until we GA `17.12.0-ce`.

Sorry for any inconvenience this may cause, I have a temporary fix going into `get.docker.com` right now to remedy this in the mean time: https://github.com/docker/docker-install/pull/48/commits/bd9d4282521d72f33f5f97fd45668470dc99d21f

**Comment by ogajduse** [comment]
@seemethere  I can't find any "Release schedule" page for Docker CE. Could you please point me to it?

**Comment by jmcfarlane** [comment]
For such a popular project I'm surprised to see Docker handles things like this (related: #143).

**Comment by caiges** [comment]
It took quite a long time after the last Fedora release too. :( Why isn't this automated?

**Comment by arjenpdevries** [comment]
A better workaround: 

    sudo mkdir -p /etc/dnf/vars
    sudo echo 26 > /etc/dnf/vars/docker_releasever
    sudo sed -i 's/\$releasever/$docker_releasever/g' /etc/yum.repos.d/docker-ce.repo

You can then later edit `/etc/dnf/vars/docker_releasever` to point to 27.

**Comment by allanlewis** [comment]
Thanks, @arjenpdevries! Although the second line will fail for permissions, I suggest using `tee`:
```
echo 26 | sudo tee /etc/dnf/vars/docker_releasever
```

**Comment by seemethere** [comment]
Closed with the release of `17.12.0-ce`: https://download.docker.com/linux/fedora/27/x86_64/

**Comment by arjenpdevries** [comment]
Awesome!
Just updated the `docker_releasever` file to contain 27 and `dnf update` installed the new release.

Thank you for the notification @seemethere .

```
$ echo 27 | sudo tee /etc/dnf/vars/docker_releasever
$ sudo dnf update
Docker CE Stable - x86_64                                                                                            47 kB/s | 3.4 kB     00:00    
Dependencies resolved.
====================================================================================================================================================
 Package                         Arch                         Version                                  Repository                              Size
====================================================================================================================================================
Upgrading:
 docker-ce                       x86_64                       17.12.0.ce-1.fc27                        docker-ce-stable                        31 M

Transaction Summary
====================================================================================================================================================
Upgrade  1 Package

Total download size: 31 M
Is this ok [y/N]: y
Downloading Packages:
docker-ce-17.12.0.ce-1.fc27.x86_64.rpm                                                                               11 MB/s |  31 MB     00:02    
----------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                11 MB/s |  31 MB     00:02     

[...]

Running as unit: run-rc1ed7c642a654e92acae910d4a6ee60a.service
  Verifying        : docker-ce-17.12.0.ce-1.fc27.x86_64                                                                                         1/2 
  Verifying        : docker-ce-17.12.0.ce-1.fc26.x86_64                                                                                         2/2 

Upgraded:
  docker-ce.x86_64 17.12.0.ce-1.fc27                                                                                                                

Complete!
```

**Comment by mgalgs** [comment]
Or if you don't want to have to update the `docker_releasever` file after every future Fedora upgrade:

```
$ sudo rm -v /etc/dnf/vars/docker_releasever
$ sudo sed -i 's/\$docker_releasever/$releasever/g' /etc/yum.repos.d/docker-ce.repo
```

**Comment by arjenpdevries** [comment]
True - though the release cycles seem independent and the issue likely to recur.
