### ISSUE TITLE
On debian sretch apt-get update produces 404 error on docker repositories

### ISSUE THREAD

**Issue by MikHulk** [docker/for-linux#167]
Hi,

* [x] This is a bug report
* [ ] This is a feature request
* [X] I searched existing issues before opening this one

The the installation process as described in the documentation here: https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-repository . Fails on some index files.

**Output of `docker version`:** not yet installed
**OS**: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64
```
$ LANG=C sudo apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.fr.debian.org/debian stretch InRelease
Hit:3 http://ftp.fr.debian.org/debian stretch-updates InRelease               
Hit:4 http://ftp.fr.debian.org/debian stretch Release                         
Ign:5 https://download.docker.com/linux stretch InRelease
Ign:6 https://download.docker.com/linux stretch Release
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Ign:8 https://download.docker.com/linux stretch/stable amd64 Packages
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Ign:8 https://download.docker.com/linux stretch/stable amd64 Packages
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Ign:8 https://download.docker.com/linux stretch/stable amd64 Packages
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Ign:8 https://download.docker.com/linux stretch/stable amd64 Packages
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Ign:8 https://download.docker.com/linux stretch/stable amd64 Packages
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Ign:7 https://download.docker.com/linux stretch/stable all Packages
Err:8 https://download.docker.com/linux stretch/stable amd64 Packages
  404  Not Found
Ign:10 https://download.docker.com/linux stretch/stable Translation-fr
Ign:11 https://download.docker.com/linux stretch/stable Translation-en
Reading package lists... Done
W: The repository 'https://download.docker.com/linux stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://download.docker.com/linux/dists/stretch/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MikHulk** [comment]
```apt-get install docker-ce```
fails too

**Comment by MikHulk** [comment]
Sorry, I made an error when I add the repository

**Comment by Sehran-S-Shigan** [comment]
root@sehran-s-shigan  ~  apt-get update            ✔  ⚡  1504  13:10:31
Hit:1 http://deb.i2p2.no unstable InRelease                                    
Hit:2 http://linux.teamviewer.com/deb stable InRelease                         
Hit:3 http://packages.microsoft.com/repos/vscode stable InRelease              
Hit:4 https://packages.microsoft.com/debian/9/prod stretch InRelease           
Hit:5 https://repo.skype.com/deb stable InRelease                              
Ign:6 https://download.docker.com/linux/debian kali-rolling InRelease          
Hit:7 https://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
Err:8 https://download.docker.com/linux/debian kali-rolling Release
  404  Not Found [IP: 13.35.189.96 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Sehran-S-Shigan** [comment]
my problem

**Comment by davidvandebunte** [comment]
This issue can occur if you follow these instructions:
https://docs.docker.com/engine/install/debian/

Rather than these:
https://docs.docker.com/engine/install/ubuntu/

**Comment by MikHulk** [comment]
Hi I am not sure your issue is related to this one. I opened it in 2017  and closed it a few time later. It was an error on my repo on my side.
