### ISSUE TITLE
Please provide repo for docker-ce on Fedora 27

### ISSUE THREAD

**Issue by ksylvan** [docker/for-linux#173]
This is the same issue that was not ever completely addressed for https://github.com/docker/for-linux/issues/35

Who do we need to bug to make this a consistent part of the Fedora release process?

In a nutshell, the installation files for Fedora 27 are missing at https://download.docker.com/linux/fedora/

**Comment by thaJeztah** [comment]
duplicate of https://github.com/docker/for-linux/issues/164
