### ISSUE TITLE
get.docker.com seems to install unstable 17.11

### ISSUE THREAD

**Issue by konradjurk** [docker/for-linux#175]
As you can see in [this file](https://github.com/hashicorp/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/provisioners/docker/cap/redhat/docker_install.rb), Vagrant uses get.docker.com which is advertised to install the latest stable docker release, which [seems to be](https://docs.docker.com/release-notes/docker-ce/) 17.09. However, 17.11 [seems to be shipped](https://stackoverflow.com/questions/47425475/docker-fails-with-error-inside-debian-vagrant-box?noredirect=1#comment82047368_47425475).

Is this expected?

**Comment by thaJeztah** [comment]
get.docker.com always installs the latest "edge" docker version, not stable; it looks like the [documentation is incorrect on this though](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-convenience-script);

> This example uses the script at get.docker.com to install the latest stable release of Docker CE on Linux. To install the latest testing version, use test.docker.com instead. In each of the commands below, replace each occurrence of get with test.

I'll open a pull request to address that

Note that for production, it's not recommended to use that script, but to use the manual procedure, and [pin docker to a specific version](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1)

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker.github.io/pull/5430 to fix the description in the documentation
