### ISSUE TITLE
Docker for Centos (CE) - Store Link is outdated

### ISSUE THREAD

**Issue by kristiehoward** [docker/for-linux#18]
### Expected behavior
https://docs.docker.com/engine/installation/linux/centos/ has an outdated link that should be:
Go to https://store.docker.com/my-content

### Actual behavior
Go to https://store.docker.com/?overlay=subscriptions.

![image](https://user-images.githubusercontent.com/7132362/27196246-8c04f2ba-51be-11e7-9f3b-50c10e64b1d5.png)

### Information
N/A

### Steps to reproduce the behavior
Go to https://docs.docker.com/engine/installation/linux/centos/

**Comment by thaJeztah** [comment]
I opened a pull request to fix the links; https://github.com/docker/docker.github.io/pull/3775

p.s., best to report issues with the documentation on https://github.com/docker/docker.github.io/issues
