### ISSUE TITLE
missing docker-ce package in buster release on debian repository [stretch has]

### ISSUE THREAD

**Issue by samueloph** [docker/for-linux#184]
* [x] This is a bug report
* [x] I searched existing issues before opening this one

### Expected behavior
Install docker-ce using the
`deb [arch=amd64] https://download.docker.com/linux/debian buster stable`
repository, as its the repository that i end up with when following https://docs.docker.com/engine/installation/linux/docker-ce/debian/

### Actual behavior
The docker-ce package is only present on the stretch release, although there's a buster release on the repository, there's no docker-ce package in there.

### Steps to reproduce the behavior

Follow the https://docs.docker.com/engine/installation/linux/docker-ce/debian/ guide using Debian Buster.

**Comment by seemethere** [comment]
Should be resolved now with the release of `17.12.0-ce`: https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/

**Comment by samueloph** [comment]
thanks!
