### ISSUE TITLE
dockerd doesn't do a proper getgrent lookup for setting group ownership on /var/run/docker.sock, thus failing with non-local group databases

### ISSUE THREAD

**Issue by jfschneider** [docker/for-linux#186]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
using "--group docker" should set group permissions on /var/run/docker.sock correctly when using non-file user and group dbs on linux (like LDAP)

### Actual behavior
when having a docker group in LDAP (and not in local /etc/group), dockerd does not set the socket group permission to "docker" but to "root"

### Steps to reproduce the behavior
1. central group db like e.g. LDAP with a docker group configured:
   "getent group docker"  produces "docker:*:1515:[REDACTED]"
2. install docker-ce rpm. rpm scriptlet correctly checks for existing docker group and does not create local group entry
3. run docker with "dockerd --group docker" results in: 
 WARN[2017-12-18T10:45:26.803102016+01:00] could not change group /var/run/docker.sock to  docker: group docker not found   
and
 ls -l /var/run/docker.sock
 srw-rw----. 1 root root 0 Dec 18 10:46 /var/run/docker.sock

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: agent01.local
ID: DKLQ:TEP2:4FXL:7I2E:CI75:X4E6:DCVM:KIVN:AT5W:J7SP:DCZM:UJDP
Docker Root Dir: /web/data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
centos7 in vagrant with virtualbox

The problem is in https://github.com/docker/docker-ce/blob/7f2221039ec497be56f63d85bae24327b2df99a6/components/engine/daemon/listeners/listeners_unix.go#L36 
lookupGid() is a function in the "listeners" package that seems to parse /etc/group directly instead of using getent calls like one usually would do (https://github.com/docker/docker-ce/blob/1ebf5edb0d6211a8bd0a326f56405c8e7eb70e5b/components/engine/daemon/listeners/group_unix.go#L15)
There is  actually a function idtools.LookupGid that seems to do both, first parsing /etc/group, then calling getent group. (Weirdly enough, it seems does that by execcmd() the system's getent command. I am not familiar with "go", doesn't it have an interface to libc's getgrent(3)??)

**Comment by jeffwji** [comment]
I'm having the same issue!

**Comment by davepow** [comment]
I'm having the same problem using NIS groups on CentOS 7. 

CentOS Linux release 7.4.1708 (Core)
3.10.0-693.11.1.el7.x86_64  
docker-ce-17.12.0.ce-1.el7.centos.x86_64

**Comment by Gestahlt** [comment]
Same here! I had to do a workaround with chown in systemd.. its ugly. Please use getent.

**Comment by nicoulaj** [comment]
Same here.

If this can help, a workaround on systemd based distros, in `/etc/systemd/system/docker.service.d/override.conf`:
```
[Service]
ExecStartPost=/usr/bin/chgrp docker /var/run/docker.sock
```

**Comment by mjameswh** [comment]
Same problem here (Fedora 29, with FreeIPA).

It seems that GoLang indeed has a built-in equivalent for `getgrent`, named `lookupGroup`. It has a _cgo_ variant (https://github.com/golang/go/blob/master/src/os/user/cgo_lookup_unix.go) which properly use the libc call. It also has a _nocgo_ variant, which simply parse the `/etc/group` file (and therefore would not integrate with nis/ldap/external user management systems).

Now, I only have very basic knowledge of Go, but it seems to me that at least some subcomponents of `dockerd` are built with `cgo` enabled, so it should be pretty easy to modify https://github.com/docker/docker-ce/blob/1ebf5edb0d6211a8bd0a326f56405c8e7eb70e5b/components/engine/daemon/listeners/group_unix.go#L15 to use GoLang's `os.user. lookupGroup`, and this should indeed allow proper handling of externally managed groups.

I will try to venture for fixing this myself, but since I am not familiar with GoLang and Docker's build process and have very little time at present, it will probably takes a few days before I can submit a pull request.

**Comment by thaJeztah** [comment]
I think this should be fixed by https://github.com/moby/moby/pull/38126 (which is in current versions of docker)
