### ISSUE TITLE
unable to prepare context .. lstat error .. permission denied

### ISSUE THREAD

**Issue by iAnanich** [docker/for-linux#194]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Utility builds an image as described in `Dockerfile` when I execute `sudo docker build .`

### Actual behavior
It throws an error:
```
unable to prepare context: unable to evaluate symlinks in context path: lstat /home/REDACTED: permission denied
```

Here `REDACTED` replaces path to the directory where I execute this command.

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   a04f55b
 Built:        Thu Sep 21 20:36:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   a04f55b
 Built:        Thu Sep 21 20:36:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-21-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.665GiB
Name: ilya-Vostro-15-3568
ID: JY44:SZBP:NXMO:4J2N:PGXJ:M6MK:OZIX:SDB4:6RZZ:UAL5:GFQU:RVUF
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 25
 System Time: 2018-01-08T00:50:38.400404506+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Directory with `Dockerfile` is on separate partition from `/` and `/home` mounted partitions, but it has all needed permissions to read/write/execute, also it is mounted under my user's home directory.

**Comment by iAnanich** [comment]
I'm sorry, I just realized that I have installed Docker from default app for package installation, and it was a version for snappy. For version installed by following steps in the documentation, it works well.

**Comment by thaJeztah** [comment]
Thanks for the update; let me close this one

**Comment by Kishaihd** [comment]
I'm having this exact same problem, except I installed Docker by following the standard documentation.
I'm on Centos 7. Should I open a new issue or can this be re-opened?

**Comment by avidale** [comment]
Have the same issue. Any ideas?
