### ISSUE TITLE
Docker set up on Red Hat Enterprise Linux Server 7.4 WARNING: overlay 

### ISSUE THREAD

**Issue by greetyv** [docker/for-linux#196]
I have installed docker ce on Red Hat Enterprise Linux Server 7.4. when i check for Docker info, it gives warning as below: WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior. Reformat the filesystem with ftype=1 to enable d_type support. Running without d_type support will not be supported in future releases.Trying to reformat the file system with 'ftype=1'. But looks like docker is pointing to the root file system and not able to umount that.How do i fix this issue? How to change the docker file system to point to one which has ftype=1?

 'docker info'
 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.5GiB
Name: fe0vmhipprd01
ID: A7IH:MOYN:W7DA:JPVA:GZNY:QG2H:SJMW:SMXS:SGYS:MGXD:7KNF:DCCR
Docker Root Dir: /net/FE0VMHIPPRD01/fs0/docker-lib
Debug Mode (client): false
Debug Mode (server): false
Https Proxy: nam:pswd@<ip>:<port>/
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

**Comment by dnephin** [comment]
```
dockerd --data-root=...
```

**Comment by thaJeztah** [comment]
closing, because this doesn’t look like a bug, and there’s an answer provided, but feel free to continue the conversation
