### ISSUE TITLE
`docker-ce` package conflicts with `docker` package, makes kubernetes installation impossible

### ISSUE THREAD

**Issue by ian4hu** [docker/for-linux#199]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

OS: Fedora 27
Docker: docker-ce 17.12 (by docker-ce.repo with `dnf install docker-ce`)
Use `dnf install kubernetes`

### Expected behavior
Installation success

### Actual behavior
met a package conflict
```shell
[ian@thinkpad ~]$ sudo LANG=en_US.UTF-8 dnf install kubernetes
Last metadata expiration check: 6:17:44 ago on Sun 14 Jan 2018 04:02:48 AM CST.
Error: 
 Problem: package kubernetes-node-1.7.3-1.fc27.x86_64 requires docker, but none of the providers can be installed
  - package docker-ce-17.12.0.ce-1.fc27.x86_64 conflicts with docker provided by docker-2:1.13.1-42.git4402c09.fc27.x86_64
  - package docker-ce-17.12.0.ce-1.fc27.x86_64 conflicts with docker provided by docker-2:1.13.1-26.gitb5e3294.fc27.x86_64
  - problem with installed package docker-ce-17.12.0.ce-1.fc27.x86_64
  - package kubernetes-1.7.3-1.fc27.x86_64 requires kubernetes-node = 1.7.3-1.fc27, but none of the providers can be installed
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)

```

### Steps to reproduce the behavior
after install docker-ce, execute `dnf install kubernetes`

**Output of `docker version`:**

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:12:17 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:14:50 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.8-300.fc27.x86_64
Operating System: Fedora 27 (Server Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.74GiB
Name: thinkpad.local
ID: xxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://xxxxx/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

The kubernetes-node requires a dependency named `docker`, but the `docker` is only provided by the `docker` package in fedora official repo. And if I install with `--allowerasing`, the `docker-ce` will be removed and `docker@fedora` will be installed, but I want to keep the docker-ce.

Can we configure the docker-ce package to provide the dependency name docker? And if we can, Will the Kubernetes use the docker-ce and can be successfully installed?

I have submit a [stackoverflow question](https://stackoverflow.com/questions/48239857/kubernetes-installation-on-fedora-meets-a-package-conflict) to get help, solution in this issue could share to it.

**Comment by seemethere** [comment]
The maintainer of the `kubernetes` package should use Boolean dependencies so that their package can rely on either `docker-ce` or `docker`. Source: http://rpm.org/user_doc/boolean_dependencies.html

The `docker` package does directly conflict with the `docker-ce` package, so removing it as a `Conflicts` isn't really the best decision from the viewpoint of both the `docker-ce` package and `docker` package.

RPM from rpmfind for information:
https://www.rpmfind.net/linux/RPM/opensuse/updates/leap/42.2/oss/x86_64/kubernetes-node-1.3.10-3.1.x86_64.html

**Comment by seemethere** [comment]
ping @ingvagabund

**Comment by ingvagabund** [comment]
Hi @seemethere, @ian4hu,

the official Fedora packaging guildelines [1] says the Boolean dependencies `MAY` be used. Though, imho it is still experimental and the impact is still not fully understood [2]. I would recommend to build an "empty" docker rpm (e.g. with 0.0.0 version) and install it together with the ``docker-ce`` if that is possible. I don't want to introduce the boolean dependencies unless I can be sure it will not break the installation and update paths.

[1] https://fedoraproject.org/wiki/Packaging:Guidelines#Rich.2FBoolean_dependencies
[2] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/GDV5ICJGYN2Y3VRPIKRBELQXUBTUQRZP/

**Comment by ingvagabund** [comment]
After some chatting on freenode looks like it's ok to use it. Let me give it a try.

**Comment by ingvagabund** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1534508

**Comment by ignatenkobrain** [comment]
Rich deps exist for many years and are supported in DNF for long time. It was just infra which didn't support it. For more than few months it is fully supported.

**Comment by ingvagabund** [comment]
Testing locally:
```bash
# rpm -qa | grep docker
docker-ce-18.01.0.ce-1.fc27.x86_64
```

```bash
# dnf install kubernetes-client-1.9.1-2.fc28.x86_64.rpm  kubernetes-node-1.9.1-2.fc28.x86_64.rpm
Last metadata expiration check: 0:05:50 ago on Mon 15 Jan 2018 02:21:53 PM UTC.
Dependencies resolved.
=============================================================================================================
 Package                           Arch              Version                   Repository               Size
=============================================================================================================
Installing:
 kubernetes-client                 x86_64            1.9.1-2.fc28              @commandline             23 M
 kubernetes-node                   x86_64            1.9.1-2.fc28              @commandline             23 M
Installing dependencies:
 conntrack-tools                   x86_64            1.4.4-5.fc27              fedora                  201 k
 libnetfilter_cthelper             x86_64            1.0.0-12.fc27             fedora                   22 k
 libnetfilter_cttimeout            x86_64            1.0.0-10.fc27             fedora                   22 k
 libnetfilter_queue                x86_64            1.0.2-10.fc27             fedora                   28 k
 socat                             x86_64            1.7.3.2-4.fc27            fedora                  296 k

Transaction Summary
=============================================================================================================
Install  7 Packages

Total size: 46 M
Total download size: 569 k
Installed size: 286 M
Is this ok [y/N]: 
```

After typing `y`, successfully installed.

**Comment by ingvagabund** [comment]
F28 (rawhide) build: https://koji.fedoraproject.org/koji/taskinfo?taskID=24215295

**Comment by ingvagabund** [comment]
F27 under construction: https://koji.fedoraproject.org/koji/taskinfo?taskID=24216030

**Comment by ingvagabund** [comment]
F27 update for testing https://bodhi.fedoraproject.org/updates/kubernetes-1.9.1-2.fc27

**Comment by seemethere** [comment]
Thanks @ingvagabund!

**Comment by seemethere** [comment]
@ingvagabund is there an ETA on when the packages with the updated specs will go live?
