### ISSUE TITLE
docker update does not change cpu quota and/or cpu-period of a running container

### ISSUE THREAD

**Issue by fmarchand** [docker/for-linux#201]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
I have a container running : 
```
docker run -it -m 100m --cpu-quota 10000 --cpu-period 100000  -e "JAVA_OPTS=-Xms48m -Xmx48m" agaetis.azurecr.io/config
```
So I set the cpu quota low on purpose and I've put 100000 for the cpu period in order to change it after ...

If I run this command (f8698855d471 : the container id I ran just before) 
```
docker update --cpu-period 100000 --cpu-quota 800000 f8698855d471
```
I expect the container to use all my cpu's (8) and to run a lot faster 

### Actual behavior
Nothing changed. My service which is a spring boot service is still booting. Without any cpu quota it should take less than 15s. So my conclusion is : the command docker update has no effects on cpu quota of my container.

### Steps to reproduce the behavior
```docker run --name test42 --cpu-quota 10000 --cpu-period 100000 --rm ashael/pi 10000```

then in another console : 
```docker update --cpu-quota 800000 test42```

**Output of `docker version`:**

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:47 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 412
 Running: 1
 Paused: 0
 Stopped: 411
Images: 166
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 990
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-25-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name: fmarchand-ThinkPad-P50
ID: MGZH:OR7W:BU4T:NGEV:AJXQ:2OAB:YQPY:L4TM:VVBF:MTTH:X3IV:RBID
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: fmarchand
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 registry.marathon.l4lb.thisdcos.directory:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
You can look at the setting for the cgroup in the container.
`docker exec <container> cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us`

You should see this value change as you change the value through docker.
Also note that there is a nice shorthand for tweaking these values, you can use `--cpus` which takes a decimal value... e.g. `.25` to give it 1/4 of a CPU, or `4` to give it 4 CPU's...  this really just tweaks the quota value (on Linux).

**Comment by cpuguy83** [comment]
Setting `--cpus` seems to work just fine in update, however `--cpu-quota` does appear broken.

**Comment by cpuguy83** [comment]
@fmarchand It's a bug. See moby/moby#36030

**Comment by fmarchand** [comment]
Oki I was still thinking I missed something. I didn't expect to find a bug in docker. Thanks for your quick answer !

**Comment by cpuguy83** [comment]
If you can, I'd suggest using the "--cpus" flag instead. It uses the same exact underlying functionality, but does all the calculations for you.
