### ISSUE TITLE
Files created in a Docker container running as root with a mapped volume show up on my File System as owned by root

### ISSUE THREAD

**Issue by jamesemwallis** [docker/for-linux#207]
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

**Not sure if this is a bug or a feature. As you have to run Docker as `sudo` then it might fit better under a feature request allowing the passing in of the current user (UID?) to ensure that the files are created as me not as root**

### Expected behavior
Files to show on my file system as owned by me.
```
drwxr--xr-x   8  jameswallis            jameswallis              4096  Jan  24  15:40  Swifty
-rw-r--r--    1  jameswallis            jameswallis              0     Jan  24  11:34  file.txt
```

### Actual behavior
Files are owned by the UID which is in use in the Docker container.
```
drwxr--xr-x   8  root            root              4096  Jan  24  15:40  Swifty
-rw-r--r--    1  root            root              0     Jan  24  11:34  file.txt
```

### Steps to reproduce the behavior

* Run a Docker container with a mapped volume.
* Exec into the container, create file in the mapped volume.
* Exit the container and check who owns the created file in your file system (Not in the container).

**Output of `docker version`:**
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 159
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-28-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.789GiB
Name: jameswallis-VirtualBox
ID: H37W:5KHF:M30L:7DY0:3EUI:DHXH:VRUS:YJCY:K6RE:ZF0I:CTQD:C7Q4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Running in VirtualBox on a MacOS. Also seen in VirtualBox running on Windows 7.

**Comment by cpuguy83** [comment]
Files are created as whatever the UID/GID was of the person/process that created it *in the container*.
You can specify the user to use when running and execing into the container.
