### ISSUE TITLE
Docs to be updated for container-selinux

### ISSUE THREAD

**Issue by annieshin** [docker/for-linux#21]
While trying to docker ce for centos...

Error: Package: docker-ce-17.06.0.ce-0.3.rc3.el7.centos.x86_64 (docker-ce-test)
           Requires: container-selinux >= 2.9
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

and 

[docker@swarm-test-centos7001-E2E-F5E74A-linux-0 ~]$ sudo yum install container-selinux
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package container-selinux available.
Error: Nothing to do

<img width="849" alt="screen shot 2017-06-15 at 11 59 01 am" src="https://user-images.githubusercontent.com/4061739/27197170-1b3ac060-51c2-11e7-939d-51b8ebf06e8d.png">

**Comment by cpuguy83** [comment]
`container-selinux` is in the extras repo, do you have it enabled?

**Comment by briantd** [comment]
@cpuguy83 

Fyi, I just ran into this too.  I spun up 2 new RHEL 7.3 instances on AWS using the marketplace AMI, then tried to install docker and got that error.  This is new, as I've done that same setup several times over the past month without incident.

<img width="1009" alt="screenshot of safari 6-23-17 12-24-38 pm" src="https://user-images.githubusercontent.com/94055/27497350-f6d4b764-580e-11e7-83d9-22030bba1bc6.png">

Did this to fix:
```
sudo yum install ftp://fr2.rpmfind.net/linux/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
```

CC @rogaha

**Comment by cpuguy83** [comment]
Opened https://github.com/docker/docker.github.io/pull/3702

Note that technically RHEL is not supported for `docker-ce`.

**Comment by dim912** [comment]
@briantd. A Lifesaving tip. Thanks.

**Comment by vgoma** [comment]
@cpuguy83 `yum-config-manager --enable extras` solved it for me. thanks

**Comment by shubhsharma10** [comment]
@cpuguy83 
For AWS: `sudo yum-config-manager --enable rhui-REGION-rhel-server-extras`
For Azure: `sudo yum-config-manager --enable rhui-rhel-7-server-rhui-extras-rpms`

**Comment by hatdropper1977** [comment]
I have this issue on Centos 7
```bash
$ uname -sr
Linux 3.10.0-514.21.1.el7.x86_64
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
$ sudo yum-config-manager --enable extras
```
When I try to install docker-ce I get this error:
```bash
Error: Package: docker-ce-17.06.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2.9
```

**Comment by mattshma** [comment]
@hatdropper1977 , make sure your *extras* repo has "container-selinux >= 2.9".

After I ran `sudo yum-config-manager --enable extras`, I still faced this problem. When I opened the *extra* repository, I didn't found any packages about container-selinux >= 2.9. 

In https://docs.docker.com/engine/installation/linux/docker-ee/rhel/, I found a clue:
> Enable the extras RHEL repository. This ensures access to the container-selinux package which is required by docker-ee.
And in the [centos7 extra repo](http://mirror.centos.org/centos/7/extras/x86_64/Packages/), you could find container-selinux-2.19.

so just make extras repo enabled (default is enabled) and make sure your extras repo has container-selinux>=2.9.

**Comment by zemmali** [comment]
rpm -Uvh ftp://fr2.rpmfind.net/linux/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm

**Comment by mstanleyjones** [comment]
For Centos, this is fixed by https://github.com/docker/docker.github.io/pull/3702. SLES still has a problem with `selinux`, for which there is no workaround, but we have documented.

**Comment by DMEvanCT** [comment]
You can try this. 

yum remove docker-ce-selinux
wget ftp://ftp.icm.edu.pl/vol/rzm6/linux-centos-vault/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
rpm -Uvh container-selinux-2.9-4.el7.noarch.rpm
yum install docker-ce

**Comment by Golovolon** [comment]
Enable `extras` and
`yum-config-manager --enable extras`
`subscription-manager repos --enable=rhel-7-server-extras-rpms`
`yum makecache fast`
`yum -y install container-selinux`

**Comment by jag78au** [comment]
Thanks for saving time to debug 👍

**Comment by duartealexf** [comment]
For those having problems with `container-selinux` in Amazon Linux 2, the latest version of Docker is available using `amazon-linux-extras` command:

```sh
sudo yum install -y amazon-linux-extras yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --enable extras
sudo amazon-linux-extras install docker
```

It installed 18.06.1-ce for me.

**Comment by mattwilson777** [comment]
> For those having problems with `container-selinux` in Amazon Linux 2, the latest version of Docker is available using `amazon-linux-extras` command:
> 
> ```shell
> sudo yum install -y amazon-linux-extras yum-utils device-mapper-persistent-data lvm2
> sudo yum-config-manager --enable extras
> sudo amazon-linux-extras install docker
> ```
> 
> It installed 18.06.1-ce for me.

This worked perfectly for me. Using the latest Amazon Linux 2 as well. Thanks for posting this.

**Comment by sept44** [comment]
yes,I just ran into this too, I try too many methond,I tried a lot of programs, including the suggestions of the above friends. Later I summed up some of them. If you installed the Centos system, it will show warning when booting. I think this is a hardware problem, maybe the computer is too old. I don't support the Centos system. At this time, I changed the ubuntu18 system and installed docker to solve it. This is my attempt and I hope to help the latecomers.

**Comment by sxiii** [comment]
Guys if anybody find a way to install Docker 19.03; please let me know. AWS Linux 2 is really unfriendly platform :(

**Comment by Sebastian2099** [comment]
Completely agree with you @sxiii, I'm trying so many ways, suggestions, but anything works :/ any help? I already try each of the suggestions posted here.

**Comment by mrk3767** [comment]
This is also an issue for me. Happened on fresh installs of Centos7 and Amazon Linux 2.

**Comment by 3bars** [comment]
> Completely agree with you @sxiii, I'm trying so many ways, suggestions, but anything works :/ any help? I already try each of the suggestions posted here.

Still having issues with all the aforementioned suggestions.

**Comment by rohanrajpal** [comment]
> > Completely agree with you @sxiii, I'm trying so many ways, suggestions, but anything works :/ any help? I already try each of the suggestions posted here.
> 
> Still having issues with all the aforementioned suggestions.
> 
> Just got it to work, be sure to delete the docker-ce.repo repo, then yum makecache fast, then try sudo amazon-linux-extras install docker

Thanks, man. Copy-paste commands:
```bash
sudo rm /etc/yum.repos.d/docker-ce.repo
yum makecache fast
sudo amazon-linux-extras install docker
```

**Comment by akash59** [comment]
Life saver 👍

**Comment by outofbeer** [comment]
> Guys if anybody find a way to install Docker 19.03; please let me know. AWS Linux 2 is really unfriendly platform :(

were you able to make it work?

**Comment by outofbeer** [comment]
use this if anyone is looking to install older version of docker on Amazon linux 2 ---https://aws.amazon.com/premiumsupport/knowledge-center/ec2-install-extras-library-software/

**Comment by Sergushka** [comment]
> > > Completely agree with you @sxiii, I'm trying so many ways, suggestions, but anything works :/ any help? I already try each of the suggestions posted here.
> > 
> > 
> > Still having issues with all the aforementioned suggestions.
> > Just got it to work, be sure to delete the docker-ce.repo repo, then yum makecache fast, then try sudo amazon-linux-extras install docker
> 
> Thanks, man. Copy-paste commands:
> 
> ```shell
> sudo rm /etc/yum.repos.d/docker-ce.repo
> yum makecache fast
> sudo amazon-linux-extras install docker
> ```

Thanks this worked for me

**Comment by qiujiangkun** [comment]
For those who has trouble with selinux on Amazon Linux 2 AMI, try `amazon-linux-extras install selinux-ng` which will install container-selinux somehow
