### ISSUE TITLE
Unexpected Network slow down performance with Apache on Docker

### ISSUE THREAD

**Issue by frjaraur** [docker/for-linux#216]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Apache on Docker with same performance or at least minimum overhead using 100 concurrent conections than Apache on virtual host/baremetal.

### Actual behavior
I get at least +20ms (and it increases as I increase concurrency) on my tests using same apache version, same apache config and only difference is Docker.

### Steps to reproduce the behavior
All served content is in the image and running tests locally didn't show any performance issue, running apache bench tests over local deployed container.
When reaching served content remotelly, from different local network locations, I get a 14ms baseline but when using apache bench with more than 100 for concurrency, latency raises up to 40ms or even more . 
Same results using host driver or bridge.
Same resuts running apache docker container on baremetal or virtual host (vmware).
Docker Host on Baremetal and Viertual are almost the same size (CPU/Mem).
Apache Host is almost same size as Docker hosts.
Serving content with same apache version and config, installed on host didn't have this problem.

**Output of `docker version`:**

```
$ docker version

Client:

Version:         1.12.6

API version:     1.24

Package version: docker-1.12.6-55.gitc4618fb.el7.x86_64

Go version:      go1.8.3

Git commit:      c4618fb/1.12.6

Built:           Thu Aug 24 14:48:49 2017

OS/Arch:         linux/amd64

 

Server:

Version:         1.12.6

API version:     1.24

Package version: docker-1.12.6-55.gitc4618fb.el7.x86_64

Go version:      go1.8.3

Git commit:      c4618fb/1.12.6

Built:           Thu Aug 24 14:48:49 2017

OS/Arch:         linux/amd64(paste your output here)
```

**Output of `docker info`:**

```

Containers: 7

Running: 7

Paused: 0

Stopped: 0

Images: 11

Server Version: 1.12.6

Storage Driver: devicemapper

Pool Name: vg_docker-thinpool

Pool Blocksize: 65.54 kB

Base Device Size: 10.74 GB

Backing Filesystem: xfs

Data file:

Metadata file:

Data Space Used: 10 GB

Data Space Total: 14.85 GB

Data Space Available: 4.846 GB

Metadata Space Used: 7.999 MB

Metadata Space Total: 67.11 MB

Metadata Space Available: 59.11 MB

Thin Pool Minimum Free Space: 1.485 GB

Udev Sync Supported: true

Deferred Removal Enabled: true

Deferred Deletion Enabled: true

Deferred Deleted Device Count: 0

Library Version: 1.02.140-RHEL7 (2017-05-03)

Logging Driver: json-file

Cgroup Driver: systemd

Plugins:

Volume: local

Network: bridge overlay null host

Authorization: rhel-push-plugin

Swarm: inactive

Runtimes: docker-runc runc

Default Runtime: docker-runc

Security Options: seccomp

Kernel Version: 3.10.0-693.2.1.el7.x86_64

Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)

OSType: linux

Architecture: x86_64

Number of Docker Hooks: 3

CPUs: 4

Total Memory: 7.624 GiB

Name: -----------------

ID:--------------------------------

Docker Root Dir: /var/lib/docker

Debug Mode (client): false

Debug Mode (server): false

Registry: https://dockerregistry:5050/v1/

Insecure Registries:

dockerregistry:5050

127.0.0.0/8

```
I haven't found any issue about network performance in this version, not related to overlay.

Apache Bench is the tool used for this webserver testing and have done all tests many times with the same results. Poor performance using Docker against Apache installed. Performace get worse as soon as currency increases, not getting this problem on installed Apache.

**Comment by cpuguy83** [comment]
Can you give examples of the container config used when testing?
Is apache bench running on the local node?

**Comment by frjaraur** [comment]
Container run is quite normal, we add some environment variables and just expose apache ports.
docker run -d --name apache -p 8080:80 -v /data/configs_for_containers/apache:/etc/httpd \
-v   /data/logs_for_containers/apache:/var/logs/httpd internal-apache-image

Apache benchs are running using a docker container too, on same host for local tests, and from remote hosts for remote tests.
We will expect same performance as running a local install but its slower on virtual docker host or even baremetal.I searched for network performance issues with 1.12.6 and there are few related to overlays, but this is quite simple sitiation.
We tried with host network but we get same results.
Many Thanks Brian.,
Javier R.

**Comment by cpuguy83** [comment]
Some things to keep in mind with regard to network performance:

1. When using `-p 8080:80`, there is NATing involved when hitting port 8080 on the host, as such some extra overhead.
2. If hitting port 8080 on the same host, you will end up going through a userspace proxy, which would almost certainly account for the added latency.
3. Bridge networking inherently has some overhead, though I wouldn't expect the added latency just from this
4. Most of the networking related sysctl tweaks are namespaced, so the container will get default values, and may need to be tweaked further... but again I wouldn't really expect a ton of latency here outside of excessive concurrency capping out the sysctl settings.

When using host networking (ie. `docker run --net=host`), I would expect to get the same results both when in the container and not.

Back to your particular issue, I'm still having a hard time following (sorry!). Some specific scenarios with results (or approximate results) would help.
Thanks!

**Comment by frjaraur** [comment]
I will try to complete this issue which in fact seems very strange to me because if it is real many people will had this problem. That's why I am trying to give as much info as possible.
Problems arrive with concurrency, so, is there something I can check in Docker?. I am sure that concurrency is the key because it is quite clear that using a single curl/httpstat for the testing url, times are the same for apache+hw, apache+docker+hw and apache+virtual+hw. Same response times for this test on every environment, but when using ab for concurrency, I started to get more than 20ms of delay for environments related to Docker.
Many Thanks for Your Help, I am almost sure that is not a real Docker issue but can't see any other difference.

**Comment by cpuguy83** [comment]
What if you set "--log-driver=none"?

**Comment by frjaraur** [comment]
Same results without logging container output.
Using stats, contnainer performance it's OK, in fact, nothing represents problems with concurrent connections. Maybe is just an Apache problem running in containers?
Thanks Brian for your tips and help,
Javier R

**Comment by cpuguy83** [comment]
@frjaraur Is apache writing to the filesystem? (e.g. access logs)

**Comment by frjaraur** [comment]
It is writing to host filesystem using bind mount. I deleted cache configuration because it was using container /tmp, but same results (I expected best results avoiding writing to copy-on-write).
We are using Redhat's docker version with device mapping (lvdirect). Is there any concurrency limitation to Docker?, There isn't any (or at least I haven't see any) on hosts.
Many Thanks,
Javier R.

**Comment by cpuguy83** [comment]
Is something attached to the container output? if apache is blocking on writing to stdout/stderr this could cause the slowdown.

Are you certain the apache config is the same? Is one using prefork and another using threads/events?

**Comment by frjaraur** [comment]
Still doing tests. Next week we promote VM Server to production to get real traffic and watch for those latency times.
Many Thanks Brian,
Javier R.

**Comment by frjaraur** [comment]
Discard this issue it wasn't a contanir related issue. Application adds delays decribed on issue.
