### ISSUE TITLE
Just installed: Failed to connect to containerd

### ISSUE THREAD

**Issue by Glideh** [docker/for-linux#218]
Just installed Docker CE following official instructions with the repository in Ubuntu 14.04

Installation went successfully, the daemon is running

    $ ps aux | grep docker
    [...] /usr/bin/dockerd --raw-logs [...]

My user is in the docker group:

    $ groups
    [...] docker

The cli can't seem to communicate (same with sudo)

    $ docker ps
    (after 2 or 3 sec.)
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock.
    Is the docker daemon running?

The socket seems to have the correct permissions:

    $ ls -l /var/run/docker.sock
    srw-rw---- 1 root docker 0 Feb  4 16:21 /var/run/docker.sock

The log seems to claim about some issues though

    $ sudo tail -f /var/log/upstart/docker.log

> Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout
/var/run/docker.sock is up
time="2018-02-04T16:22:21.031459040+01:00" level=info msg="libcontainerd: started new docker-containerd process" pid=17147
INFO[0000] starting containerd                           module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
INFO[0000] setting subreaper...                          module=containerd
containerd: invalid argument
time="2018-02-04T16:22:21.056685023+01:00" level=error msg="containerd did not exit successfully" error="exit status 1" module=libcontainerd

Any advice to make this work ?

---

_Relog and Docker restart already done of course_

**Comment by Glideh** [comment]
3.2.0-33-generic

**Comment by dnephin** [comment]
That's the issue. https://docs.docker.com/install/linux/docker-ce/binaries/

> Version 3.10 or higher of the Linux kernel.

**Comment by Glideh** [comment]
Damned, I missed that one, Thx.
