### ISSUE TITLE
Docker for Centos - Cannot Docker Pull (no external connectivity)

### ISSUE THREAD

**Issue by kristiehoward** [docker/for-linux#22]
### Expected behavior
After following instructions to install [Docker for Centos](https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository) on my Centos 7 machine, I can verify my docker installation via `sudo docker run hello-world`

### Actual behavior
I was able to successfully install docker (with the fix of `sudo yum erase docker-engine-selinux` as in ticket https://github.com/docker/for-linux/issues/20) and run `sudo docker run hello-world` on the first two machines. I grabbed lunch and came back to follow the instructions on the last two (54) machines and when I got to `sudo docker run hello-world`, then I got issues with connectivity (docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35977->[::1]:53: read: connection refused.)

Now, I get that issue on all 4 of my machines.

```
[root@swarm-test-centos7002-E2E-50D1D7-linux-2 docker]# docker version
Client:
 Version:      17.06.0-ce-rc3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:17:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc3
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:19:01 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@swarm-test-centos7002-E2E-50D1D7-linux-2 docker]# sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:35977->[::1]:53: read: connection refused.
See 'docker run --help'.
```

### Information
My IPs per https://docs.google.com/document/d/1dIA0BnvfAKX-puJ78YPisM12QUQNdpgTOAOkhx6ZvAE/edit#:

34.211.29.111
34.211.115.9
54.244.214.198
54.190.47.80

### Steps to reproduce the behavior
Follow instructions in https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository and https://github.com/docker/for-linux/issues/20

**Comment by seemethere** [comment]
Don't believe this is an issue anymore, closing.
