### ISSUE TITLE
No binary available for v18.01.0-ce release

### ISSUE THREAD

**Issue by lox** [docker/for-linux#223]
There doesn't appear to be any binary release available in https://download.docker.com/linux/static/stable/x86_64/ for the v18.01.0-ce release. Should there be?

**Comment by thaJeztah** [comment]
18.01 and 18.02 are “edge” (monthly) releases, so they can be found in the “edge” channel; https://download.docker.com/linux/static/edge/x86_64/

Closing, but feel free to continue the conversation

**Comment by vdemeester** [comment]
@lox it shouldn't be there. 18.01 is not a stable release, it's available in `edge` : https://download.docker.com/linux/static/edge/x86_64/

The next stable will be 18.03, so this will be the next one to be available in stable.

**Comment by lox** [comment]
Ah right, so how does that work with Github's stable vs prerelease release tags? It's currently listed as a stable release: https://github.com/docker/docker-ce/releases/tag/v18.01.0-ce

The latest pre-released is https://github.com/docker/docker-ce/releases/tag/v18.02.0-ce-rc2.

**Comment by lox** [comment]
How would I answer the question on-going "What is the most recent stable Docker CE, and where can I download a binary for it"?

**Comment by lox** [comment]
I'm going to guess that https://docs.docker.com/release-notes/docker-ce/ is authoritative and we should ignore everything else?

**Comment by thaJeztah** [comment]
See the matrix in the documentation; https://docs.docker.com/install/#time-based-release-schedule

**Comment by thaJeztah** [comment]
And this announcement of the "edge" and "stable" channels; https://blog.docker.com/2017/03/docker-enterprise-edition/

**Comment by lox** [comment]
What would I hope to learn from that matrix @thaJeztah?

**Comment by lox** [comment]
OK, let me try this another way.

**Comment by lox** [comment]
Perhaps I have misunderstood what constitutes a pre-release from a Github Releases perspective. Am I right in understanding that is only used to denote a release candidate, but doesn't distinguish between Edge and Stable releases?

**Comment by thaJeztah** [comment]
Yes, GitHub doesn't have such a concept; GitHub only allows you to mark a release as "pre-relase" (which can be used for "release candidates" or "beta/alpha" releases from "ga" releases).

Note that the GitHub repository is only used for tagging the source that's used for a release; the download.docker.com repository is where Docker releases are published.

**Comment by vdemeester** [comment]
@lox GitHub releases has nothing to do with the way Docker does release really. The Github releases page is mapping any tag with some content (description, links, etc..). You can define pre-release and release (i.e. `-rc` tags and final tags).

That said, each project can define it's own way to distribute and define "channels" for their release (GitHub is not authorative there). The way Docker does release is the same as Ubuntu. For Ubuntu, there is a release 6 months and each 3 versions of Ubuntu, one is considered LTS (i.e. stable and support for a long time period). Docker does the same, with another timeframe : 1 release everymonth, and each 3 version (in march, june, september and decemeber), those are considered stable.

As @thaJeztah said, `GitHub repository is only used for tagging the source that's used for a release`, the distribution channel (for binaries, package, etc..) is not GitHub. The [matrix](https://docs.docker.com/install/#time-based-release-schedule) helps you know which version is stable and which is not. And as you said, [this page](https://docs.docker.com/release-notes/docker-ce/) lists the stable version of docker, so if you're only looking for docker stable release (and not edge ones), then this is authoritative.

**Comment by lox** [comment]
Ok, fair enough, that makes sense! I think the Ubuntu models works well because they invest a lot of effort in making it really clear. For "What is the latest stable ubuntu", the first page is https://wiki.ubuntu.com/Releases. The second page is a link to https://www.ubuntu.com/download/desktop with direct download links and some good guidance on what LTS releases are.
