### ISSUE TITLE
Docker Install Docs - Centos Vs Ubuntu Inconsistencies

### ISSUE THREAD

**Issue by kristiehoward** [docker/for-linux#24]
### Actual behavior
[Docker for Ubuntu](https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository) install docs have tabs for the CE vs EE instructions.
![image](https://user-images.githubusercontent.com/7132362/27200333-3506ed46-51ce-11e7-8800-5897a61b86ba.png)

[Docker for Centos]() install docs have sequential tabs for the CE vs EE instructions. This caused me to accidentally (4 different times...) start doing the EE install instructions after the CE install instructions because I was just following down the page.
![image](https://user-images.githubusercontent.com/7132362/27200321-31716292-51ce-11e7-9175-12f5a552ef40.png)

### Desired behavior
Both have tabs - IMO way better experience for users consuming docs

**Comment by thaJeztah** [comment]
Docs have now been split between CE https://docs.docker.com/engine/installation/linux/docker-ce/centos/ and EE https://docs.docker.com/engine/installation/linux/docker-ee/centos/

closing this issue, because this is resolved, thanks!
