### ISSUE TITLE
docker in lxd container crashes if init swarm

### ISSUE THREAD

**Issue by unclesamwk** [docker/for-linux#244]
Hey,

i use docker in lxd. if i will use swarm and init docker crashes with following message:
```
WARN[2018-03-01T12:12:17.588518549Z] Error (Unable to complete atomic operation, key modified) deleting object [endpoint_count zpnvfcscmn415cb652gg10jce], retrying.... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d4d195]
```
In older docker.io versions swarm works ...

Gruß
Sam

**Additional environment details (AWS, VirtualBox, physical, etc.)**
docker in lxd container with security.privileged = true

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and there's not enough information in the ticket to make it actionable
