### ISSUE TITLE
Docker for Ubuntu Install Docs - EE and "production" instructions in CE section

### ISSUE THREAD

**Issue by kristiehoward** [docker/for-linux#25]
### Expected behavior
CE Tab of Docker for Ubuntu Install Docs includes only instructions for Docker CE

### Actual behavior
https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository
CE Tab of Docker for Ubuntu has EE instructions and steps for "production" --> doesn't CE imply _not_ production?

![image](https://user-images.githubusercontent.com/7132362/27200468-a16e6b8a-51ce-11e7-9090-3c3f7832c38e.png)
![image](https://user-images.githubusercontent.com/7132362/27200551-e8a2ba7e-51ce-11e7-8638-274fc6d7718d.png)

### Information
https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

**Comment by thaJeztah** [comment]
Installation instructions are split now between CE and EE, so i'm closing this one as well, thanks!
