### ISSUE TITLE
Error response from daemon: cannot stop container

### ISSUE THREAD

**Issue by penhauer-xiao** [docker/for-linux#254]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
To stop is ok

### Actual behavior
     
Error response from daemon: cannot stop container: go_dev_iao: Cannot kill container 69df884e92adede99debbb3d94744e4cd6546e3d5a1af6b827b4a8698fab092a: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

### Steps to reproduce the behavior

**Output of `docker version`:**

```
 Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
 Containers: 15
 Running: 8
 Paused: 0
 Stopped: 7
Images: 28
Server Version: 17.11.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: 992280e8e265f491f7a624ab82f3e238be086e49)
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: xiaobenhua-76
ID: 7S4Z:QR2S:FYKU:TCYQ:FTNC:O7KA:CYYY:W7TL:6L6U:ELQ5:O3XP:V4B2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by tgropper** [comment]
Same issue here with version 18.01.0-ce:

```
$ sudo cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

$ sudo docker version
Client:
 Version:       18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:07:19 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:        Wed Jan 10 20:10:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

$ sudo docker-containerd --version
containerd github.com/containerd/containerd v1.0.0 89623f28b87a6004d4b785663257362d1658a729

$ sudo docker rm cfad6e8f7a91 -f
Error response from daemon: Could not kill running container cfad6e8f7a915dc16351716b5affb822b84132aae727bc3bf4f5e7f1cc105869, cannot remove - Cannot kill container cfad6e8f7a915dc16351716b5affb822b84132aae727bc3bf4f5e7f1cc105869: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

$ sudo docker kill cfad6e8f7a91
.. same error than above..
```

This particular container is a Logstash container (having same issue with an Elasticsearch container). They are both consuming all the resources from the node.

**Comment by jcrben** [comment]
I was having this issue too with `18.01.0-ce`.

By the time I ran `apt-get -y install docker-ce` the containers had stopped? I'll try to update this if I find out more.

**Comment by penhauer-xiao** [comment]
@jcrben That's just docker daemon stopped, the running container did not stop.

**Comment by jcrben** [comment]
@penhauer-xiao are you sure? I didn't try to restart my daemon, and 1 of the 4 containers (at least 2 of the others were having this issue) that I had running remained running

**Comment by penhauer-xiao** [comment]
@jcrben The problem is still there, as you said.

**Comment by rafaelcapucho** [comment]
A `sudo systemctl restart docker.service` solves the issue.

**Comment by dk766** [comment]
Same here:
$ sudo systemctl restart docker.service
$ docker stop imagebase
Error response from daemon: cannot stop container: imagebase: Cannot kill container bcef0453938e1d9b4fbabc6f6994db0577284d5520bc8125dfa974e02636d59c: unknown error after kill: runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
: unknown

**Comment by mohsenSy** [comment]
Hi,

I was having the same issue I solved it by executing a shell in the docker container using this command
`docker exec -it imagebase bash` then issuing `kill 1` command.

The container is gone by now

**Comment by lancedang** [comment]
> A `sudo systemctl restart docker.service` solves the issue.

Can you explain why can not stop the container?

**Comment by rcjsuen** [comment]
I had this issue with `ami-0fba9b33b5304d8b4` on EC2 and resolved it by rebooting the EC2 instance.

```
$ sudo docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by pshongwe** [comment]
I still have this issue. restart does not help, even stopping the docker service:
```
sudo docker version
Client:
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 02:58:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 02:57:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by hoseinipeyrov** [comment]
`sudo systemctl restart docker.service` worked for me.

**Comment by shachitaku** [comment]
restarting the computer worked for me!

**Comment by shachitaku** [comment]
always the ultimate move

**Comment by vickykumarmlt** [comment]
Docker service restart will work with docker version 19.03

**Comment by kitsao** [comment]
`sudo systemctl restart docker.service` worked for me too.

**Comment by pshongwe** [comment]
Yup `sudo systemctl restart docker.service` works

**Comment by OMRANIMEDAMINE** [comment]
sudo service docker restart
docker stop $(sudo docker ps -aq)
docker-compose down

**Comment by ranjiGT** [comment]
```sudo systemctl restart docker.service``` this works like a charm !

**Comment by dwivedithedev** [comment]
> `sudo systemctl restart docker.service` this works like a charm !

If I am on a windows system where sudo doesn't work, What should I execute? (in a normal cmd, docker beginner here!).

**Comment by sctothevision** [comment]
Better late than never, but my answer might help somebody :)
So how I solved the problem:
1. Enter the container : docker exec -it id_container /bin/bash 
2. Inside the container just write: kill 1
3.Then write docker stop id_container 
And the problem might be solved

**Comment by talisman49** [comment]
> systemctl restart docker.service

No, no lo resuelve!!!

**Comment by talisman49** [comment]
> 1. docker exec -it id_container /bin/bash

Esto lo resuelve como "apagafuegos", pero no es la mejor solución.

**Comment by shahidkarimi** [comment]
This is issue is very severe and still un-resolved. @talisman49

**Comment by Dagdimayur** [comment]
This is issue is very severe and still un-resolved.

**Comment by wpecker** [comment]
5 years and still not fixed；So disappointed

**Comment by atloZ** [comment]
> Hi,
> 
> I was having the same issue I solved it by executing a shell in the docker container using this command `docker exec -it imagebase bash` then issuing `kill 1` command.
> 
> The container is gone by now

this solved it for me :D
