### ISSUE TITLE
Files.createDirectories( ... ) with POSIX file permissions fails

### ISSUE THREAD

**Issue by asubich** [docker/for-linux#261]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Files.createDirectories( ... ) with POSIX file permissions should create any missing directories with provided permissions

### Actual behavior
Files.createDirectories( ... ) with POSIX file permissions only creates any missing directories but no permissions are set
### Steps to reproduce the behavior

I run my JAVA application on Oracle Java 8 (Ubuntu), and try creating a tree of directories with a specific POSIX permissions.
Here is the code snippet:
`Set<PosixFilePermission> perm2 = PosixFilePermissions.fromString( "rwxrwxr-x" );
System.out.println( "Creating dirs with '775' ..." + perm2 );
Files.createDirectories( Paths.get( "/tmp/mostAccessDir/mostAccessDir" ), PosixFilePermissions.asFileAttribute( perm2 ) );`
It works fine.
However, when I tried running the same code in Docker(17.12.0-ce, build c97c6d6) : CentOS : Oracle JDK it created the directories, but ignored setting the permissions.  I tried Ubuntu operating systems, and OpenJDK, but the result was consistent – NO PERMISSIONS set.
Then I decided to create the directories first and then change the permissions – two-step process.
Here is the code snippet:
`Path twoStepPath = Paths.get( "/tmp/twoStepDir" );
        System.out.println( "Creating two step dirs" );
        Files.createDirectory( twoStepPath );
        Set<PosixFilePermission> perm3 = PosixFilePermissions.fromString( "rwxrwxr-x" );
        System.out.println( "Setting two step dirs POSIX to 775" );
        Files.setPosixFilePermissions( twoStepPath, perm3 );`

**Output of `docker version`:**

```
Docker version 17.12.0-ce, build c97c6d6
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 94
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-64-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 13.52GiB
Name: LinuxVM
ID: BPI4:AYJP:AHQ7:TYYC:YKOI:WUGC:QC77:4X7C:5XH3:2HQQ:6RQE:BUON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Running in Oracle VM VirtualBOX

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and the aufs storage driver was deprecated and removed

**Comment by row49382** [comment]
I came across this issue when trying to write directories in a docker container as well. For anyone having issues with this today, and still working in Java 8, you can set the file permissions for the directories after the creation using `Files.setPosixFilePermissions`. 

```java
File file = new File("parent-dir/file");;
Files.createDirectories(file.getParentFile().toPath());
Files.setPosixFilePermissions(
    file.getParentFile().toPath(),
    PosixFilePermissions.fromString("rwxrwxr--"));
```

In the case you need to set all parent directory permissions, you will need to recurse the file's parents and set permissions at each level.

Hope this helps someone else!
