### ISSUE TITLE
Docker Build and Publish plugin is NOT working

### ISSUE THREAD

**Issue by streamhsa** [docker/for-linux#266]
I tried Docker Build and Publish plugin and it is NOT working.

### Expected behavior
Docker Build and Publish plugin should work and generate image and push it to https://hub.docker.com

### Actual behavior
Its not happening.
Console output shows.....
Building on master in workspace /var/lib/jenkins/workspace/sample
[sample] $ docker build -t hub.docker.com/computecqe/roc-master:1111 --pull=true --file=/home/taccuser/Documents/crm_taccuser_7819/Dockerfile /var/lib/jenkins/workspace/sample
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/taccuser/Documents/crm_taccuser_7819: no such file or directory
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

### Steps to reproduce the behavior
Please check the below images for the options I made.

![image](https://user-images.githubusercontent.com/8362518/38194010-b219f5d6-3692-11e8-9e84-15e8654a6ec3.png)
![image](https://user-images.githubusercontent.com/8362518/38194044-d6737998-3692-11e8-8f2c-49c471e53274.png)

**Comment by yogeshdewangan** [comment]
How have you started the jenkins? if you are using any custom volume then remove it

it should be -v /var/jenkins_home:/var/jenkins_home

**Comment by cpuguy83** [comment]
I'm going to go ahead and close this, but feel free to discuss.
This is almost certainly a configuration issue with your Dockerfile path.
