### ISSUE TITLE
Docker install for arm64 on Debian Buster

### ISSUE THREAD

**Issue by appcodr** [docker/for-linux#271]
Could not install docker-ce on Debian buster on a Dragonboard 410c . I followed the instructions from here
https://docs.docker.com/install/linux/docker-ce/debian/

```
linaro@linaro-alip:~$ sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
```

And when I manually dowload the package and install it, it says architecture not supported

`linaro@linaro-alip:~$ sudo dpkg -i docker-ce_17.12.1~ce-0~debian_armhf.deb dpkg: error processing archive docker-ce_17.12.1~ce-0~debian_armhf.deb (--install): package architecture (armhf) does not match system (arm64) Errors were encountered while processing: docker-ce_17.12.1~ce-0~debian_armhf.deb`

**Comment by seemethere** [comment]
Bit of an oversight for us, should be solved once https://github.com/docker/docker-ce-packaging/pull/102 goes through. Should start appearing in nightly builds after that PR gets through.

**Comment by appcodr** [comment]
Thanks for fixing this soon. Will this soon get in the edge channel?

**Comment by seemethere** [comment]
@appcodr the earliest release this could be in would be `18.05.0-ce` since we're already past code freeze for `18.04.0-ce`

**Comment by appcodr** [comment]
Okay, so Will I see an arm64 folder in the following url https://download.docker.com/linux/debian/dists/buster/pool/edge/

Or should I pick the docker-ce_18.04.0~ce-0~debian_armhf.deb when its available (in a month or so?)
https://download.docker.com/linux/debian/dists/buster/pool/edge/armhf/

**Comment by seemethere** [comment]
@appcodr you will see an `arm64` folder

**Comment by appcodr** [comment]
So where can  download the nightly build package for the arm64 build now that the pull request is merged?

**Comment by thaJeztah** [comment]
@Jean-Babtiste-Lasselle no need to subscribe; packages are available for a while now; https://download.docker.com/linux/debian/dists/buster/pool/stable/arm64/
