### ISSUE TITLE
Failed to connect to containerd: failed to dial

### ISSUE THREAD

**Issue by EFugier** [docker/for-linux#274]
```
sudo dockerd
INFO[2018-04-05T18:19:12.084201563+02:00] libcontainerd: docker-containerd is still running  pid=1682
Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout
```
Exact same as #218 but my kernel is up to date.

```
uname -a
Linux pop-os 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
It ran fine... only once.

If I kill the above process I get this when running `dockerd` again:

```
INFO[0000] containerd successfully booted in 0.004178s   module=containerd
INFO[2018-04-05T20:17:41.760459158+02:00] [graphdriver] using prior storage driver: aufs 
Error starting daemon: error while opening volume store metadata database: timeout
```

**Comment by YaoC** [comment]
I have the same problem with `18.03.0~ce-0~ubuntu` but my kernel is:
```Bash
uname -r
4.4.0-62-generic
```
Here is the output of `sudo dockerd --debug`
```
DEBU[2018-04-26T18:22:02.262404891+08:00] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[2018-04-26T18:22:02.262765528+08:00] libcontainerd: started new docker-containerd process  pid=22222
INFO[0000] starting containerd                           module=containerd revision=cfd04396dc68220d1cecbe686a6cc3aa5ce3667c version=v1.0.2
DEBU[0000] changing OOM score to -500                    module=containerd
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
DEBU[0019] received signal                               module=containerd signal=terminated
WARN[2018-04-26T18:22:37.264699897+08:00] daemon didn't stop within 15 secs, killing it  module=libcontainerd pid=22222
Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout
```
It turns out that `docker-containerd.sock` does not exsit : 
```
ll /var/run/docker/containerd/
total 4
drwx------ 3 root root  80 Apr 26 18:22 ./
drwx------ 3 root root  60 Apr 26 18:01 ../
-rw------- 1 root root 559 Apr 26 18:22 containerd.toml
drwx--x--x 2 root root  40 Apr 26 18:01 daemon/
```

**Comment by thaJeztah** [comment]
Looks like it's resolved so closing

**Comment by nikhilthombare** [comment]
When tried to rebuild specific app it returns the error. When try to deploy changes to dokku its gives  

`remote: docker: Error response from daemon: connection error: desc = "transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout".`

```-----> Cleaning up...
-----> Building nutst from herokuish...
docker: Error response from daemon: connection error: desc = "transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout".
tar: -: Cannot write: Broken pipe
tar: Error is not recoverable: exiting now

**Comment by sampyakurel** [comment]
Hello,

I am still getting the following error even after I rebooted the server. 
The 'docker-containerd.sock' file existed in my case. Any help resolving this issue will be much appreciated. 

> INFO[2018-12-08T01:04:36.213785476Z] pickfirstBalancer: HandleSubConnStateChange: 0xc4203d0070, CONNECTING  module=grpc
WARN[2018-12-08T01:04:56.213938543Z] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout". Reconnecting...  module=grpc
INFO[2018-12-08T01:04:56.214226159Z] pickfirstBalancer: HandleSubConnStateChange: 0xc4203d0070, TRANSIENT_FAILURE  module=grpc
INFO[2018-12-08T01:04:56.214368025Z] pickfirstBalancer: HandleSubConnStateChange: 0xc4203d0070, CONNECTING  module=grpc
**Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": context deadline exceeded**

>
