### ISSUE TITLE
docker ps output is so long it's unreadable. How about a yaml/json output option?

### ISSUE THREAD

**Issue by mlda065** [docker/for-linux#279]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

I want the output of `docker ps` to be spread clearly over multiple lines per container. 

Trying to unwrap a table that's got two line breaks per container is incredibly difficult for a human and a normal sized window. It's also difficult for a computer to read (e.g. `awk '{print $5}'`)

There should be an option you can add to `docker ps` to make it print in yaml or json. Scrolling vertically is far easier than trying to unwrap an extremely wide table in your mind.

### Expected behavior

`docker ps --human-readable`

```
- c4e4ab38d9ad
   - names:  mcordng40_xos_gui_1
   - image: docker-registry:5000/xosproject/xos-gui:candidate
   - command: "longer than normal command because theres space" 
   - created: 2 days ago          
   - status: Up 32 minutes
   - ports: 80/tcp, 0.0.0.0:4000->4000/tcp
- cec12815330a
   - names: mcordng40_vspgwc-synchronizer_1
   - image: docker-registry:5000/xosproject/vspgwc-synchronizer:candidate
   - command: "/bin/sh -c 'bash full command because we have room"
   - created: 2 days ago
   - status: Up 32 minutes
...
```

### Actual behavior

(i've used an extra narrow terminal to exaggerate the issue for clarity)

The output is impossible to read because there are many overlapping columns which are misaligned due to line breaks. 

* e.g. what are the status' of containers with 'synchroniser' in their name? It's hard for a human, and also hard for `awk` to read that.
* e.g. what command is the second container running? You can't see, because it's just `...`.

```
mlda065@mymachine:~$ docker ps
CONTAINER ID        IMAGE
                            COMMAND                  CREATED
         STATUS              PORTS

                                NAMES
c4e4ab3ad9ad        docker-registry:5000/xosproject/xos-gui:cand
idate                       "nginx -g 'daemon ..."   2 days ago
         Up 33 minutes       80/tcp, 0.0.0.0:4000->4000/tcp

                                mcordng40_xos_gui_1
cec12915130a        docker-registry:5000/xosproject/vspgwc-synch
ronizer:candidate           "/bin/sh -c 'bash ..."   2 days ago
         Up 33 minutes

                                mcordng40_vspgwc-synchronizer_1
ebf3d5169d45        docker-registry:5000/xosproject/venb-synchro
nizer:candidate             "/bin/sh -c 'bash ..."   2 days ago
         Up 33 minutes

                                mcordng40_venb-synchronizer_1
9a3c5181f9db        docker-registry:5000/xosproject/vtn-synchron
```

### Steps to reproduce the behavior

1. have a normal sized screen
1. open a terminal, maximize it
1. run `docker ps`

The effect is even worse if you have a small screen or can't maximize the window for some reason.

**Output of `docker version`:**

```
Docker version 17.06.2-ce, build cec0b72
```

**Output of `docker info`:**

```
Containers: 32
 Running: 30
 Paused: 0
 Stopped: 2
Images: 37
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 230
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.8GiB
Name: cord-head
ID: redacted
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.56.0.99:5000
 docker-registry:5000
 127.0.0.0/8
Registry Mirrors:
 http://docker-registry:5001/
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This problem exists on all platforms.

**Comment by cpuguy83** [comment]
You can supply your own custom template, and even have it be the default. See the "--format" flag.

**Comment by mlda065** [comment]
I've looked into [`--format`](https://docs.docker.com/engine/reference/commandline/ps/#formatting). As far as I can tell that's a way to customize the output but still in the same table format. The only way you can save space is to throw away columns, which isn't optimal.

Is there a way to use the `--format` flag to print in a non-table format? (e.g. json, yaml)

**Comment by thaJeztah** [comment]
You can output as JSON, e.g.;

```
docker ps --format '{{ json .}}'
```

**Comment by mlda065** [comment]
Ok great, we're getting closer. Now how do we add white space and line breaks to that json to make it human-readable?

**Comment by mlda065** [comment]
Piping the output to `python -m json.tool` does not work. That leads to an error.

But piping to `jq .` does work.

So the solution is

`docker ps --format '{{ json .}}' | jq .`

That's a bit of a mouthful, but it works.

**Comment by to-jk11** [comment]
My two cents worth here is that I was looking for the same thing and I created an alias in a `.bashrc` to make that command a little better:

`alias dpsf="docker ps --format '{{ json .}}' | jq ."` 

dpsf = docker ps format (change it to what you like)

**Comment by cpuguy83** [comment]
You can store your format in ~/.docker/config under the `psFormat` key...

e.g.

```
{
  "psFormat": "table {{.Names}}\\t{{.Image}}\\t{{.RunningFor}} ago\\t{{.Status}}\\t{{.Command}}"
}
```

**Comment by kitingChris** [comment]
Very sad that the feature request is closed! 
Actually this would be very useful!

**Comment by tanmay-happy** [comment]
You can try this command for more readable output: 

`docker ps | less -S`
