### ISSUE TITLE
How to see my application log in docker

### ISSUE THREAD

**Issue by ahilmathew** [docker/for-linux#280]
I can see all the STDOUT using docker logs <container> , but my Spring boot app writes log in a directory ( /opt/app/app.log). When I checked inside the shell of the container the application is not writing into that file. (app.log)
1. Why is my application log not being written into app.log?
2. Is there a way to use docker logs to get the app.log?

**Comment by cpuguy83** [comment]
> Why is my application log not being written into app.log?

This is an application configuration issue.

> Is there a way to use docker logs to get the app.log?

No, docker only consumes the stdout and stderr of the running process.
