### ISSUE TITLE
Container time is UTC while host time is UTC+5

### ISSUE THREAD

**Issue by saqibahmed515** [docker/for-linux#282]
* [x] This is a bug report
* [x] I searched existing issues before opening this one

### Expected behavior
Date and time of the container should be the same as the docker host.

### Actual behavior
Container date/time is UTC while the host date/time is UTC+5.

### Steps to reproduce the behavior
Start `node:6.14-alpine` image on a Centos 7 machine. 
execute `docker exec -it <container-name> date`
This would be different from the host date-time if the host is not at UTC.

### Use case
In my application (with node image as base), I have to get the system date/time and I store it in the DB for certain processing. I expect my `new Date()` to return the current date of the machine it is running on (which it does), but I get a different date because container date/time is out of sync with the actual time in my timezone. 

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 15
Server Version: 18.03.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-69594429-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 8.455GB
 Data Space Total: 107.4GB
 Data Space Available: 17.44GB
 Metadata Space Used: 12.64MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.135GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iawfdv386eb9cyj8ij0tt082z
 Is Manager: true
 ClusterID: pf4y6fmjf5cmnfmjdbz6njupp
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.88
 Manager Addresses:
  192.168.1.88:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.702GiB
Name: devlinux.ef.com
ID: EL4V:3M7R:7MJW:KBM2:T7PX:GLVS:USJN:QHHU:DCWD:2K75:AGMN:64SV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 192.168.1.88:5000
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
The Centos 7 machine is hosted on a windows machine inside VMWare in our local lab.

**Comment by cpuguy83** [comment]
This is dependent on the image you are using. All the official images use UTC timezones, but you can change tbis, or even mount in the time zone file from the host.

Closing since this is not an issue, but feel free to discuss.
Thanks.

**Comment by CodeSniperShoter** [comment]
Is it possible to change the timezone of container on runtime from host VM ?

**Comment by saqibahmed515** [comment]
@CodeSniperShoter 
Yes, it is possible. In my particular use case, I was using an alpine base image. I had to modify my base image by adding `apk add tzdata` in docker build, thus creating a new base image with tzdata. 
Afterward, I could simply change the `TZ` environment variable in my compose yml to change the timezone. This procedure may vary in various base images.

**Comment by CodeSniperShoter** [comment]
"During runtime, you'll have to do docker exec to the container to set the environment variable if you wanna change timezone. I only needed a deployment time configuration.": So you mean, even with the TZ var, we cant change container's timezone directly from host VM during running time? @saqibahmed515

**Comment by saqibahmed515** [comment]
Nope. I mean we can change the timezone of the container at any time whatsoever by following strategies:

1. During image creation, you can set `ENV TZ=timezone` in your `Dockerfile`.
2. During deployment time, you can add the environment variable in the `docker-compose.yml` or you can add it directly in `docker run` command using `-e` switch.
3. During runtime, you can do `docker exec -it <container name> bash` and `export TZ=whatever` to change the timezone of the container.

Hope that clarifies.

**Comment by CodeSniperShoter** [comment]
Yes, your explanation is very clear, but **during the running time,** I want to know, is there a way to change the Timezone of container directly from host VM, **instead of going into container firstly**, then change the Timezone info. 
As I suppose that, in the future, i should have hundreds of containers running at the same time; the method you offered is to heavy, I think.
I tried to mount the **/etc/localtime** into container from VM, but it didn't work; 
and I find if we can change the symbolic link of **/etc/localtime** file in container, we can solve this prob; but I didn't find the way to do it from host VM.

**Comment by CodeSniperShoter** [comment]
@saqibahmed515

**Comment by saqibahmed515** [comment]
@CodeSniperShoter  I have a few follow-up questions:

1. Are the containers you're deploying replicas of the same image or a few images OR you actually have hundreds of microservices running in containers?
2. Are you using `docker compose` or `docker stack`(swarm) deployment?

### What I know

If you have a few services (with replicas aggregating to hundreds) and you're deploying in a swarm with `docker stack deploy` then you can simply do `docker service update <service-name> --env-add TZ=something` from your Host VM and it will add this variable in all the replicas of the service. If you have, say, 5 services with 20 replicas each, you'll have to execute this command 5 times only. 

### Where I stumble

If you have a lot of services and/or you're deploying those services using `docker-compose`, then my knowledge is limited on how you can tackle this issue. 

Anyway, it would be better if you ask this question on https://dockercommunity.slack.com to get instant and apt answers.

**Comment by morsedl** [comment]
> Yes, your explanation is very clear, but **during the running time,** I want to know, is there a way to change the Timezone of container directly from host VM, **instead of going into container firstly**, then change the Timezone info.
> As I suppose that, in the future, i should have hundreds of containers running at the same time; the method you offered is to heavy, I think.
> I tried to mount the **/etc/localtime** into container from VM, but it didn't work;
> and I find if we can change the symbolic link of **/etc/localtime** file in container, we can solve this prob; but I didn't find the way to do it from host VM.

@saqib-ahmed @CodeSniperShoter : For Alpine Linux at least (and likely most distros) you also have to mount **/etc/timezone** as well, and it must contain one line indicating a valid timezone, in my case Europe/Berlin. My Dockerfiles set these during the build (I install tzdata with "apk add tzdata", copy /usr/share/zoneinfo/Europe/Berlin to /etc/localtime and "echo Europe/Berlin > /etc/timezone && chmod 644 /etc/timezone", and then uninstall tzdata to save a little space in the container). I don't do anything with the TZ environmental variable, which I imagine in the context of Docker likely is processed in a Docker-specific fashion.

**Comment by shivananda73** [comment]
we need to change the UTC time to IST time bcz docker are shows UTC timing so i want IST time how to do?
