### ISSUE TITLE
docker-ce package is missing for Ubuntu "Bionic" 18.04 LTS x86_64

### ISSUE THREAD

**Issue by tatsuya6502** [docker/for-linux#290]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

`docker-ce` package should be installed on Ubuntu "Bionic" 18.04 LTS by following the instructions on https://docs.docker.com/install/linux/docker-ce/ubuntu/

### Actual behavior

When running `sudo apt-get install docker-ce`, the following error ocurred and Docker CE was not installed.

```console
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

I found there is no Deb package prepared for Bionic x86_64 yet, even though there is a repository for Bionic.

https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

```
Index of /linux/ubuntu/dists/bionic/pool/stable/amd64/
---------------------------
../
---------------------------
``` 

NOTE: Ubuntu 18.04 LTS was released on Thu, Apr 28, 2018.

### Steps to reproduce the behavior

Install Ubuntu 18.04 LTS on a PC and follow the instruction on https://docs.docker.com/install/linux/docker-ce/ubuntu/.

**Output of `docker version`:**

n/a

**Output of `docker info`:**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Ubuntu "Bionic" 18.04 Desktop, installed directly on a PC.

**Comment by seemethere** [comment]
https://github.com/docker/docker-install/issues/72#issuecomment-385100450

**Comment by jalmansor** [comment]
@seemethere considering we're talking about an LTS release, and the fact that it's been available for testing for awhile (beta 1, probably a good place to start, was released March 8th), I don't see why this couldn't have been added to the build pipeline to, I don't know, maybe get an idea of what build issues to expect so when it does go final you could _actually_ have a release ready? 

Docker is not the only company that fails at this, so please don't think this is personal. I'm just tired of seeing software companies that _could_ be prepared for important OS releases and aren't. The Android development community is all over upcoming releases as soon as the first test version is dropped. I know we can do better.

**Comment by seemethere** [comment]
@jalmansor We're releasing at the earliest we can release it within our own schedule.

The [PR to add Ubuntu Bionic](https://github.com/docker/docker-ce-packaging/pull/97) was put up on March 28th and has been in our nightly pipeline since the week after that.

If you absolutely cannot wait until next week for the release of `18.05.0-ce` then you can use the latest release candidate for that using:

```
curl -fsSL test.docker.com | sh
```

**Comment by mattayes** [comment]
@seemethere Thanks for the update! To confirm: Will this be available in the stable channel sometime in June (following the quarterly release schedule)?

**Comment by seemethere** [comment]
@mattayes Yes this will we be included in our next `stable` release `18.06.0-ce` which should be released sometime in the first half of June.

**Comment by docularxu** [comment]
@seemethere Even with "curl -fsSL test.docker.com | sh", I am still seeing dockerd service start failure:

  Process: 5093 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)

$ journalctl -xe 
 shows:

5月 04 22:47:08 docularxu-Precision-7520 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.service has begun starting up.
5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29.592148011+08:00" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir=/var/lib/docker error="error getting daemon root's parent mount: Could not find source mount of /var/lib/docker"
5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29.593964972+08:00" level=info msg="libcontainerd: started new docker-containerd process" pid=9028
5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29+08:00" level=info msg="starting containerd" module=containerd revision=773c489c9c1b21a6d78b5c538cd395416ec50f88 version=v1.0.3
5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29+08:00" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
5月 04 22:49:29 docularxu-Precision-7520 dockerd[9003]: time="2018-05-04T22:49:29+08:00" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1
5月 04 22:49:37 docularxu-Precision-7520 kernel: Bluetooth: hci0: last event is not cmd complete (0x0f)

**Comment by kfilimon** [comment]
@docularxu I was following steps on https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1 and just changed "stable" to "test" in 
`sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"`
That seems to be worked

**Comment by docularxu** [comment]
thanks @kfilimon 
I now have this version installed on my ubuntu 18.04.
$ sudo docker --version
Docker version 18.05.0-ce-rc1, build 33f00ce

Cheers.

**Comment by thaJeztah** [comment]
Looks like this is resolved, so let me go ahead and close, but feel free to comment after

**Comment by leslie-qiwa** [comment]
seems like I still get this error
```
curl -sSL https://get.docker.com | CHANNEL=stable bash                                            
# Executing docker install script, commit: 36b78b2                 
+ sh -c 'apt-get update -qq >/dev/null'                            
+ sh -c 'apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'                                                   
debconf: delaying package configuration, since apt-utils is not installed                                                              
+ sh -c 'curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null'                                     
Warning: apt-key output should not be parsed (stdout is not a terminal)                                                                
+ sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list'         
+ '[' ubuntu = debian ']'        
+ sh -c 'apt-get update -qq >/dev/null'                            
+ sh -c 'apt-get install -y -qq --no-install-recommends docker-ce >/dev/null'                                                          
E: Package 'docker-ce' has no installation candidate           
```

**Comment by leslie-qiwa** [comment]
This is stripped minimum docker file which can reproduce this issue.

```
FROM ubuntu:18.04                                                  

RUN apt-get update                                                 
RUN apt-get install -y curl                                        
RUN curl -sSL https://get.docker.com | CHANNEL=stable bash     
```

**Comment by leslie-qiwa** [comment]
After change `stable` to `test`, it works.

**Comment by sant123** [comment]
Sure @leslie-qiwa, this is because the `stable` version of docker for Ubuntu 18.04 doesn't exists yet ;) meanwhile you have to use the `test` version.

**Comment by leslie-qiwa** [comment]
@sant123 @thaJeztah Thanks for detail explanation. It is helpful.

**Comment by ogolovanov** [comment]
So, "edge" version of docker should be released in neardays, right?

Right now following source does not contain docker-ce:
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge

Thanks.

**Comment by thaJeztah** [comment]
oh, you're right, 18.05 GA was not out yet on edge, it will be available soon

**Comment by thedrow** [comment]
At the very least, you should build the latest stable Docker version for Ubuntu Bionic.
If anyone wants to set up a new Ubuntu Bionic server, they should not be forced to use the edge version.

**Comment by ashleysommer** [comment]
@thedrow 
Absolutely. They should do special once-off 18.03 stable build for Bionic ASAP, so people aren't forced to use Edge, or wait until 18.06 stable.

**Comment by leizhao4** [comment]
@thedrow Agreed. I just set up a Bionic server, and now I'm stuck. Have to choose between downgrading Ubuntu or installing Docker Edge.

**Comment by thedrow** [comment]
@thaJeztah ping?

**Comment by sant123** [comment]
![image](https://user-images.githubusercontent.com/7959437/40063337-bede86d6-5822-11e8-80fb-74650cbde94f.png)

Using `test` repository. This is temporary until `stable` version comes :grin:

**Comment by thaJeztah** [comment]
Package is available now in the edge channel ([18.04 and 18.05 are edge releases](https://docs.docker.com/install/#time-based-release-schedule)) https://download.docker.com/linux/ubuntu/dists/bionic/pool/edge/amd64/

**Comment by HaehnleinMar** [comment]
It's somehow sad how docker is failing at this. Just release a package in the stable channel already already.

**Comment by HaehnleinMar** [comment]
It would really make my life (and probably these of many more) way easier.

**Comment by Fmstrat** [comment]
> Not my call (sorry!). I asked for this to be reconsidered (adding new distros/distro-versions during the support cycle of a stable release), so perhaps in future.

@theJeztah I think this is the right solution moving forward. While LTS releases don't happen often, when they do new installs are sure to use them. Builds in edge/test probably could have been running since April 5th (final beta freeze), and then start testing the latest stable docker against the ubuntu release candidate on April 19th (final freeze) with a release shortly after their 26th release.

Understanding the team is extremely busy, It would be great if the docker team could consider a pathway similar to that for other release cycles on new distros. Thanks!

Source: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

**Comment by Zeka13** [comment]
reopen plz, still no stable

**Comment by mahnunchik** [comment]
Any news?

**Comment by Fmstrat** [comment]
@mahnunchik See: https://github.com/docker/for-linux/issues/290#issuecomment-385390118 Seems that post gets updated, though it hasn't been since Apr 30.

**Comment by Fmstrat** [comment]
Btw, I've got [page-check](https://github.com/Fmstrat/page-check) running on the stable folder, so I'll put a comment here once I see the release (if no one from the docker team does).

**Comment by r3h0** [comment]
Thanks @Fmstrat! I've been checking manually most days and getting pretty sick of it. I'm waiting to upgrade to 18.04, only hang up is Docker.

**Comment by mahnunchik** [comment]
@r3h0 The same! I'm waiting for the upgrade to Ubuntu 18.04 on my desktop to have colored system wide emoji! Only Docker blocks me 😉

**Comment by Fmstrat** [comment]
It's actually easy to do without waiting. After adding the docker-ce repository, and before running `apt-get update`, edit `/etc/apt/sources.list` and change:

```
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```
to
```
deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable
```

Then, when the release occurs, change it back.

**Comment by leizhao4** [comment]
@Fmstrat That's what I'm doing right now, too. I just don't understand why 18.03 stable build cannot be released to Bionic repository. If we are able to run the Artful build on Bionic, they must be compatible. Then, why not just release it to Bionic, like other packages do?

**Comment by Fmstrat** [comment]
@leizhao4 Testing. Just because we haven't run into problems in bionic, doesn't mean some obscure container won't crash the whole system. It's best practice not to create a stable release until all test cases have been completed, and I'm sure the Docker team has 1K things on their plate so back-porting the test isn't in the cards. It seems they're already looking at ways to handle big OS releases in the future, though, so that's good!

**Comment by hackel** [comment]
Pretty pathetic this *still* isn't available for the current, stable, LTS release of Ubuntu, 2 months after its release.  You do realize that you can package previous versions of Docker for newer distributions, right?  It's not like you have to change your own product release schedule.  The excuses in this thread are ridiculous, especially coming from a commercial company that actually is expecting people to pay for their product!  Even your paying customers can't install docker on the current version of Ubuntu!

To add insult to injury, your snap release is still way behind at 17.06!  Come on...  If you would focus on that, then you wouldn't even need to concern yourself with which particular version of a distribution the host is running.  It would just work on pretty much all modern Linux distributions.

**Comment by pisymbol** [comment]
What is the current status of docker on 18.04LTS? I am running into an issue with the nightly test build.

**Comment by GADNT** [comment]
I'm also interested about this guys.

**Comment by seemethere** [comment]
@pisymbol if you're having issues with Docker CE nightly builds on 18.04 then feel free to submit an issue to this repository!

**Comment by pisymbol** [comment]
@seemethere Alright. I think it was alrighty files: docker build was failing with a permissions denied on some copy operation if that rings any bells? I downgraded to artful and that does indeed work for me.

**Comment by ddugovic** [comment]
I am grateful for the Docker team's thoughtful responses and excited Docker CE is scheduled to release this month.

**Comment by atrauzzi** [comment]
Wait - what?  Docker isn't ready and released the day a new Ubuntu release comes out?

What's up with this guys?

**Comment by shiquanwang** [comment]
It's a long wait. And nvidia-docker2 is waiting for a stable docker-ce to be ready for Ubuntu 18.04.

**Comment by HaehnleinMar** [comment]
![waiting...](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

**Comment by rajshiv169** [comment]
$ sudo apt update
$ sudo apt install apt-transport-https ca-certificates curl software-properties-common
$ sudo gedit /etc/apt/sources.list.d/docker.list
After this a notepad opens add following as per your requirements

deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
EDGE:
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge
NIGHTLY:
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic nightl

$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$ sudo apt update
$ sudo apt install docker.io

And using above commands i am able to install docker in my pc.

**Comment by ddugovic** [comment]
Strange, [Docker Docs](https://docs.docker.com/install/linux/docker-ce/ubuntu/) specifically mention uninstalling `docker.io`.

**Comment by rajshiv169** [comment]
But it worked :)

**Comment by mvandewouw** [comment]
docker.io is coming from the ubuntu repo's, not docker ones.
`
aaa@aaa:~$ sudo apt-cache policy docker.io
docker.io:
  Installed: (none)
  Candidate: 17.12.1-0ubuntu1
  Version table:
     17.12.1-0ubuntu1 500
        500 http://nl.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status`

**Comment by witek1902** [comment]
https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1
Change "stable" repository to "edge" and works fine.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

$ docker --version
Docker version 18.05.0-ce, build f150324

**Comment by TaakoMagnusen** [comment]
When will docker-ce 18.06 stable come out? 

I need this because i need to install nvidia-docker2 on my ubuntu 18.04 server i just set up. 
nvidia-docker2 requires stable docker-ce

**Comment by crapthings** [comment]
@witek1902 it works after change stable to edge

```
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

**Comment by shiquanwang** [comment]
It's 2018-06-20. Calling for 18.06 stable for Bionic.

**Comment by Fmstrat** [comment]
As per https://github.com/Fmstrat/page-check 18.03 is in stable now.

https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

**Comment by seemethere** [comment]
Awesome @Fmstrat, wasn't quite ready to announce it but I guess I might as well now.

We've gotten clearance to release `18.03.1-ce` for Ubuntu Bionic!

To install you can now use:

```
$ curl -fsSL get.docker.com | CHANNEL=stable sh
```

Thank you everyone for your patience!

**Comment by Fmstrat** [comment]
@seemethere Oops, sorry about that!

**Comment by pisymbol** [comment]
Is this package different from the artful one in any way? I installed 18.03-1.ce from the artful stable repo.

**Comment by geerlingguy** [comment]
Works in my testing, thanks!

**Comment by seemethere** [comment]
@pisymbol they should be pretty much the same. If you find any issues please let us know.

**Comment by pisymbol** [comment]
@seemethere Gotcha. Will do and thanks!

**Comment by HaehnleinMar** [comment]
![finally](https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif)

**Comment by flx42** [comment]
Any reason why the package naming changed **again** ?
xenial is `18.03.1~ce-0~ubuntu`, bionic is `18.03.1~ce~3-0~ubuntu`

**Comment by seemethere** [comment]
Hey everyone since this issue has been resolved going to lock this conversation!

If there are any other issues with Docker CE for Ubuntu Bionic feel free to post your issue to https://github.com/docker/for-linux
