### ISSUE TITLE
YUM - Forbidden error

### ISSUE THREAD

**Issue by GasimGasimzada** [docker/for-linux#298]
* [x] This is a bug report
* [ ] This is a feature request
* [x ] I searched existing issues before opening this one

### Expected behavior

Install Docker Community edition

### Actual behavior

Keep getting 403. Accessing the URL from browser also gives error:

https://download.docker.com/linux/centos/7/x86_64/stable/repodata/fd96365bf91f4b2f5a64d96cfc81ff6dfa46f46436902f08ed652a33db584b61-primary.sqlite.bz2

### Steps to reproduce the behavior

```
# yum install -y yum-utils device-mapper-persistent-data  lvm2
# yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
# yum install docker-ce
```

**Output of `docker version`:**

```
No docker for output
```

**Output of `docker info`:**

```
No docker for output
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

CentOS Linux release 7.4.1708

**Comment by seemethere** [comment]
Looking into this right now, had an issue with a build this morning and we're working on fixing this right now.

**Comment by seemethere** [comment]
Should be fixed now, closing this.

**Comment by GasimGasimzada** [comment]
thanks!
Gasim Gasimzada
e: me@gasim.xyz
p: +99450 395 72 79

**Comment by andrewhsu** [comment]
Verified repos are back up:
```
$ docker run --rm -it centos:7
[root@7e62ed6aa4dd /]# curl -fsSL get.docker.com | bash
# Executing docker install script, commit: 36b78b2
...
```
