### ISSUE TITLE
Docker for Centos - Install Instructions Causing Conflicts - 2018 update

### ISSUE THREAD

**Issue by kc0olm** [docker/for-linux#299]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This is a continuation of the thread that was closed in 2017.  There are no updates for 2018, with the new Docker packages.

Specifically, I am having the same issue with docker-ce.x86_64 0:18.03.1.ce-1.el7.centos

[root@oneWEXLinux741 .vnc]# yum install yum install docker-ce-18.03.1.ce-1.el7.centos
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
Package yum-3.4.3-154.el7.noarch already installed and latest version
No package install available.
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:18.03.1.ce-1.el7.centos will be installed
--> Processing Dependency: pigz for package: docker-ce-18.03.1.ce-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: pigz
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Tried --skip-broken:

yum install yum install docker-ce-18.03.1.ce-1.el7.centos --skip-broken
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
Package yum-3.4.3-154.el7.noarch already installed and latest version
No package install available.
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:18.03.1.ce-1.el7.centos will be installed
--> Processing Dependency: pigz for package: docker-ce-18.03.1.ce-1.el7.centos.x86_64

Packages skipped because of dependency problems:
    docker-ce-18.03.1.ce-1.el7.centos.x86_64 from docker-ce-edge

Can't find "pigz" anywhere

**Comment by kc0olm** [comment]
I was able to install it by actually doing what the error says: need to install pigz.  I suppose there is a centOS repo I could add, but I just installed from the rpm:

yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/pigz-2.3.3-1.el7.centos.x86_64.rpm

**Comment by thaJeztah** [comment]
What version of CentOS 7 are you running?

**Comment by mihai-sysbio** [comment]
Same on Red Hat Enterprise Linux Server release 7.5 (Maipo).

**Comment by bhavdeep** [comment]
The above step of installing pigz helped me to resolve the problem.
Below I am listing steps to install docker-ce on RHEL.

sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum makecache fast
To avoid error “Requires: container-selinux >= 2.9” Run following command
         sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm
To avoid error “libtool-ltdl-2.4.2-22.el7_3.x8 FAILED” Run following command
         yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/libtool-ltdl-2.4.2-22.el7_3.x86_64.rpm
To avoid Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)     Requires: pigz
Run:  
    yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/pigz-2.3.3-1.el7.centos.x86_64.rpm
sudo yum -y install docker-ce
Can test the docker running with command: sudo systemctl start docker

**Comment by thaJeztah** [comment]
I opened a PR to remove it as a hard dependency for CentOS packages; https://github.com/docker/docker-ce-packaging/pull/110

**Comment by ksummersill2** [comment]
@bhavdeep Thanks for posting the steps. Awsome work!

**Comment by hendrikhh** [comment]
Currently auf have problem with the installation again.
Error when installing docker-ce:

Error: Package: selinux-policy-3.13.1-229.el7_6.6.noarch (centos7-x86_64-updates)
           Requires: libsemanage >= 2.5-13
           Installed: libsemanage-2.5-11.el7.x86_64 (@centos7-x86_64)
               libsemanage = 2.5-11.el7
           Available: libsemanage-2.5-8.el7.i686 (centos7-x86_64)
               libsemanage = 2.5-8.el7
Error: Package: selinux-policy-targeted-3.13.1-229.el7_6.6.noarch (centos7-x86_64-updates)
           Requires: policycoreutils >= 2.5-24
           Removing: policycoreutils-2.5-17.1.el7.x86_64 (@anaconda)
               policycoreutils = 2.5-17.1.el7
           Updated By: policycoreutils-2.5-22.el7.x86_64 (centos7-x86_64)
               policycoreutils = 2.5-22.el7
Error: Package: selinux-policy-3.13.1-229.el7_6.6.noarch (centos7-x86_64-updates)
           Requires: policycoreutils >= 2.5-24
           Removing: policycoreutils-2.5-17.1.el7.x86_64 (@anaconda)
               policycoreutils = 2.5-17.1.el7
           Updated By: policycoreutils-2.5-22.el7.x86_64 (centos7-x86_64)
               policycoreutils = 2.5-22.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


I tried installing the latest version of container-selinux but there is the exact same error.
I can't even find the needed libsemanage  version (libsemanage >= 2.5-13)

yum list libsemanage --showduplicates | sort -r
This system is receiving updates from RHN Classic or Red Hat Satellite.
Loading mirror speeds from cached hostfile
Loaded plugins: fastestmirror, langpacks, rhnplugin
libsemanage.x86_64                  2.5-8.el7                    centos7-x86_64
libsemanage.x86_64                  2.5-11.el7                   centos7-x86_64
libsemanage.x86_64                  2.5-11.el7                   @centos7-x86_64
libsemanage.i686                    2.5-8.el7                    centos7-x86_64
libsemanage.i686                    2.5-11.el7                   centos7-x86_64
Installed Packages
 * extras: centos.schlundtech.de
Available Packages
