### ISSUE TITLE
error pulling image configuration (i/o timeout)

### ISSUE THREAD

**Issue by solo-framework** [docker/for-linux#3]
Docker can't pull image.

### Expected behavior
**$sudo docker run hello-world**
....
Hello from Docker!
This message shows that your installation appears to be working correctly.

..smth success output...

### Actual behavior

**$sudo docker run hello-world**
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
78445dd45222: Pulling fs layer 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/48/48b5124b2768d2b917edcb640435044a97967015485e812545546cbed5cf0233/data?Expires=1496063122&Signature=cOT6tTlp1KTte5Xy4hKRW3UQVXwAPA-yiBdJ5HLp8~jaBGPnd4rlRpOgJt4-Gqpf3vHjmcbOdl3FxUjPDDhNLmt1a~z6sUaC-xwUZuuCIFiZKlHNA9Jl-K-sJyqKli3xDFm8O0iDXZwnv1dJTxpd61Kksaxavb~dhXarDW31xnE_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 127.0.1.1:53: read udp 127.0.0.1:40048->127.0.1.1:53: i/o timeout.
See 'docker run --help'.

### Information
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

Linux afi-elite 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64
 Experimental: false

### Steps to reproduce the behavior

  1. Install docker 
  2. run `sudo docker run hello-world`

**Comment by magroski** [comment]
+1 Still can't find a fix

**Comment by cpuguy83** [comment]
`dial tcp: lookup dseasb33srnrn.cloudfront.net on 127.0.1.1:53: read udp 127.0.0.1:40048->127.0.1.1:53: i/o timeout.`

This seems to indicate that the configured resolver (127.0.0.1) is not responding.

**Comment by schollii** [comment]
@cafruv solution did not work for me. What did work is
```
service docker stop
service docker start
```
then the image built fine

**Comment by tnsilver** [comment]
it's timed out on port 40048. It's likely ubuntu firewall is blocking it. try: `sudo service ufw stop` to disable the firewall and retry.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I don't think there's anything actionable.
