### ISSUE TITLE
Update copy in docs for Docker for ubuntu, centos, rhel, oracle linux, sles

### ISSUE THREAD

**Issue by annieshin** [docker/for-linux#30]
- Docs for Docker for ubuntu, rhel, centos, oracle linux, and sles say "Go to https://store.docker.com/?overlay=subscriptions." Although that link still works, it should say https://store.docker.com/my-content instead
- "Choose Get Details / Setup Instructions within the Docker Enterprise Edition for Ubuntu section." should be changed since the button to click is "Setup" on the my-content page on Store

**Comment by thaJeztah** [comment]
This was fixed
