### ISSUE TITLE
Is there a way to make two commands(like ADD COPY RUN...) in Dokcerfile build into one layer

### ISSUE THREAD

**Issue by savagecm** [docker/for-linux#303]
* [] This is a bug report
* [x] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
For example: 

**FROM alpine:3.4     
COPY xxx.tar.gz     
RUN tar -zxvf xxx.tar.gz &&rm -rf xxx.tar.gz     
...**

we expect that xxx.tar.gz will not show in the docker image. But actually it is in the image......

As we know every command is one layer. 
int the "COPY" layer, it save the xxx.tar.gz.
In the "RUN" layer it mark the xxx.tar.gz with .wh.xxx.tar.gz that indicate to remove xxx.tar.gz. 
This makes the image contain xxx.tar.gz and make the image bigger, but actually we do not need xxx.tar.gz.

So is there a way to make "COPY" and "RUN" in one layer?

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
No. However you can use the "ADD" keyword instead which will expand the archive instead of literally copying the archive.

You can also use multi-stage builds to have a clean final image.

Closing since this isn't really an issue, but feel free to discuss. Thanks!

**Comment by savagecm** [comment]
This is just an example....
if we want to use 
**FROM alpine:3.4
COPY xxx.rpm
RUN rpm -ivh xxx.rpm&&rm -rf xxx.rpm**

This is the problem we met....

**Comment by savagecm** [comment]
Can we have a command like "CPOYandRUN"?

**Comment by cpuguy83** [comment]
Really I think you want to mount the build context into the build instance
rather than copying.
There's a proposal for this on the Moby repo from @tonistigii
