### ISSUE TITLE
docker stuck in activating

### ISSUE THREAD

**Issue by kolorafa** [docker/for-linux#310]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
start :) 

### Actual behavior

restart doesn't help :)

- systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (start) since Fri 2018-05-18 21:04:38 CEST; 6min ago
     Docs: https://docs.docker.com
 Main PID: 1522 (dockerd)
    Tasks: 48
   CGroup: /system.slice/docker.service
           ├─1522 /usr/bin/dockerd -H fd://
           └─1753 docker-containerd --config /var/run/docker/containerd/containerd.toml

maj 18 21:04:54 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:54.883280459+02:00" level=error msg="Failed to load container mount 34aad0829aabe859e97cb7676398b57f7bd4c494e66883599b6a0661c8ef6350: mount does not exist"
maj 18 21:04:54 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:54.951134176+02:00" level=error msg="Failed to load container mount 587f69f380bd7715034e86ff686ec818ae3531f1f88407361a243f8d2e98e455: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.063774327+02:00" level=error msg="Failed to load container mount 8a7458c5cee9cf70303298953bf0ff4572287927f8a5640327a2308a314b0c66: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.260677132+02:00" level=error msg="Failed to load container mount ce7ed01dd22d34520dde9d6a5f4bae60604be36f2b66e61221933b39d70dd874: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.281281709+02:00" level=error msg="Failed to load container mount ce960ca3bfa1d23917b9a8f011094d13621004f7cb3d0b7e5081e3cd03db2644: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.286426680+02:00" level=error msg="Failed to load container mount ced4190183abc42adb99396edb552f4eadad9d1401358b74be571a25cb43860a: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.376400692+02:00" level=error msg="Failed to load container mount d112a35a1c93ff13223a11a2310bca2ba9b9c8b6523ede4c487abfe46beddd3e: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.530455272+02:00" level=error msg="Failed to load container mount d24cc2b8e39a503f7eb803f8b8dcd248e4c9181cdcf7580a9f416e638eed362c: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.586753102+02:00" level=error msg="Failed to load container mount ed2538227a4a4f7269f7fc01d8f5cc7bd416e694627ad5523c715c422c04ce37: mount does not exist"
maj 18 21:04:55 kolorafa-server dockerd[1522]: time="2018-05-18T21:04:55.629913424+02:00" level=error msg="Failed to load container mount faeda4e39545277cf7a7fa8f0d8a9d6162ffaa28af0dbb17613faef9eaa38657: mount does not exist"

### Steps to reproduce the behavior

Don't know how to reproduce, but know how I ended into this error.
On ubuntu 17.10 running root (/) on BTRFS i was running docker.
After not using it for anything for some time, I tried to run one more container.
Added container, added additional IP to host (ip addr add ..) and after a while whole IO freezed.
Hard reset, tried second time, IO freezed but this time got dmesg -w running ( https://pastebin.com/90FX51zF ).
I got simmilar freeze on Arch few months ago so I assume buggy kernel so i did not try third time insted done ubuntu upgrade from 17.10 to 18.04.

After that after a reboot did try "docker" and nothing .... i assumed it happend again - btrfs freeze, but somehow now, no freeze, everything working fine except for docker that is tuck at activating.

I will probably somehow remove docker and all it's files/subvolumes from btrfs and reinstall docker, as i don't have anything on it, it was moved to different box month ago, but If that would happen on production it would be good to know how to fix/bypass it :) Maybe running docker manually with debug or something is a good start to debug it, but how? :)

**Output of `docker version`:**

doesn't run, freezes forever
docker.io/bionic,now 17.12.1-0ubuntu1 amd64 [installed]

**Output of `docker info`:**

doesn't run, freezes forever

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Physical box, Ubuntu 18.04
Intel(R) Xeon(R) CPU  5140, 12GB ram, BTRFS on / and /home, ext3 on /boot, used only for some random stuff/learning at home as a secondary pc/server :)
Docker running also on btrfs for testing purposes (both btrfs and docker on btrfs).

**Comment by mapatel7** [comment]
I have the same issue.
