### ISSUE TITLE
Any plans to self-upgrade command?

### ISSUE THREAD

**Issue by pedrofurtado** [docker/for-linux#313]
It will be great if docker have a built-in command like `docker self-upgrade`, to upgrade the version of Docker CE in our machines.

Any plans to provide a `self-upgrade` command (or something like this)?

I'm using Docker CE 18.03 on Ubuntu 16.04 LTS, and I want to upgrade to the Docker CE 18.05.

**Comment by seemethere** [comment]
You could use your package manager to facilitate the update. 

```
$ sudo apt-get update
$ sudo apt-get upgrade docker-install
```

**Comment by pedrofurtado** [comment]
@seemethere Is these commands the official way to upgrade the version of Docker?

**Comment by seemethere** [comment]
@pedrofurtado Yes that is the official way to upgrade Docker per our documentation for [Ubuntu 16.04](https://docs.docker.com/install/linux/docker-ce/ubuntu/#upgrade-docker-ce).

If you're interested in using `edge` releases like `18.05.0-ce` you are going to need to change the channel you are using in `/etc/apt/sources.list.d/docker.list` from `stable` to `edge`.
