### ISSUE TITLE
[Doc] The recommended storage drivers Centos is devicemapper or overlay2?

### ISSUE THREAD

**Issue by wpeng102** [docker/for-linux#323]
In https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-ee-and-cs-engine, the Recommended storage drivers on CentOS is `devicemapper, vfs` but in https://docs.docker.com/install/linux/docker-ce/centos/#prerequisites, it says `The overlay2 storage driver is recommended`. 
Which  storage drivers should I use in production environment?

**Comment by ahilmathew** [comment]
According to the [CIS Benchmark](https://www.cisecurity.org/benchmark/docker/) , never use the aufs storage driver. Rest everything should be fine. By default Docker CE now uses overlay2 and overlay2 drivers can be used in production environment.

**Comment by wpeng102** [comment]
@ahilmathew  Thanks.  I think we can close this issue.
