### ISSUE TITLE
Calico v3.0.5 unit TCs failing on s390x-RHEL 7.5

### ISSUE THREAD

**Issue by chakravarthy392** [docker/for-linux#332]
Observed 45 TC failures on s390x-RHEL 7.5 compared to on X86_64 when I execute Calico-3.0.5 unit test cases.

### Expected behavior
On Intel, 9 TCs skipped out of 87, remaining all are passing.

### Actual behavior
Few errors and failures are observed on s390x and many TCs execution got skipped.
[Observed the same behavior for v3.0.5 & v3.0.7 with both docker-17.05 and 18.03].

### Steps to reproduce the behavior
        cd $GOPATH/src/github.com/projectcalico/calico/calico_node
        ARCH=s390x make st 

### Context
By checking the logs , I thought the failures are due to old version of docker-17 , built and ran TCs again with latest version of  [docker-18.03-ce](https://download.docker.com/linux/static/stable/s390x/) but getting the same failures as before.

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.2
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:30 2018
 OS/Arch:      linux/s390x
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:18:15 2018
  OS/Arch:      linux/s390x
  Experimental: false

```

**Output of `docker info`:**

```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 109
Server Version: 18.03.1-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.s390x
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: s390x
CPUs: 4
Total Memory: 15.55GiB
Name: ecos0020.pok.stglabs.ibm.com
ID: NGJW:KI7Y:KDKL:CZA5:UTOA:JNLU:M4OJ:DIAI:SUWR:73UB:THBB:62B3
Docker Root Dir: /scratch/ecos0020/docker1june
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Your Environment**

- Calico version : v3.0.5

- Operating System and version: S390x-RHEL7.5

**Logs**
Result of `make st`
[RHEL7.5_ecos0020_docker18.03-ce.txt](https://github.com/docker/for-linux/files/2074822/RHEL7.5_ecos0020_docker18.03-ce.txt)

Below logs were produced by running an individual test case `test_empty_policy_for_forward_traffic` on both architectures with same docker version.
[S390X_empty_policy_for_forward_traffic.log.txt](https://github.com/docker/for-linux/files/2074802/S390X_empty_policy_for_forward_traffic.log.txt)
[X86_empty_policy_for_forward_traffic..txt](https://github.com/docker/for-linux/files/2074803/X86_empty_policy_for_forward_traffic.txt)

**Comment by seemethere** [comment]
Is this an issue with Docker CE itself or Calico?

Also we do not officially support RHEL 7.5 for Docker CE, are these problems also present on another OS?

**Comment by chakravarthy392** [comment]
Please don't mind @seemethere , those failures are resulted due to my firewall settings.
Just want to confirm one thing, [docker-ce static binaries](https://download.docker.com/linux/static/stable/s390x/) do not support RHEL 7.5 only or any other distributions also ?

**Comment by seemethere** [comment]
No we do not officially support RHEL 7.5 for Docker CE. 

We do however support RHEL 7.5 for Docker EE!
