### ISSUE TITLE
403 on curl -I https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz

### ISSUE THREAD

**Issue by royletron** [docker/for-linux#338]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

```curl -I "https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz"```

Should give us a 200 and the tar

### Actual behavior

```curl -I "https://get.docker.com/builds/Linux/x86_64/docker-1.13.0.tgz"```

Gives us 403 forbidden. I have tried this locally, on a different network and even on a VM from outside of the building. We are based in the UK

### Steps to reproduce the behavior

**Output of `docker version`:** 

N/A

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Virtual on Gcloud EU and locally in Oxford UK.

**Comment by thaJeztah** [comment]
Thanks for reporting! This should now be fixed :+1:
