### ISSUE TITLE
Docker mounts pre-existing single file as empty directory

### ISSUE THREAD

**Issue by jakewins** [docker/for-linux#344]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Mounting an existing single file as a volume should make that file available inside a container.

### Actual behavior

Docker creates an empty directory at the mount point.

### Steps to reproduce the behavior

    touch /tmp/asd
    docker run -v /tmp/asd:/asd ubuntu ls -ld /asd

Output:

    drwxr-xr-x 2 root root 40 Jun 18 17:22 /asd

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.23
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:20:43 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 45
 Running: 23
 Paused: 0
 Stopped: 22
Images: 21
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: N/A (expected: )
Security Options:
 seccomp
Kernel Version: 4.9.64
Operating System: Buildroot 2017.11
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.734GiB
Name: minikube
ID: THEP:I2T7:ELIY:3RGF:DKBR:VBEV:VZUP:WWL7:5FBH:ZEPU:GASN:EOW5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=kvm2
Experimental: false
Insecure Registries:
 10.96.0.0/12
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Tested on both OS X and Linux Mint with same results.

**Comment by vdemeester** [comment]
Hey @jakewins thanks for the report. I think when you did `touch /tmp/asd`, this was already a folder (and `touch` doesn't really care about that)

```sh
# no /tmp/asd file
λ ls -l /tmp/asd
ls: cannot access '/tmp/asd': No such file or director
λ touch /tmp/asd
λ docker run -v /tmp/asd:/asd --rm ubuntu ls -ld /asd
-rw-r--r-- 1 1000 users 0 Jun 19 07:56 /asd

# with an already existing folder
λ mkdir /tmp/asd
mkdir: created directory '/tmp/asd'
λ touch /tmp/asd
λ docker run -v /tmp/asd:/asd --rm ubuntu ls -ld /asd
drwxr-xr-x 2 1000 users 40 Jun 19 07:56 /asd
```

**Comment by jakewins** [comment]
@vdemeester hey, thanks for looking into this. I don't think this is correct though:

    ~ $ ls -ld /tmp/bla
    ls: cannot access '/tmp/bla': No such file or directory
    ~ 2 $ touch /tmp/bla
    ~ $ ls -ld /tmp/bla
    -rw-rw-r-- 1 jake jake 0 Jun 19 09:41 /tmp/bla
    ~ $ docker run -v /tmp/bla:/bla --rm ubuntu ls -ld /bla
    drwxr-xr-x 2 root root 40 Jun 19 14:42 /bla

I built docker from source yesterday - the moby github project, that is - to try to chase this a bit, but the HEAD version there does not have this issue on my machine. I assumed that was because it ends up with an older version of the docker frontend.

**Comment by jakewins** [comment]
Just had three coworkers on OS X run the following: 

    touch /tmp/bla
    ls -ld /tmp/bla
    docker run -v /tmp/bla:/bla --rm ubuntu ls -ld /bla

They got different results; two got the file mounted, one got a directory.

### docker version for coworker that got a directory

    Client:
     Version:      18.03.1-ce
     API version:  1.23
     Go version:   go1.9.5
     Git commit:   9ee9f40
     Built:        Thu Apr 26 07:13:02 2018
     OS/Arch:      darwin/amd64
     Experimental: false
     Orchestrator: swarm

    Server:
     Engine:
      Version:      17.12.1-ce
      API version:  1.35 (minimum version 1.12)
      Go version:   go1.9.4
      Git commit:   7390fc6
      Built:        Tue Feb 27 22:20:43 2018
      OS/Arch:      linux/amd64
      Experimental: false

### docker versions for the two coworkers that got a file

    Client:
     Version:      18.03.1-ce
     API version:  1.37
     Go version:   go1.9.5
     Git commit:   9ee9f40
     Built:        Thu Apr 26 07:17:38 2018
     OS/Arch:      linux/amd64
     Experimental: false
     Orchestrator: swarm

    Server:
     Engine:
      Version:      18.03.1-ce
      API version:  1.37 (minimum version 1.12)
      Go version:   go1.9.5
      Git commit:   9ee9f40
      Built:        Thu Apr 26 07:15:45 2018
      OS/Arch:      linux/amd64
      Experimental: false

    Client:
     Version:      18.05.0-ce
     API version:  1.37
     Go version:   go1.9.5
     Git commit:   f150324
     Built:        Wed May  9 22:12:05 2018
     OS/Arch:      darwin/amd64
     Experimental: false
     Orchestrator: swarm

    Server:
     Engine:
      Version:      18.05.0-ce
      API version:  1.37 (minimum version 1.12)
      Go version:   go1.10.1
      Git commit:   f150324
      Built:        Wed May  9 22:20:16 2018
      OS/Arch:      linux/amd64
      Experimental: true

**Comment by jakewins** [comment]
Hang on! We made a discovery in testing this out; it happens when we use minikubes docker env. If I open up a brand new, clean shell, then I get the correct behavior - but as soon as I run `minikube docker-env` I get directories:

    ~ $ docker run -v /tmp/bla:/bla --rm ubuntu ls -ld /bla
    -rw-rw-r-- 1 1000 1000 0 Jun 19 14:41 /bla
    ~ $ eval $(minikube docker-env)
    ~ $ docker run -v /tmp/bla:/bla --rm ubuntu ls -ld /bla
    drwxr-xr-x 2 root root 40 Jun 19 14:42 /bla

I'm not super familiar with minikubes docker-env; does that mean this should go on a separate issue tracker?

**Comment by jakewins** [comment]
Realizing docker-env from minikube is running a docker daemon inside a VM on the machine, which entirely explains this behavior - it's a bit much to expect docker to magically tunnel directories across the VM boundary, especially since as far as it knows it's on a physically different machine.. 

I'm inclined to just close this now, but pondering if it'd be worth noting somehow in the docs or something that the `-v` flags are not relative to the machine you are running `docker` on, but to the machine running the docker daemon?

**Comment by jakewins** [comment]
I'm gonna close this, I don't think this is dockers fault.

**Comment by thaJeztah** [comment]
Also note that If you're running Docker for Mac, and want to run kubernetes, you can now enable kubernetes in the Docker for Mac configuration panel; no need to install or run minikube
