### ISSUE TITLE
Dependency Issues docker-ce

### ISSUE THREAD

**Issue by Jaybomb** [docker/for-linux#346]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Docker is installed

### Actual behavior

```
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: libseccomp.so.2()(64bit)
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: libc.so.6(GLIBC_2.17)(64bit)
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: systemd-units
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: libseccomp >= 2.3
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: pigz
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: libsystemd.so.0()(64bit)
Error: Package: docker-ce-18.03.1.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2.9
```

### Steps to reproduce the behavior

Following steps from https://docs.docker.com/install/linux/docker-ce/centos/#set-up-the-repository 

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

VMware vCenter VM

`cat /etc/centos-release`
CentOS release 6.8 (Final)

`uname -a`
Linux 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Docker is only supported on Centos 7, and generally only tracks the current release (as CentOS is a rolling release).

**Comment by seemethere** [comment]
As @cpuguy83 already said we do not support CentOS 6.X, closing this.

**Comment by Jaybomb** [comment]
Dammit Jason read the Prerequisites!!
Cheers lads.
/J
