### ISSUE TITLE
driver.CreateEndpoint response are going to be lost. 

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [docker/for-linux#348]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Network driver response are going to be written to KV storage and assigned to container sandbox 
E.g. MacAddress from driver.CreateEndpoint should be assigned to container interface 

### Actual behavior
Network driver response are going to be lost, because n.getController().updateToStore(ep) performed before driver call CreateEndpoint.
e.g. MacAddress lost 

### Steps to reproduce the behavior
Use driver with CreateEndpoint response like this:
`Jun 22 09:52:10 host libnetwork-plugin[23217]: time="2018-06-22T09:52:10Z" level=info msg="CreateEndpoint response" JSON="{"Interface":{"Address":"","AddressIPv6":"","MacAddress":"EE:EE:EE:EE:EE:EE"}}"`

Look at MacAddress with 'docker inspect <continer_id> 
Look at MacAddress inside container 'ip a' etc. 

I had debugging code flow. At `(daemon *Daemon) connectToNetwork` method I always have incomplete data (no driver response included). Endpoint.Info() has priority on return data from KV storage, but data in storage is incomplete. 
This result in container creation with broken network config. 

Can see this bug only at docker-ce, seems because of this commit (missing at moby): 
https://github.com/docker/docker-ce/commit/eeeede3c5fb19289726b8b5a2481e17094302f48

**Output of `docker version`:**

```
docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:14:54 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:18:36 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge calico host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.13-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.68GiB
Name: host_here
ID: GUWI:3FBN:FM7T:35QK:FJJJ:VM7E:CJMD:EV5L:KDIU:W22T:DMXJ:KTZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 66
 System Time: 2018-06-22T09:58:24.492505617Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Cluster Store: etcd://<host_here>:2379
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
ping @ctelfer @abhi PTAL

**Comment by ctelfer** [comment]
Eventually libnetwork's changes get folded into docker-ce.  Moby just lags behind a bit.  Does your fix require changes to both libnetwork and moby or just libnetwork?  If the latter, just open up a PR there.  It will eventually get folded into docker-ce as well.

**Comment by CharlieR-o-o-t** [comment]
PR will affect only libnetwork. What version of libnetwork use docker-ce?

**Comment by thaJeztah** [comment]
You can find the commit that's used in the vendor.conf file; https://github.com/docker/docker-ce/blob/18.05/components/engine/vendor.conf#L35

**Comment by CharlieR-o-o-t** [comment]
Have no idea is there any automated merge from bump_18.03 to master :/
Created few pull requests to:
master: https://github.com/docker/libnetwork/pull/2205
bump_18.03: https://github.com/docker/libnetwork/pull/2206

**Comment by thaJeztah** [comment]
The bump 18.03 branch is used to cherry-pick fixes for 18.03.x patch releases; procedure is to merge to master first, and if a fix is decided on for backporting to a specific release, it's cherry-picked into the corresponding branch.

For patch releases, only critical / severe fixes are backported; other fixes will just follow the regular flow, and go out with the next release.


After the libnetwork pull-request is merged, the version used on moby master can be updated by opening a "vendor bump" pull request; updating the vendor.conf (and re-run the `vndr` tool), similar to this PR; https://github.com/moby/moby/pull/37252

**Comment by CharlieR-o-o-t** [comment]
@thaJeztah , `vndr` will bring about 30 commits (not mine) with bump request. + 
vendor/github.com/docker/distribution/context also will be updated (seems that some deps affect).

I'm not sure about format of commit description. Should I describe each separate commit in "includes", or describe just mine changes associated with bug? 
sorry, I'm new at this stuff, could you contact with me by email raskintech@gmail.com :)
Thank you

**Comment by thaJeztah** [comment]
Let me comment here (possibly others can benefit from it as well :smile:)

@CharlieR-o-o-t it's ok if a vendor brings in other changes (that's often the case); what I usually do is:

1. Create a compare link (`https://github.com/docker/libnetwork/compare/<current-commit>...<new-commit>`), and include that in the PR description on GitHub (this allows reviewers to get some context for changes that are included in the bump, even if some of those commits don't affect the vendored code)
2. Go through the list of commits/PR's that are included, and identify which changes I consider "relevant"; for example, changes in "test" code or documentation in libnetwork are not really relevant, so I don't include those in my commit message (and description on GitHub); for the other changes that _are_ (or _may be_) relevant, I create a bullet-list

Here's another example of a libnetwork bump; https://github.com/moby/moby/pull/37209. As you can see in that PR, I only listed _two_ PR's as "relevant changes", but there's a total of 26 commits in that bump, most of them were not relevant (some typo fixes, some linting issues, some changes to the makefile), so not included in the PR description.
