### ISSUE TITLE
docker import python3-dev-docker.tar.gz results in no valid host

### ISSUE THREAD

**Issue by bhr83** [docker/for-linux#355]
I am facing following error while trying to pull the docker image.

sudo docker import python3-dev-docker.tar.gz python3.6.3:latest
Downloading from http://python3-dev-docker.tar.gz
FATA[0008] Get http://python3-dev-docker.tar.gz: dial tcp: lookup python3-dev-docker.tar.gz: no such host

Please suggest me to fix the issue. Thanks in Advance.

**Comment by thaJeztah** [comment]
does it work if you specify the full path to the archive? 

https://docs.docker.com/engine/reference/commandline/import/#examples

**Comment by bhr83** [comment]
I am new to docker and I don't have full path. Could you please guide me how to get full path?

**Comment by seemethere** [comment]
@bhr83 do you have the file downloaded to your local machine?

**Comment by bhr83** [comment]
I don't have in my local machine.

**Comment by seemethere** [comment]
Then you will need to provide the full URL for where you can download that file.

**Comment by thaJeztah** [comment]
If your intent is to get the python image, it's better to pull the image, instead of creating your own from an archive; you can find what versions are available on hub; https://hub.docker.com/_/python/

But to get the latest 3.6 version of the official python image, you can run:

    docker pull python:3.6

**Comment by seemethere** [comment]
Going to close this, let us know if you have any other issues @bhr83!
