### ISSUE TITLE
Docker add owner is not working (also with --chown)

### ISSUE THREAD

**Issue by jica** [docker/for-linux#360]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
When adding a file / directory to the container with ADD command, it should be owned by user:group 1000:1000.

### Actual behavior
Container with files owned by user:group 1001:1001
Also when executing with ADD --chown=1000:1000

### Steps to reproduce the behavior

Dockerfile content:
```
FROM debian:stretch
RUN useradd -s /bin/nologin -m myuser
ENV USER_HOME /home/myuser
WORKDIR $USER_HOME
ADD resources/jre-7u80-linux-x64.tar.gz /usr/lib/
ENV JAVA_HOME /usr/lib/jre1.7.0_80
ADD --chown=1000:1000 resources/myapp.tgz ./
USER myuser:myuser
ENTRYPOINT [ "myapp/bin/startup.sh" ]
```
myapp.tgz is created on the host **with user 1001:1001**
Execute `docker build -t test .` to build de image (done with user 1001 and with root)
Execute `docker run -ti test bash`, and on the container, ls -al

Result:
myapp folder is owned by 1001:1001
myuser has uid=1000 gid=1000

/usr/lib/jre1.7.0_80 is **correctly owned** by myuser:myuser

I have changed (on the host) the owner of myapp.tgz to 1000:1000 with the same result
I need to create the tgz file with user 1000:1000 to get the expected behavior
Workaround: execute `RUN chown -R 1000:1000 myapp` after the ADD

**Output of `docker version`:**

```
Docker version 18.03.1-ce, build 9ee9f40
```

**Output of `docker info`:**

```
(paste your output here)
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 140
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-24-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52GiB
Name: jicenteno-pc
ID: 5IAI:AO5P:7W2Y:X72R:U5PM:EKWI:K3NX:Q2WH:JHOP:PY6J:SSQH:FFRJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by josecelano** [comment]
Hi, I'm having the same problem and here you can see what it seems to be a good explanation:

https://github.com/moby/moby/issues/35525#issuecomment-413947158

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
