### ISSUE TITLE
Resolve: "HTTPS Error 403 - Forbidden" - (رفع مشکل تحریم مخازن داکر و خطای)

### ISSUE THREAD

**Issue by NabiKAZ** [docker/for-linux#363]
<div dir=rtl>
رفع مشکل تحریم مخازن داکر و خطای HTTPS Error 403 - Forbidden
</div>

Look at the following errors:

```BASH
[root@localhost ~]# sudo yum-config-manager \
>     --add-repo \
>     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] HTTPS Error 403 - Forbidden
```

```BASH
[root@localhost ~]# lynx https://download.docker.com/linux/centos/docker-ce.repo
403 ERROR
The request could not be satisfied.
The Amazon CloudFront distribution is configured to block access from your country. 
```

This is due to Amazon CloudFront's unilateral and unjust sanctions and sanctions.
If you've encountered these errors too, I suggest using the "[SHEKAN](https://shecan.ir/)" solution and service below:

Use this DNS: `94.232.174.194` _(This is tested for iranian country users)_

For example for CentOS, use these:

```BASH
[root@localhost ~]# cat /etc/resolv.conf > resolv.conf.old
[root@localhost ~]# echo "nameserver 94.232.174.194" > /etc/resolv.conf
```

And try again to run command, and the errors will not be seen.
```BASH
[root@localhost ~]# sudo yum-config-manager \
>     --add-repo \
>     https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
```

#article

**Comment by AhmadVatani** [comment]
Not working for me on ubuntu!

**Comment by NabiKAZ** [comment]
@AhmadVatani Do you sure for well working `shecan` service?

**Comment by AhmadVatani** [comment]
@NabiKAZ how should I test it?
Fix my problem with `sshuttle` to foreign server!

**Comment by NabiKAZ** [comment]
@AhmadVatani You can referee to the site: https://shecan.ir/ for manual.

**Comment by Burtog** [comment]
Thanks a lot.. am using ubuntu and it's work for me.
could u explain what it does?  this two command

**Comment by NabiKAZ** [comment]
@Burtog First just for backup old config file, and second just write new IP in the `resolve` file for set new DNS.

**Comment by hosseinnedaee** [comment]
It just worked for me in ubuntu 18.04

**Comment by husen-hn** [comment]
I think Gradle save that you in error 403
so, if u tested it on ur fucking country IP then delete gradle file and run it with proxy.
