### ISSUE TITLE
* connect to 10.0.0.129 port 9080 failed: No route to host

### ISSUE THREAD

**Issue by a1exus** [docker/for-linux#366]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
```
root@2824cd852473:/# curl -v stack_app_1:9080
* Rebuilt URL to: stack_app_1:9080/
*   Trying 10.0.0.140...
* TCP_NODELAY set
* Connected to stack_app_1 (10.0.0.140) port 9080 (#0)
```
### Actual behavior
```
root@2824cd852473:/# curl -v stack_app_1:9080
* Rebuilt URL to: stack_app_1:9080/
*   Trying 10.0.0.129...
* TCP_NODELAY set
* connect to 10.0.0.129 port 9080 failed: No route to host
*   Trying 10.0.0.134...
* TCP_NODELAY set
* connect to 10.0.0.134 port 9080 failed: No route to host
*   Trying 10.0.0.125...
* TCP_NODELAY set
* connect to 10.0.0.125 port 9080 failed: No route to host
*   Trying 10.0.0.246...
* TCP_NODELAY set
* connect to 10.0.0.246 port 9080 failed: No route to host
*   Trying 10.0.0.248...
* TCP_NODELAY set
* connect to 10.0.0.248 port 9080 failed: No route to host
*   Trying 10.0.0.140...
* TCP_NODELAY set
* Connected to stack_app_1 (10.0.0.140) port 9080 (#0)
```
### Steps to reproduce the behavior

**Output of `docker version`:**

```
# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:14 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:24 2018
  OS/Arch:      linux/amd64
  Experimental: false
# 
```

**Output of `docker info`:**

```
# docker info 
Containers: 49
 Running: 48
 Paused: 0
 Stopped: 1
Images: 486
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: s3xcicdmrx4h5qs13l25dceic
 Is Manager: true
 ClusterID: tn4rgfreuoz6kjfynjcntdp3n
 Managers: 18
 Nodes: 18
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.142.0.6
 Manager Addresses:
  10.142.0.10:2377
  10.142.0.11:2377
  10.142.0.12:2377
  10.142.0.13:2377
  10.142.0.14:2377
  10.142.0.15:2377
  10.142.0.16:2377
  10.142.0.17:2377
  10.142.0.18:2377
  10.142.0.19:2377
  10.142.0.2:2377
  10.142.0.3:2377
  10.142.0.4:2377
  10.142.0.5:2377
  10.142.0.6:2377
  10.142.0.7:2377
  10.142.0.8:2377
  10.142.0.9:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 58.99GiB
Name: X
ID: 2AXT:IYZF:23GB:VMWW:KDFD:TUYF:VYYU:6CYF:PWRL:KETT:QE5A:Q55Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
# 
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

GCP

**Comment by cpuguy83** [comment]
Can you provide more detail?
What are you running? How is it configured?

Side note, why do you have so many managers? It is not recommended to have more than 7 which would allow up to 3 manager node failures. Also the fewer managers there are the faster the cluster will operate (because it's faster to make changes with smaller number of managers).

**Comment by a1exus** [comment]
I apologize for not including all necessary details at the first place...

A step back and my issue overall:

I have haproxy service that runs on one of the docker nodes which uses Go app backend (listens on port 0.0.0.0:9080) and through haproxy's stats, I noticed one of backend (my go app) shows down/lastchk (L4TOUT). For some troubleshooting, I tried to connect within container itself, everything works as expected (no issues), however when I tried to connect from haproxy container (which resides on same docker node) even though I use DNS host to connect, I see different IP addresses are being rotated (possible docker issue) unless of course I mis-configured something (although it always worked without any issues in the past).

As for your side note (too many managers), the reason for that is if I don't promote docker node to manager, I'm unable to connect to other docker node host/service via overlay/swarm.

**Comment by cpuguy83** [comment]
> even though I used DNS host to connect, I see different IP addresses are being rotated

Are there multiple backends? Docker does a DNS RR for scaled services.

> maybe some miss-configuration on my end

You can create a network with `--attachable` to get round this.

**Comment by a1exus** [comment]
There no multiple backends, there is only one (single) backend, "bug"?

for attachable network, `Attachable` is already `true` in my case:
```
# docker network inspect Y_X | grep Attachable
        "Attachable": true,
# 
```

**Comment by cpuguy83** [comment]
> There no multiple backends

When I say backend, I mean swarm replicas. Each replica gets its own IP and hitting the service DNS name will rotate through those.

Also are you sure the tasks are staying up and not entirely new tasks each time you query the address?

---

> for attachable network, in my case Attachable is already true:

If attachable is true, you should be able to access those networks, just know they won't be visible on a given node until you actually try to use it.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
