### ISSUE TITLE
User proxy configuration doesn't work with docker create + start

### ISSUE THREAD

**Issue by Silvanoc** [docker/for-linux#369]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Proxy configuration specified in the file `~/.docker/config.json` [as documented](https://docs.docker.com/network/proxy/) is available in a container no matter if it's started directly (with `docker run`) or in two steps (`docker create` + `docker start`).

### Actual behavior

The proxy configuration work as documented if starting the container directly with `docker run`, but it isn't passed to the container if started in two steps (`docker create` + `docker start`).

### Steps to reproduce the behavior

Create a docker proxy configuration for the user running the command, if none available (e.g. [the example provided in the documentation](https://docs.docker.com/network/proxy/#configure-the-docker-client)).

Run a container to print the active environment
`docker run alpine env`

It should print an environment with the specified proxy configuration.

Then try the same with `docker create` + `docker start`:
```shell
cont_id=$(docker create alpine env)
docker start ${cont_id} >/dev/null
docker logs ${cont_id}
docker rm ${cont_id} >/dev/null
```

And the proxy environment is missing...

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 162
Server Version: 18.06.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.53GiB
Name: xxxxxxxxxxx
ID: FJE5:HD44:VERX:G67B:HOYY:P4D7:HCL7:NENC:AR3H:W34I:XHPX:6VVO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://127.0.0.1:3128/
HTTPS Proxy: http://127.0.0.1:3128/
No Proxy: localhost,xxxxxxxxxx
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by CarlosRodar** [comment]
You didn´t found the solution?

**Comment by Silvanoc** [comment]
I nothing happened in 5 month, I wouldn't expect anybody will ever fix it, unless you do it yourself :-)

**Comment by thaJeztah** [comment]
Working on a fix, should be up in a minute

**Comment by thaJeztah** [comment]
Okay; pull request is up; https://github.com/docker/cli/pull/1573
