### ISSUE TITLE
Docker upstart/init script skips setting up cgroup mounts if substring "cgroup" appears in /etc/fstab

### ISSUE THREAD

**Issue by mattnworb** [docker/for-linux#386]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
After a reboot, the docker daemon would startup correctly and function.

### Actual behavior
We've found that if a machine makes any mention of the string `cgroup` in `/etc/fstab`, then the Upstart script skips setting up the cgroup-related mounts that the daemon needs to function. The daemon will then exit at startup with the error message:

```
... Error starting daemon: Devices cgroup isn't mounted
```

This appears to be because the Upstart script (and also the init script) exits the `pre-start` script if `grep -v '^#' /etc/fstab | grep -q cgroup` succeeds:

https://github.com/docker/docker-ce-packaging/blob/1aa29931980e51171a57cae931de9cd17966dbb0/deb/common/docker-ce.docker.upstart#L18

https://github.com/docker/docker-ce-packaging/blob/1aa29931980e51171a57cae931de9cd17966dbb0/deb/common/docker-ce.docker.init#L64

### Steps to reproduce the behavior

Add a mountpoint of any type in `/etc/fstab` containing the substring `cgroup`. In our case, this was because of a mountpoint innocently named something like:

```
/home/ext-musicgroup/... ... none    rw,bind 0       0
```

At some point reboot the machine, after which docker will not start up ok because the cgroup mounts the daemon looks for are not present.

This happened to us on a machine with Ubuntu 14.04 and `docker-engine` package version `1.12.3-0~trusty`, but (assuming my links above are correct) this logic appears to still be in the packaged Upstart/init scripts in newer versions.

**Comment by thaJeztah** [comment]
The upstart scripts have been removed, but contributions to the other init scripts are always welcome; feel free to open a pull request. Files can be found here; https://github.com/moby/moby/tree/master/contrib/init
