### ISSUE TITLE
`docker volume prune` does not work for NFS volumes (local driver)

### ISSUE THREAD

**Issue by thomvaill** [docker/for-linux#389]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
`docker volume prune` and `docker system prune --volumes` should remove unused volumes, even if their type is `nfs` (`local` driver).

This behavior is needed especially in Swarm mode when you attach NFS volumes to your services (which is a really common use case).
For replicated services, you will have a lot of volumes created all over your nodes... Since scheduling a good ol' `docker system prune --volumes --force` on your nodes is a good practice / is needed to clean regularly your Swarm, this command should also work on NFS volumes.

### Actual behavior
Volumes created with the `local` driver and with the `type=nfs` option are never pruned.

Please note that `docker volume rm` works, though.

### Steps to reproduce the behavior

Check that your node is clean:

    root@fordevdock1:~#` docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    root@fordevdock1:~# docker volume ls
    DRIVER              VOLUME NAME

Create an NFS volume:

    root@fordevdock1:~# docker volume create --driver local \
         --opt type=nfs \
         --opt o=addr=192.168.77.254,rw \
         --opt device=:/var/exports/fornfsdev \
         foo
    foo
    root@fordevdock1:~# docker volume ls
    DRIVER              VOLUME NAME
    local               foo

Try the prune command:

    root@fordevdock1:~# docker volume prune --force
    Total reclaimed space: 0B

It does not work:

    root@fordevdock1:~# docker volume ls
    DRIVER              VOLUME NAME
    local               foo

Try the system-wide prune command:

    root@fordevdock1:~# docker system prune --force --volumes
    Total reclaimed space: 0B

... it does not work either:

    root@fordevdock1:~# docker volume ls
    DRIVER              VOLUME NAME
    local               foo

**Additional information:**

For information, when I try the `prune` command, the volume's underlying NFS directory is not mounted on the host:

    root@fordevdock1:~# df -h
    Filesystem                             Size  Used Avail Use% Mounted on
    udev                                   992M     0  992M   0% /dev
    tmpfs                                  201M  9.5M  192M   5% /run
    /dev/sda1                              8.7G  1.7G  6.6G  21% /
    tmpfs                                 1003M     0 1003M   0% /dev/shm
    tmpfs                                  5.0M     0  5.0M   0% /run/lock
    tmpfs                                 1003M     0 1003M   0% /sys/fs/cgroup
    tmpfs                                  201M     0  201M   0% /run/user/1000

Docker seems to mount it automatically when a container uses it:

    root@fordevdock1:~# docker run -d -v foo:/mnt/foo alpine top
    aa9fe575b9bf59f7cd62c76610cc49bc22c92252cc9bb0994735b6d6ba64cbd5
    root@fordevdock1:~# df 
    Filesystem                            1K-blocks    Used Available Use% Mounted on
    udev                                    1015068       0   1015068   0% /dev
    tmpfs                                    205244    9696    195548   5% /run
    /dev/sda1                               9121524 1736008   6902444  21% /
    tmpfs                                   1026208       0   1026208   0% /dev/shm
    tmpfs                                      5120       0      5120   0% /run/lock
    tmpfs                                   1026208       0   1026208   0% /sys/fs/cgroup
    tmpfs                                    205240       0    205240   0% /run/user/1000
    overlay                                 9121524 1736008   6902444  21%
    /var/lib/docker/overlay2/33447a8ce7c3fc12eb54a0d6de86591ad8031edb38cc3ff40b7929a6160a56fa/merged
    shm                                       65536       0     65536   0%     /var/lib/docker/containers/aa9fe575b9bf59f7cd62c76610cc49bc22c92252cc9bb0994735b6d6ba64cbd5/mounts/shm
    :/var/exports/fornfsdev                 9121536 1085056   7553408  13% /var/lib/docker/volumes/foo/_data

... so I don't think the issue is caused by a resource lock on the node.

**Output of `docker version`:**

```
root@fordevdock1:~# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
root@fordevdock1:~# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: igom5lx42oaub5qe8vx3d6yoh
 Is Manager: true
 ClusterID: 94zze81rfp1sekf5zhx8f4hfa
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.77.11
 Manager Addresses:
  192.168.77.11:2377
  192.168.77.12:2377
  192.168.77.13:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.957GiB
Name: fordevdock1
ID: SXI4:ZQOQ:TUKT:G5X4:7POD:3KRA:2NTT:Z3HY:3SAA:DXJC:NTJZ:KDD2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://192.168.77.1:5000/
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Tested on Debian 9 Stretch, in VirtualBox

**Comment by cpuguy83** [comment]
This is primarily because we do not report statistics (e.g. `docker system df`,) for volumes created with the local driver that use options, reason being is that these are often not actually taking up space on the node.

I can see how it would be nice for `prune` to clean these up, though.

**Comment by alexamirante** [comment]
@cpuguy83 I think this is a regression. I only see this behavior on swarm nodes with docker engine >= 18.06. I have nodes with v18.03.1-ce and v18.05.1-ce and they all delete NFS volumes when I issue a `docker volume prune`.

**Comment by TomerFi** [comment]
I have the exact same problem.
I've created a couple of nfs volumes I'm trying to change destination for.
My new volumes aren't getting created because allegedly they still exists.

I'm running:
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

For now, the quickest workaround was to just change the stack or service names (I'm running in swarm mode). that causes the volume mount name to be different then the previous one, therefore a new volume is created.

I'll keep trying to figure out a new workaround, cause changing the service name for every change I want to perform for the volume configuration is definitely not the way to go, I'm just adding more volumes and messing around with my environment for no reason.

**Comment by theKBro** [comment]
same problem here with cifs volumes...

**Comment by tomdaley92** [comment]
Came here to voice the same frustration while using docker swarm mode. I have a cron job that regularly cleans up my docker swarm hosts and it would be very nice for `docker system prune --volumes` or `docker volume prune` to clean these up. 

For example, just by adjusting the swarm namespace a bit, I end up having to manually ssh into server and remove a bunch of volumes individually or run a `docker stack rm` which kind of defeats the point of automated zero-downtime deployments. In the example below the stack `handbrake_production` does not even exist at this point, but all of the volumes remain.
![image](https://user-images.githubusercontent.com/12147036/204104198-05726692-0462-41c0-a5d1-fdbd2fafd5fb.png)

Here's my docker version info:
![image](https://user-images.githubusercontent.com/12147036/204104420-3d4bdae4-50e7-4c4e-8be3-f124b7efedba.png)

**Comment by wind57** [comment]
same issue here...

Our workaround is to create NFS volumes with a custom label:

```
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=172.30.135.42,nfsvers=3 \
  --opt device=:/vol/core/ \
  --label type=custom_nfs \
  nfs-volume
```

and when its time to remove them:

```
docker volume rm $(docker volume ls --filter 'label=type=custom_nfs' -q)
```

**Comment by ericrange** [comment]
after 6 years still the same issue

**Comment by cpuguy83** [comment]
This is working as intended.
Prune was designed to clean up local disk space.
When running the "local" volume driver with mount options this is no longer space that the volume driver is managing, so they are not pruned.

We've taken this a step further in v24 and by default only prune anonymous volume (e.g. `docker run -v /foo bar:latest`).
