### ISSUE TITLE
Host and container files don't sync when subfolders are zfs datasets

### ISSUE THREAD

**Issue by JasonGantner** [docker/for-linux#393]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one
### Expected behavior
Change on files/subfolders are effective in the container and the host filesystem.
A change to a file on the host is visible from the container.
A change to a file in the container is visible from the host.

### Actual behavior
Change on files/folders are effective in the container and the host filesystem.
A change to a file on the host is visible from the container.
A change to a file in the container is visible from the host.

### Steps to reproduce the behavior

1. Create a container with a bind mounted folder. (either a zfs dataset or a regular folder in an ext4 filesystem)
2.  `zfs create -o /path/to/your/folder/subfolder your-pool/dataset`
3. Do something on or in the subfolder (edit permissions, create a file...)
4. Note that any change is not applied from the host to the container or vice-versa

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 41
 Running: 37
 Paused: 0
 Stopped: 4
Images: 137
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 369
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-131-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.8GiB
Name: --HIDDEN--
ID: --HIDDEN--
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This is a bare metal installation of Ubuntu 16.04 with zfs installed directly from the packages.

**Comment by cpuguy83** [comment]
Maybe cross-eyed here... but your "actual behavior" and "expected behavior" appear to say the same thing.

But I am going to assume the actual behavior you are seeing is you make changes to the mount tree on the host and the changes are not visible in the container.

For this to work you need to mount the volume with `rslave` propagation... This means changes to the host propagate to the container.

if you want changes in the container to be visible on the host, then you need `rshared` propagation, which will ensure that changes on either side propagate to the other side.

Example:

```
docker run -v /foo:/bar:rshared
``

**Comment by JasonGantner** [comment]
I forgot the "not" in the actual behaviour.

I didn't understood at first when I read the docs. Guess I should be more carefull next time.
It does work when setting the `rshared` option.

Sorry for the troubles and thank you for your time.
