### ISSUE TITLE
awslogs driver not work properly in cn-northwest-1 region

### ISSUE THREAD

**Issue by guojiaqi1027** [docker/for-linux#394]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Build the container with docker-compse and logging options. Specify cn-northwest-1 region and group/stream options. It should work as same as cn-north-1 region which upstream logs to CloudWatch

### Actual behavior

When I up the compose, the container show up the following lines

`ERROR: for webapp  Cannot start service webapp: Failed to initialize logging driver: RequestError: send request failed
caused by: Post https://logs.cn-northwest-1.amazonaws.com/: dial tcp: lookup logs.cn-northwest-1.amazonaws.com on 10.1.0.2:53: no such host`

In which the url should be `https://logs.cn-northwest-1.amazonaws.com.cn/`

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 62
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-130-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-10-1-1-63
ID: DJWU:YBAF:WLRJ:54BO:CDP2:K46A:VKDT:ON5K:XN3W:WHAE:DWUT:5CPL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
AWS EC2 in cn-northwest-1 region

**Comment by jhaynes** [comment]
Hi @guojiaqi1027 

The AWS SDK that is used in Docker didn't know about the `cn-northwest-1` region because it wasn't built when Docker `1.13.1`  was released. Docker `18.03` and later includes a newer AWS SDK which knows about the `cn-northwest-1` region.

**Comment by seemethere** [comment]
Closing with @jhaynes comment
