### ISSUE TITLE
docker-ce 18.06.0/18.06.1 panic in Bash for Windows

### ISSUE THREAD

**Issue by bjornmagnusson** [docker/for-linux#399]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker version should output version of Docker in Bash for Windows

### Actual behavior
docker version crashes with error message.
```
docker version
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x17e2bd8, 0x17)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x102f5c11800, 0x7f0b00000000)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [chan receive, locked to thread]:
github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register(0xc420266d20, 0x194f1a0, 0xc420356000, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus/registry.go:235 +0x1ea
github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry(0x181756d)
        /go/src/github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus/registry.go:681 +0x195

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [runnable]:
github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x194f1a0, 0xc420356000, 0xc42035a000)
        /go/src/github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus/registry.go:222
created by github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register
        /go/src/github.com/docker/cli/vendor/github.com/prometheus/client_golang/prometheus/registry.go:222 +0xa2
```

### Steps to reproduce the behavior
Install stable docker-ce (18.06.0) for ubuntu in Bash for Windows
sudo apt-get install docker-ce

**Output of `docker version`:**
Does not work
```
(paste your output here)
```

**Output of `docker info`:**
Does not work
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Windows 10
Bash for Windows

**Comment by WendySanarwanto** [comment]
+1 This issue also happened in my Windows 10 which runs Windows Linux Subsystem (Ubuntu 16.04.5 LTS)
- Docker for Windows - Settings -> General :
![image](https://user-images.githubusercontent.com/18456618/44833786-c1eadd00-ac61-11e8-858e-572c55718176.png)

- `lsb_release -a` command's output:
![image](https://user-images.githubusercontent.com/18456618/44833829-e050d880-ac61-11e8-8b93-286fad456bda.png)

- Docker for window's version in my machine:
![image](https://user-images.githubusercontent.com/18456618/44833888-037b8800-ac62-11e8-8077-72a2bda7ac72.png)

- DOCKER_HOST env variable in my `~/.bashrc` file.
![image](https://user-images.githubusercontent.com/18456618/44834224-13479c00-ac63-11e8-8130-110cf043dad7.png)

- The error messages when i ran `docker` command:
![image](https://user-images.githubusercontent.com/18456618/44834249-2a868980-ac63-11e8-9d7a-ce5930588542.png)

**Comment by d47id** [comment]
I get the same. Downgrading to 18.03.1~ce-0~ubuntu fixed this for me.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale, and I haven't seen reports about this for a long time
