### ISSUE TITLE
missing man pages in linux distro packages of 17.06.0 rc1

### ISSUE THREAD

**Issue by andrewhsu** [docker/for-linux#4]
### Expected behavior

After installing linux packages for 17.06.0 RC1, expect man pages:

`man docker`

### Actual behavior

No bueno

### Information

All linux distro packages for 17.06.0 RC1

**Comment by seemethere** [comment]
Relates to: https://github.com/docker/cli/pull/68

**Comment by andrewhsu** [comment]
This is fixed in 17.06.0 RC2.
