### ISSUE TITLE
After installing docker on VPS with VMWare, ssh stops working

### ISSUE THREAD

**Issue by Lexinek** [docker/for-linux#40]
### Expected behavior
To get connected with `ssh root@server` command

### Actual behavior
<img width="500" alt="screenshot 2017-06-21 15 27 52" src="https://user-images.githubusercontent.com/3995003/27399573-84d155c0-56bd-11e7-8980-a1c9ce21fa05.png">
During docker installation the process get stuck on this screen and after long time (like hour) i get disconnected from server.
Instantly after the `setting up docker-ce` message i am not able to ssh to server anymore:
<img width="425" alt="screenshot 2017-06-21 15 26 07" src="https://user-images.githubusercontent.com/3995003/27399635-bab966b4-56bd-11e7-81fd-c9e9335134a5.png">

### Information

  - Ubuntu 16.04 clear installation on a VMWare virtualization
  - I had a call with our infrastructure provider, we discussed a lot the details and he shared information with me, that the problem is probably has something to do with MAC addresses (i dont know how does it work internally in docker, if it changes something with the mac addresses).

As well i tried to change ssh port to 2222 to make sure the problem is not in 22 port conflict (checked as well what is listening on 22/2222, it was ssh only). As well the ssh service was normally running and listening. Here is the tcpdump screenshot (as i understood correctly, the ssh login attempt reached the server but it was unable to respond).
<img width="866" alt="screenshot 2017-06-21 15 30 53" src="https://user-images.githubusercontent.com/3995003/27400828-a392f32a-56c1-11e7-9933-aff3aaa66558.png">

### Steps to reproduce the behavior
Here is whole log on clean installation of Ubuntu 16.04, until the vps gets stucked (VMWare virtualization)
[Docker install log.txt](https://github.com/docker/for-linux/files/1092529/Docker.install.log.txt)

Any help or tips how to fix are appreciated. Basically instantly after installing docker, the VPS is unusable as i am unable to ssh to server.

**Comment by Lexinek** [comment]
Here is some additional info i was provided with:
http://wahlnetwork.com/2013/04/29/how-the-vmware-forged-transmits-security-policy-works/
https://stackoverflow.com/questions/18479242/how-to-set-the-mac-address-for-docker-lxc-containers

Though it is not much useful for me as i get locked out of VPS (not able to connect it using ssh) during the docker installation.

**Comment by Lexinek** [comment]
Bump! I am desperate.

**Comment by cpuguy83** [comment]
Can you paste your iptables rules?

**Comment by Lexinek** [comment]
@cpuguy83 this task is a bit tricky as i am unable to write dashes and slashes from web terminal (there is something wrong with keyboard layout in web console interface). 

Before installing docker, iptables should be completely flushed, i do not know if iptables is affected by docker installation.

Anyways i will try my best and let you know if i was successful getting iptables rules.

**Comment by thaJeztah** [comment]
Let me close this for now, because this went stale, but feel free to post more information if you were able to obtain that.

**Comment by MikeSorokin** [comment]
@Lexinek @thaJeztah Hi! I suppose its too late, but... I experienced the same issue. In my case, I was able to connect to server via ssh during about 1-2 minutes window after every hard reboot, then ssh connection was gone by timeout. My hosting provider offered solution  - `sudo sysctl net.ipv4.conf.all.rp_filter=0`, and it fixed this problem for me.

**Comment by Lexinek** [comment]
Hi @MikeSorokin thank you, i will try it out and let you know if it worked.

**Comment by kawazaki0** [comment]
@Lexinek Maybe your network has similar subnet as docker so the installation changes your routes. Try to change subnet for docker:
https://success.docker.com/article/How_do_I_configure_the_default_bridge_(docker0)_network_for_Docker_Engine_to_a_different_subnet
Or subnet for your network.

**Comment by AbdulkaderMakki** [comment]
I experience the same problem here
any help ?

**Comment by zopar** [comment]
Note, if you use the swarm mode should be also related to the gwbridge, consider also to change the newtork of gwbridge

https://docs.docker.com/v17.09/engine/swarm/networking/#customize-the-docker_gwbridge

**Comment by icecoll** [comment]
Same issue on centOS7 vultr host,i found two ways to fix it:
- uninstall `serverSpeeder`;
- [use docker host networking](https://docs.docker.com/network/host/)

hope it helps!

**Comment by Kavitha21-cyber** [comment]
when I install the docker in vm ware it shows sucessfully installed but when it comes to pull the tool into the docker I'm getting  message as docker.service does not exist.can you please tell me hoe to fix the problem.
