### ISSUE TITLE
Pipefail, and command fails in subscripts

### ISSUE THREAD

**Issue by FauconFan** [docker/for-linux#408]
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

```
FROM ${SOME_IMAGE}

RUN curl {SOME_URL} | cat -
```

If the curl command failed for any reason, the connectivity is unstable, the url is incorrect, or curl just doesn't exist on this system, the RUN command will build a new layer normally. 

At least, this issue must be more popular, nobody around me knows about this. Every return code command should be tested, even if it is hidden in a pipe, or in a subshell.

I don't have easy solutions for failed command in a subshell, but i discover a way with shell flags to raise errors for pipe fails.

```
FROM ${SOME_IMAGE}

# We set the default shell to bash with pipefail flag called
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl ${SOME_URL} | cat -

# We come back to the shell given by default when building a docker image.
SHELL ["/bin/sh", "-c"]
```

We can still fix commands that fail in a subshell, by using variables.

```
FROM debian

RUN \
         apt-get update && \
         apt-get install -y \
               linux-headers-$(uuname -r)
```

The uuname command fail here (It is uname), and the error is not reported... (This example is bad, the apt-get will fail because the 'linux-header-' doesn't exist, but it illustrates the issue.

```
FROM debian

RUN \
         UNAME_R=$(uuname -r) && \
         apt-get update && \
         apt-get install -y \
               linux-headers-$(uname -r)
```

This run will fail at the first line.

**Feature request**

I know that docker use the shell explicitly, and don't have to manage this issue, but it would be nice to  fail if any command fail, on any shell.

**Comment by seemethere** [comment]
Just like you said this doesn't seem to be an issue with docker, this would happen in a regular shell script much less a Dockerfile

**Comment by FauconFan** [comment]
I understand, but a Dockerfile is (at least for me) a playbook, that every machine can run to build a environment for a service. And if something fail (anything), the all build have to fail.

The only way to fix such things it to code a docker shell, or something like this...

This can be fix, by using some tricks, but, i think it's a good idea that Docker can manage this.
^^

**Comment by cpuguy83** [comment]
This is the job of the shell. Docker is running your command in a shell. If you need pipefail then you should set it.

There is no way that Docker can change this default (without breaking users).
But you can do:
```
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
```

This will make any subsequent `RUN` instructions use pipefail.

**Comment by seemethere** [comment]
Yup I don't think there's a feasible way to make this the default without breaking users. 

Thanks for the workaround @cpuguy83!
