### ISSUE TITLE
Fresh installation, ERRO[0000] error waiting for container: context canceled

### ISSUE THREAD

**Issue by DarthJahus** [docker/for-linux#409]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Correctly create and run Hello-World container.

### Actual behavior
```
# docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: function not implemented\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

### Steps to reproduce the behavior
1. Debian 9 VM from PulseHeberg.com, _freshly_ created.
```
Linux 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```
2. Docker installed by following the [steps described on the official website](https://docs.docker.com/install/linux/docker-ce/debian/).
`Docker version 18.06.0-ce, build 0ffa825`
3. `docker run hello-world`

**Output of `docker version`:**
`Docker version 18.06.0-ce, build 0ffa825`

**Output of `docker info`:**
(_Could not retreive the `docker info` output before the manager removes the VM (feel free to remove or close this issue if the information I have provided are not sufficient._)

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Debian 9 VM from PulseHeberg.com, _freshly_ created.

**Comment by DarthJahus** [comment]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one



### Expected behavior
Correctly create and run Hello-World container.

### Actual behavior
```
# docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: function not implemented\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

### Steps to reproduce the behavior
1. Debian 9 VM from PulseHeberg.com, _freshly_ created.
```
Linux 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```
2. Docker installed by following the [steps described on the official website](https://docs.docker.com/install/linux/docker-ce/debian/).
`Docker version 18.06.0-ce, build 0ffa825`
3. `docker run hello-world`



**Output of `docker version`:**
`Docker version 18.06.0-ce, build 0ffa825`

**Output of `docker info`:**
(_Could not retreive the `docker info` output before the manager removes the VM (feel free to remove or close this issue if the information I have provided are not sufficient._)

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Debian 9 VM from PulseHeberg.com, _freshly_ created.

**Comment by DarthJahus** [comment]
Just tried another VM from PulseHeberg.com, this time with Ubuntu and it's the same problem.

Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.17-1-pve
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2GiB
Name: subspace
ID: ZYAH:IVVP:XZ6C:OBDV:KECL:WPY6:AX76:HMMC:PIQO:7UKA:RAXA:N3XJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

P.-s.: Sorry for closing and reopenning the issue; it wasn't intentional.

**Comment by DarthJahus** [comment]
Just tried another VM from PulseHeberg.com, this time with Ubuntu and I get this when running `docker run hello-world`:

```
docker: Error response from daemon: Could not check if docker-default AppArmor profile was loaded: open /sys/kernel/security/apparmor/profiles: permission denied.
ERRO[0002] error waiting for container: context canceled
```

Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.17-1-pve
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2GiB
Name: subspace
ID: ZYAH:IVVP:XZ6C:OBDV:KECL:WPY6:AX76:HMMC:PIQO:7UKA:RAXA:N3XJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

P.-s.: Sorry for closing and reopenning the issue; it wasn't intentional.

**Comment by DarthJahus** [comment]
After contacting the provider's technical support, they have told me that they use LXC, which doesn't support Docker.

Feel free to close this issue.

**Comment by mexavierace12** [comment]
Downgrade your Docker. 
This command list the versions: apt-cache madison docker-ce 
Choose the 17 versions :sudo apt-get install docker-ce=<VERSION_STRING>
example: sudo apt-get install docker-ce=17.03.0~ce-0~ubuntu-trusty 

Try it out!

**Comment by shrijayan** [comment]
> After contacting the provider's technical support, they have told me that they use LXC, which doesn't support Docker.
> 
> Feel free to close this issue.

What is LXC I am trying to run docker run hello-world but the same error pops. I trying to do it in Ubuntu CLI Docker version 25.0.3.

**Comment by shrijayan** [comment]
No other solution available for this Error.

**Comment by shrijayan** [comment]
> * [x]  This is a bug report
> * [ ]  This is a feature request
> * [x]  I searched existing issues before opening this one
> 
> ### Expected behavior
> Correctly create and run Hello-World container.
> 
> ### Actual behavior
> ```
> # docker run hello-world
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: function not implemented\"": unknown.
> ERRO[0000] error waiting for container: context canceled
> ```
> 
> ### Steps to reproduce the behavior
> 1. Debian 9 VM from PulseHeberg.com, _freshly_ created.
> 
> ```
> Linux 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 GNU/Linux
> Distributor ID: Debian
> Description:    Debian GNU/Linux 9.5 (stretch)
> Release:        9.5
> Codename:       stretch
> ```
> 
> 2. Docker installed by following the [steps described on the official website](https://docs.docker.com/install/linux/docker-ce/debian/).
>    `Docker version 18.06.0-ce, build 0ffa825`
> 3. `docker run hello-world`
> 
> **Output of `docker version`:** `Docker version 18.06.0-ce, build 0ffa825`
> 
> **Output of `docker info`:** (_Could not retreive the `docker info` output before the manager removes the VM (feel free to remove or close this issue if the information I have provided are not sufficient._)
> 
> **Additional environment details (AWS, VirtualBox, physical, etc.)** Debian 9 VM from PulseHeberg.com, _freshly_ created.

This was the solution for me for this Error 
```
sudo apt remove netscript-2.4
sudo reboot
```
