### ISSUE TITLE
Docker Swarm with image versions externalized to .env file

### ISSUE THREAD

**Issue by OlivierDupre** [docker/for-linux#41]
### Contect
I have externalized the version of my images to `.env` file.
It works fine as long as I am just running `docker-compose up`
As soon as I start to deploy to the `swarm` (using swarm-mode), it fails and I must declare image versions directly in my `docker-compose.yml` file.

### Expected behavior
Understanding the image version even if it is specified as a variable valued in .env file.

### Actual behavior
Message

> Error response from daemon: rpc error: code = 3 desc = ContainerSpec: "portainer/portainer:" is not a valid repository/tag

being displayed when specifying the image version as a variable.

### Information
  - Linux distro: several Ubuntu, from 16.04
  - Docker CE version, 17.03
  - A reproducible case if this is a bug, https://github.com/OlivierDupre/docker-compose-issue branch `master` for a working case, branch `failing` for a ... failing case
  - Page URL if this is a docs issue or the name of a man page

### Steps to reproduce the behavior
  1.  Clone my repository
  2.  `docker stack deploy --compose-file docker-compose.yml local` on the `master` branch. It works fine.
  3.  `docker stack deploy --compose-file docker-compose.yml local` on the `failing` branch. It fails displaying the above message.

**Comment by dnephin** [comment]
`.env` is not a feature of `stack deploy`. You should be able to `source .env` first before running `stack deploy`.

Existing issue: https://github.com/moby/moby/issues/29133

**Comment by OlivierDupre** [comment]
Thanks,

Sorry for duplicating this issue.

**Comment by jarek-przygodzki** [comment]
Quite nice workaround is using `docker-compose config` together with [bash's process substitution](http://tldp.org/LDP/abs/html/process-sub.html)

```
docker stack deploy --compose-file=<(docker-compose --file docker-compose.ym config) STACK
```
