### ISSUE TITLE
Progress meter handling triggers dockerd crash

### ISSUE THREAD

**Issue by cjsin** [docker/for-linux#419]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

docker version docker-ce-18.06.1.ce-3.fc28.x86_64 (for fedora-28) with poorly configured storage driver (overlay2 on an xfs filesystem) 
fails to pull and install the image 'docker.io/node:10.9.0-jessie'. The error seems to trigger another error - a "unexpected EOF" error is displayed, and the docker daemon crashes, with a log that indicates that it failed to handle progress meter output.

The system which triggered this bug has an xfs root filesystem, and was configured with the overlay2 storage driver, which the docker logs indicate is not supported.
 
Additionally I was unable to replicate the error when trying the exact same packages on another system, which utilised an ext4 root filesystem and the overlay2 storage driver. 

However, I am submitting this issue because it appears that potentially this may have exposed a different bug, in the handling of the Progress meter, which has caused the docker daemon to crash.

### Expected behavior

The erronous behaviour was caused by a misconfigured system, and the docker daemon does warn about this in the logs, so the behaviour is not unexpected.

The exact same version of docker-ce on a well configured node (overlay2+ext4 with supports_dtype=true) does not exhibit the crash, and successfully pulled and extracted the image.

However I am submitting this issue because it may have exposed a different failure to handle an error condition, in the code which handles progress meter output during extraction of an image.

I have downloaded the particular blob which triggers the issue, and its sha256sum is correct, and tar is able to extract the file without reporting any errors at all. All of which seems to indicate that it was the misconfigured overlay2+xfs filesystem causing the original error, but which has potentially triggered an unrelated bug.

The 'docker info' and 'docker version' I will include below are from the system where the bug was triggered.

### Actual behavior

```
docker pull docker.io/node:10.9.0-jessie 
10.9.0-jessie: Pulling from library/node
d660b1f15b9b: Already exists 
46dde23c37b3: Already exists 
6ebaeb074589: Already exists 
e7428f935583: Already exists 
eda527043444: Already exists 
f3088daa8887: Already exists 
50db09495eb5: Extracting [==================================================>]     19MB/19MB
51810167f4e9: Download complete 
unexpected EOF
```

system log showing the dockerd crash:

```
Aug 25 23:17:22 redacted dockerd[14602]: time="2018-08-25T23:17:22.414382942+09:30" level=info msg="Docker daemon" commit=e68fc7a graphdriver(s)=overlay2 version=18.06.1-ce
Aug 25 23:17:22 redacted dockerd[14602]: time="2018-08-25T23:17:22.414485829+09:30" level=info msg="Daemon has completed initialization"
Aug 25 23:17:22 redacted dockerd[14602]: time="2018-08-25T23:17:22.477593598+09:30" level=info msg="API listen on /var/run/docker.sock"
Aug 25 23:17:22 redacted systemd[1]: Started Docker Application Container Engine.
Aug 25 23:18:42 redacted dockerd[14602]: panic: send on closed channel
Aug 25 23:18:42 redacted dockerd[14602]: goroutine 324 [running]:
Aug 25 23:18:42 redacted dockerd[14602]: github.com/docker/docker/pkg/progress.chanOutput.WriteProgress(0xc4201b8d20, 0xc42061c6e7, 0xc, 0x0, 0x0, 0x55b3b59aee19, 0xa, 0x121ecc0, 0x121ecc0, 0x0, ...)
Aug 25 23:18:42 redacted dockerd[14602]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progress.go:42 +0x68
Aug 25 23:18:42 redacted dockerd[14602]: github.com/docker/docker/pkg/progress.(*Reader).updateProgress(0xc420a0d980, 0xc4217f4001)
Aug 25 23:18:42 redacted dockerd[14602]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progressreader.go:64 +0xec
Aug 25 23:18:42 redacted dockerd[14602]: github.com/docker/docker/pkg/progress.(*Reader).Read(0xc420a0d980, 0xc4217f4000, 0x8000, 0x8000, 0x8000, 0x8000, 0x0)
Aug 25 23:18:42 redacted dockerd[14602]:         /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/pkg/progress/progressreader.go:45 +0xda
Aug 25 23:18:42 redacted dockerd[14602]: bufio.(*Reader).fill(0xc420a0d9e0)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/bufio/bufio.go:100 +0x120
Aug 25 23:18:42 redacted dockerd[14602]: bufio.(*Reader).WriteTo(0xc420a0d9e0, 0x55b3b65cfb60, 0xc42018e528, 0x7fc864dee0a0, 0xc420a0d9e0, 0x55b3b6232f01)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/bufio/bufio.go:494 +0x10f
Aug 25 23:18:42 redacted dockerd[14602]: io.copyBuffer(0x55b3b65cfb60, 0xc42018e528, 0x55b3b65cc4e0, 0xc420a0d9e0, 0x0, 0x0, 0x0, 0xc42173c3c0, 0xc42173c360, 0x20002)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/io/io.go:382 +0x36b
Aug 25 23:18:42 redacted dockerd[14602]: io.Copy(0x55b3b65cfb60, 0xc42018e528, 0x55b3b65cc4e0, 0xc420a0d9e0, 0x0, 0x0, 0x0)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/io/io.go:362 +0x5c
Aug 25 23:18:42 redacted dockerd[14602]: os/exec.(*Cmd).stdin.func1(0x55b3b65bc708, 0x0)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/os/exec/exec.go:230 +0x57
Aug 25 23:18:42 redacted dockerd[14602]: os/exec.(*Cmd).Start.func1(0xc4217e06e0, 0xc4210bcba0)
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/os/exec/exec.go:396 +0x29
Aug 25 23:18:42 redacted dockerd[14602]: created by os/exec.(*Cmd).Start
Aug 25 23:18:42 redacted dockerd[14602]:         /usr/local/go/src/os/exec/exec.go:395 +0x5e1
Aug 25 23:18:42 redacted systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 25 23:18:42 redacted systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 25 23:18:42 redacted systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 25 23:18:42 redacted systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Aug 25 23:18:42 redacted systemd[1]: Stopped Docker Application Container Engine.

```

### Steps to reproduce the behavior

- Install docker-ce-18.06.1.ce-3.fc28.x86_64 from docker-ce fedora repository, on a fedora-28 system, with xfs backing filesystem and the overlay2 storage driver,

- The storage driver has not been configured specifically, and appears to be using overlay2, because that is what I was using prior to installing docker-ce
   (the system logs shows that docker has automatically selected overlay2 due to it having been used prior)

- attempt to pull the image:   docker pull docker.io/node:10.9.0-jessie

- this seems to cause the docker daemon to crash (and systemd restarts it immediately on my system)

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:30 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.14-202.fc28.x86_64
Operating System: Fedora 28 (Twenty Eight)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.735GiB
Name: redacted
ID: <redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay2: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

As noted above, my fileystem on this box is indeed xfs, and this *does* seem to be the initial cause of the issue.
I have since tried on a node that does not use xfs, and the issue did not occur.

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This is a physical machine.

**Comment by thaJeztah** [comment]
Yes, this is expected when running overlay/overlay2 on top of a filesystem that does not have `d_type` enabled;

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

Running overlay (or overlay2) on XFS without `d_type` is known to cause issues. Older versions of docker "allows" it for backward-compatibility, but will block it for new installations. See the warning being logged about this as well when starting the daemon;

```
overlay: the backing xfs filesystem is formatted without d_type support,
which leads to incorrect behavior. Reformat the filesystem with ftype=1
to enable d_type support.
Running without d_type support will no longer be supported in Docker 17.12.
```

Also see these issues, which contain some information https://github.com/moby/moby/issues/10294, https://github.com/moby/moby/issues/29873.

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.


Closing this issue because of the above, but feel free to continue the conversation 👍
