### ISSUE TITLE
Download.docker.com

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [docker/for-linux#427]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

Finding ready made docker-ce packages in 
https://download.docker.com/linux/debian/dists/stretch/stable/binary-amd64/

### Actual behavior

Since at least yesterday only package descriptions, no binaries. Therefore the proposed installation process for docker Ce  on Debian is not successful 

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by seemethere** [comment]
They're in the pool directory

https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/
