### ISSUE TITLE
[request] please make the changelogs easier to find

### ISSUE THREAD

**Issue by erikh** [docker/for-linux#428]
I think the title speaks for itself, but I've been considering running `wget --mirror` on docker.com and then passing it through `grep -r` to find the release notes. I'm fairly certain the moby releases don't line up, or at least, if that *is* the case I think that maybe one of the docker-ce repos should say so.

Alternatively, there is an empty `CHANGELOG.md` in the docker-ce repo that would really handy to fill in with whatever I'm about to upgrade to instead of rolling the dice. :)

Hope my request is reasonable. Thanks.

**Comment by jose-bigio** [comment]
Hi @erikh although `changelog.md` is empty in the `master` branch it is populated in the release branches. For example see here: https://github.com/docker/docker-ce/blob/18.09/CHANGELOG.md. 

The changelogs are also published on the release page on github: https://github.com/docker/docker-ce/releases

Hope this helps.

**Comment by erikh** [comment]
Thanks! Yes it does.

**Comment by jrabbit** [comment]
https://docs.docker.com/release-notes/docker-ce/ Hasn't been touched since may?
