### ISSUE TITLE
Create client-only releases for all platforms

### ISSUE THREAD

**Issue by atrauzzi** [docker/for-linux#432]
_This is a feature request._ 

It would be very helpful if there was a packaged client-only installation option, especially on debian/ubuntu based systems as part of an official PPA.

_(At that point, it probably also makes some sense to distribute for macOS using homebrew and a dmg.  For Windows, an msi, with a corresponding entry on chocolatey would be well received.)_

For myself, the two scenarios that would benefit the most would be when running in WSL as well as when I'm doing DIND.

Generally, the obvious benefits are that people could stay up to date with security and feature updates consistently as part of their respective platforms software managers.

cc.
- https://github.com/moby/moby/issues/15360
- https://github.com/moby/moby/pull/20639

**Comment by seemethere** [comment]
This is already a reality on the `nightly` and `test` channel for `download.docker.com`

Set up the package repositories first and then just do:

```
apt-get install -y docker-ce-cli
```

This will be the model going forward for 18.09+

**Comment by atrauzzi** [comment]
Awesome!  I'll be sure to check that out, thanks! 😄 

_FWIW I think everyone knows about the static bundles by now.  It's kind of beside the point to mention them in this context. The only reason people ask for official packages is because any kind of static executable is frowned upon for integration and long term management._
