### ISSUE TITLE
unable to upgrade to docker-ce 18.09.0 beta1 on ubuntu

### ISSUE THREAD

**Issue by andrewhsu** [docker/for-linux#437]
### Expected behavior

Upgrading docker-ce from 18.06.1 to 18.09.0 beta1 should work:
```
$ sudo apt install docker-ce
```

### Actual behavior

```
...
Errors were encountered while processing:
 /var/cache/apt/archives/docker-ce-cli_3%3a18.09.0~ce~1.1.beta1-0~ubuntu-bionic_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Steps to reproduce the behavior

Install docker-ce 18.06.1:
```
$ curl -fsSL test.docker.com -o test-docker.sh
$ VERSION=18.06.1 sh test-docker.sh
```

Then try to upgrade:
```
$ sudo apt install docker-ce # this should install latest 18.09.1 beta1 from test channel
```

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1007-aws
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.296GiB
Name: andrewhsu-testkit-6A1E5F-ubuntu-0
ID: RDAD:BDLI:R3WL:Q6XT:NQAI:5ZCO:VEOW:H6ZE:U7SS:TLXL:YGSG:F4W7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

AWS EC2

**Comment by andrewhsu** [comment]
Workaround for now: after installing docker-ce 18.09.0 beta1 and receiving the error, can fix the install to get the 18.09.0 beta1 packages to do the thing:
```
$ sudo apt install --fix-broken
...
Setting up docker-ce-cli (3:18.09.0~ce~1.1.beta1-0~ubuntu-bionic) ...
Setting up docker-ce (3:18.09.0~ce~1.1.beta1-0~ubuntu-bionic) ...
```

**Comment by RobinKnipe** [comment]
I think I've just hit the same problem trying to install/update to `18.09.0~3-0~ubuntu-xenial`. Output from `apt`:

```
sudo apt install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  containerd.io docker-ce-cli
Recommended packages:
  aufs-tools cgroupfs-mount | cgroup-lite pigz apparmor
The following NEW packages will be installed
  containerd.io docker-ce docker-ce-cli
0 to upgrade, 3 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/50.2 MB of archives.
After this operation, 242 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 269952 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.0~rc.2-1_amd64.deb ...
Unpacking containerd.io (1.2.0~rc.2-1) ...
dpkg: error processing archive /var/cache/apt/archives/containerd.io_1.2.0~rc.2-1_amd64.deb (--unpack):
 trying to overwrite '/usr/sbin/runc', which is also in package runc 1.0.0~rc2+docker1.13.1-0ubuntu1~16.04.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce-cli (5:18.09.0~3-0~ubuntu-xenial) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce (5:18.09.0~3-0~ubuntu-xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/containerd.io_1.2.0~rc.2-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I've had to completely remove docker and specifically install the older version: `apt install docker-ce=18.06.1~ce~3-0~ubuntu`

**Comment by thaJeztah** [comment]
@RobinKnipe looks like you running into a different issue. The problem in your case is that you previously had docker installed from a version that was packaged by your distro, and that installed `runc` as a separate package.

To resolve that issue, make sure to uninstall the distro versions of `docker` and `runc`.

The issue you're having is currently tracked through https://github.com/moby/moby/issues/38185

**Comment by RobinKnipe** [comment]
Thanks @thaJeztah

**Comment by khiminrm-lemberg** [comment]
Hi! 
I have similar problems with docker. It worked till tomorrow. I got some system updates and docker stopped working.

https://docs.docker.com/install/linux/docker-ce/ubuntu/#uninstall-old-versions doesn't help me.
Only installing older version as in https://github.com/docker/for-linux/issues/437#issuecomment-437043843 provided by @RobinKnipe helps to fix docker in my Ubuntu 18.04.

Any ideas how to use updated docker on Ubuntu 18.04 or it hasn't been fixed yet? thanks!

**Comment by thaJeztah** [comment]
@khiminrm-lemberg any more information about "It worked till tomorrow"? Were there any error messages in the logs? What system updates were installed (any particular packages? kernel update?)

**Comment by smilyram001** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 463 not upgraded.
![Screenshot from 2019-03-09 06-59-44](https://user-images.githubusercontent.com/47377426/54064304-0b336f00-4239-11e9-9d7f-9b1307cf094c.png)......

How resolve this issue....kindly anyone suggest me..........

Thanking you.

**Comment by thaJeztah** [comment]
@smilyram001 read the installation instructions: https://docs.docker.com/install/linux/docker-ce/ubuntu/ looks like you haven't configured the repository for the packages

**Comment by khiminrm-lemberg** [comment]
Hi @thaJeztah, I have such errors:
![docker_error](https://user-images.githubusercontent.com/27729821/54372670-74294580-4684-11e9-8267-356a2c6fc0b2.jpg)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
