### ISSUE TITLE
Package docker-ce was not found.

### ISSUE THREAD

**Issue by artus** [docker/for-linux#462]
* [x] This is a bug report
I have followed the steps here to install docker-ce on my Debain Stretch linux environment. After adding to the sources.list, I can not install docker-ce because `The package docker-ce was not found.`. Also, the convenience script did not work.

I'm using a regular Debian Stretch 32-bit release on an Oracle Virtual Box virtual machine.

### Expected behavior
Installation of docker-ce.

### Actual behavior
`sudo apt-get install docker-ce` returns `Package docker-ce was not found.`.

### Steps to reproduce the behavior
I went through all the steps to add the docker source repo to my local `sources.list`. Yet I can not install docker-ce.

**Comment by seemethere** [comment]
Seems to be right, we do not produce packages for 32bit unless explicitly for arm32.

**Comment by seemethere** [comment]
I don't believe the `docker-ce` package has ever been supported for a 32-bit linux environment outside of armv7

**Comment by artus** [comment]
Hmm that may be my bad, I will look into it tomorrow.

**Comment by artus** [comment]
This was indeed the problem, my memory failed me and I thought I always used 32-bit although I always used 64-bit virtual machines.
