### ISSUE TITLE
start returned error: unable to find \"systemd\" in controller set: unknown"

### ISSUE THREAD

**Issue by glaudiston** [docker/for-linux#469]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Create and start a container

### Actual behavior
The container is created but stopped, a generic error output is showed in the client. Ex:

    $ docker run -d ubuntu
    db3930baf5a2dc8f9466715d6a8fd1e1bc202cda9780e82ea26846646035a73f
    docker: Error response from daemon: unable to find "systemd" in controller set: unknown.

And in the dockerd log:

    Oct 28 20:12:26 tonlfs dockerd[22376]: time="2018-10-28T20:12:26.357889526-02:00" level=error msg="db3930baf5a2dc8f9466715d6a8fd1e1bc202cda9780e82ea26846646035a73f cleanup: failed to delete container from containerd: no such container"
    Oct 28 20:12:26 tonlfs dockerd[22376]: time="2018-10-28T20:12:26.358026339-02:00" level=error msg="Handler for POST /v1.38/containers/db3930baf5a2dc8f9466715d6a8fd1e1bc202cda9780e82ea26846646035a73f/start returned error: unable to find \"systemd\" in controller set: unknown"

### Steps to reproduce the behavior

**Output of `docker version`:**

```
glaudiston:~$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
glaudiston:~$ 

```

**Output of `docker info`:**

```
glaudiston:~$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: btrfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.15ton_lfs_x86_64
Operating System: Linux From Scratch 20170225-systemd
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.649GiB
Name: tonlfs
ID: ZLRS:HTZR:KDNN:YOMF:WYMY:C52D:GR3B:T4Y6:7PY3:RAMF:PDNL:VEOM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false


```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
* Physical Dell Laptop, Core i7, 16GB RAM;
* /dev/docker is a mounted file formatted as btrfs;
* host is a linuxfromscrach build;
kernel:

    glaudiston:~$ uname -a
    Linux tonlfs 4.14.15ton_lfs_x86_64 #4 SMP Fri Feb 2 00:55:19 BRST 2018 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Looks similar to https://github.com/moby/moby/issues/36169, however Linux From Scratch is not a supported distro for the Docker packages, and packages are not tested on that distro, so I'll close this issue for that reason.

Feel free to continue the conversation though

**Comment by glaudiston** [comment]
@thaJeztah , very thanks. 
After (as root) `rm -fr /sys/fs/cgroup`

The error changed to `start returned error: cgroups: cannot find cgroup mount destination: unknown`
then I did:

    mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd

And now it's working.

**Comment by thaJeztah** [comment]
Great! fwiw, I _think_ those should be setup automatically by systemd, so not sure why they were not present. I know that once this script was useful; https://github.com/tianon/cgroupfs-mount, but that was especially if you're not running `systemd`.

If you want to verify everything is set up properly, you can also run this script; https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh - that script will provide information about (possibly) missing things on your host.
