### ISSUE TITLE
Add old packages to the "obsoletes" of the new package

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/for-linux#473]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

So, the [install documentation](https://docs.docker.com/install/linux/docker-ce/centos/#uninstall-old-versions) says to uninstall _old versions_. I recently noticed that the [supported Puppet forge module](https://forge.puppet.com/puppetlabs/docker) doesn't attempt to manage old packages. They're kind of saying it's [not their problem](https://github.com/puppetlabs/puppetlabs-docker/issues/363#issuecomment-433991718).

That got me to ask the question in [a different context](https://stackoverflow.com/questions/53068299/how-do-i-ensure-legacy-docker-packages-are-uninstalled-before-installing-the-new) and [someone mentioned](https://stackoverflow.com/questions/53068299/how-do-i-ensure-legacy-docker-packages-are-uninstalled-before-installing-the-new/53068628?noredirect=1#comment93036937_53068299) that adding the old packages to the RPM's "obsoletes" might produce the correct behavior automatically.

> RPM removes all packages matching obsoletes of packages being installed.

http://rpm.org/user_doc/dependencies.html

This seems like good behavior! I wasn't able to find [much](https://github.com/docker/for-linux/issues/20#issuecomment-308850793) in the issue tracker. Can you comment on whether this is a desirable or likely feature to implement?

### Actual behavior

For example:

```
[root@localhost vagrant]# rpm -U docker-ce-18.06.1.ce-3.el7.x86_64.rpm
warning: docker-ce-18.06.1.ce-3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
error: Failed dependencies:
        docker conflicts with docker-ce-18.06.1.ce-3.el7.x86_64
        docker-io conflicts with docker-ce-18.06.1.ce-3.el7.x86_64
```

### Steps to reproduce the behavior

Install "old" package:

```
$ sudo yum install -y docker
```

Then try to install new package:

```
$ sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
$ sudo yum install -y docker-ce
```

**Comment by thaJeztah** [comment]
There's some "obsoletes" definitions in the RPM specs https://github.com/docker/docker-ce-packaging/blob/869920b98e4923f56f8549f2d380ab069a3bae2e/rpm/SPECS/docker-ce.spec#L28-L37, but perhaps it's deliberate to not "obsolete" packages that are not packaged by us (as in; should installing the official docker package automatically _uninstall_ the distro package, or is it better to leave that decision to the user installing the package?)

@jose-bigio @corbin-coleman perhaps you know if this was "by design"?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
