### ISSUE TITLE
Docker CE 17.06 Package Names on Ubuntu Don't Match Documentation

### ISSUE THREAD

**Issue by brodmerkle** [docker/for-linux#50]
### Expected behavior
Docker CE 17.06 package names on Ubuntu should match with the format specified in the documentation.

### Actual behavior

The Docker CE 17.06 packages no longer include the Ubuntu version at the end of the package name as on prior package versions and in the documentation - at least for Xenial.

### Information

On an Ubuntu 16.04 VM I configured the Ubuntu Xenial stable repository for amd64 per the Ubuntu installation guide (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/). However, a search for docker-ce package versions reveals a surprise:

```
root@myvm123/# apt-cache madison docker-ce
 docker-ce | 17.06.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 17.03.2~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 17.03.1~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 17.03.0~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
```

Starting with Docker CE 17.06, the package name now ends in ~ubuntu, instead of ~ubuntu-xenial. The change itself is harmless enough (I'm already pulling the package out of a Xenial repo, and I'm not going to have other non-Xenial docker-ce packages on the host). However, the Ubuntu install guide is quite explicit in https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-from-a-package that the package will have a -xenial suffix - in fact the docker-ce 17.06 package is actually shown as the example in the docs, but with a -xenial suffix: 

```
$ apt-cache madison docker-ce
docker-ce | 17.06.0~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
```

Is this an intentional change to the naming convention for these packages? If so, the Ubuntu install guide for Docker CE should be updated accordingly.

### Steps to reproduce the behavior

  1. Follow the steps in the Ubuntu installation guide for Docker CE.
  2. Observe naming convention for docker-ce packages inconsistent with documentation.

**Comment by seemethere** [comment]
Relates to: https://github.com/docker/docker-ce-packaging/pull/27

**Comment by andrewhsu** [comment]
cc @mstanleyjones

**Comment by AndrewCsoka** [comment]
Please could someone confirm whether this change was intentional or not?

**Comment by seemethere** [comment]
Change was intentional.

Closing per documentation change in docker/docker.github.io#3772
