### ISSUE TITLE
No match for argument: docker-ce

### ISSUE THREAD

**Issue by ghost** [docker/for-linux#500]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Just a **normal** latest Docker install without any issues by explicitly step by step following [official Docker documentation](https://docs.docker.com/install/linux/docker-ce/fedora/)

### Actual behavior
Output:
```
[dzintars@fedora ~]$ sudo dnf install docker-ce
Docker CE Edge - x86_64                                                                            469  B/s | 575  B     00:01    
Docker CE Stable - x86_64                                                                          474  B/s | 577  B     00:01    
Docker CE Test - x86_64                                                                            457  B/s | 575  B     00:01    
Failed to synchronize cache for repo 'docker-ce-edge', ignoring this repo.
Failed to synchronize cache for repo 'docker-ce-stable', ignoring this repo.
Failed to synchronize cache for repo 'docker-ce-test', ignoring this repo.
Last metadata expiration check: 0:01:04 ago on Sat 24 Nov 2018 04:54:22 PM EET.
No match for argument: docker-ce
Error: Unable to find a match
```

1) I have **freshly installed** regular Fedora 29. Just as addition - Fusion RPMs are enabled.

### Steps to reproduce the behavior
1) Go to to [official Docker documentation](https://docs.docker.com/install/linux/docker-ce/fedora/).
2) To be sure execute [uninstall](https://docs.docker.com/install/linux/docker-ce/fedora/#uninstall-old-versions).
3) Successfully executed [repo installation](https://docs.docker.com/install/linux/docker-ce/fedora/#install-using-the-repository). No any errors provided.
4) Enabled **edge** and **test** repos.
5) Executing `sudo dnf install docker-ce` and getting error posted above.
6) Did `sudo dnf clean all && sudo dnf upgrade` and repeated `sudo dnf install docker-ce` and got the same outcome.
7) Tried `sudo dnf install docker-ce-<version>` - no luck.
8) `sudo dnf install docker` installs docker 1.3 version which is too old for me.

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Bare metal SSD Raid10 Fedora 29 machine. Installing Docker on current host. KVM are enabled but not used.

**Comment by oswee** [comment]
Can documentation be updated properly? For example some "Attention" section added if there is some delays in packaging or so?

**Comment by katzs500** [comment]
Did someone resolved that?

**Comment by hiram-abif** [comment]
> Did someone resolved that?

I think this bug got forgotten since it's been almost 4 years. At this moment I think it's better to just use podman on Fedora.

**Comment by katzs500** [comment]
10x

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
