### ISSUE TITLE
nightly build not getting installed in Fedora 29

### ISSUE THREAD

**Issue by prajwel** [docker/for-linux#507]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

I tried to install docker-ce in Fedora 29 using `curl -fsSL get.docker.com | CHANNEL=nightly sh` as stated by @seemethere in #430. But this is not working and gives the following error. 

> [user@prajwel]$ curl -fsSL get.docker.com | CHANNEL=nightly sh
> # Executing docker install script, commit: 46dc063
> 
> Either your platform is not easily detectable or is not supported by this
> installer script.
> Please visit the following URL for more detailed installation instructions:
> 
> https://docs.docker.com/engine/installation/

**Comment by seemethere** [comment]
In the process of adding support here: https://github.com/docker/docker-install/pull/85
