### ISSUE TITLE
Package modification by apt fails on Linux Subsystem for Windows

### ISSUE THREAD

**Issue by sladiri** [docker/for-linux#52]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Install and removal `docker-ce_17.06.0~ce-0~ubuntu_amd64.deb` on Linux Subsystem for Windows succeeds.

### Actual behavior
The package removal or installation fails, this is the console output:
```
Do you want to continue? [Y/n]
Get:1 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce amd
64 17.06.0~ce-0~ubuntu [20.5 MB]
Fetched 20.5 MB in 1s (11.5 MB/s)
(Reading database ... 35863 files and directories currently installed.)
Preparing to unpack .../docker-ce_17.06.0~ce-0~ubuntu_amd64.deb ...
invoke-rc.d: could not determine current runlevel
 * Stopping Docker: docker
No process in pidfile '/var/run/docker-ssd.pid' found running; none killed.
invoke-rc.d: initscript docker, action "stop" failed.
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
invoke-rc.d: could not determine current runlevel
 * Stopping Docker: docker
No process in pidfile '/var/run/docker-ssd.pid' found running; none killed.
invoke-rc.d: initscript docker, action "stop" failed.
dpkg: error processing archive /var/cache/apt/archives/docker-ce_17.06.0~ce-0~ub
untu_amd64.deb (--unpack):
 subprocess new pre-removal script returned error exit status 1
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/docker-ce_17.06.0~ce-0~ubuntu_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Steps to reproduce the behavior
- Install a fresh Linux Subsystem for Windows (with Windows Creators Update, kernel 4.4.0-43-Microsoft).
- Install docker from official repo with apt-get (Docker version 17.03.1-ce, build c6d412e)
- Update, reinstall, removal fail

**Output of `docker version`:**

```
Docker version 17.03.1-ce, build c6d412e
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 13
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: T7KP:SFFR:U3LF:4LLC:GMU3:C7EE:QJVD:BC6S:7IYD:MS4V:ITJA:G5UM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2017-07-03T14:17:22.7704622Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
PC runs Windows 10 `build 15063.447`
with Docker for Windows `Version 17.06.0-ce-win18 (12627)`
docker client runs on Linux Subsystem for Windows and connects to Windows Docker: `export DOCKER_HOST='tcp://0.0.0.0:2375'`

**Comment by SK-Shadow** [comment]
Had the same issue, first i tried the following [https://askubuntu.com/a/510887](https://askubuntu.com/a/510887):

- sudo mv /var/lib/dpkg/info/docker.* /tmp/
- sudo dpkg --remove --force-remove-reinstreq docker.io
- sudo apt-get remove docker.io
- sudo apt-get autoremove && sudo apt-get autoclean

Then tried installing docker-ce:
- closed and reopened bash (WSL)
- sudo apt-get install docker-ce

And everything got back on track.
I hope that would solve your issue too.

**Comment by bfredtim** [comment]
Thanks @SK-Shadow you posted this fix literally 2 minutes after I found this bug report and subscribed. These steps worked 100%!

**Comment by sladiri** [comment]
Thank you, unfortunately I cannot try it out on my system, it has been reinstalled already.

**Comment by lineshvr** [comment]
Thanks @SK-Shadow ,you saved my lots of time. :)

**Comment by seemethere** [comment]
Looks like this has been solved by @SK-Shadow, closing this issue.

**Comment by lkjhvcxz2002** [comment]
@SK-Shadow Thanks!! You just saved my day.

**Comment by lkjhvcxz2002** [comment]
@SK-Shadow Thanks!! You just saved my day.

**Comment by pascal082** [comment]
Follow the instruction on Microsoft page to install docker on WLS

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers
