### ISSUE TITLE
docker-ce: docker-credential-secretservice not installed for Ubuntu "Disco Dingo" 19.04

### ISSUE THREAD

**Issue by denji** [docker/for-linux#534]
> docker-credential-secretservice not installed or not available in PATH

**Comment by khal3d** [comment]
I had the same issue on Ubuntu after removing the `docker-compose` using the package manager, and install the latest version of `docker-compose` manually.

To solve this issue, I had to run the following command

```
sudo apt install golang-docker-credential-helpers
docker logout
docker login
```

**Comment by ghusta** [comment]
Thanks, it worked.

However `docker login` was optional for me.
