### ISSUE TITLE
max_user_watches much lower than docker for mac

### ISSUE THREAD

**Issue by mjgallag** [docker/for-linux#537]
See https://github.com/docker/for-mac/issues/752#issuecomment-251945128 @justincormack's comment. During docker build on docker for mac max_user_watches = 524288 and my image build succeeds. On docker for linux it fails because max_user_watches = 8192.

**Comment by cpuguy83** [comment]
docker-for-mac comes with its own custom Linux distro.

For Docker on Linux, you should configure this yourself.
