### ISSUE TITLE
ce-packaging deb builds error with upstream cli

### ISSUE THREAD

**Issue by tophj-ibm** [docker/for-linux#54]
I'm using the docker-ce-packaging repo, and trying to build debs (I'm on ppc64le but it's reproducible on x86), and running into a gopath issue with the upstream cli repo. The problem stems from https://github.com/docker/cli/blob/master/scripts/docs/generate-man.sh#L7, which tries and installs md2man, but can't because the ce-packaging gopath doesn't have any links to md2man's dependencies. 

I don't know what the proper solution should be in this case (could be a change in the packaging repo dockerfiles, or in the cli repo scripts), so opening this issue here.

You can reproduce this in the packaging repo by setting the version in the Makefile, and then running `make deb`

```sh
LDFLAGS='' make -C cli VERSION=17.06.0 GITCOMMIT=82390ebf3 dynbinary manpages
make[2]: Entering directory '/cli'
./scripts/build/dynbinary
Building dynamically linked build/docker-linux-amd64
scripts/docs/generate-man.sh
vendor/github.com/cpuguy83/go-md2man/md2man.go:9:2: cannot find package "github.com/cpuguy83/go-md2man/md2man" in any of:
	/usr/local/go/src/github.com/cpuguy83/go-md2man/md2man (from $GOROOT)
	/go/src/github.com/cpuguy83/go-md2man/md2man (from $GOPATH)
Makefile:50: recipe for target 'manpages' failed
```

**Comment by tophj-ibm** [comment]
ping @andrewhsu

**Comment by thaJeztah** [comment]
@tophj-ibm is this still an issue? saw your last comment on https://github.com/docker/docker-ce-packaging/pull/32#issuecomment-326337434

**Comment by tophj-ibm** [comment]
@thaJeztah this issue isn't. The trusty image is though https://bugs.launchpad.net/cloud-images/+bug/1711735
