### ISSUE TITLE
image pulling on 18.09 doesn't work when McAfee is installed

### ISSUE THREAD

**Issue by BSchwetzel** [docker/for-linux#550]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I can pull docker images without error

### Actual behavior
```
# docker pull debian
Using default tag: latest
latest: Pulling from library/debian
cd8eada9c7bb: Extracting [==================================================>]  45.32MB/45.32MB
failed to register layer: Error processing tar file(exit status 1): open /etc/passwd: permission denied
```
**This error does not occur in 18.06.1.**

### Steps to reproduce the behavior
see above.

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 67
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: ugroa1cmw9zirkb8silyksfh3
 Is Manager: true
 ClusterID: jnibhq6jczsycm0h680tdh58g
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.x.x.x
 Manager Addresses:
  10.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.779GiB
Name: devclient
ID: SXUE:J5L2:ZNOX:MZRQ:ZVLJ:7VUW:IGUV:XAQQ:YQGT:CAX6:NBRU:4VNC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://xxx.xxx:3128
HTTPS Proxy: http://xxx.xxx:3128
No Proxy: .xxx.xxx,localhost
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Well this is a bit complicated. My client is a VM with Ubuntu 16.04.5. My organization has installed some kind of McAfee on my client, unfortunately I am not aware of its configuration. What I do know is that the name of the identified threat is IDS_AP_RULE_PREVENT_MODIFICATION_PASSWORDFILES_LINUX. I do not know whether that is a rule shipped by McAfee or a rule that we have created.

Pls note that I did find two seemingly related reports, unfortunately without a real solution: https://forums.docker.com/t/install-centos-in-docker-failed-to-register-layer/52265 and https://github.com/moby/moby/issues/37817, although the latter is using a different version of docker, so I'd take this with a grain of salt.

**Comment by VinayKumarKnol** [comment]
@BSchwetzel , it seems like the pull mechanism is trying to gain the trust creds from the /etc/pass before pulling. It could be the case that the read by the docker application has been prohibited by the McAfee setup. Could you please check the rules you have mentioned.

**Comment by BSchwetzel** [comment]
To be honest, I totally forgot about this issue. My organization disabled the rule for me, therefore I am no longer affected and don't have access to an environment where this still happens. It seems this is a rule that's shipped by McAfee though. 

Still, it might be interesting to know what docker does (or did) with the /etc/passwd file. I really don't see why it should even interact with it. If it wanted to know if I am authorized to connect to the socket it'd have to look in /etc/group, but then it shouldn't even have started the pulling process.

Maybe it's not even docker itself that accesses it. Who knows, I certainly don't :) Feel free to close this if this question is out of scope.

**Comment by virtuald** [comment]
I'm running into this problem on Ubuntu 14.04.5, with rootless docker master-2019-10-09. I know it's a bit old, but when I disable the AV it seems to work. I'll try to get them to disable that particular rule and see if that helps.

**Comment by PriyankPa** [comment]
Any update on this? I am running rootless docker and encountering the same issue on Ubuntu 18.0
Having to turn off AV raises lot of eyebrows.

**Comment by SuperSandro2000** [comment]
https://kc.mcafee.com/corporate/index?page=content&id=KB90041

Otherwise talk with your org or use your own device.

**Comment by thaJeztah** [comment]
This doesn't look like something that can be fixed in the docker codebase; if you're still running into this, I'd recommend opening a support ticket with McAfee (or update the configuration).

Let me close this one, but feel free to continue the conversation
