### ISSUE TITLE
docker volume cause directory empty

### ISSUE THREAD

**Issue by jamz1995** [docker/for-linux#554]
When i run follow command：

`docker run -d -p 8080:8080  -v /root/webapps:/usr/local/tomcat/webapps`

It cause /usr/local/tomcat/webapps is empty,It's why?

**Comment by seemethere** [comment]
Is `/root/webapps` empty on your local machine?

Correct syntax for volume mounting is:

```bash
-v ${LOCAL_SOURCE}:${CONTAINER_DEST}
```

**Comment by jamz1995** [comment]
My local machine directory `/root/webapps` originally empty
But container directory `/usr/local/tomcat/webapps` is not empty original
When i run `docker run -d -p 8080:8080 -v /root/webapps:/usr/local/tomcat/webapps`
It cause container  directory `/usr/local/tomcat/webapps` also is empty.
I think my syntax for volume is correct,so it's why?

**Comment by cpuguy83** [comment]
This is a bind mount. Bind mounts mask over the target with the source content, this includes subtrees.

Since the source is empty, this seems to be working as expected.

**Comment by jamz1995** [comment]
@cpuguy83 You are right,bind mount will override container directory content if directory is not empty.

By the way.I use docker version 1.13.X and docker storage driver the default is overlays2,it cause this problem.

I use docker version 1.12.X and docker storage driver the default is devicemapper,it not cause this problem.

So this problem is related to docker storage driver?

**Comment by cpuguy83** [comment]
No, it's the same behavior  o matter the storage driver. Are you sure you did the same exact operation under both versions?

**Comment by jamz1995** [comment]
@cpuguy83 It seems that I remembered it wrong,it's indeed the same behavior.
Thanks a lot
