### ISSUE TITLE
https://download.docker.com/ blocks access from Ukraine

### ISSUE THREAD

**Issue by z0rc** [docker/for-linux#57]
```
curl https://download.docker.com/                
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: heKYq02LigAwWHtxiSnjSDllcrtxpdyDitVlRn2JSOBRe29Xkk_6Fw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

Please revert this change ASAP, as this breaks CI pipelines for every Ukrainian company that uses docker.

Initially reported at https://github.com/docker/distribution/issues/2329

**Comment by z0rc** [comment]
Also reported at https://github.com/moby/moby/issues/34052

**Comment by alexkostenko** [comment]
Same here.

**Comment by romulko** [comment]
as a workaround, you can use a proxy site to access content - https://www.proxysite.com/

**Comment by valentinsmoliy** [comment]
very disappointed thing from docker

**Comment by valeriyyakubovich** [comment]
The same.

**Comment by kufd** [comment]
The same porblem

**Comment by 31H0B1eV** [comment]
curl -I https://download.docker.com
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Tue, 11 Jul 2017 15:11:30 GMT
Content-Type: text/html
Content-Length: 622
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 f989b812753677758cd8909391e239ac.cloudfront.net (CloudFront)
X-Amz-Cf-Id: tfwWsK6mLZPSPyhb-SgYjZC44IPX79yjYC7HNgy_nLegSLJ6B_mIcg==

**Comment by justincormack** [comment]
I believe this is likely related to the US sanctions on Crimea https://www.treasury.gov/resource-center/sanctions/Programs/Documents/ukraine.txt

**Comment by 31H0B1eV** [comment]
There is no sanction for Ukraine.

**Comment by SirEdvin** [comment]
@justincormack But why now?)

**Comment by justincormack** [comment]
@31H0B1eV we have had some comments from people in Kiev saying they are not affected eg https://github.com/moby/moby/issues/34052#issuecomment-314444228 - it is possible that the geolocation is incorrect. I have not reached anyone who knows any more detail about this yet.

**Comment by 31H0B1eV** [comment]
Yep thanks, this is country ip blocking. Now i see this 
> The Amazon CloudFront distribution is configured to block access from your country. 
From Donetsk region of Ukraine.
It works from proxy. But ok, i can stay without docker easily.

**Comment by idvoretskyi** [comment]
@justincormack I can confirm that it doesn't work for me as well.

**Comment by samodid** [comment]
I checked it from several servers in Odessa and Lviv, it does not work for me.

**Comment by yermulnik** [comment]
Same issue here (Kyiv) via two independent ISPs.

**Comment by Ed-88** [comment]
+1 Kharkiv

**Comment by onorua** [comment]
same here

**Comment by jbaruch** [comment]
You are all invited to start a trial of [Artifactory SaaS](https://www.jfrog.com/artifactory/versions/#Cloud). Having it in a non-blocked zone will give you full access to Docker Hub as a Docker Registry.
Assuming they will fix it in a month, no costs for you.

**Comment by adiachenko** [comment]
I wish we stopped pointing fingers at ISP, because Docker isn't by far the only thing hosted on AWS and so far we haven't heard of reports from other service providers.

You know, just because you can use CloudFront geo restriction rules [doesn't mean you should](http://www.urbandictionary.com/define.php?term=trigger%20happy). What if (hypothetically speaking) that hit US? Do you imagine what shitstorm that would have been?

**Comment by excieve** [comment]
Seems to be working now, thanks!

**Comment by adiachenko** [comment]
It's working for me now too.

**Comment by binman-docker** [comment]
Hey everyone, sorry for the trouble. The IP restrictions put in place per US embargo rules were too extensive. We've unblocked Ukraine now and I'm glad to see it's working properly again. Thanks for raising the issue!

**Comment by NabiKAZ** [comment]
You can try this solution: #363
