### ISSUE TITLE
Docker CE fails to install on CentOS 7.5.1804

### ISSUE THREAD

**Issue by Ezekiel-DA** [docker/for-linux#572]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker CE installs correctly from Yum package.

### Actual behavior
Installation fails with:
```
Error: Package: policycoreutils-python-2.5-22.el7.x86_64 (cent-7-os)
           Requires: policycoreutils = 2.5-22.el7
           Installed: policycoreutils-2.5-29.el7.x86_64 (installed)
               policycoreutils = 2.5-29.el7
           Available: policycoreutils-2.5-22.el7.x86_64 (cent-7-os)
               policycoreutils = 2.5-22.el7
```

### Steps to reproduce the behavior
Try to install from the official Docker repos on CentOS 7.5.1804:
```
[root@ag-wal-v6bot ~]# uname -a
Linux ag-wal-v6bot 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@ag-wal-v6bot ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core)
Release:        7.5.1804
Codename:       Core
[root@ag-wal-v6bot ~]# yum install docker-ce
```

This results in the error above.

**Output of `docker version`:**
N/A

**Output of `docker info`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.)**
vSphere VM

**Comment by seemethere** [comment]
Doesn't seem to be an issue with the docker package itself but rather than issue with `policycoreutils-python ` package requiring a newer version of `policycoreutils` than is provided.

Going to close this since it doesn't really pertain to docker itself. Feel free to continue the discussion in this thread though.

**Comment by Ezekiel-DA** [comment]
Actually, I think the problem is the reverse: `policycoreutils-python` seems to be pinned to an exact version of `policycoreutils`, and the latter (already installed) is newer that the newest version of the former that can be installed.

That did lead me to the right answer though: it seems our IT has local mirrors of CentOS repos that do not contain the latest version of `policycoreutils-python`, hence my problem.

So it turned out to be a self inflicted wound, but at least I've gotten better at reading the output of yum and understanding dependencies, I guess!
