### ISSUE TITLE
Error initializing graphdriver: backing file system is unsupported for this graph driver (ZFS)

### ISSUE THREAD

**Issue by Akito13** [docker/for-linux#579]
Not sure if this is consciously unsupported, or by accident, so I ticked on both, bug and feature.
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
`# systemctl start docker`
_No output_, because the daemon started successfully.

### Actual behavior
```
# systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

```
# journalctl -xe
:58+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock"
:58+01:00" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock"
:58+01:00" level=info msg="containerd successfully booted in 0.035228s"
:58+01:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x13e46c40, READY" module=grpc
:58+01:00" level=info msg="parsed scheme: \"unix\"" module=grpc
:58+01:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
:58+01:00" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd
:58+01:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
:58+01:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x13e22d90, CONNECTING" module=grpc
:58+01:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0x13e22d90, READY" module=grpc
:58+01:00" level=error msg="'overlay2' is not supported over zfs" storage-driver=overlay2
:58+01:00" level=error msg="[graphdriver] prior storage driver overlay2 failed: backing file system is unsupported for this graph driver"
Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver
docker.service: Main process exited, code=exited, status=1/FAILURE
Failed to start Docker Application Container Engine.
```

### Steps to reproduce the behavior

1. `nano /etc/systemd/system/docker.service.d/docker-storage.conf`
1. Pasted
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// --data-root="/mnt/my-zfs-pool/docker"
```
3. `mv /var/lib/docker /mnt/my-zfs-pool/docker`
4. `systemctl start docker`

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

  Operating System: Raspbian GNU/Linux 9 (stretch)
            Kernel: Linux 4.14.79-v7+
      Architecture: arm

Hardware: Raspberry Pi 3 B+

**Comment by cpuguy83** [comment]
It sounds like you need to specify "zfs" as the storage driver, otherwise it will try to use overlay.

**Comment by Akito13** [comment]
> 
> 
> It sounds like you need to specify "zfs" as the storage driver, otherwise it will try to use overlay.

Thank you, for the info. I will read [this](https://docs.docker.com/storage/storagedriver/select-storage-driver/ "Docker Storage Drivers") and [this](https://docs.docker.com/storage/storagedriver/zfs-driver/ "ZFS Storage Driver"). I assume that this will be enough to solve the issue, so I am closing this issue. I will re-open or re-create if I will encounter further errors.

**Comment by akvadrako** [comment]
It looks like overlay2 is not supported on ZFS. I don't get the error message described above but with Docker 20.10.2 I do see:

> Jan 28 11:38:36 micro dockerd[6432]: time="2021-01-28T11:38:36.192458900+01:00" level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
