### ISSUE TITLE
"SecureJoin too many links" when mapping /dev to container

### ISSUE THREAD

**Issue by joseivan** [docker/for-linux#588]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

Hello,
I'm receiving a strange behavior when running a container when mapping /dev. I've made some tests and it is related with /dev/shm being a symbolic link to /run/shm.
If a run this way or /dev/shm is not a symbolic link it is ok
`docker container run -it -v/dev:/dev -v/run:/run ubuntu:xenial bash`

### Expected behavior
Container should be created and /dev should be mapped successfully.

### Actual behavior
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/containers/737382597b2da9e393cedfbe28874e03eb0a9f86190d4c238d21189b95238bd8/mounts/shm\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/39db01bff3733e3f5e82a7796b83e3925e4fdb7722ec07af9a3b17953698182b\\\" at \\\"/dev/shm\\\" caused \\\"SecureJoin: too many links\\\"\"": unknown.

### Steps to reproduce the behavior
/dev/shm should be a symbolic link to /run/shm
`docker container run -v/dev:/dev -it ubuntu:xenial bash`

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:58 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:24 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 245
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 302
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
Kernel Version: 4.4.0-142-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name: ivanLINUX
ID: TL4M:2NNX:WMI5:MQXI:HCFV:DRMI:ERMW:6CON:TYFN:GA52:W3RH:AZQW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: 127.0.0.1,localhost
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by joseivan** [comment]
The problem was Ubuntu images has inverse link. /run/shm -> /dev/shm which was causing loop.

**Comment by cjds** [comment]
What was your workaround?

**Comment by joseivan** [comment]
I had to change my host fstab to mount shm fs at /run/shm to follow docker ubuntu pattern.

**Comment by JUNgege10** [comment]
I had the same problem with ubuntu14.04, /run/shm and /dev/ SHM are soft links, can you describe your specific solution in detail? Thank you very much

**Comment by jbcpollak** [comment]
I'm having this problem with WSL2 and am unclear how to fix - fstab is empty in the WSL image.
