### ISSUE TITLE
Docker assigning already taken MAC Address

### ISSUE THREAD

**Issue by MarcelKallen** [docker/for-linux#589]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
New containers should not get a MAC address that is already taken

### Actual behavior
When inspecting the bridge interface the first and the new created container where having the same MAC address. None of the container got a manual configured MAC address.

The mac address that has been given two times: 02:42:ac:11:00:03

```bash
docker network inspect bridge | grep MacAddress
                "MacAddress": "02:42:ac:11:00:03",
                "MacAddress": "02:42:ac:11:00:09",
                "MacAddress": "02:42:ac:11:00:03",
                "MacAddress": "02:42:ac:11:00:08",
                "MacAddress": "02:42:ac:11:00:06",
                "MacAddress": "02:42:ac:11:00:04",
                "MacAddress": "02:42:ac:11:00:0b",
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Physical Host

**Comment by MarcelKallen** [comment]
Actually i´ve got the same problem.

```
docker network inspect bridge | grep MacAddress
                "MacAddress": "02:42:ac:11:00:03",
                "MacAddress": "02:42:ac:11:01:09",
                "MacAddress": "02:42:ac:11:00:08",
                "MacAddress": "02:42:ac:11:00:04",
                "MacAddress": "00:0c:29:88:30:cc",
                "MacAddress": "02:42:ac:11:00:06",
                "MacAddress": "02:42:ac:11:00:04",
                "MacAddress": "02:42:ac:11:00:0a",
                "MacAddress": "02:42:ac:11:00:0b",
```

Docker Version
``` 
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056dbc
 Built:             Thu Apr 11 04:44:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

System
```No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch```

**Comment by MarcelKallen** [comment]
Still no answer?

**Comment by arkodg** [comment]
@MarcelKallen can you please share the
1. Steps to reproduce this issue
2. And Also share `docker inspect bridge` and `docker inspect <container-name>` logs for the containers with identical MacAddress

**Comment by MarcelKallen** [comment]
Currently I´m not able to reproduce this, its happening sometimes.
If nobody is able to reproduce, I will just change the mac if it happens again (as im doing currently).

**Comment by mateuszdrab** [comment]
I've been suffering with a networking issue inside my docker environment for a while, always occurring after a reboot... finally gave it a deeper look as this weeks patching reboot caused the issue to reoccur and ended up here. 
I am suffering the same exact issue, mac address "02:42:ac:11:00:02" is duplicated. Since my docker environment is composed of rather static containers (they get recreated by watchtower), but normally stay as they are, this sounds to me like some kind of a race condition when docker starts all the containers at the same time.

Pinging the affected IP results with
```
ping 172.17.0.6
PING 172.17.0.6 (172.17.0.6) 56(84) bytes of data.
From 172.17.0.2: icmp_seq=1 Redirect Host(New nexthop: 172.17.0.6)
From 172.17.0.2: icmp_seq=2 Redirect Host(New nexthop: 172.17.0.6)
From 172.17.0.2: icmp_seq=3 Redirect Host(New nexthop: 172.17.0.6)
From 172.17.0.2: icmp_seq=4 Redirect Host(New nexthop: 172.17.0.6)
From 172.17.0.2: icmp_seq=6 Redirect Host(New nexthop: 172.17.0.6)
From 172.17.0.2 icmp_seq=5 Destination Host Unreachable
From 172.17.0.2 icmp_seq=6 Destination Host Unreachable
From 172.17.0.2: icmp_seq=9 Redirect Host(New nexthop: 172.17.0.6)
64 bytes from 172.17.0.6: icmp_seq=10 ttl=64 time=0.095 ms
From 172.17.0.2 icmp_seq=8 Destination Host Unreachable
From 172.17.0.2 icmp_seq=9 Destination Host Unreachable
From 172.17.0.2 icmp_seq=11 Destination Host Unreachable
From 172.17.0.2 icmp_seq=12 Destination Host Unreachable
From 172.17.0.2 icmp_seq=13 Destination Host Unreachable
```

and

`docker network inspect bridge | grep MacAddress` results with

                "MacAddress": "02:42:ac:11:00:09",
                "MacAddress": "02:42:ac:11:00:0d",
                "MacAddress": "02:42:ac:11:00:0a",
                "MacAddress": "02:42:ac:11:00:0c",
                "MacAddress": "02:42:ac:11:00:0e",
                "MacAddress": "02:42:ac:11:00:10",
                "MacAddress": "02:42:ac:11:00:03",
                "MacAddress": "02:42:ac:11:00:02",
                "MacAddress": "02:42:ac:11:00:08",
                "MacAddress": "02:42:ac:11:00:07",
                "MacAddress": "02:42:ac:11:00:02",
                "MacAddress": "02:42:ac:11:00:0a",
                "MacAddress": "02:42:ac:11:00:05",
                "MacAddress": "02:42:ac:11:00:0b",
                "MacAddress": "02:42:ac:11:00:0f",

Some more platform details:
```Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Platform is, VMware ESXi VM, Ubuntu 18.04 kernel 5.3.0-46-generic.

**Comment by Zammla** [comment]
@mateuszdrab I'm suffering with this issue for weeks now. I searched the whole internet but couldn't find anything. My ping results are similar to yours:
![image](https://github.com/docker/for-linux/assets/34284567/b467f1da-9144-4848-949d-ab8e3ba8ead6)

I also noticed the mac address problem:
![image](https://github.com/docker/for-linux/assets/34284567/23af5309-fe82-46ed-934a-09e27acb9cae)

It would be awesome if you found a solution! I'm going crazy with this.



Docker info:
`Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 59
  Running: 48
  Paused: 0
  Stopped: 11
 Images: 65
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.72GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 1079
  Goroutines: 1073
  EventsListeners: 0
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`
