### ISSUE TITLE
docker command not foundf

### ISSUE THREAD

**Issue by deo999** [docker/for-linux#592]
i am try to install docker in centos7 but getting following error

-bash: docker: command not found
sudo systemctl status docker is working fine.
can you please help how to fix??

**Comment by thaJeztah** [comment]
Does it work if you try to call it using its full path? (e.g., `/usr/bin/docker --version`)?

**Comment by VinayKumarKnol** [comment]
@deo999 , you should try using `which docker`. This will tell you whether the docker binary exists within the PATH directory or not.

**Comment by thaJeztah** [comment]
Let me close this ticket, as there's not a lot of information to go on


Thanks for helping, @VinayKumarKnol 🤗
