### ISSUE TITLE
Unable to install docker-ce-cli and containerd.io

### ISSUE THREAD

**Issue by BentCoder** [docker/for-linux#596]
Hi,

I get `E: Unable to locate package docker-ce-cli` and `E: Unable to locate package containerd.io` error message when running `$ sudo apt-get install docker-ce docker-ce-cli containerd.io`. However, whole installation works fine so I can use `docker` commands. I need to install `docker-ce-cli` though because apparently Jenkins Pipeline needs it in order to use `docker-compose` commands.

I am on `Debian GNU/Linux 8 (jessie) 3.16.0-4-amd64`

Thanks

**Comment by sotiris-oikonomou** [comment]
How did you solve it? I am having the same issue.

**Comment by BentCoder** [comment]
Created a Makefile and moved all docker commands into it then used those make commands in the Jenkinsfile.
