### ISSUE TITLE
shim-log.json: no such file or directory

### ISSUE THREAD

**Issue by jaykam** [docker/for-linux#605]
Hello @garethr @thaJeztah @silvin-lubecki 

I'm running the docker using the command line from last 1 year
`docker run -it image_id`

docker version is  `18.06.1-ce, build e68fc7a`

But suddenly I got this error in system logs of ubuntu

`time="2019-02-27T13:46:42.887661485Z" level=error msg="Create container failed with error: open /var/run/docker/libcontainerd/containerd/bcb5b8366904f82c53c41abb8cada31687ee376e7674483b237935378cef7147/init/shim-log.json: no such file or directory"`
`time="2019-02-27T13:46:42.956869973Z" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/9363077e0258470c90f6803e4708c2325455ed216c389e4f9dae795b409a615a: exec: \"auplink\": executable file not found in $PATH"`

Is this related to docker version or something else?

**Comment by abdilahrf** [comment]
same issue with me

**Comment by thaJeztah** [comment]
Can you post the output of `docker info` ?

**Comment by abdilahrf** [comment]
already solved by remove and install again the docker

**Comment by jaykam** [comment]
@thaJeztah 
You can see the docker info:

`
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 1
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42GiB
Name: ip-172-21-10-204
ID: JN3S:XLLC:PGKE:NL2P:E3FW:WSBV:JXNY:CFZA:M4LX:6D4Q:DXHZ:QSMD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
`

**Comment by jaykam** [comment]
@thaJeztah 
You can find the docker info:

`Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 1
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42GiB
Name: ip-172-21-10-204
ID: JN3S:XLLC:PGKE:NL2P:E3FW:WSBV:JXNY:CFZA:M4LX:6D4Q:DXHZ:QSMD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
`

**Comment by jaykam** [comment]
> Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 1
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42GiB
Name: ip-172-21-10-204
ID: JN3S:XLLC:PGKE:NL2P:E3FW:WSBV:JXNY:CFZA:M4LX:6D4Q:DXHZ:QSMD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by thaJeztah** [comment]
From this information, looks like this is a non-standard package; did you install from the official packages (https://docs.docker.com/install/linux/docker-ce/ubuntu/)?

```
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
```

Are you still able to reproduce this on the current version of Docker (18.09)?

**Comment by jaykam** [comment]
@thaJeztah 

No, I installed docker from this command
`sudo apt install docker.io`

And the answer to your 2nd question is "**No**"
docker version is `18.06.1-ce, build e68fc7a`

**Comment by jaykam** [comment]
@thaJeztah @abdilahrf 

This issue has been resolved by installing docker enterprise version.
As you can see the commands to install the docker:

`sudo apt-get install apt-transport-https ca-certificates curl software-properties-common --yes
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
sudo apt-get update
sudo apt-get install docker-ce
`
