### ISSUE TITLE
Multi-stage should build only what is needed

### ISSUE THREAD

**Issue by kenorb** [docker/for-linux#607]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

I've got [`Dockerfile` file](https://github.com/EA31337/EA31337/blob/25817bc6e0e811f0d478df8112193b1b79e7a4f2/Dockerfile) where I build 3 type of images, however when I target one, all other are built as well. This is very not efficient.

Here is a simple configuration:

```
FROM ubuntu as a
FROM ubuntu as b
FROM ubuntu as c

# a
FROM a as a-a
FROM a-a as a-a-a

# b
FROM b as b-b
FROM b-b as b-b-b

# c
FROM c as c-c
FROM c-c as c-c-c
```

### Expected behavior

When building `b-b`'s, I don't expect to build `a-a`'s.

So what I'm saying, when I've multiple targets such as a, b, c each few gigs, I don't want a and b, when building c, because it's too time consuming.

### Actual behavior

Below building `a-a` and `a-a-a` is pointless, because it's not used by `b-b`.
```
$ docker build --target b-b .
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM ubuntu as a
 ---> 47b19964fb50
Step 2/6 : FROM ubuntu as b
 ---> 47b19964fb50
Step 3/6 : FROM ubuntu as c
 ---> 47b19964fb50
Step 4/6 : FROM a as a-a
 ---> 47b19964fb50
Step 5/6 : FROM a-a as a-a-a
 ---> 47b19964fb50
Step 6/6 : FROM b as b-b
 ---> 47b19964fb50
```

Same with `c-c-c`'s:

```
$ docker build --target c-c-c .
Sending build context to Docker daemon  2.048kB
Step 1/9 : FROM ubuntu as a
 ---> 47b19964fb50
Step 2/9 : FROM ubuntu as b
 ---> 47b19964fb50
Step 3/9 : FROM ubuntu as c
 ---> 47b19964fb50
Step 4/9 : FROM a as a-a
 ---> 47b19964fb50
Step 5/9 : FROM a-a as a-a-a
 ---> 47b19964fb50
Step 6/9 : FROM b as b-b
 ---> 47b19964fb50
Step 7/9 : FROM b-b as b-b-b
 ---> 47b19964fb50
Step 8/9 : FROM c as c-c
 ---> 47b19964fb50
Step 9/9 : FROM c-c as c-c-c
 ---> 47b19964fb50
```

### Steps to reproduce the behavior

As already shown above.

**Output of `docker version`:**

```
Docker version 18.09.2, build 6247962
```

**Output of `docker info`:**

```
Kernel Version: 4.18.0-15-generic
Operating System: Ubuntu 18.10
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 125.6GiB
```

**Comment by cpuguy83** [comment]
Enable buildkit support and this will do what you want:
https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds

**Comment by kenorb** [comment]
Thank you, it works.
