### ISSUE TITLE
docker creates folder on host for docker volumes

### ISSUE THREAD

**Issue by nrobert13** [docker/for-linux#609]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker doesn't create folders on host system for docker volumes.

### Actual behavior
Mounting a host path into conteiner, and inside this host mount a docker volume, it creates a folder on the host under the host path.

### Steps to reproduce the behavior

1. make sure  /tmp/ttt doesn't exist on the host

2. run `docker run -it --rm --mount 'type=bind,src=/tmp,dst=/tmp' --mount 'type=volume,dst=/tmp/ttt' busybox` or
`docker run -it --rm -v /tmp:/tmp -v /tmp/ttt busybox`

3. check /tmp/ttt

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 215
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.39GiB
Name: nrobert-XPS-13
ID: VBR3:EYAS:V64B:KZR6:DCGE:KPVG:NRNW:26IT:LWZK:DNYV:HCZT:J46T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
There's exactly two ways that Docker could handle this:

1) the current behavior 
2) allow mounts to shadow other mounts 

In case two this would completely break your usage of volumes with bind mounts.
Basically you can't mix mounts like this without either the "/tmp" mount completely overshadowing the volume or the volume getting mounted to the host side (which also necessarily means it must create the dir).

Hidden option three would be to return an error in such cases.

**Comment by nrobert13** [comment]
I see. Thanks for the quick reply. I thought there would be a way to apply the volume in the container as an additional layer, which wouldn't reflect te changes in the host..., but I'm not that familiar with overlayfs, not sure if possible.

**Comment by cpuguy83** [comment]
We don't support overlay mounts right now. If we did it would still need to be a different mount type (e.g. `type=overlay` instead of `type=bind`).

**Comment by nrobert13** [comment]
Are there maybe ongoing efforts or plans to do it?

**Comment by cpuguy83** [comment]
Not that I am aware of.

**Comment by nrobert13** [comment]
thanks for the info! I guess we can close this.
