### ISSUE TITLE
Docker Toolbox packages not included in index on download.docker.com

### ISSUE THREAD

**Issue by thaJeztah** [docker/for-linux#62]
* [x] This is a bug report
* [x] This is a feature request
* [ ] I searched existing issues before opening this one

The Docker Toolbox page on www.docker.com (https://www.docker.com/products/docker-toolbox) has download links for Docker Toolbox;

- https://download.docker.com/mac/stable/DockerToolbox.pkg
- https://download.docker.com/win/stable/DockerToolbox.exe

However, trying to navigate to these downloads using the index on download.docker.com is not possible;

<img width="641" alt="screen shot 2017-07-19 at 00 44 52" src="https://user-images.githubusercontent.com/1804568/28343036-2a96e1f6-6bd0-11e7-8b1e-e02daf05d23d.png">

Can the index be updated to also show these packages (preferably older versions as well)?

ping @seemethere @andrewhsu PTAL

**Comment by seemethere** [comment]
Don't think this is an issue anymore, closing.

**Comment by thaJeztah** [comment]
@seemethere links are still there, and packages still are not visible in the index page; https://docs.docker.com/toolbox/overview/#ready-to-get-started 

https://download.docker.com/mac/
