### ISSUE TITLE
Can Docker containers use LXD's LXDBR0 bridge instead of the Docker0

### ISSUE THREAD

**Issue by bmullan** [docker/for-linux#621]
I use Ubuntu 18.04 and LXD.

LXD connects to the Host via a bridge called LXDBR0 and the containers get their IP addresses all on a 10.0.0.0 network.

**_I can successfully create/install Docker based web apps in an LXD container_** but by default they use the DOCKER0 bridge and get their IP addresses on a 172.x.x.x network and have no direct access to the Host as they are nested in an LXD container on a 10.x.x.x network.

My question is could a Docker container be configured to use the same LXDBR0 bridge as the LXD containers and then not need to be nested **but be a "peer" container** on the LXD 10.x.x.x network.

Looking at this: https://developer.ibm.com/recipes/tutorials/networking-your-docker-containers-using-docker0-bridge/

I think this might be possible but as I am not any kind of Docker guru I thought I'd ask here for advice or ideas how or if I could do this.

Thanks
Brian

**Comment by cpuguy83** [comment]
You can configure the bridge (--bridge option), however sharing the bridge is probably not a good idea.

**Comment by bmullan** [comment]
@cpuguy83 
Thanks for your reply.  

Could you expand on why sharing the bridge wouldn't be a good idea?  Bridge is a bridge unless there is something else Docker expects its bridge to the host to do that would affect LXD or that using the LXDBR0 bridge might do to adversely impact the Docker Containers?

**Comment by cpuguy83** [comment]
I think IP allocation conflicts become a problem here.
Instead you could setup static routing.

**Comment by bmullan** [comment]
If they are using just the LXDBR0 bridge they would/should all be using the
same DHCP server as well right?   That would prevent ip addressing
conflicts unless there was manual intervention/configuration.

**Comment by cpuguy83** [comment]
No, there is no DHCP. Docker assigns the IP address.

**Comment by bmullan** [comment]
oh, ok... then there could be a problem doing this...

thanks for you answers.
Brian
