### ISSUE TITLE
Getting this error when trying to install docker and failing to do so over and over again."E: Unable to locate package docker-ce-cli"

### ISSUE THREAD

**Issue by abhinav22rana** [docker/for-linux#623]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by davidcsi** [comment]
this is also happening to me when trying to install following https://docs.docker.com/install/linux/docker-ce/debian/
on a clean AWS instance Debian Jessie

**Comment by thaJeztah** [comment]
If you're trying to install `docker-ce-cli` on Debian jessie, that's expected; see my reply on https://github.com/docker/for-linux/issues/633

without more information, that's hard to tell though, so closing this issue, but feel free to continue the conversation
