### ISSUE TITLE
docker 18.09.x missing packages for power platform

### ISSUE THREAD

**Issue by mkumatag** [docker/for-linux#629]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
18.09.x docker-ce packages are missing for power platform
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/ppc64el/

**Comment by thaJeztah** [comment]
ping @seemethere PTAL

**Comment by andrewhsu** [comment]
Difficulty procuring ppc64le resources for our build pipeline forced us to turn off ppc64le releases for 18.09. Currently working on what the status of ppc64le resources will be for supporting builds for the future. cc @dave-tucker

**Comment by clnperez** [comment]
@mkumatag I'm aware, and have been talking to the team about this. We've let them know we're available to help, so, hopefully we can figure something out that makes everyone's life easier. :)

**Comment by mkumatag** [comment]
> Difficulty procuring ppc64le resources for our build pipeline forced us to turn off ppc64le releases for 18.09. Currently working on what the status of ppc64le resources will be for supporting builds for the future. cc @dave-tucker

@andrewhsu @dave-tucker did we make any further progress on this or we are still waiting for the resources?

**Comment by qhaas** [comment]
Appreciate Docker taking the time to consider those of us using ppc64le.  Up-to-date Docker Community Edition packages are becoming more important given the latest updates to upstream docker / nvidia-docker are [altering the workflow](https://github.com/NVIDIA/nvidia-docker/tree/master#upgrading-with-nvidia-docker2-deprecated).  Currently, the version of Docker provided by the third-party repository [documented by IBM](https://developer.ibm.com/linuxonpower/docker-on-power) doesn't seem to be compatible with the latest nvidia-docker stack.

**Comment by lazystone** [comment]
Is there any update on the issue? If problem is in the hardware then could somebody from Docker get in contact with IBM representatives or might be [those guys](https://openpowerfoundation.org/) can help.

I'm pretty sure that IBM will be happy to provide some hardware for Docker for free.

**Comment by thaJeztah** [comment]
@lazystone there's some people from IBM in this thread, and there's a conversation ongoing with people there to see if we can reinstate the build-pipeline for power and s390x

**Comment by lazystone** [comment]
Good to hear. We are trying to use power servers but lack of support sometimes frustrating. Thanks for an update!

**Comment by qhaas** [comment]
> 
> 
> there's some people from IBM in this thread

Hopefully, they've seen [this related thread](https://github.com/NVIDIA/libnvidia-container/issues/69#issuecomment-584389216) over on the libnvidia-container issues section as well.  Seems even nVidia is having trouble securing time on a ppc64le system to build/test their GPU accelerated container runtime.

**Comment by lazystone** [comment]
Are there any updates on this?

**Comment by justincormack** [comment]
Hi, IBM are going to build these, and we will distribute their builds. I don't yet know when this is going to start.

**Comment by rpsene** [comment]
we have Docker builds for P at https://oplab9.parqtec.unicamp.br/pub/ppc64el/docker/
@justincormack ^

**Comment by rpsene** [comment]
not an oficial IBM build.

**Comment by lazystone** [comment]
Okay... So there are builds from IBM, but they don't have official status yet, so Docker can't distribute those. Which looks like it's mostly some bureaucracy needs to be involved, not like super tricky technical challenges are on the way.

Could you guys, I don't know, like, maybe talk to each other? And kick some manager's a$$ both in Docker and IBM and make us - ppc/docker users happy?

**Comment by clnperez** [comment]
@lazystone That's all ongoing. It's just been very bogged down with process. I appreciate the enthusiasm, though. :D

**Comment by thaJeztah** [comment]
This should be resolved now

**Comment by qhaas** [comment]
Thanks for adding binaries for ppc64le, is it possible to get the documentation updated to reflect it?  [It currently states](https://docs.docker.com/engine/install/ubuntu/): `Docker Engine is compatible with x86_64 (or amd64), armhf, arm64, and s390x architectures.`

**Comment by thaJeztah** [comment]
Ah, good call, looks like those pages weren't updated to include the architecture; let me open a quick PR.

**Comment by thaJeztah** [comment]
- opened a PR for the docs; https://github.com/docker/docs/pull/17747
