### ISSUE TITLE
Existing and future Docker engine support for WSL

### ISSUE THREAD

**Issue by yself** [docker/for-linux#645]
_This is a feature request_

It would be great if not only the Docker client but the Docker engine did work on WSL (Windows-subsystem-for-Linux). I have seen this suggested a few times, but it is not that apparent that it does already partially work. On current 1809 build of WSL, it is possible to start Docker engine and run "some" Linux containers. The install procedure described [here](https://medium.com/devopslinks/docker-running-seamlessly-in-windows-subsystem-linux-6ef8412377aa) mostly works (install docker package as normal), but I have found that following procedure works better:

- install fresh Ubuntu 18.10 (Cosmic) (I personally use [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline) for WSL management)
- execute:
```
apt update
apt install -y wget cgroupfs-mount
wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.03.1~ce-0~ubuntu_amd64.deb -P /tmp/
dpkg -i /tmp/docker-ce_18.03.1~ce-0~ubuntu_amd64.deb
apt -y -f install
dpkg -i /tmp/docker-ce_18.03.1~ce-0~ubuntu_amd64.deb
cgroupfs-mount
mkdir -p /etc/docker
echo '{ "bridge": "none" }' >/etc/docker/daemon.json
dockerd #this may fail the first time
```

After the above steps, the docker engine will download and execute containers. From what I have tested so far, basic containers work, all database containers that I have tested (postgres, bolt, sqlserver :) , …) do not work, haproxy works...

From some of the basic commands, `docker exec` does not work without modifications of Docker sources, but after disabling keyring join (not implemented on WSL) it does start to work.

The most recent version of Docker that works this way is Docker CE 18.03, more current versions produce various errors when running containers. The fact that this version of Docker engine works seems to indicate that WSL has matured enough to warrant some more effort to update Docker engine to be more compatible with WSL.

There is already the new LCOW feature to run Linux containers on Windows which is a great, but that requires Hyper-V in Windows to be enabled, which conflicts with other virtualization solutions like VirtualBox and VMWare which I use for development (PC needs to be rebooted to enable/disable Hyper-V).

WSL works great as development tool and it would be great if it did support Docker engine some more, so one can use existing containers to test cross-platform software developed on Windows.

**Comment by shyem** [comment]
Current solution for Windows (Docker Desktop for Windows) spins up a VM in Hyper-V which does not support dynamic memory as result it eats a lot of memory on startup of docker. It works but not efficient (memory hungry). You need a minimum of 16Gb RAM, but 32GB is ideal. With WSL, it has a very little footprint (overhead) and does not require lot of RAM. I think having support for WSL would make docker more  popular and increase it's adoption in windows world which is still the most popular OS out there.

**Comment by lukemcdo** [comment]
This issue seems complete, no?

**Comment by thaJeztah** [comment]
Yes, Docker Desktop now comes with WSL2 support; let me close this ticket
