### ISSUE TITLE
Systemd unit maybe not reloaded when upgrading from 17.05 to 17.06 on Debian

### ISSUE THREAD

**Issue by jpetazzo** [docker/for-linux#65]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

After upgrading from 17.05 to 17.06, the Engine is running.

### Actual behavior

The Engine is not running.

### Steps to reproduce the behavior

When upgrading from 17.05 to 17.06 on a Debian machine, after the upgrade, the Engine was not running. I tried to start it manually with `systemctl start docker`, but that didn't help. While investigating, at some point, I did `systemctl daemon-reload` and immediately after, it worked. I suppose that the systemd unit changed but wasn't reloaded (but I can't really check since I don't have a snapshot of the machine before the upgrade 😢 )

**Comment by nrlakin** [comment]
I had this issue; they changed the launch command between 17.05 (they dropped the deprecated "docker daemon" command, which was used in the docker.service definition). The upgrade doesn't change the systemd service definition, so the daemon isn't launched. You'll need to manually change the systemd service definition. Here's the old definition:

```
~$ systemctl cat docker.service
# /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2 
Environment=
...

```

Change the ExecStart line to match this:

```
~$ systemctl cat docker.service
# /etc/systemd/system/docker.service.d/10-machine.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2 
Environment=

```

**Comment by jpetazzo** [comment]
I believe I had a different issue, since I did't have to edit the systemd unit to fix it – just reload it.

**Comment by thaJeztah** [comment]
ping @seemethere PTAL - not sure if there's anything in packaging that needs to be set to force a reload

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
