### ISSUE TITLE
Option `--memory` limit should impact the system behaviour.

### ISSUE THREAD

**Issue by axelborja** [docker/for-linux#651]
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

###  Context

I am currently working on a `Kubernetes` cluster, which uses docker.

This cluster allows me to launch jobs. For each job, I specify a memory request and a memory limit.

The memory limit will be used by `Kubernetes` to fill the `--memory` option of the `docker run` command when creating the container. If this container exceeds this limit it will be killed for OOM reason.

Now, If I go inside a container, I am a little bit surprised to see that the available system memory is not the one from the `--memory` option, but the one from the docker machine. (The Kubernetes Node)

I am surprised because a system with wrong information about available resources will not behave correctly.

Take for example the memory cache used by IO operations. If you write on disk, pages will be cached on the RAM before being written. To do this the system will evaluate how many pages could be cached using the `sysctl vm.dirty_ratio` (20 % by default) and the memory size of the system. But how this could work if the container system memory size is wrong.

### Expected behavior

The system should be able to behave correctly using the container limit.

### Actual behavior

The system does not behave correctly because it thinks it disposes of the machine RAM.

### Steps to reproduce the behavior

Ran a program with a lot of IO operations (os.write, decompression, ...) on a container limited at 10Gi of RAM, on a 180Gi Node.

-> The container will be killed because it will reach the 10Gi memory limit. 

This OOM is caused by the wrong evaluation of `dirty_ratio` * the system memory, which allow the container to use 36GB (0.2 * 180GB) of dirty pages instead of 2GB (0.2 * 10GB).

Here, the `working memory` illustrates the pages cached:
![Pod_🎸_-_Grafana](https://user-images.githubusercontent.com/14804124/56571229-cbdc9a00-65bc-11e9-8ffc-b38cc4563d8f.jpg)

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:27:07 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.104-95.84.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.69GiB
Name: REDACTED
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

AWS EKS Kubernetes 1.12

**Comment by cpuguy83** [comment]
This is working as expected. This data comes from /proc, which is generated by the kernel.
The only way to override this is to provide a custom proc fs, which is not really desirable.

If you want to find the real value you need to account for cgroup limits, which can be read from the container in /sys/fs/cgroup.
Note that this is what recent versions of java use to set the max heap size.

**Comment by axelborja** [comment]
Yes, I heard it about java, this is great. 👏 

However, here, in my example, this is Linux which will misbehave. This is a real problem.

**Comment by cpuguy83** [comment]
Sounds like a kernel bug, I think?

**Comment by cpuguy83** [comment]
Have you reported the issue to your distro provider?

**Comment by khenidak** [comment]
This will create a bigger problem. most of the standard/ld tooling (all?) uses `procfs` not not cgroups to learn about the memory (and other limits/sizes). Let us take another more interesting a slightly more complex example. Should an app running on X CPU (let us assume single core for now) but limited to 10% of X reads CPU clock speed as x/10 or just just x?

I really believe that applications that are designed to be self optimize or self discipline according to allowed resources should read from the correct source of info, instead of modifying the kernel itself..

**Comment by axelborja** [comment]
I understand your point. 

Unfortunately, I could not design my application to the allowed resource. Here I encounter problems (OOM exactly) because of the Linux misbehavior.

What I am doing is using `write()` from the OS, and `pbzip2` that also use `write()` from the OS.

So, what you suggest here is to ask changes to the Linux distribution?

**Comment by cpuguy83** [comment]
If the kernel (or a kernel module) is allocating memory based on total system memory rather than cgroup memory and yet the memory is charged to the cgroup then this definitely sounds like a bug in the kernel/module.

**Comment by axelborja** [comment]
It seems related to https://github.com/kubernetes/kubernetes/issues/61937

**Comment by axelborja** [comment]
seems related to https://github.com/kubernetes/kubernetes/issues/61937

**Comment by M00nF1sh** [comment]
@axelborja I don't think your program is got OOM killed due to page cache(vm.dirty_ratio).
Seems memcg will try to reclaim these memories occupied by page cache, then it won't kill your program.

The most possible cause of your issue is your language runtime(GC language) doesn't aware of memories available.
Can you check the memory.stats file in your pod's cg group?

**Comment by axelborja** [comment]
@M00nF1sh For cache/rss values, you can take a look at the screenshot I posted about used memory. 

Moreover, the memory cached before being written to the disk could not be reclaimed.

As a workaround I fixed `vm.background_dirty_bytes` and `vm.dirty_bytes` -> the working memory does not spike anymore on intensive IO operations. And the pod is not killed anymore.

**Comment by M00nF1sh** [comment]
I'm not a kernel expert. But according to https://github.com/torvalds/linux/blob/5ac94332248ee017964ba368cdda4ce647e3aba7/mm/vmscan.c#L2926, the kernel do kick in writeback threads and waits some time for these dirty pages to be flushed and reclaim.
For your case, you must been under intensive write operations.

I'd suggest use a daemonset to set tune these vm parameters per your usecase, until there is a kernel solution.

**Comment by axelborja** [comment]
It seems to be this 👍 

To be clear, this problem occurs because the kernel misbehave, and the dirty bytes are evaluated using the full system memory instead of the cgroup limits.

**Comment by axelborja** [comment]
@M00nF1sh 

My instances are running under `Amazon Linux 2` with kernel `4.14.104-95.84.amzn2.x86_64`.

Should I wait for a patch form `Amazon`?

Or is the bug also present on RHEL 7.5 distribution/kernel (on which is based the amazon one)?

**Comment by axelborja** [comment]
Looking at the [Control Group v2 documentation](https://github.com/torvalds/linux/blob/9221dced3069cc9ae2986ba1191b02dae560df28/Documentation/admin-guide/cgroup-v2.rst#writeback), the cgroup writeback is not implemented for `/dev/nvme0n1p1` filesystem. (of `xfs` type)

```cgroup writeback requires explicit support from the underlying filesystem. Currently, cgroup writeback is implemented on ext2, ext4 and btrfs. On other filesystems, all writeback IOs are attributed to the root cgroup.```

It explains the whole problem.

So I could close this issue which is not related to docker, but to Linux.

**Comment by M00nF1sh** [comment]
@axelborja I don't think Amazon can release a patch for this since it's more like a feature instead of security patch..
BTW, docker is still using cgroup v1 😄, but the mechanism is same
