### ISSUE TITLE
Docker for SUSE

### ISSUE THREAD

**Issue by mshahat** [docker/for-linux#658]
Hi, 

Appreciate if this is not the right repo, so I appreciate some reference. 

I can see that openSUSE, as well as SUSE Enterprise Linux installation, is not part of the Docker documentation.

I can see that Docker can be installed from SUSE repos. I can see however the latest version available as of today as 18.09.1. Accordingly, I am trying to understand how frequent is SUSE repos are updated with Docker released. 

Thanks,

**Comment by seemethere** [comment]
Docker for SLES is supported in our enterprise product.

https://docs.docker.com/install/linux/docker-ee/suse/

The docker that is available from the SUSE repositories is not maintained by us and is thus not officially supported.

We do not have any plans to support openSUSE as of now.

**Comment by mshahat** [comment]
Thanks, @seemethere ... so the distribution provided is actually built by SUSE?

**Comment by thaJeztah** [comment]
We have packages for SLES for s390x, which are built by IBM, but currently no plans to provide for other architectures l.

Let me close this ticket for now
