### ISSUE TITLE
Docker 17.06-ce binaries has not been uploaded to  get.docker.com/builds

### ISSUE THREAD

**Issue by krise3k** [docker/for-linux#67]
Docker 17.06-ce Linux binaries has not been uploaded to https://get.docker.com/builds/
When you check this page, lastest version is  docker 17.05-ce

### Steps to reproduce the behavior
`curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.06.0-ce.tgz`

**Comment by thaJeztah** [comment]
Static builds can be found at their new home;

- https://download.docker.com/linux/static/
- https://download.docker.com/mac/static/
- https://download.docker.com/win/static/

**Comment by krise3k** [comment]
@thaJeztah thanks for guiding me. It's possible to add this info to https://get.docker.com/builds/ for faster redirection to new addres?

**Comment by thaJeztah** [comment]
@andrewhsu @seemethere ^^

**Comment by seemethere** [comment]
The index has been updated with a simple message:

```
Static builds can now be found at https://download.docker.com/linux/static
```

**Comment by thaJeztah** [comment]
@seemethere perhaps mention the Mac and Windows builds as well?

**Comment by seemethere** [comment]
@thaJeztah updated to:

```
Static builds can now be found at:

  Linux:   https://download.docker.com/linux/static
  MacOS:   https://download.docker.com/mac/static
  Windows: https://download.docker.com/win/static

```

**Comment by thaJeztah** [comment]
Perfect! Let me close this issue
