### ISSUE TITLE
Docker-ce installation failed

### ISSUE THREAD

**Issue by ClepToManix** [docker/for-linux#68]
Hello at all,

i try to install docker-ce for my mailcow installation. i run the command 
`curl -sSL https://get.docker.com/ | sh`

and thats the output:

```
+ sh -c apt-get install -y -q apt-transport-https ca-certificates curl software-properties-common
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.20).
curl is already the newest version (7.47.0-1ubuntu2.2).
software-properties-common is already the newest version (0.96.20.7).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
docker-ce (17.06.0~ce-0~ubuntu) wird eingerichtet ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Do 2017-07-27 11:34:42 CEST; 4ms ago
     Docs: https://docs.docker.com
  Process: 25235 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 25235 (code=exited, status=1/FAILURE)
dpkg: Fehler beim Bearbeiten des Paketes docker-ce (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I have installed Ubuntu 16.04.2 and dont have any docker versions before.
i have updated and upgraded the system before the installation. Hope you can help me

**Comment by cpuguy83** [comment]
Can you provide the output of `journalctl -fu docker`?
Thanks!

**Comment by ClepToManix** [comment]
`Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.982596333+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984692850+02:00" level=warning msg="Your kernel does not support oom control"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984711450+02:00" level=warning msg="Your kernel does not support memory swappiness"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984721229+02:00" level=warning msg="Your kernel does not support kernel memory limit"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984726798+02:00" level=warning msg="Unable to find cpu cgroup in mounts"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984753529+02:00" level=warning msg="Unable to find cpuset cgroup in mounts"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: time="2017-07-27T14:09:41.984787175+02:00" level=warning msg="mountpoint for pids not found"
Jul 27 14:09:41 h2710636.stratoserver.net dockerd[31248]: Error starting daemon: Devices cgroup isn't mounted
`
I think the problem is my provider. He virtualize with virtuozzo and the kernel dont support docker. But i can install an docker application in my plesk, but this doenst help me :o

**Comment by cpuguy83** [comment]
Please have a look at https://help.virtuozzo.com/customer/en/portal/articles/2510011-docker-inside-of-container-installation-and-known-issues

I'm going to close since this does not look like a Docker issue but rather a configuration on the host, but feel free to continue to discuss.
