### ISSUE TITLE
"Is the docker daemon running?" on newly installed raspberry pi zero w

### ISSUE THREAD

**Issue by lucaszanella** [docker/for-linux#681]
`docker volume create --name $OVPN_DATA`

Then I get:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
`

Tried to restart:

```
systemctl start docker
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'docker.service'.
Multiple identities can be used for authentication:
 1.  ,,, (pi)
 2.  root
Choose identity to authenticate as (1-2): 1
Password: 
==== AUTHENTICATION COMPLETE ===
Job for docker.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status docker.service" and "journalctl -xe" for details.

```

Then:

```
pi@raspberrypi:~ $ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: core-dump) since Tue 2019-05-28 02:35:26 BST; 23s ago
     Docs: https://docs.docker.com
  Process: 10074 ExecStart=/usr/bin/dockerd -H unix:// (code=dumped, signal=SEGV)
 Main PID: 10074 (code=dumped, signal=SEGV)
      CPU: 431ms

May 28 02:35:26 raspberrypi systemd[1]: docker.service: Unit entered failed state.
May 28 02:35:26 raspberrypi systemd[1]: docker.service: Failed with result 'core-dump'.
May 28 02:35:26 raspberrypi systemd[1]: Stopped Docker Application Container Engine.
```
I'm on a rasbperry pi zero w with the newest raspbian desktop

https://github.com/docker/for-linux/issues/490 didn't help

**Comment by tylerdurden94** [comment]
I have the same issue on the install I performed last night.

**Comment by lucaszanella** [comment]
I also did a fresh installation on the raspberry pi B+ and I'm having the same problem

**Comment by mocktottel** [comment]
Do you have any solution? I've the same problem.

**Comment by ndanyluk** [comment]
Unfortunately this issue has existed since 18.09.0.  The docker packaging folks don't seem to package the armhf packages with armv6 in mind

**Comment by leighghunt** [comment]
Stumbled across this whilst looking into an issue I'm having getting compose working on a Pi Zero W - however I think I resolved/worked around this issue by pinning to 18.06 with the following in my install script:

```
echo -e "Package: docker-ce\nPin: version 18.06.*\nPin-Priority: 1000" | sudo tee /etc/apt/preferences
curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
sudo usermod -aG docker pi
```

More info: https://github.com/moby/moby/issues/38175#issuecomment-443458860 and https://github.com/docker/for-linux/issues/490

**Comment by thaJeztah** [comment]
This should be resolved now with the container.io_1.2.10-2 package; https://github.com/moby/moby/issues/38175#issuecomment-540355951

> Hey guys!
> 
> Just released new [containerd.io package](https://download.docker.com/linux/raspbian/dists/buster/pool/stable/armhf/containerd.io_1.2.10-2_armhf.deb) version 1.2.10-2 to the https://download.docker.com repositories, please let me know if that resolves all issues related to this segmentation fault, I do not currently have a armv6 machine to test on.
>
> Sorry for the late update on this, hopefully this issue is now resolved

**Comment by Tweega** [comment]
I found my answer [here](https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket) in the end
