### ISSUE TITLE
docker build slow due to slow docker-untar (not using server capacity)

### ISSUE THREAD

**Issue by eaglerainbow** [docker/for-linux#685]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Performing a RUN step with installing a reasonable number of Ubuntu packages in a `docker build` should termine within a reasonable amount of time (and not 4+ hours). If necessary, the full capacity of IO/memory/CPU available shall be used.

### Actual behavior
The commit of the RUN step is not taking the full CPU/IO capacity of the underlying server, but is quite slow.

### Steps to reproduce the behavior
Create the following Dockerfile:

```
FROM ubuntu:18.04

ARG uid=1000
ARG gid=1000
RUN echo "${gid} ${uid}"

# Some further ENV stuff

RUN DEBIAN_FRONTEND=noninteractive && \
   apt-get update && apt-get -y install -y tzdata && \
   ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
   dpkg-reconfigure --frontend noninteractive tzdata && \
   apt-get -y install -y apt-transport-https ca-certificates \
     wget curl unzip vim git less mc jed \
     python python-openstackclient  && \
   apt-get -q autoremove && \
   apt-get -q clean -y && \
   rm -rf /var/lib/apt/lists/*

# There are further RUN commands below, but they don't matter
```

Build it with

```bash 
$ docker build -t test:latest .
```

The FROM/ARGs and the first RUN command go through like nothing (as expected).
Hitting the second RUN command, it is expected that this will take a little, as we install quite a bunch of applications via the package manager. apt and all the tools roughly require two minutes to complete (a runtime I am totally okay with).

After having written the last line to the console

```
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded
```

the system takes ages to complete (apparently, the commit of the RUN command is performed). I already kept it running for 4+ hours, but the next layer (the next RUN) command had not being reached, yet. 

**Output of `docker version`:**

```
Client:
Version:           18.09.0
API version:       1.39
Go version:        go1.10.4
Git commit:        4d60db4
Built:             Wed Nov  7 00:48:57 2018
OS/Arch:           linux/amd64
Experimental:      false
 
Server: Docker Engine - Community
Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 
```

**Output of `docker info`:**

```
Containers: 10
Running: 7
Paused: 0
Stopped: 3
Images: 31
Server Version: 18.09.0
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
apparmor
seccomp
  Profile: default
Kernel Version: 4.4.0-139-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.843GiB
Name: *redacted*
ID: LRB4:T5O6:CTCW:QNGG:6J4O:5PY4:SVYC:GAJL:ZDIZ:JTFE:*REDACTED*:*REDACTED*
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: *redacted*
HTTPS Proxy: *redacted*
No Proxy: local,169.254/16,*.REDACTED*
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine
 
WARNING: API is accessible on http://127.0.0.1:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: API is accessible on http://*REDACTED*:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

* Virtual Machine running on a linux amd64 (Ubuntu 16.04.5 LTS)
* Backing file system is ext4
* The machine has 4 GB of RAM, 2 vCPUs (Xeon E7-8880 v4)
* /var/lib/docker is mapped through lvm to an SSD. read/write performance on that disk is known to me 200+ MB/s.

The same behavior may also be observed on a similar machine with even more hardware capacity.

**Comment by eaglerainbow** [comment]
Having docker in that state, checking the system load, you see that the entire system is idling (loadavg < 0.1). There is more than 1GB of free RAM. Once in a very while you see `dockerd` briefly doing something, but with <2% CPU load. Moreover, checking IO load (using `iotop`) I see both `Total DISK READ` and `Total DISK WRITE` to be around 30 K/s (which is nothing). The underlying disk beneath the backing file system is known to be SSD. The backing file system still has more than 10 GB of free space.

Also checking `ps auxw | grep docker` I see that docker build is in a blocked state and the sub-process

```
docker-untar /var/lib/docker/overlay2/0475df....07/diff
```

is running, but in state "stopped". In sum after 2+ hrs of wall-clock time, this process has consumed less than 2 CPU-seconds so far. Looking into the diff dir mentioned by docker-untar above, making several snapshots of `du -sh .`, I can see that the data volume in that directory increases very slowly (rate ~1 MB / 3 minutes, that's roughly 5,5 kb/s - even ancient floppy disks were faster than this!). At the time of writing, there were 103 MB in it. A `find . | wc -l` resulted in the value of 5157, equally only going up very slowly (162 files had been written during those 3 minutes it took to generate 1 MB of data).

Running containers on the same machine and reading/writing to the container's attached image is without problem.

**Comment by cpuguy83** [comment]
Have you done an iostat on this?

**Comment by eaglerainbow** [comment]
Thanks for the quick response. No, so far I did not, but here is what I could get:

All snapshots had been created using 

```bash 
$ sudo iostat -t -x /dev/mapper/docker-docker 5 10
```` 

where as `/dev/mapper/docker-docker` is pointing to /dev/dm-0 where the hypervisor is mounting the disk to. 

While the vm is not running any `docker build` command, we have the following load picture:

``` 
06/01/2019 07:58:53 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.41    0.00    0.91    0.20    0.00   96.48

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.20    1.60     4.80     6.40     8.00     0.00    0.00    0.00    0.00   0.00   0.00
``` 
Yes, there are some background processes running, which cost us some CPU cycles, but the load is very constant and low-profile constant IO is happening only a different disk. 

While docker build is running and installing the packages (apt), you see the following pattern:
```

06/01/2019 08:00:00 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          24.07    0.00   22.76   12.39    0.00   40.79

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00  200.60 3503.60  1448.80 26812.80    15.26     2.48    0.67    0.49    0.68   0.14  50.72
```

which also makes sense to me. The disk is busy writing data (here in this special snaphot: 26.8 MB/s). I also saw higher but also lower values during this phase.


Here is now a iostat trace during the problematic time phase. What you see is a 1:1 copy&paste. The command was issue *after* the `docker-untar` process appeared in the process list:

```
$ sudo iostat -t -x /dev/mapper/docker-docker 5 10
Linux 4.4.0-139-generic (redacted)     06/01/2019      _x86_64_        (2 CPU)

06/01/2019 08:00:59 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           5.98    0.00    1.20    0.15    0.00   92.66

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    2.08    0.93    69.91    20.32    60.05     0.00    0.85    0.71    1.15   0.13   0.04

06/01/2019 08:01:04 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.21    0.00    1.71    0.40    0.00   94.68

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.60  777.60     6.40 17073.60    43.84     6.16    7.91    0.50    7.92   0.02   1.60

06/01/2019 08:01:09 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.96    0.00    1.21    0.00    0.00   91.83

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    0.40   51.60     6.40   206.40     8.18     0.20    3.94    0.00    3.97   0.02   0.08

06/01/2019 08:01:14 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.72    0.00    0.80    0.20    0.00   95.28

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.20    0.00     4.80     0.00     8.00     0.00    0.67    0.67    0.00   0.67   0.08

06/01/2019 08:01:19 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.31    0.00    0.60    0.00    0.00   97.09

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    0.20    4.00     0.80    16.00     8.00     0.00    0.00    0.00    0.00   0.00   0.00

06/01/2019 08:01:24 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.23    0.00    0.81    0.10    0.00   95.86

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.40    0.00     5.60     0.00     8.00     0.00    0.00    0.00    0.00   0.00   0.00

06/01/2019 08:01:29 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          10.26    0.00    2.01    0.00    0.00   87.73

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    0.20    5.20     0.80    20.80     8.00     0.00    0.00    0.00    0.00   0.00   0.00

06/01/2019 08:01:34 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          14.86    0.00    2.21    0.20    0.00   82.73

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.20    0.00     4.80     0.00     8.00     0.00    0.00    0.00    0.00   0.00   0.00

06/01/2019 08:01:39 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.33    0.00    1.11    0.10    0.00   92.46

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    0.00    4.20     0.00    21.60    10.29     0.01    3.24    0.00    3.24   0.19   0.08

06/01/2019 08:01:44 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.02    0.00    0.81    0.10    0.00   96.07

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
dm-0              0.00     0.00    1.20   64.00     4.80   326.40    10.16     0.18    2.82    0.67    2.86   0.02   0.16

```

We once see write load of ~17MB/s. I am unsure whether this also couldn't be "something else". But all other iostat snapshots show write throughputs around 20 - 300 kB/s.


Can I be of help providing further data / analysis / tests?

**Comment by eaglerainbow** [comment]
I once had also tried to strace the docker-untar process, hoping to get some more insights. There, I could also see strange "hanging effects", but could not understand properly what this was all about. 
Do you think that this might help you here somehow?

**Comment by eaglerainbow** [comment]
This here *could* be something:

I started strace like this:

``` bash
$ sudo strace -p 13723 -T -t
``` 

whereas 13723 is the process id of the `docker-untar` process. Amongst a huge load of other data, here is a possibly interesting chunk:

```
20:20:22 write(3, "", 0)                = 0 <0.000014>
20:20:22 read(0, "\3\363\r\n+\34aZc\0\0\0\0\0\0\0\0\5\0\0\0@\0\0\0s\234\1\0\0d\0"..., 20516) = 3584 <0.000026>
20:20:22 write(3, "\3\363\r\n+\34aZc\0\0\0\0\0\0\0\0\5\0\0\0@\0\0\0s\234\1\0\0d\0"..., 3584) = 3584 <0.000028>
20:20:22 read(0, "\v\0\203\2\0\1|\0\0j\10\0d\10\0|\4\0d\6\0\31j\f\0\203\2\0\1d\0\0"..., 16932) = 16932 <9.398829>
20:20:31 futex(0x55a709936470, FUTEX_WAKE, 1) = 1 <0.000083>
20:20:31 write(3, "\v\0\203\2\0\1|\0\0j\10\0d\10\0|\4\0d\6\0\31j\f\0\203\2\0\1d\0\0"..., 16932) = 16932 <0.000114>
20:20:31 close(3)                       = 0 <0.000081>
20:20:31 lchown("/usr/lib/python2.7/dist-packages/cliff/tests/test_app.pyc", 0, 0) = 0 <0.000095>
20:20:31 fchmodat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/cliff/tests/test_app.pyc", 0644) = 0 <0.000092>
20:20:31 utimensat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/cliff/tests/test_app.pyc", [{1559419236, 0}, {1559419236, 0}], 0) = 0 <0.000137>
20:20:31 read(0, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 476) = 476 <0.000041>
20:20:31 read(0, "usr/lib/python2.7/dist-packages/"..., 512) = 512 <0.000055>
```

Interesting might be the last line starting with `20:20:22`. 
Note that this read operation took 9+ seconds in the syscall, waiting until the handle returned 16932 bytes from fd 0 (a.k.a. stdin). So, in short, `docker-untar` could work faster, but the producer is not providing data fast enough. 

Does this make sense to anyone?

**Comment by cpuguy83** [comment]
Not really. `docker-untar` is pretty simple.
If there is very little CPU utilization, then it almost must be I/O related.

**Comment by cpuguy83** [comment]
The producer in this case is dockerd.

**Comment by eaglerainbow** [comment]
I tried to strace the dockerd process (same approach as before). However, the only thing I get is:

```
strace: Process 13822 attached
20:34:05 futex(0x5563aa611ec8, FUTEX_WAIT, 0, NULL^Cstrace: Process 13822 detached
 <detached ...>
``` 
(`^C` is me after ~8 minutes of non-activity). 

Are you sure the producer is the `dockerd` process?

**Comment by eaglerainbow** [comment]
(background: Before creating a GH issue here, I had created a stackoverflow question, which then pointed to here).

At https://superuser.com/questions/1443782/docker-build-slow-due-to-slow-docker-untar-not-using-server-capacity#comment2178562_1443782 there might be another piece of information, which *might* be relevant: Another user reported that executing the same scenario with 18.06.0-ce worked for him with a runtime of ~3 minutes (which would perfectly fit to my performance expectation). The same user did not try with 18.09.0-ce, though.

**Comment by eaglerainbow** [comment]
I just read through [Docker's Release Notes](https://docs.docker.com/engine/release-notes/) - mainly the delta between 18.09.0 and 18.09.6. I could not find anything there, giving me an indication about a fix that was provided recently for this issue here (or I could not read that from the release note statements).

**Comment by cpuguy83** [comment]
dockerd is absolutely the producer, though it could be coming from a pulled layer, or data copied in a build instruction just depends on the use case.

Data is tar'd (or already a tar) and extracted into the container's rootfs via docker-untar, which is actually even built into the dockerd binary. You could execute this yourself by calling exec with argv0 set to `docker-untar` instead of `dockerd`

Did you check I/O on the system? There is not a whole lot going on here in docker, especially if there is no CPU being used but data is still flowing.

**Comment by eaglerainbow** [comment]
> dockerd is absolutely the producer, though it could be coming from a pulled layer, or data copied in a build instruction just depends on the use case.

I don't think so that it's either from a foreign layer or from build data: The file names which run through the strace of `docker-untar` indicates that these are the python files, which were just installed by the RUN command before (so, they were downloaded from the Ubuntu mirror and then installed by apt).

> Did you check I/O on the system? There is not a whole lot going on here in docker, especially if there is no CPU being used but data is still flowing.

I can confirm that `docker-untar` still is running (the whole time while we write each other - yes, it's still the same call of `docker build`) by going into the corresponding /var/lib/docker/overlay2/.../diff folder. There, checking using `find .| wc -l`, I can confirm that further files are written to disk slowly. Still also I can see corresponding activities of `docker-untar` in the `strace`. At the same time `iostat` shows (roughly) the same result as described in https://github.com/docker/for-linux/issues/685#issuecomment-497974389 . Also `iotop` seconds what we see otherwise: write throughput (for the entire system) is typically between 20 - 300 kB/s - but almost all the time originating from other processes (but not `docker-untar` or `dockerd`). 
I could not see anything that would block any I/O requests. I also can check things in /var/lib/docker  using bash commands - and response times are fast as hell... Also the entire system is by no means sluggish.

Furthermore, I just did the following experiment:

```bash
root$ dd if=/dev/zero of=/var/lib/docker/test.file bs=2048 count=$((2048*256))
```

which resulted in a write time of 3 (three) seconds (i.e. 500MB/s).

Even performing an ugly
```bash
root$ dd if=/dev/zero of=/var/lib/docker/test.file bs=2048 count=$((2048*256)) oflag=direct
```

shows that we can write with ~6.9 MB/s (mind the small block size of 2048 bytes). The `docker-untar` process even does not get near to these throughput values.

**Comment by cpuguy83** [comment]
@eaglerainbow 

When you do a `RUN` instruction data is written to a read/write layer.
At the end of `RUN`, data is committed to a read-only layer as part of a new image.
The commit step will copy the data out of the r/w layer and into the a new r/o layer.
This is done by taring up the contents and then unpacking that data into the new layer. `docker-untar` handles the unpack.

**Comment by eaglerainbow** [comment]
Okay, that's understood. 
That means writing to the r/w layer (within the `RUN` command) is fast like hell. 
Also apparently letting `docker-untar` unpacking to the new layer during the commit step does not seem to be the problem. 
The current *guess* would be that we can't tar up fast enough  - or we can't hand over data fast enough between the tar'ing process (dockerd?) and `docker-untar`.

Any ideas how I could verify/triangulate this?

**Comment by cpuguy83** [comment]
A goroutine trace of dockerd will help see what exactly it is doing, which may or may not shed some light on things.

You can get this by hitting /debug/pprof/goroutine?debug=2 on the docker socket
Example with curl:

```
curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2
```

**Comment by eaglerainbow** [comment]
Read performance from the disk can't be a problem. Just as an experiment, I did:

```bash
root$ cd /var/lib/docker
root$ time tar c . >/dev/null
``` 

The `real` value was `0m7.340s`. `du -sh :` returns 7.2G

**Comment by eaglerainbow** [comment]
> [...] goroutine trace [...]

Okay, will try to collect that data.
Problem with it is that I apparently need to restart docker with `-D` enabled. Unfortunately, I can't do this on this machine right now. 
Will report back as soon as I have some data.

**Comment by cpuguy83** [comment]
@eaglerainbow You could add `{"Debug": true}` to `/etc/docker/daemon.json` (which may not exist, so just create it), and then send `SIGHUP` to `dockerd`.

**Comment by eaglerainbow** [comment]
> You could add {"Debug": true} to /etc/docker/daemon.json

Thanks - that was a good hint.
I reproduced the entire scenario and did a `/debug/pprof/goroutine?debug=2` snaphot roughly 10 minutes after start (during the situation in question):

[goroutine.log](https://github.com/docker/for-linux/files/3244493/goroutine.log)

In parallel I also checked strace on `dockerd` again - same result as before.

**Comment by eaglerainbow** [comment]
I think I found the reason why I could not see anything from `dockerd` in the strace: I did not consider that `dockerd` has forked additional threads. Thanks to https://stackoverflow.com/a/49110122/6350762 pointing out, how you may handle this properly.

With a little of jumping around in `/proc/*/fd` I could determine that dockerd has opened fd 79 for writing to `docker-untar`. Equipped with this fd, I searched for pids, which were dealing with fd 79. I filtered the strace on one of them (i.e. pid 17605). I then tried to sketch some long-running syscall. For instance, I stumbled over:

```
17605 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/script_helper.py", O_RDONLY|O_CLOEXEC <unfinished ...>
17605 07:37:08 <... openat resumed> )   = 67 <4.702864>
```
4.7 seconds is a hell lot of a time for opening one file!

Doing

```bash
$  sudo less /var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/script_helper.py
```

on the command line, however, gives an immediate response and 

```bash
$ strace -T -t cat /var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/script_helper.py
```

is also very fast:

```
07:46:49 open("/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/script_helper.py", O_RDONLY) = 3 <0.000165>
07:46:49 fstat(3, {st_mode=S_IFREG|0644, st_size=10438, ...}) = 0 <0.000016>
```

I make out of this, that `dockerd` (or the storage driver?) is doing *something* different for opening files than the standard command line tools.

**Comment by eaglerainbow** [comment]
Just for the sake of completeness: I can find further cases in the `dockerd`'s strace log which have similar run times for `openat` calls. However, I also can find cases where the performance was okay:

```
13828 07:36:44 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/libregrtest/utils.py", O_RDONLY|O_CLOEXEC <unfinished ...>
17605 07:36:47 openat(AT_FDCWD, "/var/run/docker/netns/d53980d967f6", O_RDONLY) = 74 <0.000184>
13825 07:36:47 openat(AT_FDCWD, "/var/run/docker/netns/d53980d967f6", O_RDONLY <unfinished ...>
13825 07:36:47 <... openat resumed> )   = 74 <0.000191>
13828 07:36:49 <... openat resumed> )   = 67 <4.715240>
13828 07:36:49 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/pystone.py", O_RDONLY|O_CLOEXEC <unfinished ...>
13828 07:36:54 <... openat resumed> )   = 67 <4.701475>
13828 07:36:54 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/regrtest.py", O_RDONLY|O_CLOEXEC <unfinished ...>
13828 07:36:58 <... openat resumed> )   = 67 <4.701741>
13828 07:36:58 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support", O_RDONLY|O_CLOEXEC) = 67 <0.000022>
13828 07:36:58 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/__init__.py", O_RDONLY|O_CLOEXEC <unfinished ...>
13828 07:37:03 <... openat resumed> )   = 67 <4.739032>
13828 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/__pycache__", O_RDONLY|O_CLOEXEC <unfinished ...>
13828 07:37:03 <... openat resumed> )   = 67 <0.000056>
13828 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/__pycache__/__init__.cpython-36.pyc", O_RDONLY|O_CLOEXEC <unfinished ...>
13828 07:37:03 <... openat resumed> )   = 67 <0.008986>
17605 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/__pycache__/script_helper.cpython-36.pyc", O_RDONLY|O_CLOEXEC <unfinished ...>
17605 07:37:03 <... openat resumed> )   = 67 <0.004973>
17605 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/__pycache__/testresult.cpython-36.pyc", O_RDONLY|O_CLOEXEC <unfinished ...>
17605 07:37:03 <... openat resumed> )   = 67 <0.004132>
17605 07:37:03 openat(AT_FDCWD, "/var/lib/docker/overlay2/f4a565a936393c22165855e0726865beaaf6519e62c02d59671018adb56890b9/diff/usr/lib/python3.6/test/support/script_helper.py", O_RDONLY|O_CLOEXEC <unfinished ...>
17605 07:37:08 <... openat resumed> )   = 67 <4.702864>
```

**Comment by eaglerainbow** [comment]
Just for the record:

Mounting of the ext4 at /var/lib/docker is done with

``` 
/dev/mapper/docker-docker on /var/lib/docker type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

The file system had been created with

```
sudo mkfs -t ext4 /dev/mapper/docker-docker
```

**Comment by eaglerainbow** [comment]
For the record: I created a new VM running our installation scripts (the same scripts which also installed docker on the old vm, which has the issue reported in this case here) and I am *not* able to reproduce the issue.
However, it should be noted that
``` bash
docker-test:~$ sudo docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

So, that was also an upgrade from 18.09.0 to 18.09.6.

**Comment by eaglerainbow** [comment]
I had the guts to upgrade the original VM (the one for which I initially had the created this issue here) from 18.09.0 to 18.09.6 (that also sound reasonable due to several CVEs mentioned in the release notes). I had hoped for that this also would solve this issue here. But: 😢 Same as before.

**Comment by eaglerainbow** [comment]
I gave up now: I just moved the original server from overlay2/ext4 to btrfs/btrfs (copying all images, etc.). The test-build (as mentioned above) has been performed now within less than 3 minutes (including the commit of the layer). I know that performance of btrfs is considered to be not as good as with overlay2 - but what is performance, if you have jitter like hell and which is so harsh that it even blocks you functional-wise.

I still have yet another VM, which is also suffering from this issue here. In the near future I will also move that one to btrfs/btrfs. If I find time, I might backup all the images there and just try to recreate the ext4 fs (instead) to see if it's just an internal file system issue only. If I will do so, I would also post the result here. 

I am mentally more or less through with ext4 as docker's backing file system: If it resists intensive analysis of unpredictable behavior for more than 48hrs, IMO it's not worth being used in production.

**Comment by eaglerainbow** [comment]
My previous statement was premature: Also btrfs/btrfs on the original server shows this "bad behavior" after ~35hrs of runtime.

Instead of `docker-untar` I see `docker-applyLayer` starving for data (via strace logs):
```
docker-applyLayer /var/lib/docker/btrfs/subvolumes/cbb772bfc14254ef76111393d5c2da3f8394d58f39fcc4812a4573c7c6a5cf6d
```

I checked the fd 0 for that process and determined that it is connected to fd 26 at dockerd.  Again, I can spot `openat` commands which take long:

``` 
1344  07:28:53 openat(AT_FDCWD, "/var/lib/docker/btrfs/subvolumes/bb5080e84154ee35e1e3555c606487fcb07c71eda42e5b09c22c04395e1bd1c7/usr/lib/python2.7/dist-packages/Crypto/SelfTest/Random/test_rpoolcompat.py", O_RDONLY|O_CLOEXEC <unfinished ...>
1344  07:28:58 <... openat resumed> )   = 24 <4.710068>
```
(just one example).

**Comment by eaglerainbow** [comment]
It looks like that this correlated with the virus scanner running on the VMs: McAfee. The problem appears to worsen over time. If I restart McAfee, then afterwards on both machines (btrfs/btrfs and overlay2/ext4) the duration for building the sample image is significantly better. This discharges docker to a major extend.

**Comment by cpuguy83** [comment]
Ah, that makes sense.
Going to close this because it doesn't seem like there's really anything we can do here.

**Comment by Alexc0007** [comment]
hi, i have experienced the same issue with docker version 19.03
downgrading to 18.06 solved the issue for me(only temporary, since i cant stay with an old version forever).
i dont have McAfee running on my system so i cant blame it....
my OS is Amazon Linux 2.
i have some other Amazon Linux 2 machines that dont have the same problem...

wish i knew what is the difference between those machines everything works OK on, and those that its not...

**Comment by wilsonleecn** [comment]
Same issue here, docker version 19.03

**Comment by jrop** [comment]
We started getting much better Docker build performance after switching to `docker buildx` (BuildKit).

**Comment by dmikushin** [comment]
Docker data transfer performance is indeed becoming slower over time, no antivirus involved. On Linux running for 265 days, I waited several hours in hope to a simple COPY command, gave up, and then tried to "git clone" directly in the Dockerfile, and it also appeared to be hanging infinitely on `docker-untar`, without any activity in iotop and any errors in dmesg. The problem went away after reboot. I don't have any other payload on this machine, but the Docker itself and containers. My guess it that something leaks system resources, such as file descriptors, and then there is no proper handling of an error condition - your Python code just keeps repeating the same line in an infinite loop...

**Comment by openaphid** [comment]
> Docker data transfer performance is indeed becoming slower over time, no antivirus involved. On Linux running for 265 days, I waited several hours in hope to a simple COPY command, gave up, and then tried to "git clone" directly in the Dockerfile, and it also appeared to be hanging infinitely on `docker-untar`, without any activity in iotop and any errors in dmesg. The problem went away after reboot. I don't have any other payload on this machine, but the Docker itself and containers. My guess it that something leaks system resources, such as file descriptors, and then there is no proper handling of an error condition - your Python code just keeps repeating the same line in an infinite loop...

I'm experiencing a similar issue with Docker `20.10.77` on Ubuntu 22.04 + `5.15.0-37-generic`.

A simple docker `mkdir` command takes minutes to finish:

```
 => CACHED [superset-node  3/12] RUN npm install -g npm@7 pnpm       0.0s
 => [superset-node  4/11] RUN mkdir -p /app/superset/assets       148.5s
```

The whole system gets sluggish too, like Chrome complains tabs are not responding, etc.

It makes sense if there is a system-level resource leak.
