### ISSUE TITLE
Build Faild due to the curl version in golang:1.12.5 when host is behind a proxy

### ISSUE THREAD

**Issue by sophy228** [docker/for-linux#686]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
My host network is behind a https proxy. and find build failed as curl can not download anything in "dock build" process

So I tried to build a test dockfile:

 DOCKER_BUILDKIT="1" docker build  --build-arg=CROSS=false --build-arg http_proxy=http://10.239.4.100:913 --build-arg https_proxy=https://10.239.4.100:913  -t "docker-dev:111" -f "Dockerfile" .

FROM golang:1.12.5
MAINTAINER Docker Newbee <newbee@docker.com>
#COPY curl /usr/bin/curl
#COPY libcurl* /usr/lib/x86_64-linux-gnu/
RUN curl -Ls https://download.docker.com/linux/static/stable/x86_64/docker-17.06.2-ce.tgz

The above will be failed due to :
curl: (35) Unknown SSL protocol error in connection to 10.239.4.100:913

You can also try to
 run docker run -t -i "golang:1.12.5" /bin/bash
and do the same thing, then error is the same.

While wget works well in "golang:1.12.5" image. and Then I tried to downgrade the curl in it. it works with HTTPS with version 7.47.  The default curl version in "golang:1.12.5"  is 7.52...

**Comment by thaJeztah** [comment]
Do you see the same problem with `DOCKER_BUILDKIT=0` ?

From the description, this looks to be an issue with the golang image (or, more likely, the curl version that's installed from the debian repositories in the debian:stretch image that's used as base-image for golang)

Could you open a ticket in the issue tracker for the Golang image? https://github.com/docker-library/golang/issues
