### ISSUE TITLE
Docker is not getting installed on CentOs(6.7).

### ISSUE THREAD

**Issue by Mo33n** [docker/for-linux#69]
yum install docker-ce
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.oss.ou.edu
 * extras: mirror.metrocast.net
 * updates: mirror.cc.columbia.edu
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:17.06.0.ce-1.el7.centos will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Processing Dependency: libsystemd.so.0(LIBSYSTEMD_209)(64bit) for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Processing Dependency: systemd-units for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Processing Dependency: libseccomp.so.2()(64bit) for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Processing Dependency: libsystemd.so.0()(64bit) for package: docker-ce-17.06.0.ce-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: libseccomp.so.2()(64bit)
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: systemd-units
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: container-selinux >= 2.9
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: libsystemd.so.0()(64bit)
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: libc.so.6(GLIBC_2.17)(64bit)
Error: Package: docker-ce-17.06.0.ce-1.el7.centos.x86_64 (docker-ce-edge)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by cpuguy83** [comment]
Docker is not supported on centos 6.x.
