### ISSUE TITLE
Duplicated ExposedPorts on Second Container when docker inspect

### ISSUE THREAD

**Issue by joaquin386** [docker/for-linux#7]
### Expected behavior
docker inspect --format=" {{ .Config.ExposedPorts }} " 3d6e801c813e
 map[100/udp:{}] 
docker inspect --format=" {{ .Config.ExposedPorts }} " e6ce614a2f89
 map[101/udp:{}] 

### Actual behavior
docker inspect --format=" {{ .Config.ExposedPorts }} " 3d6e801c813e
 map[100/udp:{}] 
docker inspect --format=" {{ .Config.ExposedPorts }} " e6ce614a2f89
 map[101/udp:{} 100/udp:{}] 

The first container seems it is outputing the correct info. The second contianer is putting the exposePort of the first container.

### Information

  - Linux distro: CentOS 7
  - Docker CE version: 17.03.1-ce
  - A reproducible case if this is a bug, Dockerfiles FTW

### Steps to reproduce the behavior

1. 
Contianer 1:
On Dockerfile: EXPOSE 100/udp
On docker-compose:
 services:
   ports:
      - "100:100/udp"
Contianer 2:
On Dockerfile: EXPOSE 101/udp
On docker-compose:
 services:
   ports:
      - "101:101/udp"

2. Using macvlan network and both containers are on the same docker network macvlan
3. docker-compose up -d
4. Execute the above docker inspect and check the parameter ExposedPorts

**Comment by thaJeztah** [comment]
Looks like you also posted this in https://github.com/moby/moby/issues/33544. Let me close this one so that the discussion doesn't diverge
