### ISSUE TITLE
--env-file does not support export in .env file

### ISSUE THREAD

**Issue by servel333** [docker/for-linux#701]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

I am uncertain if this is a 'bug' or 'feature request'. The Docker team can decide.

### Expected behavior

Container runs normally, with env vars from `.env` in environment of container.

### Actual behavior

```
docker: poorly formatted environment: variable 'export AWS_ACCESS_KEY_ID' has white spaces.
See 'docker run --help'.
```

### Steps to reproduce the behavior

`.env` file
```
#!/bin/bash

export AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxx
export AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

`docker run --env-file ./.env --rm node:10.5.0-alpine`

**Output of `docker version`:**

```
docker --version
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 634
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: GRB6:T5A7:T4YH:ONB3:RXCT:65RE:IXJA:6MT5:TQTU:OUYE:F2XM:VEWL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 57
 System Time: 2019-06-18T20:23:12.4844023Z
 EventsListeners: 2
Http Proxy: gateway.docker.internal:3128
Https Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

macOS High Sierra
Version 10.13.6 (17G7024)

**Comment by xhissy** [comment]
Hey,

This is expected behavour. You do not need to specify export.
This page should help: https://docs.docker.com/compose/env-file/

**Key take away:**
"Compose expects each line in an env file to be in VAR=VAL format."

**Example file:**

```
AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by servel333** [comment]
Sounds like this is a feature request then. This behavior makes it impossible to have one file that can be executed as `( source .env ; command.sh )` and also as `docker run --env-file ./.env --rm node:10.5.0-alpine`, which is frustrating.

I believe the only change that would be needed would be ignoring the word `export` before the variable name.

**Comment by xhissy** [comment]
Why do you need to run the source command?
The variables will already be set.

If setup the .env file correctly you should never need to use the source command.

**Comment by servel333** [comment]
I don't want to pollute my shell environment with my env file most of the time. I run commands a lot with different env configurations... Or am I missing something? What would I use instead of `source`?

**Comment by xhissy** [comment]
If you are passing a env file at run time why do you need to source that file immediately after?

Scenario -

Docker run with env file:
Defines the following -
ABC = 123
DEF = 456

Running source .env would do the following:
Replace current value for ABC with 123
Replace current value for DEF with 456

**Comment by servel333** [comment]
Oh, I often need to run commands inside docker, and on my native shell. So `( source .env ; command.sh )` would not be in docker.

**Comment by xhissy** [comment]
Ah fair enough
Doesn't sound like its something docker should support.

Try using a bash script to bridge the gap. This should read each line of the .env file and run the export for you:

```
while read p; do
  export "$p"
done <.env
```

**Comment by servel333** [comment]
That could work. Thanks. I'll try that out.
