### ISSUE TITLE
docker lvm-thinpool show 100% why still can write data to disk?

### ISSUE THREAD

**Issue by hwhe** [docker/for-linux#731]
* [ ] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

[root@test0527-84049 ~]# lvs -a
  LV               VG     Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  kubernetes       vgpaas -wi-ao---- 10.00g                                                    
  [lvol0_pmspare]  vgpaas ewi-------  5.00g                                                    
  thinpool         vgpaas twi-aot-D- 80.00g             **100.00** 0.12                            
  [thinpool_tdata] vgpaas Twi-ao---- 80.00g                                                    
  [thinpool_tmeta] vgpaas ewi-ao----  5.00g                                                    
[root@test0527-84049 ~]# 

root@test0527-84049 ~]# docker info | grep Space
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
 Data Space Used: 85.9GB
 Data Space Total: 85.9GB
 **Data Space Available: 0B**
 Metadata Space Used: 6.463MB
 Metadata Space Total: 5.365GB
 Metadata Space Available: 5.358GB
 Thin Pool Minimum Free Space: 8.589GB
[root@test0527-84049 ~]# 

[root@test0527-84049 ~]# df -h | grep dm-
/dev/dm-5                       10G   33M   10G   1% /var/lib/docker/devicemapper/mnt/a8f6aa6fb185ebee0e6c74a7a8613e826db16ad7b371e78403356c677617979d
/dev/dm-6                       10G   33M   10G   1% /var/lib/docker/devicemapper/mnt/0687412fe5878f0990bc3968a59bed7e3296a46a58db239800549ce76d426960
/dev/dm-4                       10G   10G   20K 100% /var/lib/docker/devicemapper/mnt/af93ee69dd4aa9ddc23b510071999117c6848ecf1d6d694acbf6ba79fb3e8f49
/dev/dm-7                       10G   10G   20K 100% /var/lib/docker/devicemapper/mnt/52261f78a3cd85c52b08d220037e69c3dedbf7876553e70801e7773b7b574f57
/dev/dm-10                      10G   33M   10G   1% /var/lib/docker/devicemapper/mnt/2d4e4b547b7ba8e18f07a6b55770934352311a694cb3bc252cd08a624582fc63
/dev/dm-9                       10G   10G   20K 100% /var/lib/docker/devicemapper/mnt/62e871d13d0371218f771f2ebb8a7e84f59ff6d6fa81aab9bc8375564b792aa9
/dev/dm-11                      10G   33M   10G   1% /var/lib/docker/devicemapper/mnt/6ac7f933ff96d8addc78691c923c9ba8da3419edba77132bbbb8afca8dbccdcc

docker use thinpool vgpass, data% has reached to 100%, and docker info show no Data Space Available.
but i still can wirte data to disk in docker.

### Expected behavior
no disk space avaliable, any docker can't write data to disk.

### Actual behavior
my docker still can write data to disk.
who know why?

### Steps to reproduce the behavior

**Output of `docker version`:**

```[root@test0527-84049 ~]# docker version
Client:
 Version:      17.06.1-ce-rc1
 EulerVersion: 17.06.0.60
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   a599cfa
 Built:        Wed Feb 13 15:11:41 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce-rc1
 EulerVersion: 17.06.0.60
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   a599cfa
 Built:        Wed Feb 13 15:11:15 2019
 OS/Arch:      linux/amd64
 Experimental: false
[root@test0527-84049 ~]# 
(paste your output here)
```

**Output of `docker info`:**

```[root@test0527-84049 ~]# docker info
Containers: 22
 Running: 20
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 17.06.1-ce-rc1
Storage Driver: devicemapper
 Pool Name: vgpaas-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 85.9GB
 Data Space Total: 85.9GB
 Data Space Available: 0B
 Metadata Space Used: 6.463MB
 Metadata Space Total: 5.365GB
 Metadata Space Available: 5.358GB
 Thin Pool Minimum Free Space: 8.589GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
 Semaphore Set Used: 0
 Semaphore Set Total: 128
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: default runc
Default Runtime: runc
Init Binary: docker-init
containerd version: be96570d857a7ebb7c5aade8ba2d13f6863364aa (expected: d737904185972195c46a43009a1ebfd915547f43)
runc version: f05978158e9c026796d4b142db5d20d20655d91a (expected: a3a1cbfaa690777f5f9059d3feaff1eff0b98625)
init version: N/A (expected: )
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.62.59.83.h128.x86_64
Operating System: EulerOS 2.0 (SP2)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.686GiB
Name: test0527-84049
ID: J55K:BXDD:OCVS:GH2K:OFP5:4P4S:A4AM:DC4U:ZPKC:FEBP:GOSA:YTY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://100.79.0.44:20202/
Live Restore Enabled: true

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
[root@test0527-84049 ~
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
devicemapper was deprecated and removed; let me close this one
