### ISSUE TITLE
Feature Request - Store original run parameters

### ISSUE THREAD

**Issue by ebogdum** [docker/for-linux#74]
Hi,

It would be very nice if the run command parameters would be stored in the docker inspect configuration.
On very complex setups loosing the original create command can be a disaster and at the moment there is no way of "replicating" the same command except going trough the "docker inspect <container-name>" by hand and gathering info.

It would be perfect if in "docker inspect <container-name>" there would be a field "create-command" or something appropriate that would store the original create/run command eg. "docker run -tid --restart=always -p 80:80 -p 443:443 -v /opt/nginx:/opt/nginx -v /opt/nginx_projects:/opt/nginx_projects nginx-prod" and this doesn't contain the network setup, or any extra environment variables.

Practically the new field should make the creation of a container reproducible without any fear of changes.

Thanks.

**Comment by dnephin** [comment]
This could be accomplished pretty easily by using labels.
In whatever script you use to start docker prepare the command line first:

```
docker_run_flags="..."
docker run --label com.example.myapp.flags="$docker_run_flags" $docker_run_flags
```

**Comment by ebogdum** [comment]
Hi, 

That is brilliant, now just to keep in mind to make this a part of every deploy. Well, thank you dnephin.

I'm going to close this.

Cheers guys.

**Comment by ebogdum** [comment]
Actually just to make it easier for everyone. I'm going to make a script and post it here.

Thanks
