### ISSUE TITLE
Branches for older releases

### ISSUE THREAD

**Issue by anhilde** [docker/for-linux#75]
Hi,

how can I find the sources for an older version of the docker cli? I use Docker version 1.12.6, build 88a4867/1.12.6

I have a problem here and would like to investigate it myself. I only find tags for 17.06 and 17.07. How can I checkout an older version?

Best Regards,

André

**Comment by dnephin** [comment]
Older tags are available at https://github.com/moby/moby

**Comment by thaJeztah** [comment]
Yes, Docker 17.05 and older can be found here; https://github.com/moby/moby/releases , Docker CE 17.06 and above are tagged in https://github.com/docker/docker-ce/releases
