### ISSUE TITLE
proxyconnect tcp: dial tcp: lookup : server misbehaving --><<Ubuntu 16.04 docker proxy behind corporate authentication not happening >>

### ISSUE THREAD

**Issue by ericjoy1991** [docker/for-linux#751]
* [ ] I searched existing issues before opening this one

### Expected behavior
I)docker login should succeed
2)docker run hello-world should run properly

### Actual behavior

docker logout
Not logged in to https://index.docker.io/v1/
root@bc-VirtualBox:/home/bc/Desktop/BC/TheOrgBook/docker# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 123456
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup usrname on 10.200.50.100:53: server misbehaving

sudo docker run hello-world
Unable to find image 'hello-world:latest' locally docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup usrname on 10.200.50.100:53: server misbehaving. See 'docker run --help'.

### Steps to reproduce the behavior
```
124 sudo apt update
125 apt-get update && apt-get upgrade -y
126 sudo apt-get install \n apt-transport-https \n ca-certificates \n curl \n gnupg-agent \n software-properties-common
127 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
128 sudo apt-key fingerprint 0EBFCD88
129 lsb_release -cs
130 sudo add-apt-repository \n "deb [arch=amd64] https://download.docker.com/linux/ubuntu \n $(lsb_release -cs) \n stable test nightly"
131 docker --version
132 sudo apt-get update
133 sudo apt-get install docker-ce docker-ce-cli containerd.io
134 apt-cache madison docker-ce
137 sudo apt-get install docker-ce=5:19.03.1~3-0~ubuntu-xenial docker-ce-cli=5:19.03.1~3-0~ubuntu-xenial containerd.io
```

**Output of `docker version`:**

```
Docker version 19.03.1, build 74b1e89e8a
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-55-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.852GiB
 Name: bc-VirtualBox
 ID: QMI6:NVI5:J7VQ:3HW3:QAM7:ZUUE:QQ3E:GH3B:XGNR:SRMU:LJC6:XCNT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://usrname:paswrod@proxy.example.com:8080/
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (Ubuntu 16.04)**
```
/.docker# lsb_release -a
No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 16.04.6 LTS Release: 16.04 Codename: xenial

/.docker# docker --version
Docker version 19.03.1, build 74b1e89e8a

/.docker# uname -a
Linux bc-VirtualBox 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

/Desktop# cat /etc/apt/apt.conf
Acquire::http::proxy "http://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::https::proxy "https://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::ftp::proxy "ftp://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::socks::proxy "socks://usrname:paswrod@proxy.example.com:8080/";

/Desktop# cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://usrname:paswrod@proxy.example.com:8080/" 
Environment="HTTPS_PROXY=https://usrname:paswrod@proxy.example.com:8080/ 
Environment="NO_PROXY="localhost,127.0.0.1,::1"

~/.docker# cat config.json
{ "proxies": { "default":
{
 "httpProxy": "http://usrname:paswrod@proxy.example.com:8080",

 "httpsProxy": "https://usrname:paswrod@proxy.example.com:8080",

 "noProxy": "localhost,127.0.0.0/8,*.local,host.docker.internal"
} } }
once PROXY is configured tries out below steps
sudo systemctl daemon-reload
sudo systemctl restart docker.service



```

**Comment by thaJeztah** [comment]
Does it work if you configure a different DNS server? https://stackoverflow.com/a/34833611

**Comment by ericjoy1991** [comment]
Hi thaJeztah , thank you for reaching out to take a look on this issue.
I have performed the listed steps to change the DNS server in my ubuntu system a few seconds ago .

_1)Go to the Network icon in the top panel.
2)Select Edit Connections.
3)Open the connection that you wish to modify, (in my case i choose **Bridge =docker0**)
4)Select the IPv4 tab.
5)Set the Method to Automatic (DHCP) addresses only.
6)In the DNS Servers field, enter a comma-separated list of your DNS servers(**127.0.1.1, 8.8.4.4, 8.8.8.8**) .
7)Click the Save button_

then i restarted the network using
/etc/init.d/networking restart


And tired out the same steps , but the issue still perists. Do you have any other thoughts on this?

**Comment by ericjoy1991** [comment]
Hi @thaJeztah ,

I was able to get past the issue mentioned above...Before that idid set proxy for the listed location since i was behind a corporate proxy . Hope this helps others who is facing similar issues.

##################################

**~# cat /etc/apt/apt.conf**
_Acquire::http::proxy "http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/";
Acquire::https::proxy "http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/";
Acquire::ftp::proxy "ftp://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/";
Acquire::socks::proxy "socks://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/";_

##################################

**~# cat .gitconfig**
_[http]
        sslVerify = true
        sslCAinfo = /etc/ssl/certs/ca-certificates.crt
        proxy = http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>
[user]
        email = my_email@outlook.com
        name = myusername_

##################################

**~# cat /etc/systemd/system/docker.service.d/https-proxy.conf**
[_Service]
Environment="HTTPS_PROXY=http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>"_


##################################

**:~# cat .docker/config.json**
_{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "MzQ1NjE5sOmEgiBbrish9vazIwMTk="
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.1 (linux)"
        },
        "proxies": {
                "default": {
                        "httpProxy": "http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>",
                        "httpsProxy": "https://<usr_name>:<pas_word>@<proxy_dns>:<port_num>",
                        "noProxy": "localhost,127.0.0.0/8,*.local,host.docker.internal"
                }
        }_

##################################

**:~# cat /etc/environment**
_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
https_proxy="http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/"
http_proxy="http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/"
ftp_proxy="ftp://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/"
socks_proxy="socks://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/"_


##################################


_export HTTPS_PROXY=http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/
export HTTP_PROXY=http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/
export FTP_PROXY=ftp://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/
export SOCKS_PROXY=socks://<usr_name>:<pas_word>@<proxy_dns>:<port_num>/_

##################################



Things which was the major cause for proxy issue is listing down:

> I was using a character in my password , which is suppose to be replaced by equalent (eg : # should replace by %23) .
 Hence to avoid further confusions i reset my password without special characters.

> As per docker's official site if we are using behind a https proxy we have to follow the format given as below


**~# cat /etc/systemd/system/docker.service.d/https-proxy.conf**
_[Service]
Environment="HTTPS_PROXY=https://<usr_name>:<pas_word>@<proxy_dns>:<port_num>"_






but once i started using the below given format only then my  "https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: EOF" was resolved

_[Service]
Environment="HTTPS_PROXY=http://<usr_name>:<pas_word>@<proxy_dns>:<port_num>"_

[even for "HTTPS_PROXY" i had to use 'http' ]

**Comment by jeubis** [comment]
@EtricKombat just thought I would say thanks for that hint at the end. HTTPS_PROXY has to use http://your-proxy. That was way harder than what it needed to be :(

**Comment by EtricKombat** [comment]
@jeubis  i'm glad that you figure it out and were kind enough to explain it back to me.

**Comment by gagan211** [comment]
@EtricKombat thanks a lot ,it worked properly after the instructions that yoy mentioned.
