### ISSUE TITLE
Docker pull ignore registry-mirrors

### ISSUE THREAD

**Issue by rickywu** [docker/for-linux#754]
* [x] This is a bug report

### Steps to reproduce the behavior
1. daemon.json:
```
{
  "registry-mirrors": ["http://10.16.2.206:8003"],
  "insecure-registries": [
    "10.16.2.206:8003"
  ]
}
```

2. docker info:
```
Insecure Registries:
 10.16.2.206:8003
 127.0.0.0/8
Registry Mirrors:
 http://10.16.2.206:8003/
```

3. docker pull mysql
```
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.16.10.98:53: read udp 10.0.28.17:38377->10.16.10.98:53: i/o timeout
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 13
 Running: 9
 Paused: 0
 Stopped: 4
Images: 55
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: tidb-dev
ID: TJLV:ZUAH:ET32:OPUX:5AVB:SDDP:LPZW:ZQM5:Q2ZH:2DDF:AVZV:CQUI
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 10.16.2.206:8003
 127.0.0.0/8
Registry Mirrors:
 http://10.16.2.206:8003/
Live Restore Enabled: false
Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
```

How to skip query for registry-1.docker.io if my server without internet access?

**Comment by cnwangjie** [comment]
same with me
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 19
2.168.64.4:35449->192.168.64.1:53: read: connection refused
```

**Comment by kevin-wang-cy** [comment]
Same issue (docker skip the registry-mirror settings) on the latest version.

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by mlaffargue** [comment]
> Same issue (docker skip the registry-mirror settings) on the latest version.

@kevin-wang-cy Do you mean it worked in previous version ?

I just installed a nexus repository and have the same problem

**Comment by ncouse** [comment]
I had a similar problem, but it was a configuration issue on the internal mirror.

The problem is that it does contact the mirror and fails and then reverts to trying the main registry which fails, but only this is reported on the console. 

I eventually saw the errors in syslog and was able to identify the issue. 

The console output is very confusing in terms of trying to figure out what is actually going on. 


Someone mentioned using Nexus for their mirror. Note that this by default requires a login, so contacting this registry as a mirror may silently fail in the background. Disable the auth for pull or perform a login.

**Comment by rickywu** [comment]
@ncouse  Probally this is the root cause, my docker can use mirror not, other people should check your registry auth and settings.

**Comment by sduqlsc** [comment]
Hi, i have the same issue:
```Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 29
 Server Version: 19.03.4-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.8-3-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 14.59GiB
 Name: manjaro-eden
 ID: YCY6:5HE4:I4GO:H75A:2MX2:H26H:WI4X:GDYM:57FK:ATOA:L24L:3TPI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

when setting mirrors in the `daemon.json` with the content 
```
{
  "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn/"]
}
```

the question is it was ok before, but now i have to remove the file in which case it would work all right.

**Comment by gaoweibupt** [comment]
I have the same problem. My docker is working in centos8 in the virtualBox, and it also ignored DNS of the centos8.

**Comment by psytester** [comment]
Just in case others will have same issue as me.
I'm behind a JFrog Artefactory Caching-Proxy without direct internet access and the JFrog remote-docker is set-up as in [JFrog wiki](https://www.jfrog.com/confluence/display/RTF/Docker+Registry#DockerRegistry-RemoteDockerRepositories)

I only have credentials to the JFrog Artefactory here to ```<JFrog-artifactory-hostname>```.
This Artefactory logs in into real docker.io with its own credentials.
```
# docker login <JFrog-artifactory-hostname>
.....
Login Succeeded
```

Default pulling images does not work:
```
# docker pull selenium/node-firefox:latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
```
because I have to prefix the image with path-prefix ```<JFrog-artifactory-hostname>/docker-remote```
```
# docker pull <JFrog-artifactory-hostname>/docker-remote/selenium/node-firefox:latest
latest: Pulling from docker-remote/selenium/node-firefox
7ddbc47eeb70: Already exists
...
Digest: sha256:3a92810aca49182944c72e15c68dd8561731f25e723983d8702a9234d32163d6
Status: Downloaded newer image for <JFrog-artifactory-hostname>/docker-remote/selenium/node-firefox:latest
<JFrog-artifactory-hostname>/docker-remote/selenium/node-firefox:latest
```

Default running the image will not work, due to missing internet access and registry-1.docker.io is unknown:
```
# docker run -d -v /dev/shm:/dev/shm selenium/node-firefox
Unable to find image 'selenium/node-firefox:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution.
See 'docker run --help'.
```

But running the image with the path-prefix ```<JFrog-artifactory-hostname>/docker-remote``` again, it finally works:
```
# docker run -d -v /dev/shm:/dev/shm <JFrog-artifactory-hostname>/docker-remote/selenium/node-firefox
3408b60fb567b688056864e142c109a8b82f84bf09e1e9273193660841faac16

# docker ps
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS               NAMES
3408b60fb567        <JFrog-artifactory-hostname>/docker-remote/selenium/node-firefox   "/opt/bin/entry_poin…"   8 seconds ago       Up 7 seconds                            affectionate_darwin
```

Playing around with a registry-mirror did not solve my problem nor setting up a [http-proxy](https://docs.docker.com/config/daemon/#httphttps-proxy) because my system is 100% "offline" and behind this JFrog Artefactory server.

BTW: I'm running on Ubuntu 18.04 with docker-ce 19.03.4 and containerd.io 1.2.10-3

**Comment by jl-massey** [comment]
I found this SAME problem that made no sense at all to me.   I added credentials for everything that SHOULD have worked...until:

For me, the solution was...unexpected:
`docker logout`

I had cached credentials for docker.io and apparently that was making it check it first.   After logging out of it, things worked as expected.   Bug or just unexpected....you be the judge!

**Comment by libinglong** [comment]
> I found this SAME problem that made no sense at all to me. I added credentials for everything that SHOULD have worked...until:
> 
> For me, the solution was...unexpected:
> `docker logout`
> 
> I had cached credentials for docker.io and apparently that was making it check it first. After logging out of it, things worked as expected. Bug or just unexpected....you be the judge!

Amazing!This works for me!

**Comment by GF-Huang** [comment]
Same issue, how to solve.

**Comment by volkovd** [comment]
> I found this SAME problem that made no sense at all to me. I added credentials for everything that SHOULD have worked...until:
> 
> For me, the solution was...unexpected:
> `docker logout`
> 
> I had cached credentials for docker.io and apparently that was making it check it first. After logging out of it, things worked as expected. Bug or just unexpected....you be the judge!

Worked for me as well. 
Just do "docker logout <your_repo_url:port>" for all repos where you logged in and then login again.

**Comment by FrankFang** [comment]
`docker logout` is Not working for me

**Comment by Persi** [comment]
> I found this SAME problem that made no sense at all to me. I added credentials for everything that SHOULD have worked...until:
> 
> For me, the solution was...unexpected: `docker logout`
> 
> I had cached credentials for docker.io and apparently that was making it check it first. After logging out of it, things worked as expected. Bug or just unexpected....you be the judge!

You are a god! :D Thanks for saving me hours of wasting time!

**Comment by micheljung** [comment]
In my case, this didn't work:

```
{
  "registry-mirrors": ["http://127.0.0.1"]
}
```

But this did:
```
{
  "registry-mirrors": ["http://127.0.0.1:5000"]
}
```

**Comment by sunlad1** [comment]
> I found this SAME problem that made no sense at all to me. I added credentials for everything that SHOULD have worked...until:
> 
> For me, the solution was...unexpected: `docker logout`
> 
> I had cached credentials for docker.io and apparently that was making it check it first. After logging out of it, things worked as expected. Bug or just unexpected....you be the judge!

worked for me either, thx very much

**Comment by VChernyshoff** [comment]
I have found some solution my case:

issue:
1. pull postgress:14
2. docker tag postgress:14 mynexus.local:10084/postgres:14
3. docker push mynexus.local:10084/postgres:14
4. on machine with no internet I have mirror:
`     "registry-mirrors": ["http://mynexus.local:10084"]`
5. I do docker pull postgres:14 and get 
`Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 54.198.86.24:443: connect: connection refused`
6. I have notice, that when image has group, like 
    docker pull testcontainers/ryuk:0.3.4 - it works fine.
7. The solution is add **'library'** when tag image:
not correct: `docker tag postgress:14 mynexus.local:10084/postgres:14`
correct: `docker tag postgress:14 mynexus.local:10084/library/postgres:14`
8. After pushing image mynexus.local:10084/library/postgres:14, the command `docker pull postgres:14` works fine from mynexus.local
