### ISSUE TITLE
Name resolution problem in alpine linux

### ISSUE THREAD

**Issue by xmagpie** [docker/for-linux#755]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Description
I have a container which I need to send requests to the server in the private network. I know about issues related to DNS settings and have the modified `/etc/docker/daemon.json` (submitted below). I have tested several scenarios:

1. Running container based on the **ubuntu:latest (18.04)** image **without** specifying custom network. This works as expected, I am able to resolve the private server inside the container.
2. Running container based on the **ubuntu:latest (18.04)** image **with** specifying custom network. This also works as expected, I am able to resolve the private server inside the container.
3. Running container based on the **alpine:latest (3.10.1)** image **without** specifying custom network. This again works as expected, I am able to resolve the private server inside the container.
4. Running container based on the **alpine:latest (3.10.1)** image **with** specifying custom network. This again works as expected, I am **not** able to resolve the private server inside the container.

As I said the last use-case fails.

### Expected behavior
The server from the private network should be resolvable and one should be able to ping it inside the container based on the alpine image (similar to the ubuntu container).

### Actual behavior
The server is not resolvable and the ping command fails.

### Steps to reproduce the behavior
1. Set DNS `"dns"` and `"dns-search"` settings in the `/etc/docker/daemon.json` for the usage of private DNS servers and local domain.
2. Create test network `docker network create testnet`.
2. Run docker container based on the alpine linux: `docker run --rm -it --network=testnet alpine:3.10.1`.
3. Ping the machine from the private network without specifying it's full name, e.g. `ping server` instead of `ping server.private.local.domain`.
4. Get `ping: bad address 'your machine'`

**Output of `docker version`:**

```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 62
 Server Version: 19.03.1-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.2.5-arch1-1-ARCH
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.27GiB
 Name: private-host
 ID: SUE3:ELVQ:JJLL:N5FF:5OWF:Y2WU:EDDA:B7GY:XHES:U6RN:K7P2:QS4K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  private-registry:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
1. Alpine Linux image version 3.10.1
2. Contents of the `/etc/docker/daemon.json` (without sensitive data):

```
{"insecure-registries" : ["private-registry:5000"], "dns": ["<private-dns-sever-ip>", "<private-dns-sever-ip>"], "dns-search": ["private.local.domain"]}
```

3. Host `/etc/resolv.conf`

```
# Generated by resolvconf
domain private.local.domain
nameserver <private-dns-sever-ip>
nameserver <private-dns-sever-ip>
```

4. Container `/etc/resolv.conf`

```
search private.local.domain
nameserver 127.0.0.11
options ndots:0
```

**Comment by arkodg** [comment]
@xmagpie can you also share the container `/etc/resolv.conf` output for the ubuntu image that works

**Comment by xmagpie** [comment]
@arkodg sure, it is the same as the last one:
```
search private.local.domain
nameserver 127.0.0.11
options ndots:0
```

I should mention that this and the previous `/etc/resolv.conf` file contents relate to alpine and ubuntu containers that run **with** custom network enabled.

For the case without custom network, `/etc/resolv.conf` equals to the host one (both for alpine and ubuntu containers), e.g.:
```
domain private.local.domain
nameserver <private-dns-sever-ip>
nameserver <private-dns-sever-ip>
```

I  suspect that this may relate to how the DNS settings and `resolv.conf` file are handled in alpine linux itself (maybe differences of ndots handling etc, [see](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS)) but I am not sure because of different behavior with or without custom network enabled.

**Comment by xmagpie** [comment]
I can verify that the problem relates to the `/etc/resolv.conf` (ndots option) handling in alpine itself. If I change ndots value in `/etc/resolv.conf` from 0 to e.g. 5, my private server becomes resolvable and the `ping` command succeeds.

I think, that the issue can be closed now?

**Comment by arkodg** [comment]
thanks for confirming it was a `ndots` configuration issue

lets close the issue !
