### ISSUE TITLE
Grouping commands in one layer

### ISSUE THREAD

**Issue by ppoilbarbe** [docker/for-linux#765]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

#### Group command

It would be nice to add a GROUP and ENDGROUP kind of keywords to docker file to allow
all commands between these two keywords to act in a single layer.

This may improve readability of Dockerfiles (especially with RUN commands)
when you want to minimize images/layer sizes (for example installing packages
line by line and cleaning caches)

Issue #303 asks a question for a little use case of this one.

#### --ignore-groups

This option may be added to the "docker build" command in order to ignore group
definitions. This is for developers which may want to test a special command.

At now, when I want to test, I have to break all piped run commands (many commands
joined by "&&") each time. With this behaviour, il it simplified (just adding option to
docker build). No risk of error. One version of Dockerfile

### Actual behavior

Does not exist

**Additional environment details (AWS, VirtualBox, physical, etc.)**

All.

**Comment by cpuguy83** [comment]
Sounds like https://github.com/moby/moby/issues/34423
Let's move the discussion there, thanks!
