### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by universeroc** [docker/for-linux#782]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
docker daemon started

### Actual behavior
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Steps to reproduce the behavior
1. docker pull ubuntu:18.04
2. docker run -it ubuntu:18.04 /bin/bash
3. apt update && apt install docker
4. service docker start

**Output of `docker version`:**
```
Docker version 18.09.7, build 2d0083d
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
docker client is Docker for Desktop on Windows 10

**Comment by cpuguy83** [comment]
You can't run docker in a container without `--privileged`.
You'll also likely need to `-v /var/lib/docker`.

In fact there is an official image for running docker-in-docker: `docker:dind`

**Comment by niv-breez** [comment]
I am getting the same error.
The command I use:
docker run -i --privileged -v /var/lib/docker -t my-docker:my-tag /bin/bash
