### ISSUE TITLE
Docker daemon restarts on fatal error "concurrent map writes"

### ISSUE THREAD

**Issue by JakeBonek** [docker/for-linux#807]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker should handle concurrent map writes gracefully.
[docker_logs.txt](https://github.com/docker/for-linux/files/3698065/docker_logs.txt)
[docker_logs2.txt](https://github.com/docker/for-linux/files/3698077/docker_logs2.txt)

### Actual behavior
Docker daemon restarts after error message "fatal error: concurrent map writes"

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 59
  Running: 7
  Paused: 0
  Stopped: 52
 Images: 70
 Server Version: 18.09.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-29-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 56
 Total Memory: 503.8GiB
 Name: cn04
 ID: 45ZP:5HM7:R4G4:4AWS:F3UX:HJW7:IZXR:G5DF:WP6Z:TE6H:JFJA:2SLX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

These are running on baremetal via Rancher 1.6. We have other hosts running a 4.18.0 kernel in the same environment and we don't see this issue. Only on the host were we have the 5.0.0-29 kernel are we experiencing this problem.

**Comment by cpuguy83** [comment]
Thanks, this is fixed already in the 19.03.2 release.
https://github.com/docker/engine/pull/310

I see your server version (18.09) is older than your client (19.03).
To get this fix you must upgrade to 19.03.2.

Thanks!
