### ISSUE TITLE
Why is Docker able to handle SIGTERM only with & wait command?

### ISSUE THREAD

**Issue by mne1991** [docker/for-linux#81]
I am facing strange behavior, I have Docker image which has this entry point script:

    #!/bin/bash
    trap " \
            service apache2 stop; \
            " SIGHUP SIGINT SIGTERM
    trap "exit" ERR
    
    service apache2 start
    
    tail -f /var/log/apache2/access.log

The previous script does **NOT** handles the SIGTERM as supposed, it just does nothing! (I can see that in Apache log, that it was terminated uncleanly), and Docker waits for 10 seconds and then kill it.

But when I change the last line to the following, **it works perfectly**!

    tail -f /var/log/apache2/access.log & wait

The following also did **NOT** work:

    tail -f /var/log/apache2/access.log &

Could some one explain that behavior for me? I didn't understand why is that happening. What is that magic behind `& wait`? And is there any better way to keep Docker container running, and in the same time being able to handle the signals?

**Comment by PaulCharlton** [comment]
1. “wait” waits for all child processes (apache and tail) to terminate cleanly, even when it receives a SIGTERM
2. the “&” without a wait allows an immediate “exit 0” from the script, which terminates all child processes
3. the “tail” without the “&” waits for “tail” to receive SIGTERM, then immediately exits the script, killing the child apache process.

**Comment by cpuguy83** [comment]
Why not start apache directly rather than going through `service`?

The reason the first case is failing is because you have `tail` running in the foreground and are not stopping it, you are only stopping `apache2` (assuming it actually works).

Closing since this isn't really an issue, but feel free to discuss.
Thanks!

**Comment by MohammedNoureldin** [comment]
> Why not start apache directly rather than going through `service`?
> 
> The reason the first case is failing is because you have `tail` running in the foreground and are not stopping it, you are only stopping `apache2` (assuming it actually works).
> 
> Closing since this isn't really an issue, but feel free to discuss. Thanks!

Excuse me please for my too late reply. Somehow I missed this totally though I am daily on GitHub. Just it was funny that I've been googling this again, and came again to my question :)

Just to answer your question 4 years later, this was actually a simplified example, it is interesting in case I have multiple services running and I want to kill some of them gracefully.
