### ISSUE TITLE
YUM - Forbidden error

### ISSUE THREAD

**Issue by objohnson** [docker/for-linux#814]
This is a bug report
 This is a feature request
[x ] I searched existing issues before opening this one
Expected behavior
Install Docker Community edition

Actual behavior
Keep getting 403. Accessing the URL from browser also gives error:

https://download.docker.com/linux/centos/docker-ce.repo

Steps to reproduce the behavior

```bash
# yum install -y yum-utils device-mapper-persistent-data  lvm2
# yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
# yum install docker-ce
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] HTTPS Error 403 - Forbidden
```

Output of docker version:

No docker for output
Output of docker info:

No docker for output
Additional environment details (AWS, VirtualBox, physical, etc.)

**Comment by Will-W** [comment]
I'm getting the same trying to add the docker repos on Fedora. The whole of https://download.docker.com/linux is giving a 403.

**Comment by jensenja** [comment]
probably related to #812 - they're working on it

**Comment by seemethere** [comment]
Issue should now be resolved, this can be closed
