### ISSUE TITLE
containerd 1.2.10 deb package missing ubuntu xenial

### ISSUE THREAD

**Issue by Heimschmiede** [docker/for-linux#816]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

when upgrading to docker-ce 19.03.3 on Ubuntu Xenial I get a 404 while downloading the related package of containerd (version 1.2.10).

```
root@xxxx:~# apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease         
Hit:3 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease                       
Get:4 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]                  
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Fetched 66.2 kB in 0s (125 kB/s)                  
Reading package lists... Done
root@xxxx:~# apt-get dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  linux-headers-4.4.0-165 linux-headers-4.4.0-165-generic linux-image-4.4.0-165-generic
  linux-modules-4.4.0-165-generic linux-modules-extra-4.4.0-165-generic
The following packages will be upgraded:
  base-files containerd.io docker-ce docker-ce-cli e2fslibs e2fsprogs grub-legacy-ec2
  initramfs-tools initramfs-tools-bin initramfs-tools-core libcomerr2 libpython2.7
  libpython2.7-dev libpython2.7-minimal libpython2.7-stdlib libpython3.5
  libpython3.5-minimal libpython3.5-stdlib libss2 linux-generic linux-headers-generic
  linux-image-generic linux-libc-dev python2.7 python2.7-dev python2.7-minimal python3.5
  python3.5-minimal tzdata
29 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.8 MB/192 MB of archives.
After this operation, 296 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 https://download.docker.com/linux/ubuntu xenial/stable amd64 containerd.io amd64 1.2.10-2
  404  Not Found
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/containerd.io_1.2.10-2_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

Latest containerd package available in
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/
is version 1.2.6-3

### Expected behavior

`apt-get dist-upgrade` succeeds upgrading to latest docker-ce version

### Actual behavior

404 while downloading containerd 1.2.10

### Steps to reproduce the behavior

```
apt-get update
apt-get dist-upgrade
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:26:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-164-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.949GiB
 Name: xxxx
 ID: 7X75:SQ3C:6TZZ:4AY4:KWAL:FORZ:CG34:FZ7F:OS4L:7XNH:APLO:2UPZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by tallandtree** [comment]
I have the same with fedora:

`Cannot download Packages/containerd.io-1.2.10-3.2.fc29.x86_64.rpm: All mirrors were tried; Last error: Status code: 404 for https://download.docker.com/linux/fedora/29/x86_64/stable/Packages/containerd.io-1.2.10-3.2.fc29.x86_64.rpm `

Guess some issue with this particular version.

**Comment by Heimschmiede** [comment]
in the release notes of docker-ce 19.03.3 it is written that containerd got bumped to 1.2.10
see https://github.com/docker/docker-ce/releases/tag/v19.03.3

**Comment by tallandtree** [comment]
@Heimschmiede : does that explain why it is not available?

**Comment by erzetpe** [comment]
Same issue for Ubuntu Bionic. Latest package is containerd 1.2.6.

**Comment by cchris-org** [comment]
+1  Debian Stretch

**Comment by lukaskellerstein** [comment]
+1

**Comment by cost6** [comment]
+1 Debian Stretch

**Comment by Heimschmiede** [comment]
> @Heimschmiede : does that explain why it is not available?

@tallandtree: yes but I think it got forgotten to upload the new containerd deb package.

**Comment by Cpmorrissey** [comment]
+1 debian stretch, MX-18.3_x64 Continuum, 4.19.0-1-amd64 x86_64, Xfce 4.12.3.
Temp fix,    echo "containerd.io hold" | sudo dpkg --set-selections
Just dont forget to remove hold after fix,    echo "containerd.io install" | sudo dpkg --set-selections

**Comment by mhbates** [comment]
+1 Debian Stretch

**Comment by mydeadlyvenoms** [comment]
+1 Debian Stretch

**Comment by howard6066** [comment]
+1 Ubuntu 16.04

**Comment by prasket** [comment]
+1 Debian Stretch 
----
Err:1 https://download.docker.com/linux/debian stretch/stable amd64 containerd.io amd64 1.2.10-2
  404  Not Found
E: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.10-2_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by daniel-dsouza** [comment]
temporary fix for xenial similar to @Cpmorrissey 

```
sudo apt-mark hold containerd.io
// do what apt operation you were originally trying for
sudo apt-mark unhold containerd.io
```

**Comment by RedbackThomson** [comment]
The missing packages are the result of their CI/CD pipeline failing.
See the following issue:
https://github.com/docker/for-linux/issues/812#issuecomment-540634441

**Comment by RedbackThomson** [comment]
See my discussions here if you would like to manually patch containerd/runc is the meantime:

https://github.com/opencontainers/runc/issues/2138

**Comment by Cpmorrissey** [comment]
Actually seems to be fixed now.. Clean your apt cache then update and upgrade. Working for debian stretch atleast

**Comment by RedbackThomson** [comment]
> Actually seems to be fixed now.. Clean your apt cache then update and upgrade. Working for debian stretch atleast

https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/ The repository does not show containerd 1.2.10, though.

**Comment by Cpmorrissey** [comment]
> > Actually seems to be fixed now.. Clean your apt cache then update and upgrade. Working for debian stretch atleast
> 
> https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/ The repository does not show containerd 1.2.10, though.

Hmm thats weird. I literally just tried it, updated to 1.2.10 from 1.2.6

**Comment by db-coder** [comment]
I just updated to 1.2.10-2 too. Looks like it's fixed.

**Comment by thaJeztah** [comment]
yup; packages were just brought back up; https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/

sorry for the inconvenience! let me close this one
