### ISSUE TITLE
Unable to find image 'hello_world:latest' locally docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). See 'docker run --help'.

### ISSUE THREAD

**Issue by bpradeep508** [docker/for-linux#819]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
Looks like the connection timed out. Did you check connectivity?

**Comment by bpradeep508** [comment]
no

**Comment by cpuguy83** [comment]
I'm going to close this since it doesn't look like a bug, but feel free to discuss.
Thanks!

**Comment by bpradeep508** [comment]
hello world not running
