### ISSUE TITLE
Feature Request: Allowing to Specify Owner for Docker Secrets

### ISSUE THREAD

**Issue by codecitizen** [docker/for-linux#82]
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Give an option for docker secrets to set the owner, e.g.: 

`docker service create --secret source=ssh-key,target=/home/myuser/.ssh/id_rsa,owner=myuser ...`

In my case: I maintain a CI system that has multiple workers running in a docker swarm. The CI software I use requires to run as a none-root user in the container. All of my build pipelines eventually require a `ssh` or `scp` connection to their deployment server. I'd like to distribute the private key to thee swarm instances via *docker secrets*, but the owner is always set to *root*, therefore I can't use the secrets file as private key. Running `chown -R myuser /home/myuser/.ssh` won't work either, resulting in `chown: /home/myuser/.ssh/id_rsa: Read-only file system`.

**Comment by dnephin** [comment]
This is already supported, but I couldn't find it document anywhere outside of the [compose reference](https://docs.docker.com/compose/compose-file/#long-syntax-2).

You can use uid and gid when you attach a secret to a service. 
```
--secret name,uid=...,gid=...
```

**Comment by codecitizen** [comment]
Oh, nice, thank you!
