### ISSUE TITLE
Missing 18.09.10 files on repository

### ISSUE THREAD

**Issue by eduardobaitello** [docker/for-linux#824]
As stated in [Docker Engine Release Notes](https://docs.docker.com/engine/release-notes/#180910), the 18.09.10 version was released on 2019-10-08.

I'm trying to install the respective Docker CE on CentOS, but the `.rpm` files are not available at the [CentOS 7 repo](https://download.docker.com/linux/centos/7/x86_64/stable/Packages/). I can't even find a [tag/release for 18.09.10](https://github.com/docker/docker-ce/releases/tag/v18.09.10) on docker-ce GitHub.

The files were not built or I'm missing something?

_The 19.03.3 (released on the same day) is correctly available at CentOS repository and Github release._

**Comment by MycroftHolmes1989** [comment]
One is Enterprise and one is community. That's why, probably.

**Comment by MycroftHolmes1989** [comment]
One is Docker Enterprise and the other is Docker Community. Is that why?

**Comment by eduardobaitello** [comment]
@MycroftHolmes1989 As per the release notes page:

> Docker Engine - Enterprise builds upon the corresponding Docker Engine - Community that it references...

So there should be a corresponding CE version available in the repos.

**Comment by sudo-bmitch** [comment]
Older versions of Docker CE are only supported and patched for about a month after the next major release comes out. The Docker Enterprise releases continue on older versions for much longer, I believe a year. So there should not be any more docker-ce 18.09 releases now that 19.03 has been out for several months.

**Comment by seemethere** [comment]
@sudo-bmitch is correct, major CE releases are only supported for one month after the following major CE release.

18.09 CE support ended in August.

**Comment by eduardobaitello** [comment]
Thanks for clarifying. Closing this as it is not as an issue though.

I hope that Kubernetes [validates](https://github.com/kubernetes/kubernetes/blob/54a30700a38452a5113adcfba0f98adcc5e05f2d/CHANGELOG-1.16.md#unchanged) Docker version 19.x soon :)
