### ISSUE TITLE
yum install docker failing

### ISSUE THREAD

**Issue by rlupo06** [docker/for-linux#826]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
All package get install

### Actual behavior
```
# sudo yum install docker-ce docker-ce-cli containerd.io
Resolving Dependencies
--> Running transaction check
---> Package containerd.io.x86_64 0:1.2.5-3.1.el7 will be updated
---> Package containerd.io.x86_64 0:1.2.10-3.2.el7 will be an update
--> Processing Dependency: container-selinux >= 2:2.74 for package: containerd.io-1.2.10-3.2.el7.x86_64
---> Package docker-ce.x86_64 3:18.09.5-3.el7 will be updated
---> Package docker-ce.x86_64 3:19.03.3-3.el7 will be an update
--> Processing Dependency: container-selinux >= 2:2.74 for package: 3:docker-ce-19.03.3-3.el7.x86_64
---> Package docker-ce-cli.x86_64 1:18.09.5-3.el7 will be updated
---> Package docker-ce-cli.x86_64 1:19.03.3-3.el7 will be an update
--> Finished Dependency Resolution
Error: Package: containerd.io-1.2.10-3.2.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
           Installed: 2:container-selinux-2.9-4.el7.noarch (installed)
               container-selinux = 2:2.9-4.el7
Error: Package: 3:docker-ce-19.03.3-3.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
           Installed: 2:container-selinux-2.9-4.el7.noarch (installed)
               container-selinux = 2:2.9-4.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
### Steps to reproduce the behavior
```
sudo yum install docker-ce docker-ce-cli containerd.io
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: tpro6jjwcj0qg02yssiylj6wa
 Is Manager: false
 Node Address: 172.30.171.132
 Manager Addresses:
  172.30.171.104:2377
  172.30.171.105:2377
  172.30.171.116:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.638GiB
Name: docker-swarm-worker-7.novalocal
ID: Y65F:RPXW:M4R4:65PP:DBQY:C3WQ:ZDEP:FAQH:AKSI:OLUC:UY5Z:KFNP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 172.30.155.141
 172.30.155.141:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by fheuer** [comment]
You instance could not find that package. You need to install it separately. You can enable the server-extra-rpms repo 

`subscription-manager repos --enable=rhel-7-server-extras-rpms`

or try to install it from centos packages:

`sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm`

**Comment by rushins** [comment]
hello i have the same error today can't install seems the repository is not available from the following.

sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

**Comment by rlupo06** [comment]
> You instance could not find that package. You need to install it separately. You can enable the server-extra-rpms repo
> 
> `subscription-manager repos --enable=rhel-7-server-extras-rpms`
> 
> or try to install it from centos packages:
> 
> `sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm`

The instance does have that packaged installed. If you look at the error message it states that selinux-2.95... is installed     

 `Installed: 2:container-selinux-2.9-4.el7.noarch (installed)`

**Comment by fheuer** [comment]
Well, I clearly overlooked that.
I tried to install on a new vm (centos 7.7.1908) via convenience script and its procedure was completed without error.

Did you try to remove container-selinux-2.9-4.el7.noarch and reinstall via
`sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm` ?

You might be on a centos 8?

**Comment by fheuer** [comment]
Also there ist `https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm`

**Comment by rlupo06** [comment]
> Well, I clearly overlooked that.
> I tried to install on a new vm (centos 7.7.1908) via convenience script and its procedure was completed without error.
> 
> Did you try to remove container-selinux-2.9-4.el7.noarch and reinstall via
> `sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm` ?
> 
> You might be on a centos 8?

I tried removing the container-selinux-2.9-4.el7.noarch and reinstall however the issue still persists. I'm on centos 7. The docker info prints out Operating System: CentOS Linux 7 (Core)

**Comment by andrewhsu** [comment]
@rlupo06 you should have the `extras` repo enabled (comes enabled by default for centos7):
```
$ yum repoinfo extras
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.tocici.com
 * extras: mirror.tocici.com
 * updates: mirror.tocici.com
Repo-id      : extras/7/x86_64
Repo-name    : CentOS-7 - Extras
Repo-status  : enabled
Repo-revision: 1571783745
Repo-updated : Tue Oct 22 22:35:46 2019
Repo-pkgs    : 305
Repo-size    : 407 M
Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=genclo
Repo-baseurl : http://mirror.tocici.com/centos/7.7.1908/extras/x86_64/ (9 more)
Repo-expire  : 21,600 second(s) (last: Wed Oct 23 19:01:28 2019)
  Filter     : read-only:present
Repo-filename: /etc/yum.repos.d/CentOS-Base.repo

repolist: 305
```
check to make sure that is the case because installation of docker-ce should go fine, i just checked myself with official documentation https://docs.docker.com/install/linux/docker-ce/centos/

**Comment by kolyshkin** [comment]
@rlupo06 Maybe you need to upgrade your centos system first, as in
`yum update`.

After you do it, can you please report the output of
`rpm -q centos-release`
and try upgrading docker-ce again?

**Comment by zhulinwei** [comment]
maybe you should reboot your machine and select Amazon Linux 2 (not Amazon Linux) as your environment

**Comment by rlupo06** [comment]
> @rlupo06 you should have the `extras` repo enabled (comes enabled by default for centos7):
> 
> ```
> $ yum repoinfo extras
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: mirror.tocici.com
>  * extras: mirror.tocici.com
>  * updates: mirror.tocici.com
> Repo-id      : extras/7/x86_64
> Repo-name    : CentOS-7 - Extras
> Repo-status  : enabled
> Repo-revision: 1571783745
> Repo-updated : Tue Oct 22 22:35:46 2019
> Repo-pkgs    : 305
> Repo-size    : 407 M
> Repo-mirrors : http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=genclo
> Repo-baseurl : http://mirror.tocici.com/centos/7.7.1908/extras/x86_64/ (9 more)
> Repo-expire  : 21,600 second(s) (last: Wed Oct 23 19:01:28 2019)
>   Filter     : read-only:present
> Repo-filename: /etc/yum.repos.d/CentOS-Base.repo
> 
> repolist: 305
> ```
> 
> check to make sure that is the case because installation of docker-ce should go fine, i just checked myself with official documentation https://docs.docker.com/install/linux/docker-ce/centos/

@andrewhsu that did the trick. Thank you

**Comment by cloudmadhavan** [comment]
Try this Solution:-

yum install http://ftp.riken.jp/Linux/cern/centos/7/extras/x86_64/Packages/container-selinux-2.74-1.el7.noarch.rpm

If you want to install different version of container-selinux, please find the relevant package in below Linux and Install.

http://ftp.riken.jp/Linux/cern/centos/7/extras/x86_64/Packages/

**Comment by kukreti13579** [comment]
> sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm

[root@ip-10-0-0-15 ec2-user]# sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm
Last metadata expiration check: 0:03:21 ago on Fri 28 Aug 2020 07:11:56 AM UTC.
[MIRROR] container-selinux-2.95-2.el7_6.noarch.rpm: Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
[MIRROR] container-selinux-2.95-2.el7_6.noarch.rpm: Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
[MIRROR] container-selinux-2.95-2.el7_6.noarch.rpm: Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
[MIRROR] container-selinux-2.95-2.el7_6.noarch.rpm: Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
[FAILED] container-selinux-2.95-2.el7_6.noarch.rpm: Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
Status code: 404 for http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm (IP: 160.116.15.18)
[root@ip-10-0-0-15 ec2-user]#

**Comment by mrdvt92** [comment]
In CentOS 7.9, I had to enable the extras repo for yum to find the container-selinux RPM.

$ sudo yum install docker-ce --enablerepo=extras
