### ISSUE TITLE
[centos 7] In file './docker-compose.yml', the service name True must be a quoted string, i.e. 'True'.

### ISSUE THREAD

**Issue by ishowman** [docker/for-linux#827]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

I have try using container follow some docs like:
- [docker compose getting started](https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile)
- [verdaccio](https://verdaccio.org/docs/en/docker.html#using-docker-compose)

### Expected behavior
Expected running after I input `docker-compose up` command
### Actual behavior
`docker-compose up` command gets errors:
In file './docker-compose.yml', the service name True must be a quoted string, i.e. 'True'.

### Steps to reproduce the behavior
- follow the docs above to create `docker-compose.yml` file
- input `docker-compose up`
- getting the error

**Output of `docker version`:**

```
Docker version 18.09.5, build e8ff056
```

**Output of `docker info`:**

```
ERROR: In file './docker-compose.yml', the service name True must be a quoted string, i.e. 'True'.
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
system: centOS 7 ( maybe the bug is only happend to centOS)
docker-compose version 1.24.1, build 4667896b

**Comment by ishowman** [comment]
I am learning docker compose today, but as I followed the steps in docs, it didn't work as expect, but report an error in my terminal. The error message is in question title, which tells me that docker-compose.yml file has some errors. But my docker-compose.yml file is copied from those docs I mentioned in issue. So I don't know the reason the error happens. I checked the docker-compose.yml file serveral time, found nothing wrong

**Comment by andrewhsu** [comment]
@ishowman sorry, i don't see a `True` in the docs you pointed to: https://verdaccio.org/docs/en/docker.html#using-docker-compose

but from i surmise, could possibly be a yaml syntax issue.

**Comment by thaJeztah** [comment]
In YAML files, `True` is a keyword (and automatically gets parsed as a boolean. The YAML parser then generates the error, because a boolean cannot be used as key / name for the service; https://juliankniephoff.wordpress.com/2012/09/01/reserved-words-in-yaml-and-translating-booleans-in-rails/

**Comment by Edon-Du** [comment]
you can try yaml files. not yml files

**Comment by ppdouble** [comment]
say, trying `version: '3.3'` instead of `on: '3.3'`
