### ISSUE TITLE
moved from docker.io to docker-ce no countainer is coming up 

### ISSUE THREAD

**Issue by zakikhani** [docker/for-linux#828]
* [x] This is a bug report
* [ ] This is a feature request
* [X ] I searched existing issues before opening this one

### Expected behavior
container comes up after "docker run **"
and I does on newly installed server, but those what had docker.io before are not working

### Actual behavior
No container comes up, not even hello-word, they hang and I have to kill the process 
it looks it get stock on runc part

I can see a lot of older container-id in folders like 
:
/sys/kernel/slab/
/sys/fs/cgroup/systemd/docker/
/sys/fs/cgroup/perf_event/docker

(but already cleared "/var/lib/docker /etc/docker /var/run/docker.cok"

runc stays in init
Docker prune, or purge didn't remove the file, (couldn't delete them manually) 

### Steps to reproduce the behavior
I don't think it's linux ro docker version. I have servers that are working fine on new servers. just existing one has problem

**Output of `docker version`:**
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Output of `docker info`:**

Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-62-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 47.13GiB
 Name: sc0010-culper-ring
 ID: G7M4:TLJR:C7NN:XARI:JIW3:7FE7:AJAG:XVWF:XVTW:VKYE:BXPC:7GMF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.)**
runc --version
runc version 1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev

Uname:
 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrewhsu** [comment]
The recommended way to get from docker.io to docker-ce is to uninstall docker.io:
https://docs.docker.com/install/linux/docker-ce/ubuntu/#uninstall-old-versions

The packages docker.io is likely provided by ubuntu and we don't test a migration from docker.io to docker-ce, provided by docker.
