### ISSUE TITLE
Failed to start Docker Application Container Engine after enabling ipv6

### ISSUE THREAD

**Issue by ntopulos** [docker/for-linux#829]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

1. [enable ipv6 following the documentation](https://docs.docker.com/config/daemon/ipv6/) (v19.03)
2. reboot
3. get a working Docker deamon with ipv6

### Actual behavior

If I create a `/etc/docker/daemon.json`, the daemon ceases to work after reboot. Effectivelly ipv6 does not work.

Starting the daemon manually:

    systemctl start docker

Results in:

    Job for docker.service failed because the control process exited with error code.
    See "systemctl status docker.service" and "journalctl -xe" for details.
    
Output of `systemctl status docker.service`:

        ● docker.service - Docker Application Container Engine
    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
    Active: failed (Result: exit-code) since Thu 2019-10-17 22:24:46 UTC; 12min ago
        Docs: https://docs.docker.com
    Process: 1229 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
    Main PID: 1229 (code=exited, status=1/FAILURE)

To get Docker working again:

     rm /etc/docker/daemon.json
     reboot

It looks like `daemon.json` cannot exist in order for Docker to function.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-65-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.5MiB
 Name: ***
 ID: ***
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
Can you `journalctl -fu docker` to get the logs from it?

**Comment by ntopulos** [comment]
Yes, here is the output of `journalctl -fu docker`.

After `systemctl start docker`, it seems good:

    systemd[1]: Reloading Docker Application Container Engine.
    dockerd[875]: time="2019-10-17T23:42:30.336514734Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json"
    dockerd[875]: time="2019-10-17T23:42:30.340435985Z" level=info msg="Reloaded configuration: {\"mtu\":1500,\"pidfile\":\"/var/run/docker.pid\",\"data-root\":\"/var/lib/docker\",\"exec-root\":\"/var/run/docker\",\"group\":\"docker\",\"deprecated-key-path\":\"/etc/docker/key.json\",\"max-concurrent-downloads\":3,\"max-concurrent-uploads\":5,\"shutdown-timeout\":15,\"hosts\":[\"fd://\"],\"log-level\":\"info\",\"swarm-default-advertise-addr\":\"\",\"swarm-raft-heartbeat-tick\":0,\"swarm-raft-election-tick\":0,\"metrics-addr\":\"\",\"log-driver\":\"json-file\",\"ip\":\"0.0.0.0\",\"icc\":true,\"ipv6\":true,\"iptables\":true,\"ip-forward\":true,\"ip-masq\":true,\"userland-proxy\":true,\"default-address-pools\":{},\"network-control-plane-mtu\":1500,\"experimental\":false,\"containerd\":\"/run/containerd/containerd.sock\",\"builder\":{\"GC\":{}},\"containerd-namespace\":\"moby\",\"containerd-plugin-namespace\":\"plugins.moby\",\"runtimes\":{\"runc\":{\"path\":\"runc\"}},\"default-runtime\":\"runc\",\"oom-score-adjust\":-500,\"default-shm-size\":67108864,\"default-ipc-mode\":\"private\",\"resolv-conf\":\"/run/systemd/resolve/resolv.conf\"}"
    systemd[1]: Reloaded Docker Application Container Engine.

But after the `reboot`:

    dockerd[1286]: failed to start daemon: Error initializing network controller: Error creating default "bridge" network: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network
    systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
    systemd[1]: docker.service: Failed with result 'exit-code'.
    systemd[1]: Failed to start Docker Application Container Engine.

Ok, it seems like the issue comes from the "bridge" network.

**Comment by arkodg** [comment]
@ntopulos looks like
```
"fixed-cidr-v6": <>
```
is missing and for ipv6 should be a mandatory field
Raised a docs issue : https://github.com/docker/docker.github.io/issues/9676


Docker does not support IPv6 NAT and so this field is needed
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/#how-ipv6-works-on-docker has better details

We can leave this issue open to handle this error gracefully

**Comment by ntopulos** [comment]
@arkodg Thank you, after adding `fixed-cidr-v6": "2001:db8:1::/64` to `/etc/docker/daemon.json`, the daemon starts as expected.

**Comment by arkodg** [comment]
@ntopulos according to https://tools.ietf.org/html/rfc3849 `2001:db8:1::/32` is a documentation only prefix and should not be used in production

**Comment by ntopulos** [comment]
@arkodg good to know. I used `/64`, is this ok?

**docker swarm**

I don't know if I should open another issue about that, but as it is strongly related to the initial issue and the referenced documentation, I will try here:

After activating ipv6 how is swarm suppose to react?

[The documentation writes](https://docs.docker.com/config/daemon/ipv6/):

> Before you can use IPv6 in Docker containers or **swarm** services, you need to enable IPv6 support in the Docker daemon.

But when I `docker network inspect my_swarm_default` I see something like this for each container, they do not have any ipv6 address and tests reveal that they are not reachable by ipv6:

    "IPv4Address": "10.0.0.8/24",
    "IPv6Address": ""

I would like to enable ipv6 on one container, but how?

I use `docker-compose.yml` v3.*, is there a way to activate ipv6 on swarm containers?  
[The documentation says no](https://docs.docker.com/compose/compose-file/#replicas):

> Not supported in Compose File version 3

But then how to get ipv6 on a container in swarm?
