### ISSUE TITLE
Release binaries are not available for all operating systems

### ISSUE THREAD

**Issue by carolynvs** [docker/for-linux#83]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I expected to be able to download v17.03.2-ce for mac or win. However only linux has a binary for that release, and its on the new release location.

### Actual behavior
Only v17.06.0-ce is present for the other architectures.

### Steps to reproduce the behavior
1. Try to download from the old location https://get.docker.com/builds/Darwin/x86_64/docker-17.03.2-ce.tgz and it fails with 403 Forbidden.
1. Try to download from the new location https://download.docker.com/mac/static/stable/x86_64/docker-17.03.2-ce.tgz and it fails with 404 Not Found.

### Context
I am the maintainer for the [Docker Version Manager](https://howtowhale.github.io/dvm/) and am updating it to support the new download location. `dvm` needs to be able to build the right URL based on a version + os + arch, but at the moment some releases fail because the binary isn't available for all operating systems.

Since the binaries are split across multiple locations, I'm trying to work out how dvm should know where to download the release from. I was hoping it was as simple as "everything before 17.06 is in the new location", but it appears that patches for older releases, like 17.03.2, are going to be in the new location. Do I have that right?

**Comment by seemethere** [comment]
Currently 17.03.2-ce is EOL and is not supported. 

If binaries are not up for a specific platform as of today, they will not be uploaded since 17.03.2-ce has reach its EOL.

**Comment by carolynvs** [comment]
Ah okay, I didn't know about the EOL policy. Thanks that makes sense!

**Comment by thaJeztah** [comment]
Also note that the docker CLI now does version negotiation, so when talking to an older daemon, the CLI will automatically downgrade to the API version supported by that daemon; the only limitation is that it won't negotiate to daemons older than docker 1.12, but those versions are no longer supported in general

**Comment by carolynvs** [comment]
Yup! I know that dvm in theory isn't needed anymore since that feature went in. But I like it, and enough people pester me for fixes/updates that either there's a usability gap that we don't know about or it's in some other way useful. 😁
