### ISSUE TITLE
add-apt-repository failed due to "File has unexpected size" 

### ISSUE THREAD

**Issue by tiancaohz** [docker/for-linux#830]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

try to install the latest docker-ce on aws p2 instance, when "add-apt-repository", got "File has unexpected size" error. run the same command successfully on other p2 instances. 

### Expected behavior
```add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"``` succeeds adding to apt source 

### Actual behavior
```
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:4 http://repo.saltstack.com/apt/ubuntu/18.04/amd64/archive/2017.7.8 bionic InRelease
Hit:5 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease
Get:6 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Hit:7 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  InRelease
Hit:8 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [753 kB]
Hit:12 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease
Get:13 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
Hit:15 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:16 https://download.docker.com/linux/ubuntu bionic/edge amd64 Packages [8083 B]
Err:16 https://download.docker.com/linux/ubuntu bionic/edge amd64 Packages
  File has unexpected size (9509 != 8083). Mirror sync in progress? [IP: 13.32.255.191 443]
  Hashes of expected file:
   - Filesize:8083 [weak]
   - SHA512:11868c15edf472144d6723c2d39a8acf08824f9e1624300eff9e5f44eb94e175597346ed3cf90bc97cc47b70a347558fb92bbf94e57a242d4078d0c869d68bad
   - SHA256:2821e8863cb73778253a78a316d1d66dc62c6d88bebed641a17681578f2a4624
   - SHA1:a2e1194177434fd07dd0adaf2c7d24c535463e6b [weak]
   - MD5Sum:85d6f68faf213f555fe2c3c787d2eac9 [weak]
  Release file created at: Sat, 17 Aug 2019 05:05:01 +0000
Get:17 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages [7889 B]
Err:17 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages

Fetched 1158 kB in 1s (874 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/edge/binary-amd64/Packages.bz2  File has unexpected size (9509 != 8083). Mirror sync in progress? [IP: 13.32.255.191 443]
   Hashes of expected file:
    - Filesize:8083 [weak]
    - SHA512:11868c15edf472144d6723c2d39a8acf08824f9e1624300eff9e5f44eb94e175597346ed3cf90bc97cc47b70a347558fb92bbf94e57a242d4078d0c869d68bad
    - SHA256:2821e8863cb73778253a78a316d1d66dc62c6d88bebed641a17681578f2a4624
    - SHA1:a2e1194177434fd07dd0adaf2c7d24c535463e6b [weak]
    - MD5Sum:85d6f68faf213f555fe2c3c787d2eac9 [weak]
   Release file created at: Sat, 17 Aug 2019 05:05:01 +0000
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages.bz2
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Steps to reproduce the behavior
```sudo apt-get install apt-transport-https ca-certificates curl software-properties-common```
```curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -```
```sudo apt-key fingerprint 0EBFCD88```
```add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge"```

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
AWS P2 instance/ubuntu 18.04

**Comment by Jawastew** [comment]
Same issue using the https://get.docker.com script on ubuntu 19.04/disco
```sh
jawa@ubuntu ~> curl -s https://get.docker.com | bash
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
+ sudo -E sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
+ sudo -E sh -c 'curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null'
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" > /etc/apt/sources.list.d/docker.list'
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/disco/stable/binary-amd64/Packages.bz2  File has unexpected size (3466 != 2422). Mirror sync in progress? [IP: 2600:9000:214f:1c00:3:db06:4200:93a1 443]
   Hashes of expected file:
    - Filesize:2422 [weak]
    - SHA512:9196af68b35d83a33f7e8de3c0e12821cf6bfb394eb59e16c1a37397a8fafa3bd413c5a27fa25bdbab60a50b34afceaed48bcb59974ca89d38078f4990e7ba8c
    - SHA256:2d492ea4fd65492485b040b6391433e02ba68242be1cfa36c45d8797fee2fa97
    - SHA1:d692298f45420a491c0034fd967448af737b11e9 [weak]
    - MD5Sum:483c3e68f0e200a32815cf4bdd50f43b [weak]
   Release file created at: Sat, 17 Aug 2019 05:05:02 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jbarrick-mesosphere** [comment]
Also seeing this.

**Comment by bensherman** [comment]
Same with stretch:

```
Err:7 https://download.docker.com/linux/debian stretch/stable amd64 Packages
  Writing more data than expected (11116 > 9983)
  Hashes of expected file:
   - Filesize:9983 [weak]
   - SHA512:4faf843dcb2544a9135a36ecfc4b914dd4e9cdada9a5e20e4994f5dd33d2d5aacb44f237bf9bf7048bac571e8be47d04975f8d93a19dab67dbfc231b68012011
   - SHA256:db9d0a054919cfa52440f1d59ec3f4f2fd15b89661c87f35f02a24f3832a6ce6
   - SHA1:d52b8071d1449718bc483c54a5bc698a26107aa6 [weak]
   - MD5Sum:d7b024e64ef3849c725f4ce1f05bf7a7 [weak]
  Release file created at: Sat, 17 Aug 2019 05:04:49 +0000
Fetched 44.8 kB in 0s (64.9 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/stable/binary-amd64/Packages.bz2  Writing more data than expected (11116 > 9983)
   Hashes of expected file:
    - Filesize:9983 [weak]
    - SHA512:4faf843dcb2544a9135a36ecfc4b914dd4e9cdada9a5e20e4994f5dd33d2d5aacb44f237bf9bf7048bac571e8be47d04975f8d93a19dab67dbfc231b68012011
    - SHA256:db9d0a054919cfa52440f1d59ec3f4f2fd15b89661c87f35f02a24f3832a6ce6
    - SHA1:d52b8071d1449718bc483c54a5bc698a26107aa6 [weak]
    - MD5Sum:d7b024e64ef3849c725f4ce1f05bf7a7 [weak]
   Release file created at: Sat, 17 Aug 2019 05:04:49 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jcwimer** [comment]
Same issue on debian stretch 64 bit.

```
$ curl -s https://get.docker.com | bash
 sh -c 'apt-get update -qq >/dev/null'
     + sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
     + sh -c 'curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null'
     Warning: apt-key output should not be parsed (stdout is not a terminal)
     + sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable" > /etc/apt/sources.list.d/docker.list'
     + sh -c 'apt-get update -qq >/dev/null'
     E
     :
     Failed to fetch https://download.docker.com/linux/debian/dists/stretch/stable/binary-amd64/Packages.bz2  Writing more data than expected (11116 > 9983)
    
     Hashes of expected file:
    
      - Filesize:9983 [weak]
    
      - SHA512:4faf843dcb2544a9135a36ecfc4b914dd4e9cdada9a5e20e4994f5dd33d2d5aacb44f237bf9bf7048bac571e8be47d04975f8d93a19dab67dbfc231b68012011
    
      - SHA256:db9d0a054919cfa52440f1d59ec3f4f2fd15b89661c87f35f02a24f3832a6ce6
    
      - SHA1:d52b8071d1449718bc483c54a5bc698a26107aa6 [weak]
    
      - MD5Sum:d7b024e64ef3849c725f4ce1f05bf7a7 [weak]
    
    Release file created at: Sat, 17 Aug 2019 05:04:49 +0000
    E
     :
    Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by seemethere** [comment]
We are aware of the issue and are in the middle of a rollback, expect repositories to resume normal service in about ~30min

**Comment by SpikesDivZero** [comment]
@seemethere Does this rollback also cover the CentOS 7 repos?

```
failure: repodata/41e005ebd85154b765a5b043b3f94ac79eccdabd4028b54259461fb5fa48f500-primary.sqlite.bz2 from docker-ce-stable: [Errno 256] No more mirrors to try.
https://download.docker.com/linux/centos/7/x86_64/stable/repodata/41e005ebd85154b765a5b043b3f94ac79eccdabd4028b54259461fb5fa48f500-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by laundmo** [comment]
Same issue still persists here `Ubuntu 18.04.3 LTS (GNU/Linux 4.4.0-148-generic x86_64)` running on Virtual Private Server

```
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:6 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages [7,889 B]
Err:6 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
  File has unexpected size (9051 != 7889). Mirror sync in progress? [IP: 13.35.253.106 443]
  Hashes of expected file:
   - Filesize:7889 [weak]
   - SHA512:db24e63e6f882530d40047cda5c5cb43a9fd6936d518162135b59f315d9cf0e189453bddd8ee67ed0ef622012da02ecfd5f4e3419cfd116835651b37e4b6a7aa
   - SHA256:fed3e5b48da23965790e21466523ae19c1afe34f31e9005ac343e6b6a4c36d63
   - SHA1:f22380168007fac2e32b2d882a5120a288ed89e1 [weak]
   - MD5Sum:d35d55f528a96c383f4f3c1280cdd214 [weak]
  Release file created at: Sat, 17 Aug 2019 05:05:01 +0000
Fetched 64.4 kB in 1s (68.3 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages.bz2  File has unexpected size (9051 != 7889). Mirror sync in progress? [IP: 13.35.253.106 443]
   Hashes of expected file:
    - Filesize:7889 [weak]
    - SHA512:db24e63e6f882530d40047cda5c5cb43a9fd6936d518162135b59f315d9cf0e189453bddd8ee67ed0ef622012da02ecfd5f4e3419cfd116835651b37e4b6a7aa
    - SHA256:fed3e5b48da23965790e21466523ae19c1afe34f31e9005ac343e6b6a4c36d63
    - SHA1:f22380168007fac2e32b2d882a5120a288ed89e1 [weak]
    - MD5Sum:d35d55f528a96c383f4f3c1280cdd214 [weak]
   Release file created at: Sat, 17 Aug 2019 05:05:01 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by arm2arm** [comment]
debian 10 still persist....:(

**Comment by KeithIMyers** [comment]
> We are aware of the issue and are in the middle of a rollback, expect repositories to resume normal service in about ~30min

Good Morning,
I wanted to follow up to see if there has been any progress with the rollback

**Comment by robtow-wattzon** [comment]
**We are seeing sort of thing this as well:**

`TASK [system : update apt] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [52.8.240.200]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages.bz2  File has unexpected size (9051 != 7889). Mirror sync in progress? [IP: 99.84.224.79 443]\nHashes of expected file:\n - Filesize:7889 [weak]\n - SHA512:db24e63e6f882530d40047cda5c5cb43a9fd6936d518162135b59f315d9cf0e189453bddd8ee67ed0ef622012da02ecfd5f4e3419cfd116835651b37e4b6a7aa\n - SHA256:fed3e5b48da23965790e21466523ae19c1afe34f31e9005ac343e6b6a4c36d63\n - SHA1:f22380168007fac2e32b2d882a5120a288ed89e1 [weak]\n - MD5Sum:d35d55f528a96c383f4f3c1280cdd214 [weak]\nRelease file created at: Sat, 17 Aug 2019 05:05:01 +0000\n, E:Some index files failed to download. They have been ignored, or old ones used instead."}
fatal: [18.144.59.9]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages.bz2  File has unexpected size (9051 != 7889). Mirror sync in progress? [IP: 99.84.224.78 443]\nHashes of expected file:\n - Filesize:7889 [weak]\n - SHA512:db24e63e6f882530d40047cda5c5cb43a9fd6936d518162135b59f315d9cf0e189453bddd8ee67ed0ef622012da02ecfd5f4e3419cfd116835651b37e4b6a7aa\n - SHA256:fed3e5b48da23965790e21466523ae19c1afe34f31e9005ac343e6b6a4c36d63\n - SHA1:f22380168007fac2e32b2d882a5120a288ed89e1 [weak]\n - MD5Sum:d35d55f528a96c383f4f3c1280cdd214 [weak]\nRelease file created at: Sat, 17 Aug 2019 05:05:01 +0000\n, E:Some index files failed to download. They have been ignored, or old ones used instead."}`

**Comment by mfbnigel** [comment]
So as a fun side effect of this, our ci/cd build infrastructure has stopped working as we scale up and down ec2 build instances throughout the day via docker-machine.

4pm on a friday, gets you every time :)

**Comment by KeithIMyers** [comment]
@mfbnigel - I am in the same boat

**Comment by andrchalov** [comment]
Do you have a working mirrors?

**Comment by Marcuzz** [comment]
@KeithIMyers @mfbnigel Same here, we were deploying a change in our infrastructure right as this happened and now a specific microservice is out of service 🙄

**Comment by stealthiscode** [comment]
That'll teach us to not have local apt caches...  (It's on my TODO list but there are only a handful of us!  I have an excuse!  I swear!)

**Comment by eddiezab** [comment]
> That'll teach us to not have local apt caches... (It's on my TODO list but there are only a handful of us! I have an excuse! I swear!)

Even use my local cache got bitten by this. :(

**Comment by Brian-McM** [comment]
Any update? This issue is killing me right now. Is there perhaps a work around?

**Comment by massucattoj** [comment]
I`m using UBUNTU 18.04 here, and still persist the same "error"!

**Comment by Brian-McM** [comment]
@massucattoj I'm 1804 right as well, can confirm it's very much an issue still

**Comment by stealthiscode** [comment]
Debian stretch checking in successfully now.  :tada:

**Comment by odinnordico** [comment]
I had the same issue but It is working for me now, on debian 10
`add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"`

**Comment by massucattoj** [comment]
it`s the same command that I execute here.. I hope that Ubuntu will be next..

**Comment by raeisi** [comment]
Ubuntu 18.04 is still the same

Err:6 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
  File has unexpected size (9051 != 7889). Mirror sync in progress? [IP: 13.225.78.127 443]
  Hashes of expected file:
   - Filesize:7889 [weak]

**Comment by wildhart** [comment]
Ubuntu 18.04 working now!

**Comment by rmalleman** [comment]
still down for me.

**Comment by carlwain74** [comment]
Ubuntu 18.04 still down for me

**Comment by massucattoj** [comment]
same here! still down for Ubuntu 18.04

**Comment by Brian-McM** [comment]
still broken here

**Comment by rmalleman** [comment]
Mine just worked, probably hasn't hit all the mirrors yet

**Comment by wildhart** [comment]
Confirmation that Ubuntu 18.04 is working for me:
```
ssh -i "./.keys/ec2.pem" ubuntu@<redacted>.com
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1051-aws x86_64)
...
ubuntu@ip-..........:~$ sudo apt-get clean && sudo apt-get update
Hit:1 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease           <- Success!                                         
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                  
Reading package lists... Done
```
Plus docker successfully installed and website up & running.  Did the rest of you `sudo apt-get clean`?  Maybe it depends on where your mirror is.  My server is in Sydney.

**Comment by parlir** [comment]
Just tried again and it seems to be working for me.

**Comment by massucattoj** [comment]
Done! It works!!!!

**Comment by babatundebusari** [comment]
does not work still with 16.04

```
root@server-1:~# wget -qO- https://get.docker.com/ | sh
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-amd64/Packages  Writing more data than expected (72288 > 68255)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by carlwain74** [comment]
Still broken for me

> Step 10/25 : RUN curl -sSL https://get.docker.com/ | sh
>  ---> Running in 4e90f025a360
> # Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
> + sh -c apt-get update -qq >/dev/null
> + sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
> debconf: delaying package configuration, since apt-utils is not installed
> + sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> + sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
> + sh -c apt-get update -qq >/dev/null
> E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages.gz  File has unexpected size (9542 != 8136). Mirror sync in progress? [IP: 13.32.255.153 443]
>    Hashes of expected file:
>     - Filesize:8136 [weak]
>     - SHA512:cae0db957b3d05634c1efb449ca7dbc9b6104ba31da7b62210270d2d484e26ca6a360305775c8a49a45b7c9713ed981ac5c6f7f908f37c88cc6f03fd8e5c81d3
>     - SHA256:e7794912e27bf876f2cee72cbbd58bdf13536a7acc65dceaa0be54fced7d2840
>     - SHA1:4f41aa33c4e9cb200e0ae968ad5703b743ef007b [weak]
>     - MD5Sum:183f23ccced88dc77c55d44259d5ff3d [weak]
>    Release file created at: Sat, 17 Aug 2019 05:05:01 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command '/bin/sh -c curl -sSL https://get.docker.com/ | sh' returned a non-zero code: 100

**Comment by Cyb3rWard0g** [comment]
It works for Ubuntu Bionic 18 

# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
dpkg-preconfigure: unable to re-open stdin: No such file or directory
+ sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by carlwain74** [comment]
Ubuntu 18.04 is working for me using official docker script 👍

**Comment by babatundebusari** [comment]
> Ubuntu 18.04 is working for me using official docker script 👍

can you paste the official docker script you referring to?

**Comment by artificialexit** [comment]
> > Ubuntu 18.04 is working for me using official docker script +1
> 
> can you paste the link to the official docker script you referring to?
@babatundebusari 
https://github.com/docker/docker-install#usage

**Comment by babatundebusari** [comment]
> > > Ubuntu 18.04 is working for me using official docker script +1
> > 
> > 
> > can you paste the link to the official docker script you referring to?
> 
> @babatundebusari
> https://github.com/docker/docker-install#usage

cool thats what i thought...seems working for 16.04 now as well

```
root@server-1:~# wget -qO- https://get.docker.com/ | sh
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2
 Built:             Tue Oct  8 00:59:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2
  Built:            Tue Oct  8 00:58:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
```

what did you guys do? anyways thanks for the quick fix

**Comment by dbeetz** [comment]
Works for me now on Ubuntu 16.04.6

**Comment by carlwain74** [comment]
> > Ubuntu 18.04 is working for me using official docker script 👍
> 
> can you paste the link to the official docker script you referring to?

curl -sSL https://get.docker.com/ | sh

**Comment by seemethere** [comment]
This issue can be closed, repositories have been restored.

**Comment by scottstensland** [comment]
I wonder if this outage impacted folks who installed onto ubuntu using the debian package 

    docker-io

instead of the golang approach package  `docker-ce` which I know was impacted ... see details https://askubuntu.com/questions/1182820/why-is-docker-not-in-official-ubuntu-repos

**Comment by leandroramos** [comment]
Same error in Debian 12:

```
Err:8 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 18.245.96.57 443]
  Hashes of expected file:
   - Filesize:12572 [weak]
   - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
   - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
   - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
   - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
  Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
```

**Comment by likethecolor** [comment]
Having a similar issue trying to run through gitlab's ci/cd pipeline.  Was fine yesterday, Aug 24, 2023 @ 16:23 CDT.  I came in this morning and reran that same job and this error started to appear (no changes to the deployment scripts).
```
...
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: Failed to fetch https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages.bz2  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 3.163.24.100 443]
   Hashes of expected file:
    - Filesize:12572 [weak]
    - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
    - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
    - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
    - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
   Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by nickgrajecki** [comment]
Same issue here

```Err:5 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 216.137.44.20 443]
  Hashes of expected file:
   - Filesize:12572 [weak]
   - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
   - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
   - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
   - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
  Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
Fetched 43.3 kB in 0s (107 kB/s)
Reading package lists... Done
E: Failed to fetch https://download.docker.com/linux/debian/dists/bookworm/stable/binary-amd64/Packages.bz2  File has unexpected size (11933 != 12572). Mirror sync in progress? [IP: 216.137.44.20 443]
   Hashes of expected file:
    - Filesize:12572 [weak]
    - SHA512:1ad46ae4661e094a3fbc4a185aca32140daf869eb5e46ed3b7d29c1dd3c231b9d695bb92d012773977ff302dfa177db422bd65cd9f27c625b5bbb5f68a9b0b7e
    - SHA256:ee0bedebe6acb9402c045d29d3773107aa40e7786fed18b022b651ae472491af
    - SHA1:af790455ef83c7ba6d9cf7420def8a029b7467db [weak]
    - MD5Sum:1b1679de2f388310db9ca9ca973f7e56 [weak]
   Release file created at: Thu, 24 Aug 2023 14:10:41 +0000
```

**Comment by XavierGeerinck** [comment]
+1 started appearing ±30mins ago here

**Comment by MrGeneration** [comment]
This is a closed issue.
There's a new issue here: https://github.com/docker/for-linux/issues/1475

If you found this by google, don't bump this one but subscribe the new one. :)
