### ISSUE TITLE
How to rm docker successfully, Error response from daemon: container  "driver "overlay" failed to remove root filesystem"

### ISSUE THREAD

**Issue by TidyHuang** [docker/for-linux#839]
Could someone help how to delete the docker container, thanks！

* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
1. stop and rm container successfully

### Actual behavior
1. Error response from daemon: container a0b16a2972e475d851c09e9d4ff39dcab170039bedc3b0cb1d2de81005cdf4d5: driver "overlay" failed to remove root filesystem: remove /var/lib/docker/overlay/d4690a38a8a3087d8a050cba521a8fbdd55da0841cfbfb442cd1938846d8f689/upper/var/log/tsar.data: operation not permitted

2.  Docker status in ‘Removal In Progress'

### Steps to reproduce the behavior
1. stop container and the container in Exit status
2. rm  container and return error
3. reboot and then rm can't solve the problem

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**
ontainers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Kernel Version: 3.16.56-OpenNetworkLinux
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.49GiB
Name: xxxx
ID: 3GEI:OISF:CSAX:5UQS:GAHU:LULV:V4CW:NY36:RNAW:I6OV:GU4J:BV3F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by andrewhsu** [comment]
We no longer support debian jessie operating system (looks like yours is a derivative of that because of the old kernel version).

Also, the docker-ce 18.06.x version is no longer supported.

If possible, please have a go with latest version of docker avail, docker-ce 19.03.x, and a newer debian version.
