### ISSUE TITLE
cannot start docker-ce service on ubuntu with error ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by sonersivri** [docker/for-linux#84]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker service start

### Actual behavior
docker service cannot start
 systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-08-22 16:36:27 +03; 1s ago
     Docs: https://docs.docker.com
  Process: 2295 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 2295 (code=exited, status=1/FAILURE)

Aug 22 16:36:27 devops systemd[1]: Failed to start Docker Application Container Engine.
Aug 22 16:36:27 devops systemd[1]: docker.service: Unit entered failed state.
Aug 22 16:36:27 devops systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 22 16:36:27 devops systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 22 16:36:27 devops systemd[1]: Stopped Docker Application Container Engine.
Aug 22 16:36:27 devops systemd[1]: docker.service: Start request repeated too quickly.
Aug 22 16:36:27 devops systemd[1]: Failed to start Docker Application Container Engine

### Steps to reproduce the behavior

**Output of `docker version`:**
docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```
(paste your output here)
```

**Output of `docker info`:**
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
docker0 does not exists
physical 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

ifconfig
eno1      Link encap:Ethernet  HWaddr c8:60:00:c1:4b:2a  
          inet addr:192.168.1.251  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ca60:ff:fec1:4b2a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9424 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1048 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1678940 (1.6 MB)  TX bytes:135916 (135.9 KB)
          Interrupt:20 Memory:f7300000-f7320000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:11840 (11.8 KB)  TX bytes:11840 (11.8 KB)

**Comment by clement-michelet** [comment]
I run into the same issue after upgrading from legacy repository to new docker-ce repository following official install documentation.
Current workaround is to downgrade to `17.03.2~ce-0~debian-stretch` version.

---

`journalctl -xe -u docker.service` output :

```
-- Unit docker.service has begun starting up.
Aug 22 19:13:54 External-Cube docker[11546]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 19:13:54 External-Cube systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is failed.
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Unit entered failed state.
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 22 19:13:54 External-Cube systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has finished shutting down.
Aug 22 19:13:54 External-Cube systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has begun starting up.
Aug 22 19:13:54 External-Cube docker[11586]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 19:13:54 External-Cube systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is failed.
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Unit entered failed state.
Aug 22 19:13:54 External-Cube systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 22 19:13:55 External-Cube systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 22 19:13:55 External-Cube systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has finished shutting down.
Aug 22 19:13:55 External-Cube systemd[1]: docker.service: Start request repeated too quickly.
Aug 22 19:13:55 External-Cube systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit docker.service has failed.
--
-- The result is failed.
Aug 22 19:13:55 External-Cube systemd[1]: docker.service: Unit entered failed state.
Aug 22 19:13:55 External-Cube systemd[1]: docker.service: Failed with result 'exit-code'.
```

`lsb-release -a` output:

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        8
Codename:       stretch
```

**Comment by clement-michelet** [comment]
This is still not resolved with `docker-ce-17.06.2~ce-0~debian-stretch`.

**Comment by cpuguy83** [comment]
@clement-michelet 
This is not an issue with the docker-ce package but rather a systemd unit override file supplied by the user... or potentially an older version of docker-machine.

In the case of docker-machine I believe it would be in `/etc/systemd/system/docker.service.d/10-machine.conf`.

**Comment by cpuguy83** [comment]
@sonersivri We need more details to troubleshoot the issue.
Can you provide the output of `journalctl -fu docker` after a failed start attempt?

**Comment by sonersivri** [comment]
I cannot wait for response I remove docker-ce and reinstall it and continue
working.
I cannot send you journalctl -fu docker response

Soner Sivri

2017-09-21 17:30 GMT+03:00 Brian Goff <notifications@github.com>:

**Comment by cpuguy83** [comment]
I will close this for now. If you have the issue again, feel free to ping here or open a new issue.
Thanks!

**Comment by Dayjo** [comment]
@cpuguy83 My problem was the old docker-machine config file, I edited this to change it to use dockerd and it seems to work ok. Is it worth keeping this file or just removing it?

**Comment by sylvainar** [comment]
I still have this issue, on a fresh install of Ubuntu 16.04 server. 
```
mars 16 08:20:01 finch systemd[1]: docker.service: Start request repeated too quickly.
mars 16 08:20:01 finch systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: L'unité (unit) docker.service a échoué
```

**Comment by hackstep** [comment]
I have resolved it by removing "-H fd://" in /etc/systemd/system/multi-user.target.wants/docker.service

**Comment by sylvainar** [comment]
I have resolved it by formatting everything and going back to Debian… Thanks for the tip anyway.

**Comment by danieldeveloper001** [comment]
A solution for those facing this issue on Fedora Server 27 when trying to allow connection from remote docker clients to server side docker daemon.

Remove old docker installations and configure the official dnf repository for docker...

```
$ sudo dnf remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine
$ sudo dnf -y install dnf-plugins-core
$ sudo dnf config-manager --add-repo \
                  https://download.docker.com/linux/fedora/docker-ce.repo
```

... install docker-ce ...

```
$ sudo dnf install docker-ce
```

... edit the docker service daemon configuration ...

```
$ sudo systemctl edit docker.service
```

... include the following lines to allow connecting from the remote docker client ...

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd fd:// -H tcp://0.0.0.0:2375
```

... restart systemctl daemon, enable and start docker ...

```
$ sudo systemctl daemon-reload
$ sudo systemctl enable docker
$ sudo systemctl start docker
```

... and it should be working now. Succesfully tested in my environment, the trick is removing the *-H fd://* that is included in official documentation and using the dnf package from official docker repository. My environment settings, below.

- Windows 10 Professional
  - Windows Subsystem For Linux
    - Docker Client
  - Hyper-V
    - Fedora Server 27
      - Docker Daemon

[Source 1 - Docker on Fedora Docs](https://docs.docker.com/install/linux/docker-ce/fedora/#install-docker-ce-1)
[Source 2 - Post Install Setps for Linux Docs](https://docs.docker.com/install/linux/linux-postinstall/#configure-where-the-docker-daemon-listens-for-connections)

**Comment by danieldeveloper001** [comment]
Don't forget, on your client to set the DOCKER_HOST environment variable...

```
$ export DOCKER_HOST=192.168.0.200:2357
```

... replacing the ip and port with your own, of course :)

**Comment by karlwilbur** [comment]
I have the same problem. Spent hours trying different things to no avail. Turned out it was because my VPN (ExpressVPN) was running. I disconnected and everything was fine. I wish that there was more specific debugging information from the error message during installation.

I found that it was a networking issue because I ran:
```
sudo dockerd -D
```

**Comment by brentkearney** [comment]
With Docker version 18.03.1-ce, build 9ee9f40 on a fresh install on Ubuntu 16.04 Server with all packages up-to-date (Linux lyceum 2.6.32-042stab124.2 #1 SMP Fri Sep 1 20:42:18 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux), I get:
``
#  journalctl -fu docker
-- Logs begin at Sat 2018-04-28 18:55:31 EDT. --
Apr 30 10:23:26 lyceum dockerd[4568]: time="2018-04-30T10:23:26-04:00" level=info msg="containerd successfully booted in 0.007882s" module=containerd
Apr 30 10:23:26 lyceum dockerd[4568]: time="2018-04-30T10:23:26.653351386-04:00" level=fatal msg="Your Linux kernel version 2.6.32-042stab124.2 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer."
Apr 30 10:23:26 lyceum systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 30 10:23:26 lyceum systemd[1]: Failed to start Docker Application Container Engine.
Apr 30 10:23:26 lyceum systemd[1]: docker.service: Unit entered failed state.
Apr 30 10:23:26 lyceum systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 30 10:23:26 lyceum systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Apr 30 10:23:26 lyceum systemd[1]: Stopped Docker Application Container Engine.
Apr 30 10:23:26 lyceum systemd[1]: docker.service: Start request repeated too quickly.
Apr 30 10:23:26 lyceum systemd[1]: Failed to start Docker Application Container Engine.
``

**Comment by cpuguy83** [comment]
Docker is not supported on such an old kernel. 3.10 is the oldest kernel
supported.

**Comment by sheershoff** [comment]
Running `sudo dockerd -D` helped me to find out it was an error with IPv6 that I turned on just out of curiosity in `/etc/docker/daemon.json`. I've reedited it to be an empty JSON (since ipv6 was the only setting there) and upgrade worked like a charm.

**Comment by sparr** [comment]
I encountered this same error while connected to a VPN. Disconnecting allowed dockerd to start up, and docker-ce package installation to finish.

**Comment by nurzhan-izbassov** [comment]
> I encountered this same error while connected to a VPN. Disconnecting allowed dockerd to start up, and docker-ce package installation to finish.

Thanks. It helped me to resolve this problem.

**Comment by didnthodl** [comment]
> I had the same problem. I have Docker running on my other laptop and my desktop just fine, but it won't install on this laptop. I spent hours trying different things to no avail. Turned out it was because my VPN (ExpressVPN) was running. I disconnected and everything was fine. I wish that there were more specific debugging information from the error message during installation.
> 
> I found that it was a networking issue because I ran:
> 
> ```
> sudo dockerd -D
> ```
> 
> (I'm running Ubuntu 16.04 on all of my machines)

Thanks... I also had a VPN active and that was the reason. Why on Earth would that be a problem?!

**Comment by karlwilbur** [comment]
@didnthodl, 

>  Why on Earth would that be a problem?!

It really depends on the VPN client and its configuration. ExpressVPN, for example, creates firewall rules (`iptables`) that prevent some Docker network creation and communication. This is to ensure that there is no malicious network leakage. Once Docker is installed, and any of its network created, you should be able to build, start, and stop containers without issues with having your VPN up. Adding new networks (like in a `docker-compose.yml` file) will need to have the VPN off.

There may be a better workaround that doesn't require bounding the VPN client each time you add a new project with its own network. Any such solution will likely require modifying the VPN clinet's default `iptables` rules and would likely need to be run every time the VPN client starts, which isn't much more "hands off" that just bouncing the client for new projects.

I feel your frustration.

**Comment by cwilby** [comment]
Ran into this issue, the problem for me was a badly formatted `/etc/docker/daemon.json`.  Fixing that let me run the service again.

**Comment by ahmadsb101** [comment]
@cwilby Yes you are right. but what is the correct format for daemon.json
I did exactly as docker website said but i ran to this issue and your recommendation came as a miracle. 
thanks.

**Comment by cwilby** [comment]
@ahmadsb101 You'll find full examples on https://docs.docker.com/engine/reference/commandline/dockerd/, but you shouldn't need most of the available fields.  Generally speaking though, make sure the document itself is valid JSON with something like jsonlint.com.

**Comment by sanderjo** [comment]
> Running `sudo dockerd -D` helped me to find out it was an error with IPv6 that I turned on just out of curiosity in `/etc/docker/daemon.json`. I've reedited it to be an empty JSON (since ipv6 was the only setting there) and upgrade worked like a charm.

Ah, that was it! The `sudo dockerd -D` revealed:

`failed to start daemon: Error initializing network controller: Error creating default "bridge" network: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network
`
IPv6 the cause of failing docker ... how annoying & silly

**Comment by drf5n** [comment]
Trying docker from the command line in Daemon mode with `docker -D` gives much better debugging feedback and suggestions than what you get out of  `systemctl start docker` or `systemctl status docker`.

My root error was 

```
...
INFO[2026-05-07T11:47:08.540521779-04:00] Daemon shutdown complete                      error="error initializing buildkit: error creating buildkit instance: legacy (v1) cache metadata found at \"/var/lib/docker/buildkit/metadata.db\" and needs to be removed or migrated; downgrade BuildKit to v0.27.1 to perform automatic migration or remove the existing cache"
error initializing buildkit: error creating buildkit instance: legacy (v1) cache metadata found at "/var/lib/docker/buildkit/metadata.db" and needs to be removed or migrated; downgrade BuildKit to v0.27.1 to perform automatic migration or remove the existing cache
...
```

Which I corrected by deleting `/var/lib/docker/buildkit/metadata.db`
