### ISSUE TITLE
Add entrypoint override in docker exec

### ISSUE THREAD

**Issue by bauerjj** [docker/for-linux#843]
* [ ] This is a bug report
* [x] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Currently, there is no possibility to enter a stopped container or running container and overriding the entrypoint using `docker exec xxxx --entrypoint=''` like you can do with `docker run`. This would be useful to have for example if the container first builds a program upon entry in `build.sh` as outlined in the Dockerfile, but then allows the user to enter it again without running the `build.sh` again. 

I have tried emulating this by waiting for user input in the `build.sh` script that would allow me to cancel the build from starting, however it doesn't seem like it recognizes the keyboard from `stdin` even when using `docker exec -i myimage xxxxx`.

**Comment by thaJeztah** [comment]
Could you show actual steps where you're running into an issue? I don't think `docker exec` inherits the container's entry point, so there should be no entry point if you run `docker exec`

**Comment by bauerjj** [comment]
@thaJeztah , you are correct, there is no `docker exec` entrypoint. I was suggesting this as a feature request so that it would be possible to start already stopped containers without incurring the entrypoint.

**Comment by sblanton** [comment]
I'm trying to do this as well and would love this feature. Seems to be a glaring omission. How can I debug a running container? Or, am I fundamentally misunderstanding how docker works?

**Comment by thaJeztah** [comment]
Could you elaborate on what you're trying to do? `docker exec` allows you to run a second process in the same container, for example;

```bash
# a container that's running
docker run -d --name mycontainer -p 8080:80 nginx:alpine

# start a second process in the container (e.g. a shell), and view processes inside the container
docker exec -it mycontainer sh
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
   32 nginx     0:00 nginx: worker process
   33 nginx     0:00 nginx: worker process
   34 nginx     0:00 nginx: worker process
   35 nginx     0:00 nginx: worker process
   36 root      0:00 sh
   42 root      0:00 ps aux
```

Alternatively, attach to the container / the container's main process (which was started with `-d` / `--detach`, so running in the background);

```bash
docker attach mycontainer
172.17.0.1 - - [23/Mar/2022:16:37:25 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.79.1" "-"
```

**Comment by thaJeztah** [comment]
and if your container does not have a shell (which can be if it's started from a minimal image), you can also start another container that joins the first container's namespace(s); this allows you to run debugging tools within the namespace (e.g. wireshark); here's an alpine container that joins the existing containers' pid and network namespaces, and shows the running processes in the namespace (which shows the `nginx` process of the container that it joined and the `sh` process of the alpine container);


```bash
docker run -it --rm --pid=container:mycontainer --network=container:mycontainer alpine sh
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
   33 101       0:00 nginx: worker process
   34 101       0:00 nginx: worker process
   35 101       0:00 nginx: worker process
   36 101       0:00 nginx: worker process
   37 root      0:00 sh
   44 root      0:00 ps aux
```

**Comment by thaJeztah** [comment]
looks like this went stale
