### ISSUE TITLE
Ubuntu become too slow after i upgraded from 19.04 to 19.10

### ISSUE THREAD

**Issue by dracesh** [docker/for-linux#847]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment]
Do you have more details? Please fill out all the bug report information.
"Ubuntu became slow" doesn't even look like a bug report for docker.

Closing for now but feel free to ping back and we can open it back up.

Thanks!
