### ISSUE TITLE
bash: __docker_daemon_is_experimental: command not found

### ISSUE THREAD

**Issue by RuioWolf** [docker/for-linux#854]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
using tab to auto complete commands

### Actual behavior
```
[root@localhost ~]# docker service bash: __docker_daemon_is_experimental: command not found

create   inspect  list     ls       ps       remove   rm       scale    update   
```

### Steps to reproduce the behavior
click tab when try to complete it like `docker service` and click TAB

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: z32d9y8v3xpvinelskqpkz0ds
  Is Manager: true
  ClusterID: jrrpt1w20ztfe1fgk3zg2kaq5
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 3
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.138.128
  Manager Addresses:
   192.168.138.128:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.8-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: localhost.localdomain
 ID: K6EV:EFPJ:6YQM:PGMD:HIL7:W4A3:PVEU:2MAU:5V25:NAB3:WHV5:ECFA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

in VMware 15.5

CentOS Linux release 7.7.1908 (Core) - 5.3.8-1.el7.elrepo.x86_64

**Comment by albers** [comment]
The completions for `docker service` should be:

    create    inspect   logs      ls        ps        rm        rollback  scale     update

Your output 

    [root@localhost ~]# docker service bash: __docker_daemon_is_experimental: command not found
    create   inspect  list     ls       ps       remove   rm       scale    update 

contains the command aliases `list` and `remove` which are definitely not suggested. Also, `logs` and `rollback` are missing.

You seem to be using a very outdated version of the completion script.

I assume you have two completion scripts on your computer which get both sourced in and interfere with each other. See https://github.com/moby/moby/issues/30867#issuecomment-279654054 for a similar issue on Debian boxes.

The completion file should be located in */usr/share/bash-completion/completions/docker*, and there should be no file in */etc/bash_completion.d/docker*.

**Comment by thaJeztah** [comment]
Thanks for looking @albers - from the description, looks like this is not a bug, so I'll go ahead and close this issue, but feel free to continue the conversation

**Comment by RuioWolf** [comment]
Thank you so much, I just received notification. My laptop which has this problem is broken and for now I can't reproduce it on my PC. Will check it out after I get it back.
