### ISSUE TITLE
starting container process caused "exec: \"echo hello world\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by neethumoltp** [docker/for-linux#871]
I'm running the docker file with below simple lines and getting this error. Can someone help?
FROM alpine

CMD ["echo hello world"]

output of docker build :
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
89d9c30c1d48: Pull complete 
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
 ---> 965ea09ff2eb
Step 2/2 : CMD ["echo hello world"]
 ---> Running in 7733bde62508
Removing intermediate container 7733bde62508
 ---> d629e1f9f228
Successfully built d629e1f9f228

ERROR:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"echo hello world\": executable file not found in $PATH": unknown

**Comment by cpuguy83** [comment]
Remove the json array and just have an unquoted string.

Docker is trying to execute a command called "echo hello world" instead of a command called "echo" with arguments of "hello world".
