### ISSUE TITLE
Docs are invalid: No "deb" package

### ISSUE THREAD

**Issue by akopchinskiy** [docker/for-linux#874]
Documentation: 
![image](https://i.imgur.com/XYL8EWg.png)

Actual repository:
![image](https://i.imgur.com/rE5JcoU.png)

Where is **.deb** file here?

**Comment by thaJeztah** [comment]
The structure is a bit confusing, but the debs are in the `pools` subdirectory (as described above), for example, for Ubuntu "bionic" on amd64; https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

**Comment by thaJeztah** [comment]
closing this ticket as it appears you were looking in the wrong path, but feel free to continue the conversation
