### ISSUE TITLE
docker-ce 19.03.5 proxy variables not working for runtime containers

### ISSUE THREAD

**Issue by adespain** [docker/for-linux#878]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior 

I would expect to see traffic trying to hit my proxy server when docker grabs images from docker hub.

### Actual behavior
I see traffic trying to go directly to docker hub and is not using the proxy specified in the environment variable

### Steps to reproduce the behavior
set the proxy variable and make sure it is set with:
`echo $HTTP_PROXY`
Try to run a container with golang by specifying the HTTP_PROXY variable
`docker run -e HTTP_PROXY golang:1.9`

I have tried setting the systemd config as well by creating a file here:
/etc/systemd/system/docker.service.d/http-proxy.conf
then ran `systemctl daemon-reload` and then `service docker restart`

**Output of `docker version`:**

```
Docker version 19.03.5, build 633a0ea838
```

**Output of `docker info`:**

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-170-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 992.1MiB
 Name: cmsp-sand1
 ID: BPFR:QNXD:WVD5:5TXT:AXDQ:YNXT:APCN:U4XS:7OTZ:73NP:JW34:KNSM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
This is running on nested vm.  Hyper-V vm running linux, linux is running a virtualbox vagrant vm

**Comment by cpuguy83** [comment]
Do you have more specifics as to the daemon config?
I also see you are on 16.04. As I recall, 16.04 uses upstart, not systemd.

**Comment by adespain** [comment]
Yes 16.04 has systemd, 14.04 was upstart i believe, if it didn't I'd probably get an error when I try a systemctl daemon-reload right?...Here is the config for the file:

/etc/systemd/system/docker.service.d/http-proxy.conf
```
[Service]
Environment="HTTP_PROXY=http://user:password@10.10.10.10:8080"
Environment="HTTPS_PROXY=https://user:password@10.10.10.10:8080"
```

**Comment by adespain** [comment]
updated the environment to: This is running on nested vm.  Hyper-V vm running linux, linux is running a virtualbox vagrant vm

**Comment by adespain** [comment]
0


I removed the HTTPS_PROXY setting from the systemd http-proxy.conf file and that fixed it, apparently my proxy doesn't support tls connections so I didn't need both HTTP_PROXY and HTTPS_PROXY
