### ISSUE TITLE
using same image, Docker version 19.03.4 can communicate supervisord.sock but not under 17.03.2-ce 

### ISSUE THREAD

**Issue by lj99boy** [docker/for-linux#884]
* [x] This is a bug report

### Expected behavior
# supervisorctl status
show supervisord detail

### Actual behavior
Docker version 19.03.4:
# supervisord --version
3.2.4
# supervisorctl status
cron                             RUNNING   pid 10, uptime 0:00:29
nginx                            RUNNING   pid 9, uptime 0:00:29
php-fpm                          RUNNING   pid 8, uptime 0:00:29

Docker version 17.03.2-ce:
# supervisord --version
3.2.4
# supervisorctl status
unix:///run/supervisord.sock refused connection

but if i modify the /etc/supervisord.conf
from using unix_http_server to inet_http_server  both above can work well

### Steps to reproduce the behavior

dockerfile:
FROM php:7.1.12-fpm-alpine
RUN apk add supervisor

**Output of `docker version`:**

```
Version:          19.03.4
API version:      1.40 (minimum version 1.12)

Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
```

**Output of `docker info`:**

```
17.03.2-ce:

Containers: 92
 Running: 87
 Paused: 0
 Stopped: 5
Images: 99
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.71 GiB
Name: PsqtestA33-210
ID: E6EH:UXS2:7OKI:UCYW:KADW:LGXW:3FHZ:C5JG:N5WY:OOBN:ZKHO:CPWI

-------------
19.03.4:

Debug Mode: false

Server:
 Containers: 108
  Running: 101
  Paused: 0
  Stopped: 7
 Images: 90
 Server Version: 19.03.4
 Storage Driver: devicemapper
  Pool Name: vg_docker-thinpool
  Pool Blocksize: 524.3kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data Space Used: 21.93GB
  Data Space Total: 429.5GB
  Data Space Available: 407.6GB
  Metadata Space Used: 10.14MB
  Metadata Space Total: 4.295GB
  Metadata Space Available: 4.285GB
  Thin Pool Minimum Free Space: 42.95GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.158-RHEL7 (2019-05-13)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-327.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 40
 Total Memory: 94.15GiB
 Name: ezmall-test-k8s
 ID: 673U:NYSN:C2KB:J2UF:ZSVJ:HSDX:BZWL:RJQO:HSTS:6W5G:W46A:CG5S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://registry.docker-cn.com/
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Not sure what the difference in behaviour would be between 19.03 and 17.03 for this particular case, but a _lot_ has changed between those versions (including a full rewrite / replacement of the runtime).

Docker 17.03 is really, really old, and reached EOL in June 2017; it hasn't received updates since, and has known, unpatched vulnerabilities, some of which as _critical_, so I'd recommend updating to a current version (both docker and your operating system as it looks like the version of CentOS you're running is also EOL)

I'll close this ticket because of the above, but feel free to comment after  I closed

**Comment by lj99boy** [comment]
@thaJeztah i see， thanks for the reply。basically what i mentioned above simply like 17.03 using supervisor AF_UNIX instead of AF_INET would go wrong。i will make the update soonly :)
