### ISSUE TITLE
Docker rootless not working

### ISSUE THREAD

**Issue by JesterOrNot** [docker/for-linux#885]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker is installed and ready to go

### Steps to reproduce the behavior

after starting docker rootless it asks for root
![image](https://user-images.githubusercontent.com/50386709/71527859-cef1fd80-28a2-11ea-9f8e-58a8c17e7e33.png)

run my environment in browser [here](https://gitpod.io/#https://github.com/JesterOrNot/Gitpod-Docker/blob/master/.gitpod.Dockerfile)

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           master-dockerproject-2019-12-11
 API version:       1.41
 Go version:        go1.12.12
 Git commit:        08eaead2
 Built:             Wed Dec 11 23:52:32 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///tmp/docker-33333/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///tmp/docker-33333/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by AkihiroSuda** [comment]
Better to ask gitpod.

Probably they need to tweak sysctl stuff or use privileged containers if they use containers.
https://docs.docker.com/engine/security/rootless/

**Comment by JesterOrNot** [comment]
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted

**Comment by thaJeztah** [comment]
closing this one in favour of https://github.com/gitpod-io/gitpod/issues/52
