### ISSUE TITLE
Typo in ErrorLog components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go

### ISSUE THREAD

**Issue by alainvanhoof** [docker/for-linux#89]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

msg="enabling default vlan on bridge br0 failed open /sys/class/net/br0/bridge/default_pvid: permission denied"

### Actual behavior

msg="endbling default vlan on bridge br0 failed open /sys/class/net/br0/bridge/default_pvid: permission denied"

### Steps to reproduce the behavior

git clone docker-ce.git
cd docker-ce
grep -r endbling *

components/engine/vendor/github.com/docker/libnetwork/drivers/overlay/ov_network.go:		logrus.Errorf("endbling default vlan on bridge %s failed %v", brName, err)

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by rosebude** [comment]
The same one, just after migrate to docker 17.09.0-ce
docker swarm init show me:
```
 level=error msg="endbling default vlan on bridge br0 failed open /sys/class/net/br0/bridge/default_pvid:             permission denied"
dockerd[6316]: time="2017-10-05T20:59:53.594778574+02:00" level=error msg="reexec to set bridge default vlan failed exit status 1"
```

No way to manager/worker to join the leader...

**Comment by thaJeztah** [comment]
Thanks for reporting!

That code is vendored from the libnetwork repository; I opened a pull request to fix the typo: https://github.com/docker/libnetwork/pull/1973

After that pull request is merged, it will be resolved in Docker the next time the libnetwork package is updated.

I'm closing the issue here for housekeeping, but feel free to continue the conversation 👍

**Comment by yuklia** [comment]
The same one.
Docker version: **18.04.0-ce**

`docker stack deploy --with-registry-auth --compose-file docker-compose.yml`

```
level=error msg="reexec to set bridge default vlan failed exit status 1"

level=error msg="enabling default vlan on bridge br0 failed open /sys/class/net/br0/bridge/default_pvid: permission denied"
```

**Comment by marcospaulosss** [comment]
Alguma solução sobre esse problema?
