### ISSUE TITLE
Cant install docker ubuntu 19.10 x86_64

### ISSUE THREAD

**Issue by toniejestgorlik1337** [docker/for-linux#892]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

im using tutorial from https://docs.docker.com/install/linux/docker-ce/ubuntu/
i dont know what is wrong but yours repository dont work for me 

$ sudo apt-get update
0% [Pracuje]
Stary:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease
Stary:2 http://security.ubuntu.com/ubuntu eoan-security InRelease
Stary:3 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease
Ign.:4 https://download.docker.com/linux/ubuntu eoan InRelease
Stary:5 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Błąd:6 https://download.docker.com/linux/ubuntu eoan Release
  404  Not Found [IP: 54.230.229.4 443]
Czytanie list pakietów... Gotowe
E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by MycroftHolmes1989** [comment]
Issue is already open: https://github.com/docker/for-linux/issues/832
