### ISSUE TITLE
tls handshake error 

### ISSUE THREAD

**Issue by sumathi1010** [docker/for-linux#894]
Throws TLS handshake error , i'm trying to pull snyk/broker . 
is it certificate error ? if YES what certificate i should be adding , or is it corporate proxy blocking it 
-->docker pull snyk/broker

_ERROR:_
**Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: remote error: tls: handshake failure**

**Comment by thaJeztah** [comment]
The `snyk/broker` image does not have a `:latest` tag, so you need to specify the tag to use (e.g. `snyk/broker:github-com`) see the documentation for that image on Docker Hub; https://hub.docker.com/r/snyk/broker
