### ISSUE TITLE
ADD failed: stat /var/lib/docker/tmp/docker-builderXXXXXX: no such file or directory

### ISSUE THREAD

**Issue by mauri870** [docker/for-linux#90]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
COPY/ADD should work with absolute paths

### Actual behavior
An error occur when trying to ADD/COPY with an absolute path

```
Sending build context to Docker daemon  90.62kB
Step 1/2 : FROM alpine:latest
 ---> 02674b9cb179
Step 2/2 : ADD /tmp /tmp
ADD failed: stat /var/lib/docker/tmp/docker-builder310665597/tmp: no such file or directory
```

### Steps to reproduce the behavior
```
FROM alpine:latest
ADD /tmp /tmp # COPY fails too
```

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Wed Jul 26 18:03:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Wed Jul 26 20:03:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 162
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.7-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: mauri870-pc
ID: 7CHC:HTHK:NHE6:EF7M:F4SU:2GNG:SGX4:XGFG:FSKF:26LD:O5YX:H5GN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Physical. Seems to be related with https://github.com/docker/for-mac/issues/1922

**Comment by dnephin** [comment]
Paths in a `Dockerfile` are always relative to the the context directory. The context directory is the positional argument passed to `docker build` (often `.`).

If there is no `./tmp` in the context directory then this is the expected behaviour.

**Comment by mauri870** [comment]
@dnephin This behavior has been introduced recently? Because I remember using absolute paths in my Dockerfiles without problems 😕

**Comment by dnephin** [comment]
I believe it has always been this way.

**Comment by mauri870** [comment]
Thanks for your help @dnephin

**Comment by janmchan** [comment]
![screen shot 2017-09-07 at 10 40 35 pm](https://user-images.githubusercontent.com/8134768/30159697-9c873be2-941d-11e7-90f1-ffcce6537318.png)
Why is the context still in the tmp folder when I specified the actual path and not .?

**Comment by qbikez** [comment]
@janmchan I had exactly the same problem with dotnet and docker. Turned out that the directory I was trying to COPY was ignored by `.dockerignore` (which in turn was generated by dotnet itself). Once I changed `.dockerignore`, everything worked.

**Comment by netspark** [comment]
@qbikez, how did you change the .dockerignore file?
I have it like this:
```
*
!obj/Docker/empty/

```
and is still giving the same copy error

**Comment by qbikez** [comment]
@netspark Mine looks like this:

```
*
!obj/Docker/publish/*
!obj/Docker/empty/
```

So everything besides `obj/Docker/publish/*` and `obj/Docker/empty/` is ignored. By default, the generated `Dockerfile` does:

```
COPY ${source:-obj/Docker/publish} .
```

So it copies from a directory that's not ignored and everything is fine. But, if in your `Dockerfile` you have a COPY that uses any other directory, like `COPY bin/Debug/netcoreapp2.0/ .` (or if you set `source` arg to something else), then docker will say "no such file or directory", because `bin/Debug/netcoreapp2.0/` is ignored (thanks to the wildcard `*` in `.dockerignore`. 

If you're unsure of what is ignored or is this the cause at all, you can just try and remove `.dockerignore`. Docker may build a little slower, but there will be one moving part less to worry about.

**Comment by AshtonHylton-awin** [comment]
This happened to me when trying to run the docker file from a different directory.

I had the `COPY failed: stat /var/lib/docker/tmp/docker-builder929708051/XXXX: no such file or directory` and managed to resolve this by specifying the docker file.

Running `docker build . -f docker/development/Dockerfile` worked.

But running `Running `docker build docker/development/Dockerfile` caused this issue.

`-f` or `--file` to specify the name and location of the `Dockerfile`.

It found it strange at first because when i had the `Dockerfile` in the apps root directory it worked fine. This will help if you want to manage your environment docker files a little better.

**Comment by huawei-tomas** [comment]
I'm getting same behavior from `COPY ./pytorch /app/pytorch`

**Comment by bulletblp4** [comment]
I am trying to copy ~/.ssh/id_rsa to my container.
Below is how my dockerfile looks line 
`# Pull base image
FROM openjdk:8u171 AS init
VOLUME /root/.ssh

# make sure your domain is accepted
ADD ~/.ssh/id_rsa /root/.ssh
RUN echo $(ls /root/.ssh)
RUN echo "StrictHostKeyChecking no " > /root/.ssh/config`

I get a similar error : `ADD failed: stat /var/lib/docker/tmp/docker-builder898806991/~/.ssh/id_rsa: no such file or directory`

**Comment by AncalagonTheBlack** [comment]
Same Error

**Comment by kieranbop** [comment]
same Error

**Comment by gazataeon** [comment]
Same with both relative or not paths

**Comment by FabrizioCafolla** [comment]
if you have .dockerignore file in folder, you should be add **/directoryFile

Dockerfile nginx
`FROM nginx:1.10

ADD ./**docker-compose**/nginx/vhosts.conf /etc/nginx/conf.d/default.conf`

.dockerignore
`**/docker-compose`

**Comment by csbenk** [comment]
I too had same error. Since I had many dockerfiles in the directory I was giving the file:
 `$ sudo docker build -t image-name:version - < test3.dockerfile`
This used to give the the following error:
> COPY failed: stat /var/lib/docker/tmp/docker-builder132607663/xxx/xxxx: no such file or directory

Afterwards, I change my dockerfile name to Dockerfile and built it by:
`$ sudo docker build -t image-name:version .`
This worked! The path of the file to be copied was right (_relative path_) from the start. Second time it worked and the first time it didn't work.

**Comment by thaJeztah** [comment]
@csbenk in your case, the issue you were having is due to the syntax you used; depending on the syntax when piping a dockerfile to `stdin`, the context is sent, or not;


Set up the test directory, and make some files;

```
mkdir test && cd test
touch one two three four
```

Create a Dockerfile

```
cat <<EOF>Dockerfile
FROM busybox
COPY . /files
EOF
```

#### Build (with the Dockerfile from stdin) using `-`

This syntax takes the Dockerfile from stdin, but no build-context (so no files are sent to the daemon to be used during build);

```bash
cat ./Dockerfile | docker build -t bla -
```

Once the build completes; run the image, and notice that no files were added;

```bash
docker run --rm bla ls -la /files
total 8
drwx------    2 root     root          4096 Nov 13 18:04 .
drwxr-xr-x    1 root     root          4096 Nov 13 18:10 ..
```

#### Build (with the `-f` flag and `-` with a Dockerfile from stdin)

This syntax is _slightly_ different; the build in the example below uses the following arguments

- `-t bla2` name/tag for the image
- `-f` use a custom Dockerfile (instead of a file named `Dockerfile` in the current directory)
- `-` the custom Dockerfile will be piped to `stdin`, not from a file
- `.` use the current (`.`) directory as build-context, and send any file present to the daemon to be used during build



```bash
cat ./Dockerfile | docker build -t bla2 -f- .
```

Once the build completes; run the image, and notice that the files were added;


```bash
docker run --rm bla2 ls -la /files
total 12
drwx------    2 root     root          4096 Nov 13 18:11 .
drwxr-xr-x    1 root     root          4096 Nov 13 18:11 ..
-rw-r--r--    1 root     root            27 Nov 13 18:10 Dockerfile
-rw-r--r--    1 root     root             0 Nov 13 18:03 four
-rw-r--r--    1 root     root             0 Nov 13 18:03 one
-rw-r--r--    1 root     root             0 Nov 13 18:03 three
-rw-r--r--    1 root     root             0 Nov 13 18:03 two
```

**Comment by csbenk** [comment]
Thanks for the detailed explanation @thaJeztah

**Comment by thaJeztah** [comment]
You're welcome! There was an issue for improving the docs around this (https://github.com/docker/docker.github.io/issues/3538);  and improvements were made in https://github.com/docker/docker.github.io/pull/6807, but if you have suggestions how to improve the documentation, that would be welcome 

/cc @ahh-docker

**Comment by rahulsrivastava71** [comment]
i am trying to copy config file from like COPY X.config /etc/share/
and getting error as my X.config and Dockerfile is both present there in same folder 
received error COPY failed: stat /var/lib/docker/tmp/docker-builder211907681/X.config: no such file or directory

**Comment by ahh-docker** [comment]
@thaJeztah if this is a documentation issue, can you please create an issue in docker.github.io and reference this? I'll be happy to get it fixed. Thanks!

**Comment by bhadouriyanikhil** [comment]
> i am trying to copy config file from like COPY X.config /etc/share/
> and getting error as my X.config and Dockerfile is both present there in same folder
> received error COPY failed: stat /var/lib/docker/tmp/docker-builder211907681/X.config: no such file or directory

if you could share folder structure and where your files are located, it would be helpful to look into your issue.

**Comment by hanlina0737** [comment]
I have the same error,confused ,I try many times but still failed

**Comment by alexei-developer** [comment]
same error:
Step 12/23 : ADD ${KEY_FILE_ZWB_SRC}/id_rsa /root/.ssh/
ADD failed: stat /var/lib/docker/tmp/docker-builder903141078/media/alexei/data/_Projects/Tools/files/id_rsa: no such file or directory

**Comment by thaJeztah** [comment]
@alexei-developer is `media/alexei/data/_Projects/Tools/files/id_rsa` within your build context? Paths in your Dockerfile are not absolute paths on your filesystem, but relative to the build-context, so if you trigger a build from, e.g. `/home/myname/myproject`, then the file you're adding will be relative to that, so `/home/myname/myproject/media/alexei/data/_Projects/Tools/files/id_rsa`

Also, what you're doing looks quite dangerous; you should likely not be adding your private keys to a Docker image, but provide them at runtime. If you need them at _build_ time (for steps inside your Dockerfile), have a look at https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066

**Comment by alexei-developer** [comment]
${KEY_FILE_ZWB_SRC} is "/media/alexei/data/_Projects/Tools/files" with slash begin. Run docker build in "/media/alexei/data/_Projects/Tools/ci/master/". If create relative path "../../../files" get error "failed: Forbidden path outside the build context: ../../../files/id_rsa ()"

docker info:
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 89
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 70
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.64GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by thaJeztah** [comment]
So `/media/alexei/data/_Projects/Tools/ci/master/` is your build-context; the Dockerfile (by _design_) does not have access to anything outside of that directory. This design has a couple of reasons;

1. `docker build` is done on the host where the `daemon` runs; this may not be the same machine as your local machine (e.g. it could be a docker daemon running remotely). When triggering a build, the context is sent to the daemon, which puts it in a temporary directory, and starts the build, using those files
2. Security; the `Dockerfile` should not be able to access random files on your (or someone else's) machine. Actually, exactly for the reason above; if I want a Dockerfile to have access to a file, I should explicitly provide it access to those files. Otherwise, someone could hand me a Dockerfile, ask me to build and push it and steal my keys. (note that symlinks won't be evaluated when sending the build-context to the daemon, so you can't create a symlink to something outside the build-context for the same reason)

If you need to use files from multiple locations on your machine, you may be interested in this proposal I wrote; https://github.com/moby/moby/issues/37129

**Comment by GrigorievNick** [comment]
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Mon Oct  1 14:25:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon Oct  1 14:25:33 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Still same issue.

**Comment by amir3code** [comment]
My problem was with `.gitignore`  
Check if you have any `.gitignore` files ( in nested directories ) that are ignoring inner directories and change them.

**Comment by panique** [comment]
if you simply want to use a Dockerfile from OUTSIDE the current folder, make your docker-compose like this:

```
    # set the to-be-used folder via *context*
    build:
      context: ./../folderoutsideofcurrentfolder
      dockerfile: Dockerfile
```

**Comment by ZamzamMumin** [comment]
I am having the same error: Kindly help me!
PS C:\Users\zmumin\MyDockerImage> docker build --tag hello .
Sending build context to Docker daemon  2.189MB
Step 1/3 : FROM scratch
 --->
Step 2/3 : ADD hello /
ADD failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder008000438\hello: The system cannot find the file specified.
PS C:\Users\zmumin\MyDockerImage> docker --version
Docker version 18.09.2, build 6247962
PS C:\Users\zmumin\MyDockerImage> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     true
 I want to take the static binary named hello from my current directory and add it to the root directory of the image file. Trying to build the image by invoking the docker build command which would go through the Dockerfile’s contents and generate the image.

**Comment by LeoK80** [comment]
same issue here.

Context is current directory `.`
directory contains file to be added
directive is `ADD myfile.zip /` to add the archive to the docker container root

error refers to: `ADD failed: stat /var/lib/docker/tmp/docker-builder<somenumber>/myfile.zip: no such file or directory`

Obviously the file being looked for does not exist in said `/var/lib` directory as I never placed it there. I'm presuming that the file is just taken from current context (as many builds before) and unpacked to root. Dito goes for `COPY` directive which I've also tried unsuccessfully. 

Docker version 19.03.0-rc3, build 27fcb77 on Ubuntu 19.04 docker-ce install (not snap).

**Comment by vnckppl** [comment]
I had the same issue and noticed that there were some unsaved files that I had open in emacs in the folder I tried to add to my docker container. These files get prepended with a # by emacs. Removing these files solved my issue. It may be worth to check if you have any files with unconventional characters in the file name.

**Comment by thaJeztah** [comment]
> Obviously the file being looked for does not exist in said /var/lib directory as I never placed it there. I'm presuming that the file is just taken from current context (as many builds before) and unpacked to root. Dito goes for COPY directive which I've also tried unsuccessfully.

When doing a `docker build`, the files from your local context are sent to the daemon, and put in a temporary directory; that directory is used to build the image (the actual build is performed on the daemon side).

Might also be worth checking if there's no `.dockerignore` in your project that's preventing the file from being added

**Comment by ZamzamMumin** [comment]
I don't have a .dockeringore file in my project. just the dockerfile. I am still having the same error even after doing what you all said.

**Comment by mankuuuuu** [comment]
I am also the facing the same issue.
Docker version 18.06.0-ce, build 0ffa825

It is behaving differently while using ADD, COPY and RUN cp in Dockerfile

**ADD, COPY**
---------------------------------------------------------------------------------------------------
Devils-Notebook:compose-demo1$ docker build --build-arg path="/tmp/compose-demo1/my-app-1.0-SNAPSHOT.jar" . 
Sending build context to Docker daemon  158.7kB
Step 1/7 : FROM ubuntu:16.04
 ---> 13c9f1285025
Step 2/7 : MAINTAINER ***
 ---> Using cache
 ---> f3745af9071a
Step 3/7 : WORKDIR "/tmp/compose-demo1"
 ---> Using cache
 ---> 18b03dd3afb5
Step 4/7 : ARG path
 ---> Using cache
 ---> fe1583246d33
Step 5/7 : COPY $path /
COPY failed: stat /var/lib/docker/tmp/docker-builder987237575/tmp/compose-demo1/my-app-1.0-SNAPSHOT.jar: no such file or directory

** Here I am passing absolute path and it failed while running ADD and COPY **
---------------------------------------------------------------------------------------------------
Devils-Notebook:compose-demo1$ docker build --build-arg path="my-app-1.0-SNAPSHOT.jar" . 
Sending build context to Docker daemon  158.7kB
Step 1/7 : FROM ubuntu:16.04
 ---> 13c9f1285025
Step 2/7 : MAINTAINER ***
 ---> Using cache
 ---> f3745af9071a
Step 3/7 : WORKDIR "/tmp/compose-demo1"
 ---> Using cache
 ---> 18b03dd3afb5
Step 4/7 : ARG path
 ---> Using cache
 ---> fe1583246d33
Step 5/7 : COPY $path /
 ---> Using cache
 ---> 45475ea30617
Step 6/7 : CMD [“echo”,”Image created”]
 ---> Using cache
 ---> 4b1eaa7ea59d
Step 7/7 : CMD ["ls","/"]
 ---> Using cache
 ---> c2eba45fea9a
Successfully built c2eba45fea9a

** Here it ran successfully while passing app name which resides in current directory **
----------------------------------------------------------------------------------------------------
Devils-Notebook:compose-demo1 $ ls my-app-1.0-SNAPSHOT.jar 
my-app-1.0-SNAPSHOT.jar
----------------------------------------------------------------------------------------------------
**RUN cp**

Devils-Notebook:compose-demo1$ docker build --build-arg path=my-app-1.0-SNAPSHOT.jar .
Sending build context to Docker daemon  158.7kB
Step 1/7 : FROM ubuntu:16.04
 ---> 13c9f1285025
Step 2/7 : MAINTAINER ***
 ---> Using cache
 ---> f3745af9071a
Step 3/7 : WORKDIR /tmp/compose-demo1
 ---> Running in 2bbc23ea2bf2
Removing intermediate container 2bbc23ea2bf2
 ---> 18b03dd3afb5
Step 4/7 : ARG path
 ---> Running in fd58406a17a4
Removing intermediate container fd58406a17a4
 ---> fe1583246d33
Step 5/7 : RUN cp my-app-1.0-SNAPSHOT.jar /
 ---> Running in fa537f8438e5
cp: cannot stat 'my-app-1.0-SNAPSHOT.jar': No such file or directory
The command '/bin/sh -c cp my-app-1.0-SNAPSHOT.jar /' returned a non-zero code: 1

** While using RUN cp it is not able to stat the file **

**Comment by bennya1** [comment]
The context is whatever comes after the docker build command options.
`docker build [OPTIONS] PATH` 

Meaning: 
`docker build -f /path/Dockerfile` = will only fetch the Dockerfile from the specified location, context is not changed.

However:
`docker build -f /path/Dockerfile /desiredcontext` = will use /desiredcontext as the root directory while building the image.

https://docs.docker.com/engine/reference/commandline/build/

**Comment by akhapersky** [comment]
> The context is whatever comes after the docker build command options.
> `docker build [OPTIONS] PATH`
> 
> Meaning:
> `docker build -f /path/Dockerfile` = will only fetch the Dockerfile from the specified location, context is not changed.
> 
> However:
> `docker build -f /path/Dockerfile /desiredcontext` = will use /desiredcontext as the root directory while building the image.
> 
> https://docs.docker.com/engine/reference/commandline/build/

Awesome!!! Thank You for your explanation!

**Comment by d3pr3553d** [comment]
I have the same error. 
COPY file.xml /to/container/directory

COPY failed: stat /var/lib/docker/tmp/docker-builderxxxxxxxxx/file: : no such file or directory

The files are in the same directory. Why does this happen and what is the current workaround?

**Comment by LeoK80** [comment]
> When doing a `docker build`, the files from your local context are sent to the daemon, and put in a temporary directory; that directory is used to build the image (the actual build is performed on the daemon side).
> 
> When doing a docker build, the files from your local context are sent to the daemon, and put in a temporary directory; that directory is used to build the image (the actual build is performed on the daemon side).Might also be worth checking if there's no `.dockerignore` in your project that's preventing the file from being added

There's no .dockerignore in my project.
Basically what you're telling me is that the file from 'current context' is not being copied to the temporary directory. This can only mean either of two things: 1. the docker daemon doesn't have sufficient rights or space to create the temporary directory and files (and expand them if necessary), or 2. there's a bug in the directive that fails to place the expected files from 'current context' to into the temporary directory as to subsequently use them for the required/expected actions.

**Comment by herrmann** [comment]
I'm having the same issue as @d3pr3553d above: I can copy a file but not a directory, from the same directory.

**Comment by Adinas92** [comment]
I deleted .dockerignore but I still had the same issue, resseting local docker registry helps.

**Comment by Leigh092478** [comment]
Hi All,

After a fresh install of docker desktop, I try to create a simple docker image. I follow this simple instructions , https://spring.io/guides/gs/spring-boot-docker/, and downloaded their sample application, https://github.com/spring-guides/gs-spring-boot-docker. I try to build the dockerfile but I getting this error always.

![image](https://user-images.githubusercontent.com/41415875/73272409-48bc3480-421d-11ea-9258-dae7b5da5ccb.png)

This is the command I use;

C:\Users\username\git\gs-spring-boot-docker\complete>docker build .
Sending build context to Docker daemon    170kB
Step 1/8 : FROM openjdk:8-jdk-alpine
 ---> a3562aa0b991
Step 2/8 : RUN addgroup -S spring && adduser -S spring -G spring
 ---> Running in e01e403959a8
Removing intermediate container e01e403959a8
 ---> 83a809f8dbfd
Step 3/8 : USER spring:spring
 ---> Running in f3650de20b63
Removing intermediate container f3650de20b63
 ---> d33c24a5ceca
Step 4/8 : ARG DEPENDENCY=target/dependency
 ---> Running in 89033c72b131
Removing intermediate container 89033c72b131
 ---> ef52242cd3f9
Step 5/8 : COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY failed: stat /var/lib/docker/tmp/docker-builder916359289/target/dependency/BOOT-INF/lib: no such file or directory

C:\Users\username\git\gs-spring-boot-docker\complete>

Does anybody encounters the same issue and resolve it?

Any Idea guys?

Thank you.

**Comment by anujshah1003** [comment]
I had the same error - I was keepind the Dockerfile in a directory with other scripts and was using this below command for building docker image
docker build -t test-docker -> Dockerfile

then I kept the Dockerfile in separate directory and used the below command and my error got solved
docker build -t test-docker .

**Comment by DanielYWoo** [comment]
> I'm having the same issue as @d3pr3553d above: I can copy a file but not a directory, from the same directory.

I have exactly the same problem, can add file, but not directory.
Docker version 19.03.5, build 633a0ea
Mac OSX Catalina

**Comment by johnbazan** [comment]
> @janmchan I had exactly the same problem with dotnet and docker. Turned out that the directory I was trying to COPY was ignored by `.dockerignore` (which in turn was generated by dotnet itself). Once I changed `.dockerignore`, everything worked.

This comment saved me a lot of debugging time. Thanks.

**Comment by noddy09** [comment]
Same issue occurred while doing 
`docker load --input file.tar.gz`

stat /var/lib/docker/tmp: no such file or directory.

**Comment by sutidor** [comment]
My Solution:
I had a typo in the required file (ADD), which was the only one added to the image. The result would have been an **empty** image which resulted in the build folder not being created, which resulted in it couldn't be found. D'ugh.

Detail:
`$ ls`
main.py
Dockerfile


Dockerfile (wrong)
...
`ADD main /`
...

Dockerfile (correct)
...
`ADD main.py /`
...

**Comment by radhegithub** [comment]
@Jenkinserver: shell Script:
# Update kubernetes deployment with new image.
WEB_IMAGE_NAME="${ACR_LOGINSERVER}/azure-vote-front:kube${BUILD_NUMBER}"
kubectl set image deployment/azure-vote-front azure-vote-front=$WEB_IMAGE_NAME --kubeconfig /var/lib/jenkins/config

Error:
+ kubectl set image deployment/azure-vote-front azure-vote-front=****.azurecr.io/azure-vote-front:kube3 --kubeconfig /var/lib/jenkins/config
error: stat /var/lib/jenkins/config: no such file or directory

New docker , please help

**Comment by Izvunzemen** [comment]
Make sure that you don't do this:
`docker build -f somewhere/Dockerfile . `

But this:
`docker build -f somewhere/Dockerfile somewhere/ `

**Comment by jasperf** [comment]
> @janmchan I had exactly the same problem with dotnet and docker. Turned out that the directory I was trying to COPY was ignored by `.dockerignore` (which in turn was generated by dotnet itself). Once I changed `.dockerignore`, everything worked.

Exactly my issue to @qbikez . Thanks for the comment here!

**Comment by ThomHehl** [comment]
I am running through the tutorial at: https://docker-curriculum.com/ and am having this issue. Here is my dockerfile as copied from the tutorial
```
# start from base
FROM ubuntu:18.04

MAINTAINER Prakhar Srivastav <prakhar@prakhar.me>

# install system-wide deps for python and node
RUN apt-get -yqq update
RUN apt-get -yqq install python3-pip python3-dev curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -yq nodejs

# copy our application code
ADD flask-app /opt/flask-app
WORKDIR /opt/flask-app

# fetch app specific deps
RUN npm install
RUN npm run build
RUN pip3 install -r requirements.txt

# expose port
EXPOSE 5000

# start app
CMD [ "python3", "./app.py" ]

```
And when I run it, I get

```
thomas@bravos:~/git/foodtrucks-web$ sudo docker build -t heavyweight/foodtrucks-web -f ~/git/foodtrucks-web/Dockerfile ~/git/foodtrucks-web/
Sending build context to Docker daemon  3.072kB
Step 1/13 : FROM ubuntu:18.04
 ---> 6526a1858e5d
Step 2/13 : MAINTAINER Prakhar Srivastav <prakhar@prakhar.me>
 ---> Using cache
 ---> f7a8216c0f21
Step 3/13 : RUN apt-get -yqq update
 ---> Using cache
 ---> c87f01274fd1
Step 4/13 : RUN apt-get -yqq install python3-pip python3-dev curl gnupg
 ---> Using cache
 ---> f5f3fb1de240
Step 5/13 : RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
 ---> Using cache
 ---> b61ee044b6a0
Step 6/13 : RUN apt-get install -yq nodejs
 ---> Using cache
 ---> f585f12b229b
Step 7/13 : ADD flask-app /opt/flask-app
ADD failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder133660286/flask-app: no such file or directory

```
Note, I started with `docker build -t heavyweight/foodtrucks-web .` and made changes according to the items listed here.

I changed the group of /var/snap/docker/common/var-lib-docker/tmp to be docker and added rwxt to the group.

It's extremely frustrating when the tutorial doesn't work. I am running under Ubuntu 20.04.

**Comment by thaJeztah** [comment]
@ThomHehl  I suspect you're running the snap package of Docker, which is maintained by Ubuntu, and I've seen various issues with those packages being broken; are you seeing the same problem with the official docker packages? (https://docs.docker.com/engine/install/ubuntu/)

**Comment by ThomHehl** [comment]
@thaJeztah  I was. Uninstalled and installed from the link you provided. Exact same issue.

**Comment by thaJeztah** [comment]
Are you sure you cloned the right github repository? Is the `flask-app` directory present in the directory from which you're building?

```bash
git clone https://github.com/prakhar1989/FoodTrucks.git ~/Projects/test/repro-90/foodtrucks-web

docker build -t foo -f ~/Projects/test/repro-90/foodtrucks-web/Dockerfile ~/Projects/test/repro-90/foodtrucks-web/
...
Sending build context to Docker daemon  9.371MB
Step 1/13 : FROM ubuntu:18.04
...
Successfully built 64ed18260ce5
Successfully tagged foo:latest
```

**Comment by ThomHehl** [comment]
@thaJeztah I created the flask-app directory where Dockerfile was and that seems to have fixed the problem. Thanks for your help.

I think to tutorial needs a little work. When I started the section with elasticsearch and the flask app, I started my own folder to work on this, because I didn't know what else to do. There needs to be some explanation here. Are you on the docker team?

**Comment by thaJeztah** [comment]
I'm on the docker team, but that tutorial is not written by Docker; I can see it being easily confused for something written by Docker, because of the domain-name and use of the logo (perhaps someone should contact the maintainer of that tutorial to update). Official docs can be found in https://docs.docker.com

**Comment by ThomHehl** [comment]
Oh, dear. I'm usually more careful of these things. I think it was the icon that got me.
OK, thanks.

**Comment by thaJeztah** [comment]
Which isn't to say the content is bad 😅; at a glance, it looked nicely written (but didn't look closely)

**Comment by EricoCartmanez** [comment]
It worked for my by copying the folder to the directory where Dockerfile is located.

**Comment by junaidahmed501** [comment]
> Paths in a `Dockerfile` are always relative to the the context directory. The context directory is the positional argument passed to `docker build` (often `.`).
> 
> If there is no `./tmp` in the context directory then this is the expected behaviour.

Thanks, man. I had my path set to `/home/junaid/workspace/keycloak-custom/standalone-ha.xml` but then I copied the standalone-ha.xml file to the directory where my Dockerfile was & updated my command from `ADD ./home/junaid/workspace/keycloak-custom/standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml` to `ADD ./standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml`
