### ISSUE TITLE
updates for containerd.io rpm for centos7 missing at docker-ce yum repo

### ISSUE THREAD

**Issue by ravilr** [docker/for-linux#901]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

the last containerd rpm version available at https://download.docker.com/linux/centos/7/x86_64/stable/Packages/ is containerd.io-1.2.6.  
Since docker-ce no more ships containerd, can we get containerd.io rpms uploaded as part of docker-ce release.  docker-ce-19.05.3 is expected to work with containerd.io-1.2.10 ? whose rpm is missing in the above repo..

**Comment by tiborvass** [comment]
Closing as this should no longer be an issue. Let me know if you disagree.

**Comment by ravilr** [comment]
@tiborvass  For CentOS rpm repo, still don't see any new newer containerd.io rpm's at https://download.docker.com/linux/centos/7/x86_64/stable/Packages/ 
Am i looking at the right place ?

**Comment by ravilr** [comment]
@tiborvass i do see containerd.io-1.2.10 now,  would there be a containerd.io-1.2.13 rpm uploaded or containerd.io-1.2.10 compatible/good with latest docker-ce-19.03.6 ?
