### ISSUE TITLE
docker-ce package for ARM debian

### ISSUE THREAD

**Issue by antony-rheneus** [docker/for-linux#906]
* [x] This is a bug report

On apt update, I get below error "connection refused"

Err:6 https://download.docker.com/linux/debian stretch InRelease
  FailReason: ConnectionRefused

Also,

docker-ce packages are removed recently from below repo for ARMHF and ARM64.  Only containerd.io package is found. Whereas the same is found on x86_64/AMD64 arch.

https://download.docker.com/linux/debian/dists/stretch/stable/

Let me know how to install docker-ce package for ARMHF/ARM64?

**Commands Used to Reproduce:**

```
add-apt-repository deb arch=arm64,armhf https://download.docker.com/linux/debian stretch stable
apt-get update
Err:6 https://download.docker.com/linux/debian stretch InRelease
  FailReason: ConnectionRefused
Reading package lists...
W: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/InRelease  FailReason: ConnectionRefused
W: Some index files failed to download. They have been ignored, or old ones used instead.

apt-get -y install docker-ce
E: Unable to locate package
```

**Comment by thaJeztah** [comment]
Thanks!

@arkodg @tiborvass @ehazlett FYI

**Comment by arkodg** [comment]
@antony-rheneus this issue should be resolved now, apologies for the temporary disruption

**Comment by thaJeztah** [comment]
looks to be resolved yes; https://download.docker.com/linux/debian/dists/stretch/pool/stable/armhf/
