### ISSUE TITLE
Docker-ce package for linux mint tricia

### ISSUE THREAD

**Issue by light42** [docker/for-linux#908]
Time when issue happened: 24 January 2020, around 09.10-09.20 UTC+07.00.

Following official installation procedure on https://docs.docker.com/install/linux/docker-ce/ubuntu/, I faced issue when I entered command apt update.

sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease                                               
Ign:2 https://download.docker.com/linux/ubuntu tricia InRelease                                                      
Hit:3 http://archive.canonical.com/ubuntu bionic InRelease                                                           
Err:4 https://download.docker.com/linux/ubuntu tricia Release                                  
  404  Not Found [IP: 13.35.8.75 443]
Ign:5 http://packages.linuxmint.com tricia InRelease                
Hit:6 http://packages.linuxmint.com tricia Release
Hit:8 http://mirror.poliwangi.ac.id/ubuntu bionic InRelease
Get:9 http://mirror.poliwangi.ac.id/ubuntu bionic-updates InRelease [88,7 kB]       
Get:10 http://mirror.poliwangi.ac.id/ubuntu bionic-backports InRelease [74,6 kB]    
Reading package lists... Done                                  
E: The repository 'https://download.docker.com/linux/ubuntu tricia Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Possible solution:
I guess it happened because of the wrong url, so I edit the repo url to:
https://download.docker.com/linux/ubuntu bionic Release

Which worked.
Yet I'm not sure if this the ideal solution, maybe docker dudes planned to have docker-linux mint repo entirely separated from ubuntu.

**Comment by wakedeer** [comment]
I run into the same issue with **Linux Mint 19.3**
Indeed, there is a workaround: substitute $(lsb_release -cs) for bionic
for example: `sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" ` it works fine

 Thanks a lot, @light42

**Comment by thaJeztah** [comment]
We don't officially support Debian and Ubuntu derivatives, but in most cases, substituting the corresponding ubuntu/debian version in the installation instructions should work (as mentioned above)

I'll close this ticket because of the above
