### ISSUE TITLE
ADD failed: stat /var/lib/docker/tmp/docker-builderXXXXXX: no such file or directory

### ISSUE THREAD

**Issue by Leigh092478** [docker/for-linux#915]
Hi All,

After a fresh install of docker desktop, I try to create a simple docker image. I follow this simple instructions , https://spring.io/guides/gs/spring-boot-docker/, and downloaded their sample application, https://github.com/spring-guides/gs-spring-boot-docker. I try to build the dockerfile but I getting this error always.

![image](https://user-images.githubusercontent.com/41415875/73275299-e1ed4a00-4221-11ea-99ef-f062a07e5dea.png)

This is the command I use;

C:\Users\username\git\gs-spring-boot-docker\complete>docker build .
Sending build context to Docker daemon 170kB
Step 1/8 : FROM openjdk:8-jdk-alpine
---> a3562aa0b991
Step 2/8 : RUN addgroup -S spring && adduser -S spring -G spring
---> Running in e01e403959a8
Removing intermediate container e01e403959a8
---> 83a809f8dbfd
Step 3/8 : USER spring:spring
---> Running in f3650de20b63
Removing intermediate container f3650de20b63
---> d33c24a5ceca
Step 4/8 : ARG DEPENDENCY=target/dependency
---> Running in 89033c72b131
Removing intermediate container 89033c72b131
---> ef52242cd3f9
Step 5/8 : COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY failed: stat /var/lib/docker/tmp/docker-builder916359289/target/dependency/BOOT-INF/lib: no such file or directory

C:\Users\username\git\gs-spring-boot-docker\complete>

Does anybody encounters the same issue and resolve it?

Any Idea guys?

Thank you.

**Comment by serban-sre** [comment]
This is mainly for 2 reasons that are not related to docker, so imho the issue should be closed here and addressed on the spring-boot project.

1. you haven't built the hello.Application - this can be done with gradlew or mvnw. Once done, as per the readme:
If you are using Gradle, execute:

`./gradlew build` // build command
`java -jar build/libs/gs-spring-boot-docker-0.1.0.jar` // run app locally, not in the container

2. you haven't adapted the Dockerfile to add the generated artifact(library in this case) to the app/lib
Assuming you that you have used gradle as above, the correct Dockerfile to use is eg:

```
FROM openjdk:8-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG BUILD_DIR=build
COPY ${BUILD_DIR}/libs /app/lib/
ENTRYPOINT ["java","-jar","app/lib/gs-spring-boot-docker-0.1.0.jar"]
```
build the docker image:
`docker build . -t app-springboot`

run the docker app image:

```
test@test-VirtualBox ~/gs-spring-boot-docker/complete $ docker run image-springboot

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.1.RELEASE)

2020-01-30 16:39:03.633  INFO 1 --- [           main] hello.Application                        : Starting Application on 9ad0cf3d00fe with PID 1 (/app/lib/gs-spring-boot-docker-0.1.0.jar started by spring in /)
```

**Comment by thaJeztah** [comment]
This doesn't appear to be a bug, so closing

**Comment by eaccmk** [comment]
_....probably too late_ ,but may be few more people returned after reading it (by not able to find the Answer) .
Most probably @Leigh092478  was following [Spring Boot with Docker](https://spring.io/guides/gs/spring-boot-docker/)

This step did not fall in the official documentation in right sequence or may be we missed to follow that religiously :) : 
**From a Maven build:** `mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)`
or
**From a Gradle build:** `mkdir -p build/dependency && (cd build/dependency; jar -xf ../libs/*.jar)`

And Don't forget to run this again:

If you are using **Gradle**, execute: `./gradlew build && java -jar build/libs/gs-spring-boot-docker-0.1.0.jar`
If you are using **Maven**, execute: `./mvnw package && java -jar target/gs-spring-boot-docker-0.1.0.jar`

**Comment by mousumi8** [comment]
./gradlew build && java -jar build/libs/gs-spring-boot-docker-0.1.0.jar, this command got deprecated. Can you plz help on it I am getting same error while doing a dockerization of springboot app in ubuntu machine using gitlab-cli.yml file.

ADD failed: stat /var/lib/docker/tmp/docker-builder246550089/build/libs/{somename}-1.0.jar: no such file or directory
