### ISSUE TITLE
Docker: error creating aufs mount to /var/lib/docker/aufs/mnt/

### ISSUE THREAD

**Issue by manishalankala** [docker/for-linux#917]
* [] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

setup rancher in different container

adding host on other container gives the below error.
### Steps to reproduce the behavior

**Output of `docker version`:**

Client: Version:           18.06.1-ce API version:       1.38
 Go version:        go1.10.3 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64  Experimental:     false
```
(paste your output here)
```

**Output of `docker info`:**
/var/lib/docker# docker version
Client: Version:           18.06.1-ce API version:       1.38
 Go version:        go1.10.3 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64  Experimental:     false
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

![image](https://user-images.githubusercontent.com/33985509/73448163-8bd2f080-4360-11ea-813e-83b6d92f817c.png)

![image](https://user-images.githubusercontent.com/33985509/73447471-174b8200-435f-11ea-8f3f-6f61c12bbf40.png)

![image](https://user-images.githubusercontent.com/33985509/73447925-0bac8b00-4360-11ea-86f3-1b378cd320f8.png)

![image](https://user-images.githubusercontent.com/33985509/73447985-31d22b00-4360-11ea-98fc-c7001a80af54.png)

![image](https://user-images.githubusercontent.com/33985509/73448036-4b737280-4360-11ea-9a7c-b887d347e207.png)

**Comment by thaJeztah** [comment]
Not exactly sure how these are setup with Rancher, but from those logs it looks like (possibly a docker-in-docker instance) is trying to create an `aufs` storage on top of an `overlayfs` mount, which is not possible. I think the best place to get support for this would be through Rancher support.

Note that Docker 18.06 reached EOL two years ago, so I would highly recommend using a more current version.

closing this ticket because of the above, but feel free to continue the conversation

**Comment by SooLee** [comment]
I'm using docker 19.03.13 on ubuntu 20.04, docker in docker.
Got the same error.
```
docker run cgap/cgap:v17 bwa
```
```
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/6075d06b45d4989c38151c33c2452dd58ecc456b9e1bafca19e70e9e7a33bcfe-init: mount target=/var/lib/docker/aufs/mnt/6075d06b45d4989c38151c33c2452dd58ecc456b9e1bafca19e70e9e7a33bcfe-init data=br:/var/lib/docker/aufs/diff/6075d06b45d4989c38151c33c2452dd58ecc456b9e1bafca19e70e9e7a33bcfe-init=rw:/var/lib/docker/aufs/diff/eb93bb8e73766c8295be4f9a3250f19a603304a9c286d382ec39a744e4e1c436=ro+wh:/var/lib/docker/aufs/diff/f6a73b7446a90fe3a7c73840c800fa3cda42b7cee670f4455bd53c0c2e39b8d5=ro+wh:/var/lib/docker/aufs/diff/a4d0facc467bb2bc730ce1b6b2c80555f047e86c173df36ed218f365a292e5cc=ro+wh:/var/lib/docker/aufs/diff/366c41ed13359500fd405678547862fed8e81c968088c1ad4cd051d8b23c7ec0=ro+wh:/var/lib/docker/aufs/diff/df594259466b76ba528603d946a80fd82b1965d7495abff3508d029fe9049f5c=ro+wh:/var/lib/docker/aufs/diff/9d1adf758821626978916c90ca36bc6e02d91d0a6a2bb0efa866f58106fe626e=ro+wh:/var/lib/docker/aufs/diff/3b41ead3c8ed40c29fbc0858f36c82f56e9de0b294b3b300a3e0ec2b9a49642a=ro+wh:/var/lib/docker/aufs/diff/e37de56db1a014b480559a06cea04332e05f0d4505090f84f6a2d1d2ef894e3b=ro+wh:/var/lib/docker/aufs/diff/5975349c2df3736928335bd740bdcbd48d8650fe22839db4f9f86f811d4e99bf=ro+wh:/var/lib/docker/aufs/diff/a7f783a81e995591a7b88983e0b78537926659b480f52f820ead906fe7c1ede6=ro+wh:/var/lib/docker/aufs/diff/1d698805d38e024cb15821615c2c7eae488153b599f049f687ba4f9b7e64e34a=ro+wh:/var/lib/docker/aufs/diff/6a5502a3a500250053dd6030d7d3abf2c96c47f175ff7bd3dc06809e6c87629d=ro+wh:/var/lib/docker/aufs/diff/afd2df047883646d8d459431c31de48cf1488249bc7a7a56317bcaaf1e7fac3a=ro+wh:/var/lib/docker/aufs/diff/d029c6004b99e4462ad173d73d82e9b427b3ef758a3e9aa6d13318d25c077f61=ro+wh:/var/lib/docker/aufs/diff/bdb04bcf52470408b0ef8cb079b8defc903a3c9e9a76f35122d07d36cc06ba6b=ro+wh:/var/lib/docker/aufs/diff/d4c3126a6b2801f9bd43fbe4f2dbc0aaf57963f898210515d17156a34bf7e155=ro+wh:/var/lib/docker/aufs/diff/fc79314b47412eaa5eba8e30afd2da9f32e8e0ec970426f176f481a47280e9d1=ro+wh:/var/lib/docker/aufs/diff/bb48e1d8f875fb4288306a1edc99bd8a9dbbed5028f1cd40b4f666fe2bf4f755=ro+wh:/var/lib/docker/aufs/diff/aac77a86c2029911a26c554f0dc8c92cb6c94080a7be186a4fb5ebd4f9fedf97=ro+wh:/var/lib/docker/aufs/diff/aae73d4bde9f33f0db40549c2d6308730bd7de60f3eb46002c671a996b45b252=ro+wh:/var/lib/docker/aufs/diff/6c9b054636b2c24531723e2d71dbc88dcaad36a5587abc456e10cf502b03b48f=ro+wh:/var/lib/docker/aufs/diff/4fcf700440f12a381ed16f0ab11c1e1ee28a9ad7890a8afec07d67ad2fc2aba2=ro+wh:/var/lib/docker/aufs/diff/8e380bffc9d9e920c7772d95f51df0383effac73062a9df137849bba36b7e46b=ro+wh:/var/lib/docker/aufs/diff/461591bb0346c390616b075f8f0264c9233bd328221e1a3ed64a38d2877665ad=ro+wh:/var/lib/docker/aufs/diff/4521d7e5047d76e12cb1e740ec8df76cc87057c5543db2811d740830c6ff6d2e=ro+wh:/var/lib/docker/aufs/diff/a283bb2939da3a1fc314f4079c8d180a437c1da761d9da14e10251c571fa08ad=ro+wh:/var/lib/docker/aufs/diff/71dbb7d2cfff87003efd3a467d893d09f62920811635a44625086955b2cd1a11=ro+wh:/var/lib/docker/aufs/diff/83a7b4ca333db8123f6e163d98c9ae5846a2a4414794fa01059eea535dd1a986=ro+wh:/var/lib/docker/aufs/diff/bf12c8a0ab3d9c987c6035f79cc17586b482171954e47aa2a986bda01bd69e78=ro+wh:/var/lib/docker/aufs/diff/84c735334904c644abbb10e36041b0ef9b30e0c659c0928229390d84b1381d31=ro+wh:/var/lib/docker/aufs/diff/b15a4a1b0c0f092c0f868daec6ac925c34371465bbe6e46ca19b362e2267071c=ro+wh:/var/lib/docker/aufs/diff/4e84260edfc4454ecde570fd1b2b815426307912cbf7e8da827c9c9c60ef74eb=ro+wh:/var/lib/docker/aufs/diff/9c405079f8575472df6a2b7575ca4b1b8a6ffdaa18f490cbf01b5608778a4d48=ro+wh:/var/lib/docker/aufs/diff/99132c31bc10e3e024cc16d8f3f23c454c472aa1404d0e07e32627cd67c850a5=ro+wh:/var/lib/docker/aufs/diff/1a9923a5a18f795beb6cf2e9819c829e545b56f95cdd4d68f88b78aaf8753cba=ro+wh:/var/lib/docker/aufs/diff/c702e1c5be0d12865108dcd2664ec6c096ec5519d6672a082f73484fd9d7f22d=ro+wh:/var/lib/docker/aufs/diff/aa7839d68b537a41006e0be70516e0ebf5d0fe8b9844558697e48199f32cbd39=ro+wh:/var/lib/docker/aufs/diff/d87ecf6c6c5e4bc5940b6a48f7907c6562f13432ef5705ac7e58114592d151a4=ro+wh:/var/lib/docker/aufs/diff/840aaec872088b644d07d04154772d6ecb067296bbc3e1601c609a34a92b718f=ro+wh:/var/lib/docker/aufs/diff/a2974ddbb40252a7cedd464ae3cd357b901e1150c57495a34524c77aff78496d=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument.
```
