### ISSUE TITLE
docker v19.03 not available for s390x 

### ISSUE THREAD

**Issue by sid226** [docker/for-linux#921]
* [x] This is a feature request
* [x] I searched existing issues before opening this one

docker v19.03 not available for s390x 
followed instructions on : https://docs.docker.com/install/linux/docker-ce/ubuntu/
### Actual behavior
```
apt-cache madison docker-ce
 docker-ce | 18.06.3~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.2~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.1~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.0~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.03.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.03.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.12.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.12.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.09.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.2~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages


**Output of `docker version`:**
```
docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:09 2019
 OS/Arch:           linux/s390x
 Experimental:      false
```
```
apt-cache madison docker-ce
 docker-ce | 18.06.3~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.2~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.1~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.06.0~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.03.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 18.03.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.12.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.12.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.09.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.2~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages
 docker-ce | 17.06.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/stable s390x Packages

```

**Comment by arkodg** [comment]
@sid226 thanks for raising this issue, we're working on this request !
cc: @StefanScherer

**Comment by sid226** [comment]
gentle ping @arkodg  any updates? Thanks : )

**Comment by StefanScherer** [comment]
@sid226 Let me close this ticket. We depend on IBM to provide packages, and they delivered 20.10.7 for current Ubuntu distros.

**Comment by sid226** [comment]
@StefanScherer thanks for the update. issue can be closed.

**Comment by thaJeztah** [comment]
Yes, let me close this ticket.

Packages for s390x should be available again (for docker 20.10.7 going forward); note that Ubuntu Xenial (16.04) reached EOL, and no packages will be published for that version of Ubuntu; https://download.docker.com/linux/ubuntu/dists/hirsute/pool/stable/s390x/

**Comment by rohitsakala** [comment]
@thaJeztah @StefanScherer  @arkodg  what about s390x support for the latest versions of in here https://download.docker.com/linux/static/stable/s390x/ since docker container image https://hub.docker.com/_/docker building process is based on that. 

Thanks :)

**Comment by rohitsakala** [comment]
Created a new issue https://github.com/docker/for-linux/issues/1310 to keep them different.
