### ISSUE TITLE
IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready

### ISSUE THREAD

**Issue by bdrung** [docker/for-linux#924]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

After installation and reboot, I expect the `docker0` bridge device to have an IP address assigned.

### Actual behavior

No IP address is assigned to the bridge device:

```
$ ip a show docker0
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:05:ac:1a:30 brd ff:ff:ff:ff:ff:ff
```

The kernel complains that the link is not ready:

```
$ dmesg | grep docker0 
[    9.796292] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
```

Restarting the docker daemon will solve the issue:

```
$ systemctl restart docker.service
$ ip a show docker0
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:05:ac:1a:30 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

### Steps to reproduce the behavior

Just install docker on Ubuntu 18.04:

```
apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
```

Then you will experience this issue.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-76-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 973.5MiB
 Name: ubuntu
 ID: CWW4:7GCL:TGSX:HPPN:GKN7:CWQR:Q6LX:FXKE:UDRM:PTOO:5ZYR:3MA7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

This issues is reproducible in the IONOS Enterprise Cloud with a minimal Ubuntu 18.04 image. This Ubuntu 18.04 image does not contain any modifications (all packages come from Ubuntu).

**Comment by arkodg** [comment]
@bdrung are you referring to a docker package upgrade scenario ? The repro steps outlined don't start the daemon so the `docker0` interface wont be created

**Comment by stefano-gurrieri** [comment]
Hi,

I've the same issue on my Linux embedded platform. Did you find any solution?

**Comment by jjqoie** [comment]
HI,
I have a embedded linux and also observe this error/warning, except that an IPv4 address is shown after boot - no restart of dockerd required for this.
I'm not sure if this is the problem why hello-world is not starting but I also observe this error/warning.

thanks
best regards
Jochen

**Error shown during startup: dmesg**
[   17.650952] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready


**vi /etc/docker/daemon.json**
{
  "ipv6": false
}


**ip a show docker0**
7: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:7b:52:66:d8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever


**When running docker hello-world**
docker run hello-world
[ 1211.452934] docker0: port 1(veth6febeca) entered blocking state
[ 1211.458657] docker0: port 1(veth6febeca) entered disabled state
[ 1211.464715] device veth6febeca entered promiscuous mode
**[ 1211.470111] IPv6: ADDRCONF(NETDEV_UP): veth6febeca: link is not ready**
[ 1211.949935] cgroup: runc (1254) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
[ 1211.964580] cgroup: "memory" requires setting use_hierarchy to 1 on the root
[ 1212.171426] docker0: port 1(veth6febeca) entered disabled state
[ 1212.177858] device veth6febeca left promiscuous mode
[ 1212.182532] docker0: port 1(veth6febeca) entered disabled state
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"mqueue\\\" to rootfs \\\"/var/lib/docker/overlay2/83560e85794b02a16d35eb3ec85ba566b94cc4d79e2285d2667658238826f2c9/merged\\\" at \\\"/dev/mqueue\\\" caused \\\"no such device\\\"\"": unknown.
ERRO[0002] error waiting for container: context canceled


**docker version**
Client:
 Version:           19.03.2-ce
 API version:       1.40
 Go version:        go1.12.9
 Git commit:        6a30dfca03
 Built:             Thu Mar 26 15:49:12 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       6a30dfca03664a0b6bf0646a7d389ee7d0318e6e
  Built:            Thu Mar 26 15:41:08 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.2.7-11-gfd103cb7.m
  GitCommit:        fd103cb716352c7e19768e4fed057f71d68902a0.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683-dirty

docker version
Client:
 Version:           19.03.2-ce
 API version:       1.40
 Go version:        go1.12.9
 Git commit:        6a30dfca03
 Built:             Thu Mar 26 15:49:12 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       6a30dfca03664a0b6bf0646a7d389ee7d0318e6e
  Built:            Thu Mar 26 15:41:08 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.2.7-11-gfd103cb7.m
  GitCommit:        fd103cb716352c7e19768e4fed057f71d68902a0.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683-dirty

 **docker info**
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.2-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fd103cb716352c7e19768e4fed057f71d68902a0.m
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f-dirty
 init version: fec3683-dirty (expected: fec3683b971d9)
 Kernel Version: 4.19.59-rt24+g9e4aaf669f3a
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.343GiB
 Name: s32g274aevb
 ID: EIUG:SGJC:3GPR:TBNF:3D6O:BBWV:DGTV:SA4X:5LYF:JDHE:CQ7P:SYW7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:5000
  127.0.0.0/8
 Registry Mirrors:
  http://localhost:5000/
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by spuder** [comment]
Do you have ipforwarding enabled?
```
cat /proc/sys/net/ipv4/ip_forward
```

Check `dmesg | grep docker` for errors. 

Possibly related https://github.com/moby/moby/issues/26492

**Comment by bdrung** [comment]
We figured out the cause. We had this netplan configuration:
```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    all:
      match:
        name: "*" 
      dhcp4: yes
      dhcp6: yes
```

This match also applied to `docker0` causing the symptoms described in this ticket. After changing the netplan config to
```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    all:
      match:
        name: "en*" 
      dhcp4: yes
      dhcp6: yes
```
docker starts without this issue.
