### ISSUE TITLE
containerd 1.2.12 deb package missing Debian 9 stretch

### ISSUE THREAD

**Issue by abraxxa** [docker/for-linux#929]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
apt upgrade updates all packages

### Actual behavior
When upgrading to docker-ce 19.03.5 on Debian 9 Stretch I get a 404 while downloading the related package of containerd (version 1.2.12).
`E: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.12-1_amd64.deb  404  Not Found`

This looks to me like the same issue as in #816.

### Steps to reproduce the behavior
`apt update; apt upgrade`

**Comment by WildWeassel** [comment]
Hello,

Same 404 error observed on  **docker-ce 18.09.9** on **Debian 9 Stretch** while performing an update with apt.

Latest available seem to be:
https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.10-3_amd64.deb

**Comment by arkodg** [comment]
this relates to https://github.com/moby/moby/issues/40514#issuecomment-586054841

**Comment by abraxxa** [comment]
Thanks for the pointer!
But it should be fixable by ensuring the Packages file doesn't include a 1.2.12 url.

**Comment by tiborvass** [comment]
Closing as this should be fixed by now.
