### ISSUE TITLE
docker 19 require realtime kernel ?

### ISSUE THREAD

**Issue by JOduMonT** [docker/for-linux#938]
when I install ubuntu 18.04 lts server with ssh
then run 
```
OS=$(lsb_release -s -i)
VERSION=$(lsb_release -s -c)
curl -fsSL https://download.docker.com/linux/${OS,,}/gpg | apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/${OS,,} $VERSION stable" > /etc/apt/sources.list.d/docker.list
apt update
apt install -y docker-cli docker-ce container.io
systemctl start docker-ce
systemctl status docker-ce
```
Docker version 19.03.6, build 369ce74a3c ends with 2 warnings message:
Your kernel does not support cgroup rt period
Your kernel does not support cgroup rt runtime

I tried with linux-image-generic which is kernel 4.15.0
and linux-image-generic-hwe-18.04 which is kernel 5.3.0

-----

While when I install ubuntu 18.04 lts server with ssh
then run 

```
OS=$(lsb_release -s -i)
VERSION=$(lsb_release -s -c)

curl -sL "https://download.docker.com/linux/ubuntu/dists/$VERSION/pool/stable/amd64/containerd.io_1.2.2-3_amd64.deb" -o /tmp/containerd.deb
curl -sL "https://download.docker.com/linux/ubuntu/dists/$VERSION/pool/stable/amd64/docker-ce-cli_18.09.2~3-0~ubuntu-$VERSION_amd64.deb" -o /tmp/docker-ce-cli.deb
curl -sL "https://download.docker.com/linux/ubuntu/dists/$VERSION/pool/stable/amd64/docker-ce_18.09.2~3-0~ubuntu-$VERSION_amd64.deb" -o /tmp/docker.deb
apt install -y /tmp/containerd.deb  /tmp/docker-ce-cli.deb /tmp/docker.deb
rm /tmp/containerd.deb /tmp/docker-ce-cli.deb /tmp/docker.deb

systemctl start docker-ce
systemctl status docker-ce
```
the Docker 18.09.2 don't have these warnings messages

## Could you please fix the *stable* docker package

Thank you

**Comment by thaJeztah** [comment]
Docker 19.03 and up include these warning in the `docker info` output, whereas older versions only logged these warnings in the daemon logs (this pull request refactored the daemon code to include these warnings: https://github.com/moby/moby/pull/38675, and for this particular warnings, these lines: https://github.com/moby/moby/pull/38675/files#diff-bd68dc38124653d028ccef1d009bf6dbL143-R134)

The warnings are "harmless", but provide you information that certain limits cannot be used/applied for your containers (which could previously go unnoticed, unless you checked the daemon logs).

Check your system/kernel configuration for features that are possibly missing, you can also use the `check-config` script; the latest version can be found here: https://github.com/moby/moby/blob/master/contrib/check-config.sh
