### ISSUE TITLE
Some changes not saved in layer

### ISSUE THREAD

**Issue by vlk-charles** [docker/for-linux#94]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Building with the following Dockerfile:

```
FROM grafana/grafana:4.4.3

RUN touch /etc/grafana/testfile && ls -l /etc/grafana
RUN ls -l /etc/grafana
```

the output of both `ls` invocations should be the same and the resulting image should contain the `testfile`.

### Actual behavior
The new file is missing again in the following layer.

```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM grafana/grafana:4.4.3
 ---> 49e2eb4da222
Step 2/3 : RUN touch /etc/grafana/testfile && ls -l /etc/grafana
 ---> Running in a8f434224c86
total 16
-rw-r----- 1 root grafana 12064 Aug  7 09:18 grafana.ini
-rw-r----- 1 root grafana  3469 Aug  7 09:18 ldap.toml
-rw-r--r-- 1 root root        0 Aug 31 13:48 testfile
 ---> 73a97568f1f5
Removing intermediate container a8f434224c86
Step 3/3 : RUN ls -l /etc/grafana
 ---> Running in 486747bdd8cb
total 16
-rw-r----- 1 root grafana 12064 Aug  7 09:18 grafana.ini
-rw-r----- 1 root grafana  3469 Aug  7 09:18 ldap.toml
 ---> 95255ffc1a82
Removing intermediate container 486747bdd8cb
Successfully built 95255ffc1a82
```

Same thing happens when I try to remove one of the files in `/etc/grafana`. It is there again in the next layer.

### Steps to reproduce the behavior
`Docker build .` with the above Dockerfile. This does not happen with all containers and paths. The above is a case I came across. If I `touch` the file in `/` for example, it is preserved.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 113
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 25.51GiB
Name: ubuntu1
ID: ZSC7:3VAV:U3JD:XIUN:OLEV:HS2T:GTYX:RE6E:WQHC:4CDB:WGWI:IQKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details**

This is on a physical machine with Ubuntu Server 16.04.3 LTS with HWE kernel. Everything is on ext4 and besides the storage driver being `overlay2`, this is a pretty much standard set-up. Complete contents of `/etc/docker/daemon.json`:

```
{
"storage-driver": "overlay2"
}
```

**Comment by vlk-charles** [comment]
According to [the documentation](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce), `overlay2` is among the recommended drivers for Ubuntu since 14.04.4 and 16.04.

**Comment by vlk-charles** [comment]
I just noticed /etc/grafana is a volume (marked so in the image). Is this behavior intended for volumes?

**Comment by vlk-charles** [comment]
Oh, so this is [documented](https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes) and is therefore a feature, not a bug:

> Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

My bad. Closing the issue.

**Comment by vlk-charles** [comment]
People have been trying to fix this "feature" for a while now:
https://github.com/moby/moby/issues/3639

**Comment by saginadir** [comment]
@vlk-charles any work around you've used to solve this?

**Comment by vlk-charles** [comment]
@saginadir I don't remember how I solved it back then. I imagine something like storing the files at a different location (outside volume) and having a script move them to the right one on container start-up should work.
