### ISSUE TITLE
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release.

### ISSUE THREAD

**Issue by chamer81** [docker/for-linux#942]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Actual behavior

When a push to our OpenShift image registry fails due to an imagestream tag quota limit reached, we receive a deprecation notice.  We are not sure whether this warning is correctly reporting a problem with our infrastructure:  

```console
$ docker push "${IMAGE}"
The push refers to repository [registry.appuio.ch/example-django/example-django]
ae4a3fee0df9: Preparing
...
fd33502eb220: Pushed
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the registry.appuio.ch registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
denied
```

The notice does not appear when the push succeeds, so it's not clear whether the target registry is actually using a deprecated schema or whether the notice is also emitted for other types of push errors.

According to our analysis, the [source code that emits the notice](https://github.com/docker/docker-ce/blob/master/components/engine/distribution/push_v2.go#L183-L193) may be doing a fallback to a deprecated schema version.

### Expected behavior

We would expect a deprecation notice to appear every time an image is pushed to a registry with the deprecated schema, and not to appear under any other circumstances, so it would be clearer whether the notice is relevant or not.

### Steps to reproduce the behavior

Attempt to push an image to an OpenShift image registry in which the tag quota limit has been exhausted.

**Output of `docker version`:**
(Output of GitLab-CI pipeline, running the latest official Docker image)

```
Pulling docker image docker.io/library/docker ...
Using docker image sha256:6512892b576811235f68a6dcd5fbe10b387ac0ba3709aeaf80cd5cfcecb387c7 for docker.io/library/docker ...
Running on runner-0277ea0f-project-14535846-concurrent-0 via runner-0277ea0f-srm-1581736725-a02e3b27...
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Docker CI runner on GitLab.com

Complete output of the build job here: https://gitlab.com/appuio/example-django/-/jobs/438375719

**Comment by bittner** [comment]
I can confirm this behavior. This looks like a bug of the Docker client, which needs to be fixed. The deprecation notice alarms customers, unnecessarily as it seems, which creates overhead in our daily operations.

**Comment by megian** [comment]
Similar issues seen with the version "Docker version 19.03.6, build 369ce74a3c"

**Comment by cpuguy83** [comment]
Would this be sufficient? https://github.com/moby/moby/pull/40671
