### ISSUE TITLE
Docker process dead when building an image

### ISSUE THREAD

**Issue by gainskills** [docker/for-linux#943]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
The process should not happen

### Actual behavior
See 'Steps to reproduce the behavior' part, the docker process hang during docker building an image

I rollback the docker version to 18.09.9, the issue doesn't come

### Steps to reproduce the behavior

- Build the docker environment with a docker-compose file: docker-compose -f stack.yml -f
[stack.txt](https://github.com/docker/for-linux/files/4252369/stack.txt)

    _Note_: 
        1.  Limited by GitHub file type policy, I changed the file extension from 'yml' to 'txt'
        2. The file is in a project subfolder: dockerfiles 

- Docker will build the image: redmine with the [docker file](https://github.com/gainskills/redmine/blob/master/4.1/alpine/Dockerfile)
 
- The docker process will hang at the step:

```
RUN set -eux; \
	[ ! -d "$HOME" ]; \
	mkdir -p "$HOME"; \
	chown redmine:redmine "$HOME"; \
	chmod 1777 "$HOME"
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Sorry,  I didn't collect this info I uninstalled the version and rollback to 18.09.9 to brought my production environment up
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
vm on digitial ocean

**Comment by mstr0m** [comment]
containerd 1.2.13 fixed this issue

https://github.com/moby/moby/issues/40514#issuecomment-586054841
