### ISSUE TITLE
Can not remove the container which rootfs is shared bind-mount, after `docker cp`

### ISSUE THREAD

**Issue by spyyang** [docker/for-linux#958]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

When bind mounting `/var/lib/docker`  with the shared propagation，the container which volumes have the mounted subpath should be removed successfully after running `docker cp`.

### Actual behavior

Failed to remove the container and the status is `in removal process`.

### Steps to reproduce the behavior

```bash
systemctl stop docker
mkdir -p /data/docker
mount -B /var/lib/docker /data/docker
systemctl start docker

mkdir -p /mnt/test/subpath /data/testsubpath
mount -B /mnt/test/subpath /data/testsubpath
containerid=$(docker run -d -v /root/mnt:/test busybox sleep 100000)
touch foo
docker cp foo $containerid:/root/
docker rm -f $containerid
```

Failed to remove the container, and get the message like this:
```
Error response from daemon: container 9b5aed0422817ff1394bf65eab661ffbbc09fd7a812a2d25e49480ee1cd7304d: driver "overlay2" failed to remove root filesystem: remove /var/lib/docker/overlay2/909d3fede686d72a377367cb1c5da30f7402dda9a872964599125c0e2221a143/merged: device or resource busy
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:52:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

**Output of `docker info`:**

```
Containers: 40
 Running: 21
 Paused: 0
 Stopped: 19
Images: 10
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.65-netease
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.1GiB
Name: 
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 139
 Goroutines: 127
 System Time: 2020-03-23T15:04:13.779343209+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

- physical

### Related commits

https://github.com/docker/docker-ce/commit/cacd4007776672e918162936d8846eb51a5300e6
https://github.com/docker/docker-ce/commit/e076bccb458aeadab9380ce0636456ad6317a85f    
https://github.com/docker/docker-ce/commit/9803272f2db84df7955b16c0d847ad72cdc494d1

### Suggestions for a fix

Fix this problem manually:
```bash
mount --make-rprivate /var/lib/docker/overlay2/<layer>/merged
umount -l /var/lib/docker/overlay2/<layer>/merged/<busy-path>
```

Actually `docker cp` mounts  `volume` to `/var/lib/docker/overlay2/<layer>/merged/<volumepath>` 
 using rbind-mount option(can show by `mount|grep <layer>`). 

So changing the mount way like this may fix it:
1. `mount --bind volume-path /var/lib/docker/overlay2/<layer>/merged/<volume-path>`
2. `mount --make-private /var/lib/docker/overlay2/<layer>/merged/<volume-path>`
3. `mount --bind volume-subpath /var/lib/docker/overlay2/<layer>/merged/<volume-subpath>`

Recursively do step2/3 to deal with the subpaths which mounted outside.

**Comment by thaJeztah** [comment]
@kolyshkin @cpuguy83 ptal

not sure if this is fully fixable (mount propagation and namespaces are a can of worms)
