### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by srusru** [docker/for-linux#966]
![error](https://user-images.githubusercontent.com/40003348/77968695-943a9f80-72ad-11ea-8890-c5702a25c8e0.PNG)
I see this error in when i exec into my pod in Azure kubernetes 
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
This is my dockerfile:

FROM node:lts-alpine3.11
COPY . /app
WORKDIR /app
RUN yarn install
RUN yarn build
FROM nginx:mainline-alpine
COPY --from=0 /app/build /app/build
COPY --from=0 /app/docker/nginx /etc/nginx
CMD ["nginx", "-g", "daemon off;"]

Please do help. Thanks in advance

**Comment by cpuguy83** [comment]
That's because `bash` is not installed in the image.
You'll need to run `sh` if you want a shell.

**Comment by geneno99** [comment]
how to run sh 
can reply the steps please

**Comment by JamesB192** [comment]
dupe of #963 others?
