### ISSUE TITLE
Missing Debian dependency on "apparmor" package

### ISSUE THREAD

**Issue by Silvanoc** [docker/for-linux#974]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Debian package `docker-ce` declares the package `apparmor` as a recommended dependency (because it provides the tool `apparmor_parser`, required by Docker to apply AppArmor profiles).

A warning or similar appears in the logs if running a container on a system with the AppArmor module present, but missing the package `apparmor`.

Strange enough, the Ubuntu packages have that recommended dependency...

### Actual behavior

No dependency on the debian package `apparmor` declared nowhere.

`docker info` reports that AppArmor is supported (probably based on the presence of the corresponding module) and everything looks as if AppArmor would be enforced. But listing the AppArmor profiles with `cat /sys/kernel/security/apparmor/profiles` shows that no ApArmor profile is being loaded.

### Steps to reproduce the behavior

1. Obtain a Debian system that doesn't contain the package `apparmor` (for example building one with `debootstrap`).
2. Install `docker-ce`.
3. Execute `docker info` and check the presence of the entry `apparmor` under `Security Options`.
4. Run a container without specifying any AppArmor profile.
5. Run `docker inspect <container-id> | jq -r '.[0].AppArmorProfile'` and confirm that it reports the AppArmor profile `docker-default` as being applied.
6. **Confirm that the AppArmor profile `docker-default` is not loaded**, running `/sys/kernel/security/apparmor/profiles`. It fails due to the absence of the tool `apparmor_parser`, but it's being silently ignored. Most probably no AppArmor profile is loaded at all.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.98-rt40
 Operating System: ... (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 981.8MiB
 Name: iosie.localdomain
 ID: VTS4:74KU:DNHS:LWEC:P7LY:K3DJ:T23T:JK6X:FVQS:7Q5I:CJ7Y:FA54
 Docker Root Dir: ...
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
Did some digging into the background for this (see the linked PR), and opened https://github.com/docker/docker-ce-packaging/pull/487
