### ISSUE TITLE
[ERROR] Can't run any container that binds a port

### ISSUE THREAD

**Issue by maxjf1** [docker/for-linux#977]
My docker recently isn't working because an crazy bug. I've tried everything.

No images/containers are working, if they try to bind any port. For instance, the following simple http server:

`docker run -it danjellz/http-server`

i get the following error (cannot bind port):

    net.js:1420
          throw new ERR_SOCKET_BAD_PORT(options.port);
          ^

    RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.

Another example is an mysql server with docker-compose. With the following example:

    version: '3'
    services:
        db:
          image: mysql:5.7
          command: --log_error_verbosity=1
          environment: # DB configs
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

i get the following error:

    db_1  | 2020-04-12 23:05:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
    db_1  | 2020-04-12 23:05:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
    db_1  | 2020-04-12 23:05:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
    db_1  | 2020-04-12T23:05:13.329093Z 0 [ERROR] Failed to create a socket for IPv4 '0.0.0.0': errno: 13.
    db_1  | 2020-04-12T23:05:13.329130Z 0 [ERROR] Can't create IP socket: Permission denied
    db_1  | 2020-04-12T23:05:13.329135Z 0 [ERROR] Aborting
    db_1  | 
    base_db_1 exited with code 1

this happens with all images, i don't know why. Note that isn't an error exposing the port

I've tried to remove docker completly (according to documentation) and reinstall it. Removed possible packages that may cause network issues, but nothing. System info:

```
              ............                maxjf1@DELL-NOTE-MAX
          .';;;;;.       .,;,.            OS: Deepin 15.11 stable
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 4.15.0-30deepin-generic
     .;::::::::'     .,::;;,''''',.       Uptime: 42m
    ,'.::::::::    .;;'.          ';      Packages: 2426
   ;'  'cccccc,   ,' :: '..        .:     Shell: zsh 5.3.1
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1920x1080
 .l.     cllll' ., .lc  :; .l'       l.   WM: KWin
 .c       :lllc  ;cl:  .l' .ll.      :'   GTK Theme: Mojave-dark [GTK2/3]
 .l        'looc. .   ,o:  'oo'      c,   Icon Theme: Mojave-CT-Night-Mode
 .o.         .:ool::coc'  .ooo'      o.   CPU: Intel Core i5-8300H CPU @ 4GHz
  ::            .....   .;dddo      ;c    GPU: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
   l:...            .';lddddo.     ,o     RAM: 3356MiB / 7836MiB
    lxxxxxdoolllodxxxxxxxxxc      :l     
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.  

```

**Comment by thaJeztah** [comment]
Deepin Linux is not a linux distro that is supported, and we don't provide packages for that Linux distribution, so I don't think I'm able to help; I'd recommend opening a support ticket in the Deepin issue tracker.

I'm closing this ticket because of the above, but feel free to continue the conversation
