### ISSUE TITLE
Missing release.md file for disco release 

### ISSUE THREAD

**Issue by manojsdoshi** [docker/for-linux#978]
http://archive.ubuntu.com/ubuntu disco Release' does not have a Release file

**Comment by manojsdoshi** [comment]
Err:6 http://archive.ubuntu.com/ubuntu disco Release
   404  Not Found [IP: 91.189.88.152 80]
 Err:7 http://archive.ubuntu.com/ubuntu disco-updates Release
   404  Not Found [IP: 91.189.88.152 80]
 Err:8 http://archive.ubuntu.com/ubuntu disco-backports Release
   404  Not Found [IP: 91.189.88.152 80]
 Reading package lists...
 E: The repository 'http://security.ubuntu.com/ubuntu disco-security Release' does not have a Release file.
 E: The repository 'http://archive.ubuntu.com/ubuntu disco Release' does not have a Release file.
 E: The repository 'http://archive.ubuntu.com/ubuntu disco-updates Release' does not have a Release fi

**Comment by Raykazan** [comment]
I found this... may be related:
https://askubuntu.com/questions/1228164/ubuntu-19-04-sudo-apt-get-update-throws-an-error

Seems the EOL of this release...

**Comment by SuperSandro2000** [comment]
Yeah, disco is no longer on the repo. See http://archive.ubuntu.com/ubuntu/dists/

**Comment by thaJeztah** [comment]
Closing this one, because ubuntu disco reached EOL
