### ISSUE TITLE
Container logs may grow endlessly

### ISSUE THREAD

**Issue by Himura2la** [docker/for-linux#985]
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

* I can run any container as long as I need

### Actual behavior

* Our production `nginx` was up for several months, and generated ~80G of logs.

### Steps to reproduce the behavior

* Run any container that outputs to stdout for a long period of time without changing a default logging driver

# Proposal:

Don't use bare `json-file` logging driver without rotation by default.

I expect to have `journald` as a default logging driver on all SystemD-enabled systems. Other systems should also use a better logging driver.

---

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 53
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-11-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 2.8GiB
 Name: REDACTED
 ID: REDACTED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
This is working as expected. We can't really change the default b/c other systems depend on it.

There are options on `json-file` to enable rotation and compression.
Additionally you can use the `local` log driver which defaults to use rotation/compression.
Or of course `journald` if you like.

You can set the default logger and log options to use *for new containers* in `/etc/docker/daemon.json`.
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

**Comment by Himura2la** [comment]
This issue is about the default behavior for new installations. I think it worth BC in some version
