### ISSUE TITLE
daemon failed to start: Error starting daemon on raspberry

### ISSUE THREAD

**Issue by boistordu** [docker/for-linux#986]
Hi,
Just to warn you that on one of my new raspberry pi4, it still occurs what happened on this ticket: https://github.com/docker/for-linux/issues/123
I had to create the network by myself, even after a reboot etc. It doesn't happen on all my raspberry pi4 and pi3 and there are all fresh installations, very simple. I don't know what trigger this.

`Linux mobilecrap4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`
But the absence of a proper separate docker.log file make the work difficult, I had to go see in daemon.log and syslog just to be sure which error it was. That would be also nice to change...

**Comment by thaJeztah** [comment]
What are the logs? Without more details, it will be difficult to look into. Also you mention that it works on "some" machines but not on other ones; what's the difference between those machines?

**Comment by thaJeztah** [comment]
looks like this went stale
