### ISSUE TITLE
wrong times in config.h.in files created using autoheader in a mounted directory

### ISSUE THREAD

**Issue by alepinio** [docker/for-linux#990]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
*atime* and *mtime* of a `config.h.in` file created using `autoheader` in a filesystem directory attached to a `ubuntu:18.04` container are representative of the time at which the file was created

### Actual behavior
*atime* and *mtime* of a `config.h.in` file created using `autoheader` in a filesystem directory attached to a `ubuntu:18.04` container are rounded to the second

### Steps to reproduce the behavior
1. `echo "AC_CONFIG_HEADERS([config.h])" > configure.ac`
2. `docker run -it --mount type=bind,source=$(pwd),destination=/home ubuntu:18.04 bash`
3. `apt update ; apt install autoconf`
4. `cd home`
5. `autoheader --verbose`
6. `stat config.h.in` and you will get something like:
```
root@3aec1ecd6533:/home# stat config.h.in
  File: config.h.in
  Size: 64        	Blocks: 8          IO Block: 4096   regular file
Device: 806h/2054d	Inode: 924907      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-04-28 01:51:43.000000000 +0000
Modify: 2020-04-28 01:51:43.000000000 +0000
Change: 2020-04-28 01:51:43.861686019 +0000
 Birth: -
```
Note wrong times (abnormally rounded) in *atime* and *mtime*.

**Output of `docker version`:**

```
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
❯ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-96-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.674GiB
 Name: hp
 ID: EHU4:RHR3:GUSG:W7JC:B7YF:B3DN:MS5H:SVZ5:UKLP:VR74:DX3D:QXZK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
I think this is somehow related to bind-mounts in general (perhaps there's an option to preserve precision?)

Here's to reproduce the exact same situation without using a container, but when bind-mounting a directory;

```bash
mkdir test && cd test

# create a "home" dir, and create configure.ac
mkdir home && echo "AC_CONFIG_HEADERS([config.h])" > home/configure.ac

# run automake and check mtime, atime:
cd home
autoheader --verbose

stat config.h.in
  File: config.h.in
  Size: 64        	Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d	Inode: 1564124     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-04-28 11:04:08.514090456 +0000
Modify: 2020-04-28 11:04:08.514090456 +0000
Change: 2020-04-28 11:04:08.514090456 +0000
 Birth: -
```

Now do the same with a bind-mount:

```bash
# cleanup files from the previous test
rm -R autom4te.cache config.h.in

cd ../

# create a "mountedhome" mountpoint, and mount "home" there
mkdir mountedhome
mount -o bind ./home ./mountedhome

# mount properties the bind mount:
mount | grep mountedhome
/dev/vda1 on /root/test/mountedhome type ext4 (rw,relatime,data=ordered)

# run autoheader inside the mounted home bind-mount
cd mountedhome
autoheader --verbose


stat config.h.in
  File: config.h.in
  Size: 64        	Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d	Inode: 1806440     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-04-28 11:07:47.000000000 +0000
Modify: 2020-04-28 11:07:47.000000000 +0000
Change: 2020-04-28 11:07:47.563228235 +0000
 Birth: -
```

**Comment by thaJeztah** [comment]
Or is it `autoheader` that treats bind-mounts different? (haven't checked if output of `autoheader --verbose` is different, you may want to do a diff between the output if anything stands out

**Comment by alepinio** [comment]
Wow, definitely not an issue with `docker`. I didn't try that. Thank you very much for the additional information!

**Comment by thaJeztah** [comment]
You're welcome! If you manage to find out where the issue is (if it's in autoheader, or if there's some option for bind-mounts that influences this), feel free to comment here (I'm curious as well 😅)

**Comment by ntorresalberto** [comment]
I do not if relevant or not, but I can't think of a place to document it, so I'll just leave it here:
I used the steps written by @thaJeztah and found:

- I **cannot reproduce this problem at all** on a native Fedora installation using **btrfs** on root (it simply works fine).
- I can **reproduce this problem exactly**  on a virtual machine running ubuntu 18.04 on an **ext4** partition.
- I can **reproduce a similar problem**  on a virtual machine running ubuntu 18.04 on an **btrfs** partition (the file created by autoheader already has 0s in access/usage time, even before trying to reproduce with the bind-mounted directory).

**Comment by alepinio** [comment]
https://bugs.launchpad.net/ubuntu/+source/autoconf/+bug/1878934
