### ISSUE TITLE
Docker Repository for Focal Fossa is not available

### ISSUE THREAD

**Issue by sunilpoojari** [docker/for-linux#992]
I am on POP OS 20.04 (Ubuntu 20.04) I ran the following command to add Docker Repository for Focal Fossa but it is not available, and it gave me the following error.
Please add the Repository for Focal Fossa.   @thaJeztah @crosbymichael @vieux @albers

Here it is not available: [https://download.docker.com/linux/ubuntu/dists/](url) 

Similar Issue: #833 

**Command to add Repository:**
```
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

**Error:**
```
Err:9 https://download.docker.com/linux/ubuntu focal Release
  404  Not Found [IP: 54.182.0.86 443]
```

**Comment by leogouveia** [comment]
Any update?
Is there a workaround or a planned date to release it to focal?

**Comment by sunilpoojari** [comment]
> Any update?
> Is there a workaround or a planned date to release it to focal?

No Update Yet.

**Comment by ihor-sviziev** [comment]
Workaround: use repo for Ubuntu 18.04 Bionic, like this:
```bash
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   bionic \
   stable"
```

**Comment by akharitonov** [comment]
> Related to [docker/docker.github.io#10703](https://github.com/docker/docker.github.io/issues/10703) (and #940), there is more activity.
> Also we have workaround: use repo for Ubuntu 18.04 Bionic, like this:
> 
> ```shell
> sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    bionic \
>    stable"
> ```

Why would you use 18.04 release in 20.04?  **Focal** release is much more closely related to **eoan** (19.10). If you must use 20.04 and want to install docker, should use eoan instead. 

```
$ sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable"
```

**Comment by Desnoo** [comment]
The classic way now works for the focal release (20.04). I tested it today.

**Comment by akharitonov** [comment]
Yes, there's focal branch now in the repo:
https://download.docker.com/linux/ubuntu/dists/focal/

**Comment by AlistairB** [comment]
This is not working for me. I tried with local server and `Main server` for packages.

```bash
sudo apt install -y \
>   docker-ce \
>   docker-ce-cli \
>   containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
```

**Comment by akharitonov** [comment]
https://github.com/docker/docker.github.io/issues/10703#issuecomment-629361190

**Comment by AlistairB** [comment]
Ah thanks!

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!
