### ISSUE TITLE
docker ps ... just hangs  also docker install fails

### ISSUE THREAD

**Issue by scottstensland** [docker/for-linux#993]
docker ps stuck … docker install also just hangs

docker ps hangs forever was the first symptom so I purged docker and tried to reinstall ... the install never finishes

```
dpkg -l|grep docker
iF  docker-ce                                  5:19.03.8~3-0~ubuntu-bionic                amd64        Docker: the open-source application container engine
ii  docker-ce-cli                              5:19.03.8~3-0~ubuntu-bionic                amd64        Docker CLI: the open-source application container engine

```

notice in above the docker installed failed as per iF ... details see dpkg -l | head -3

on Ubuntu 20.04 docker fails to finish its install

```
sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aufs-tools cgroupfs-mount containerd.io docker-ce-cli pigz
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount containerd.io docker-ce docker-ce-cli pigz
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/85.7 MB of archives.
After this operation, 385 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package pigz.
(Reading database ... 272586 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Selecting previously unselected package aufs-tools.
Preparing to unpack .../1-aufs-tools_1%3a4.14+20190211-1ubuntu1_amd64.deb ...
Unpacking aufs-tools (1:4.14+20190211-1ubuntu1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../2-cgroupfs-mount_1.4_all.deb ...
Unpacking cgroupfs-mount (1.4) ...
Selecting previously unselected package containerd.io.
Preparing to unpack .../3-containerd.io_1.2.13-1_amd64.deb ...
Unpacking containerd.io (1.2.13-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../4-docker-ce-cli_5%3a19.03.8~3-0~ubuntu-bionic_amd64.deb ...
Unpacking docker-ce-cli (5:19.03.8~3-0~ubuntu-bionic) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../5-docker-ce_5%3a19.03.8~3-0~ubuntu-bionic_amd64.deb ...
Unpacking docker-ce (5:19.03.8~3-0~ubuntu-bionic) ...
Setting up aufs-tools (1:4.14+20190211-1ubuntu1) ...
Setting up containerd.io (1.2.13-1) ...
Setting up docker-ce-cli (5:19.03.8~3-0~ubuntu-bionic) ...
Setting up pigz (2.4-1) ...
Setting up cgroupfs-mount (1.4) ...
Setting up docker-ce (5:19.03.8~3-0~ubuntu-bionic) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.

```

previous install was OK until I noticed docker ps was hanging forever ... I purged docker including deleting all of

```
apt-get purge docker-*  -y
rm -rf /var/lib/docker
systemctl daemon-reload

```

here is my apt entry

```
cd  /etc/apt ; grep -r docker 

sources.list.d/docker.list:deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```

then I ran above install which also just hangs forever 

    docker version   #  also just hangs even as root

```
uname -m && uname -r && cat /etc/*release
x86_64
5.4.0-30-generic
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"

```

I am about to reformat my laptop and reinstall Ubuntu 20.04 from scratch ... any advise ?

PS ... my remote VPS ubuntu 18.04 all run docker fine so dunno if this is Ubuntu 20.04 related although I have seen docker run OK on other 20.04 boxes

**Comment by alekmlynek** [comment]
I'm on 19.10 and am getting the exact same problem. 
1. Starting docker hangs
2. Reinstalling (With config purge, etc) does not work
3. I can "reinstall" by killing the dockerd process, but it will continue freezing

`❯ sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  containerd.io docker-ce docker-ce-cli
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/85.6 MB of archives.
After this operation, 384 MB of additional disk space will be used.
Selecting previously unselected package containerd.io.
(Reading database ... 238207 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.13-1_amd64.deb ...
Unpacking containerd.io (1.2.13-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a19.03.8~3-0~ubuntu-eoan_amd64.deb ...
Unpacking docker-ce-cli (5:19.03.8~3-0~ubuntu-eoan) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a19.03.8~3-0~ubuntu-eoan_amd64.deb ...
Unpacking docker-ce (5:19.03.8~3-0~ubuntu-eoan) ...
Setting up containerd.io (1.2.13-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up docker-ce-cli (5:19.03.8~3-0~ubuntu-eoan) ...
Setting up docker-ce (5:19.03.8~3-0~ubuntu-eoan) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
`

**Comment by scottstensland** [comment]
on Ubuntu 20.04 above error happened on kernel 5.4.0-30-generic 
however issue goes away when I revert back to kernel 5.4.0-29-generic
then issue returns if I go back to kernel 5.4.0-30-generic

**Comment by alekmlynek** [comment]
My issue is on 19.10 kernel 5.3.0-52-generic

**Comment by kolomerot** [comment]
I have the same issue on 19.10 kernel 5.3.0-52-generic

**Comment by scottstensland** [comment]
I can confirm same issue on a different laptop 20.04 which is OK on 5.4.0-29-generic yet has issue on 5.4.0-30-generic  then is fixed simply by booting into Recovery and choosing 5.4.0-29-generic


```
	docker version
	Client: Docker Engine - Community
	 Version:           19.03.8
	 API version:       1.40
	 Go version:        go1.12.17
	 Git commit:        afacb8b7f0
	 Built:             Wed Mar 11 01:25:46 2020
	 OS/Arch:           linux/amd64
	 Experimental:      false

	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.8
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.12.17
	  Git commit:       afacb8b7f0
	  Built:            Wed Mar 11 01:24:19 2020
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          1.2.13
	  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
	 runc:
	  Version:          1.0.0-rc10
	  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683
```

**Comment by isfanazha** [comment]
I have the same issue on 18.04 with kernel Linux 5.3.0-52-generic. Here are the logs:
```
Feb 20 20:45:24 mypc dockerd[19243]: time="2020-02-20T20:45:24.975713677+07:00" level=warning msg="Your kernel does not support swap memory limit"
Feb 20 20:45:24 mypc dockerd[19243]: time="2020-02-20T20:45:24.975735513+07:00" level=warning msg="Your kernel does not support cgroup rt period"
Feb 20 20:45:24 mypc dockerd[19243]: time="2020-02-20T20:45:24.975741536+07:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Feb 20 20:45:24 mypc dockerd[19243]: time="2020-02-20T20:45:24.975746532+07:00" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 20 20:45:24 mypc dockerd[19243]: time="2020-02-20T20:45:24.975751380+07:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
```

**Comment by dobrikov91** [comment]
Same issue on 5.4.0-30-generic kernel

**Comment by kolomerot** [comment]
> I have the same issue on 19.10 kernel 5.3.0-52-generic

But on Ubuntu 19.10 kernel 5.3.0-**51**-generic work normally.

**Comment by scottstensland** [comment]
its working OK on Ubuntu 20.04 with 

    uname -a
    Linux milan 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alekmlynek** [comment]
Upgraded to the latest kernel, working once again on: 5.3.0-53-generic

**Comment by kolomerot** [comment]
> Upgraded to the latest kernel, working once again on: 5.3.0-53-generic

I'm confirm what for Ubuntu 19.10 on latest kernel 5.3.0-53 works normally again.

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!

**Comment by scottstensland** [comment]
its OK on Ubuntu 20.04 with

    uname -a
    Linux milan 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux


    grep -r docker /etc/apt
    # /etc/apt/sources.list.d/docker.list:# deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test
    /etc/apt/sources.list.d/docker.list:deb [arch=amd64] https://download.docker.com/linux/ubuntu focal test




	docker version
	Client: Docker Engine - Community
	 Version:           19.03.9
	 API version:       1.40
	 Go version:        go1.13.10
	 Git commit:        9d988398e7
	 Built:             Fri May 15 00:25:20 2020
	 OS/Arch:           linux/amd64
	 Experimental:      false

	Server: Docker Engine - Community
	 Engine:
	  Version:          19.03.9
	  API version:      1.40 (minimum version 1.12)
	  Go version:       go1.13.10
	  Git commit:       9d988398e7
	  Built:            Fri May 15 00:23:53 2020
	  OS/Arch:          linux/amd64
	  Experimental:     false
	 containerd:
	  Version:          1.2.13
	  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
	 runc:
	  Version:          1.0.0-rc10
	  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
	 docker-init:
	  Version:          0.18.0
	  GitCommit:        fec3683

**Comment by thaJeztah** [comment]
Let me close this one, as packages for 20.04 are now available, but feel free to comment if this is still an issue

**Comment by julianpoemp** [comment]
Same issue with Ubuntu 20.04 LTS, Kernel LTS 4.9.230. I tried it on my Odroid N2, making a fresh install using this image: https://wiki.odroid.com/odroid-n2/os_images/ubuntu/20200715

Because I can't get a more up-to-date Kernel I'll go back to LTS 18.04.

**Comment by antop** [comment]
Even on Ubuntu 18.04.1 - 5.3.0-53-generic, I had the same issue and after some checks and tests I found a workaround that could be useful to whom doesn't want to upgrade to Ubuntu 20.04. 

**_Possible problem:_** 

The problem, seems to me, related to some versions of docker, on specific kernel version and permissions set during the process update.

**_Possible solution:_** 

1) Completely uninstall docker and related files(images/containers/volumes...)
```
sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-ce-cli
sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce 
sudo rm -rf /var/lib/docker /etc/docker
sudo rm /etc/apparmor.d/docker
sudo groupdel docker
sudo rm -rf /var/run/docker.sock
```
2) Upgrade the kernel with the latest version
```
sudo apt-get update
sudo apt-get dist-upgrade
```
3) Install docker again: https://docs.docker.com/engine/install/ubuntu/

4) Configure your user to allow Docker runs as non-root user.
```
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker # or log out and log in to activate changes to groups.
```
Now, should work

**Comment by Mouradif** [comment]
Same problem here installing on Ubuntu 22.04 by following the installation guide on docs.docker.com
