### ISSUE TITLE
clear cache in docker file

### ISSUE THREAD

**Issue by vramanagit** [docker/for-linux#995]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment]
I think this was opened accidentally, as there's no info in the description. Let me go ahead and close
